#!/usr/bin/env python3
"""
Appends Telugu (te), Kannada (kn), Malayalam (ml) to dict_south_indic.py
"""

TE_CODE = '''
TE_NEW = {
    "category.Wallet / Purse": "వాలెట్ / పర్స్",
    "category.Bag / Luggage": "బ్యాగ్ / లగేజ్",
    "category.ID / Card": "గుర్తింపు కార్డు",
    "urgency.Contains ID": "గుర్తింపు కార్డు ఉంది",
    "voice.stop": "రికార్డింగ్ ఆపు",
    "voice.error": "వాయిస్ గుర్తింపులో లోపం ఏర్పడింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    "voice.hint": "వస్తువు బ్రాండ్, రంగు, ప్రదేశం, తేదీ వంటి వివరాలు చెప్పండి.",
    "report.title": "వస్తువును నమోదు చేయండి",
    "report.subtitle": "పోగొట్టుకున్న లేదా దొరికిన వస్తువును సురక్షితంగా నివేదించండి.",
    "report.type": "నివేదిక రకం",
    "report.typeLost": "నేను వస్తువును పోగొట్టుకున్నాను",
    "report.typeFound": "నాకు ఒక వస్తువు దొరికింది",
    "report.stepBasics": "1. ప్రాథమిక వివరాలు",
    "report.stepLocation": "2. ప్రదేశం & తేదీ",
    "report.stepPhotos": "3. ఫోటోలు & ఆధారాలు",
    "report.stepSecurity": "4. భద్రత & సంప్రదింపు",
    "report.itemTitle": "వస్తువు పేరు",
    "report.itemTitlePlaceholder": "ఉదా. నల్ల తోలు టైటాన్ వాచ్, నీలి వైల్డ్‌క్రాఫ్ట్ బ్యాగ్",
    "report.category": "వర్గం",
    "report.selectCategory": "వస్తువు వర్గాన్ని ఎంచుకోండి",
    "report.description": "వివరణాత్మక వివరాలు",
    "report.descriptionPlaceholder": "రంగు, మోడల్, గుర్తులు, లోపలి వస్తువులు మొదలైనవి పేర్కొనండి...",
    "report.location": "ప్రదేశం (దొరికిన / పోయిన స్థలం)",
    "report.locationPlaceholder": "ఉదా. సికింద్రాబాద్ రైల్వే స్టేషన్ ప్లాట్‌ఫారమ్ 1, హైదరాబాద్",
    "report.date": "తేదీ & సుమారు సమయం",
    "report.urgency": "అత్యవసర స్థాయి",
    "report.urgencyNormal": "సాధారణం",
    "report.urgencyUrgent": "అత్యవసరం",
    "report.urgencyMedical": "వైద్యపరమైన / అత్యంత క్లిష్టమైనది",
    "report.photos": "ఫోటోలు అప్‌లోడ్ చేయండి",
    "report.photosHint": "స్పష్టమైన ఫోటోలు AI సరిపోలిక ఖచ్చితత్వాన్ని పెంచుతాయి.",
    "report.reward": "బహుమతి మొత్తం (ఐచ్ఛికం)",
    "report.rewardPlaceholder": "₹ మొత్తం రూపాయలలో",
    "report.contact": "వాట్సాప్ / ఫోన్ సంప్రదింపు",
    "report.contactPlaceholder": "10 అంకెల మొబైల్ సంఖ్య",
    "report.pin": "4 అంకెల భద్రతా పిన్",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "తరువాత సవరించడానికి లేదా పరిష్కరించినట్లు గుర్తించడానికి అవసరం.",
    "report.submit": "కమ్యూనిటీకి నివేదికను సమర్పించండి",
    "report.submitting": "సురక్షిత రిజిస్ట్రీలో ప్రచురిస్తోంది...",
    "report.success": "మీ నివేదిక విజయవంతంగా ప్రచురించబడింది!",
    "report.viewListing": "జాబితాలో చూడండి",
    "report.brand": "బ్రాండ్ / తయారీదారు",
    "report.brandPlaceholder": "ఉదా. ఆపిల్, శామ్‌సంగ్, టైటాన్, వైల్డ్‌క్రాఫ్ట్",
    "report.primaryColor": "ప్రధాన రంగు",
    "report.secondaryColor": "ద్వితీయ రంగు",
    "report.landmark": "సమీప ల్యాండ్‌మార్క్",
    "report.landmarkPlaceholder": "ఉదా. ప్లాట్‌ఫారమ్ 2 ఎస్కలేటర్ వద్ద, కేఫ్ ఎదురుగా",
    "report.secretClue": "రహస్య గుర్తింపు ఆధారం (ధృవీకరణ కోసం)",
    "report.secretCluePlaceholder": "ఉదా. లోపలి జేబులో ఎరుపు కీచైన్, చెక్కబడిన పేరు 'RS'",
    "feed.searchPlaceholder": "వస్తువులు, ట్యాగ్‌లు, రంగులు, నగరాలు వెతకండి...",
    "feed.filters": "ఫిల్టర్లు",
    "feed.applyFilters": "ఫిల్టర్లను వర్తింపజేయండి",
    "feed.recentSearches": "ఇటీవలి శోధనలు",
    "feed.savedSearches": "సేవ్ చేసిన శోధనలు",
    "feed.listingRegistry": "రిజిస్ట్రీ జాబితా",
    "feed.category": "వర్గం",
    "feed.allCategories": "అన్ని వర్గాలు",
    "feed.city": "నగరం",
    "feed.allCities": "అన్ని నగరాలు",
    "feed.dateRange": "తేదీ పరిధి",
    "feed.proximity": "దూర పరిధి",
    "feed.allProximities": "అన్ని దూరాలు (ఏదైనా పరిధి)",
    "feed.within5km": "5 కి.మీ లోపల",
    "feed.within15km": "15 కి.మీ లోపల",
    "feed.within30km": "30 కి.మీ లోపల",
    "feed.within50km": "50 కి.మీ లోపల",
    "feed.sortCatalog": "జాబితాను క్రమబద్ధీకరించు",
    "feed.colorSwatch": "రంగు ప్యాలెట్",
    "feed.allColors": "అన్ని రంగులు",
    "feed.hardwareBrand": "బ్రాండ్ తయారీదారు",
    "feed.allBrands": "అన్ని బ్రాండ్లు",
    "feed.resetFilters": "ఫిల్టర్లను రీసెట్ చేయండి",
    "feed.viewList": "జాబితా",
    "feed.viewMap": "మ్యాప్",
    "feed.noMatchesFound": "రిజిస్ట్రీలో సరిపోలికలు కనుగొనబడలేదు",
    "feed.noMatchesDesc": "ఈ ఫిల్టర్లతో ఏ వస్తువులూ సరిపోలలేదు. శోధన పదాలను మార్చండి లేదా ఫిల్టర్లను రీసెట్ చేయండి.",
    "feed.reportItem": "పోగొట్టుకున్న/దొరికిన వస్తువును నమోదు చేయండి",
    "feed.saveParameters": "శోధన పారామితులను సేవ్ చేయండి",
    "feed.deleteSavedSearch": "సేవ్ చేసిన శోధనను తొలగించండి",
    "feed.universalSearchBar": "సార్వత్రిక శోధన పట్టీ",
    "feed.clearSearch": "శోధనను క్లియర్ చేయండి",
    "feed.toggleFilters": "అధునాతన ఫిల్టర్లను ఆన్/ఆఫ్ చేయండి",
    "feed.newestFirst": "కొత్తవి మొదట",
    "feed.oldestFirst": "పాతవి మొదట",
    "feed.highestReward": "అత్యధిక బహుమతి",
    "feed.closestDistance": "సమీప దూరం",
    "postcard.unlockConnection": "కనెక్షన్‌ను అన్‌లాక్ చేయండి",
    "postcard.iHaveThisItem": "ఈ వస్తువు నా దగ్గర ఉంది",
    "postcard.reclaimed": "తిరిగి పొందబడింది మరియు అప్పగించబడింది",
    "postcard.claims": "క్లెయిమ్‌లు",
    "postcard.image": "చిత్రం",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI సరిపోలిక",
    "postcard.geminiMatches": "జెమినీ స్మార్ట్ సరిపోలికలను కనుగొంది!",
    "postcard.contactOwner": "యజమానిని సంప్రదించండి",
    "postcard.creatorNotice": "ఈ జాబితా యొక్క ధృవీకరించబడిన సృష్టికర్త మాత్రమే సరిపోలిక వివరాలను చూడగలరు.",
    "postcard.markResolved": "పరిష్కరించబడినట్లు గుర్తించండి",
    "postcard.deleteListing": "జాబితాను తొలగించండి",
    "postcard.unlockWithPin": "సెక్యూరిటీ పిన్‌తో సంప్రదింపులను అన్‌లాక్ చేయండి",
    "postcard.manageClaims": "క్లెయిమ్‌లను నిర్వహించండి మరియు ఆమోదించండి/తిరస్కరించండి",
    "postcard.shareTemplate": "షేరింగ్ టెక్స్ట్‌ను కాపీ చేయండి",
    "postcard.downloadCard": "కార్డును చిత్రంగా డౌన్‌లోడ్ చేయండి",
    "postcard.qrSettings": "ఇంటరాక్టివ్ QR & ప్రింట్ సెట్టింగ్‌లు",
    "postcard.postedOn": "పోస్ట్ చేయబడింది",
    "postcard.reward": "బహుమతి",
    "postcard.secureHandover": "సురక్షిత అప్పగింత",
    "matches.title": "AI స్మార్ట్ సరిపోలికలు & పరస్పర ధృవీకరణ",
    "matches.subtitle": "జెమినీ పోయిన మరియు దొరికిన జాబితాలను పోల్చుతుంది. చాట్ చేయడానికి ముందు పరస్పర ధృవీకరణ తప్పనిసరి.",
    "matches.myMatches": "నా సరిపోలికలు",
    "matches.publicMatches": "పబ్లిక్ సరిపోలికలు",
    "matches.threshold": "కనిష్ట పరిమితి:",
    "matches.security": "భద్రత:",
    "matches.mutualApprovalRequired": "పరస్పర ఆమోదం అవసరం",
    "matches.noMatchesFound": "సంభావ్య సరిపోలికలు కనుగొనబడలేదు",
    "matches.improveReport": "మీ నివేదికను మెరుగుపరచండి",
    "matches.noPhoto": "ఫోటో లేదు",
    "matches.chatLive": "లైవ్ చాట్",
    "matches.chatLocked": "చాట్ లాక్ చేయబడింది",
    "matches.inspectReview": "తనిఖీ చేయండి & సమీక్షించండి",
    "matches.openChatLive": "లైవ్ చాట్‌ను తెరవండి",
    "matches.verifyApprove": "ధృవీకరించి ఆమోదించండి",
    "matches.approvalNotice": "చాట్ అన్‌లాక్ కావడానికి ముందు యజమాని మరియు కనుగొన్న వ్యక్తి ఇద్దరూ ధృవీకరణను ఆమోదించాలి.",
    "matches.tabComparison": "పోలిక",
    "matches.tabVerification": "ధృవీకరణ",
    "matches.tabTrust": "నమ్మకం & వాట్సాప్",
    "matches.tabHandover": "అప్పగింత",
    "matches.noImageProvided": "చిత్రం అందించబడలేదు",
    "matches.itemName": "వస్తువు పేరు",
    "matches.category": "వర్గం",
    "matches.reward": "బహుమతి",
    "matches.locationAddress": "ప్రదేశం & చిరునామా",
    "matches.detailsDescription": "వివరణాత్మక సమాచారం",
    "matches.finderContact": "కనుగొన్న వ్యక్తి సంప్రదింపు",
    "matches.matchStatus": "సరిపోలిక స్థితి:",
    "matches.mutualConfirmed": "పరస్పర ఆమోదం నిర్ధారించబడింది. ఇరుపక్షాలూ ధృవీకరణను పూర్తి చేశాయి.",
    "matches.mutualProtocol": "పరస్పర ధృవీకరణ ప్రోటోకాల్",
    "matches.protocolNotice": "మోసాన్ని నివారించడానికి ఇరుపక్షాలూ ధృవీకరణ వివరాలను సమర్పిస్తాయి. ఆమోదించే వరకు చాట్ లాక్ చేయబడుతుంది.",
    "matches.ownerStatus": "యజమాని స్థితి",
    "matches.submittedBy": "సమర్పించినవారు:",
    "matches.aiScore": "AI ధృవీకరణ స్కోరు:",
    "matches.ownerNotSubmitted": "యజమాని ఇంకా ధృవీకరణ సమాధానాలను సమర్పించలేదు.",
    "matches.finderStatus": "కనుగొన్న వ్యక్తి స్థితి",
    "matches.finderNotSubmitted": "కనుగొన్న వ్యక్తి ఇంకా సమాధానాలను సమర్పించలేదు.",
    "matches.actionControls": "చర్య నియంత్రణలు",
    "matches.selectRole": "వివరాలను సమర్పించడానికి లేదా సమీక్షించడానికి మీ పాత్రను ఎంచుకోండి.",
    "matches.iAmOwner": "నేను యజమానిని",
    "matches.iAmFinder": "నాకు ఈ వస్తువు దొరికింది",
    "matches.yourName": "మీ పేరు",
    "matches.contactWhatsApp": "వాట్సాప్ / సంప్రదింపు",
    "matches.forensicQuestions": "ఫోరెన్సిక్ ధృవీకరణ ప్రశ్నలు",
    "matches.trustTitle": "పరస్పర నమ్మకం & సురక్షిత వాట్సాప్ సంప్రదింపు",
    "matches.trustNotice": "భద్రత కోసం, ఇద్దరు వ్యక్తులు \"నేను ఈ వ్యక్తిని నమ్ముతున్నాను\" అని క్లిక్ చేసిన తర్వాతే ఫోన్ నంబర్లు కనిపిస్తాయి.",
    "matches.ownerTrust": "యజమాని నమ్మకం",
    "matches.finderTrust": "కనుగొన్న వ్యక్తి నమ్మకం",
    "matches.unlocked": "అన్‌లాక్ చేయబడింది",
    "matches.masked": "దాచబడింది",
    "matches.contactAlias": "సంప్రదింపు పేరు / మారుపేరు",
    "matches.phoneWhatsApp": "ఫోన్ / వాట్సాప్",
    "matches.openWhatsApp": "వాట్సాప్ చాట్ తెరవండి",
    "matches.directCall": "డైరెక్ట్ కాల్",
    "matches.trustInstructions": "వాట్సాప్ లింక్ మరియు ఫోన్ నంబర్ చూడటానికి క్రింది బటన్‌ను క్లిక్ చేయండి.",
    "matches.trustConsent": "నమ్మకాన్ని క్లిక్ చేయడం ద్వారా, సురక్షిత అప్పగింత కోసం సంప్రదింపు వివరాలను పంచుకోవడానికి మీరు అంగీకరిస్తున్నారు.",
    "matches.reunitedResolved": "వస్తువు విజయవంతంగా అప్పగించబడింది మరియు కేసు పరిష్కరించబడింది!",
    "matches.reunitedNotice": "యజమాని మరియు కనుగొన్న వ్యక్తి ఇద్దరూ సురక్షిత అప్పగింతను నిర్ధారించారు.",
    "matches.handoverProtocol": "సురక్షిత అప్పగింత ప్రోటోకాల్",
    "matches.handoverNotice": "బహిరంగ ప్రదేశంలో సమావేశం ఏర్పాటు చేసుకోండి (ఉదా. మెట్రో స్టేషన్ లేదా పోలీస్ స్టేషన్). అప్పగించిన తర్వాత ఇద్దరూ నిర్ధారించండి.",
    "matches.handoverSchedule": "అప్పగింత సమయం & ప్రదేశం",
    "matches.publicMeetingSpot": "బహిరంగ సమావేశ స్థలం",
    "matches.scheduledDateTime": "షెడ్యూల్ చేసిన తేదీ / సమయం",
    "matches.confirmHandover": "అప్పగింతను నిర్ధారించండి మరియు కేసును ముగించండి",
    "matches.confirmHandoverDesc": "వస్తువును పొందిన తర్వాత, ప్రక్రియను పూర్తి చేయడానికి నిర్ధారించండి.",
    "matches.iHandedOver": "నేను ఈ వస్తువును అప్పగించాను",
    "matches.iReceived": "నాకు నా వస్తువు అందింది",
    "matches.chatUnlocksAfter": "ధృవీకరణ తర్వాత సురక్షిత చాట్ అన్‌లాక్ అవుతుంది",
    "matches.chatUnlocksDesc": "క్లెయిమ్ ధృవీకరించబడిన తర్వాత ఇరుపక్షాల మధ్య సురక్షిత చాట్ స్వయంచాలకంగా ప్రారంభమవుతుంది.",
    "matches.goToVerification": "ధృవీకరణ ట్యాబ్‌కు వెళ్లండి",
    "matches.secureHandoverChat": "సురక్షిత అప్పగింత చాట్",
    "matches.connectionVerified": "కనెక్షన్ ధృవీకరించబడింది! సురక్షిత అప్పగింత కోసం సందేశం పంపండి.",
    "matches.dismissMatch": "సరిపోలికను విస్మరించండి",
    "matches.shareMatch": "భాగస్వామ్యం చేయండి",
    "matches.directClaim": "నేరుగా క్లెయిమ్ చేయండి",
    "claim.ownershipIndex": "యాజమాన్య విశ్వసనీయత సూచిక",
    "claim.safeVerification": "సురక్షిత యాజమాన్య ధృవీకరణ",
    "claim.stepsNotice": "అప్పగింతను సురక్షితంగా మరియు ప్రామాణికంగా చేయడానికి మేము ప్రైవేట్ దశలను ఉపయోగిస్తాము.",
    "claim.protectedContact": "మీ సంప్రదింపు వివరాలు పూర్తిగా సురక్షితం. ధృవీకరించబడిన వ్యక్తి మాత్రమే చూడగలరు.",
    "claim.unlockedMutual": "పరస్పర ధృవీకరణ తర్వాతే సంప్రదింపు ఎంపికలు అన్‌లాక్ చేయబడతాయి. మీ ఫోన్ ఎప్పుడూ బహిర్గతం కాదు.",
    "claim.aiEvaluationNotice": "మోసాన్ని నివారించడానికి మా AI క్లెయిమ్‌లను మూల్యాంకనం చేస్తుంది.",
    "claim.trackingNotice": "ప్రత్యేకమైన ట్రాకింగ్ కోడ్‌లు ఇరుపక్షాలను రక్షిస్తాయి.",
    "claim.modalDescription": "వస్తువు నిజమైన యజమానికి చేరేలా చూడటానికి, సంప్రదింపు వివరాలను పంచుకునే ముందు మేము సరిపోలికను ధృవీకరిస్తాము.",
    "claim.aiPreparingQuestions": "AI మీ ధృవీకరణ ప్రశ్నలను సిద్ధం చేస్తోంది...",
    "claim.claimantName": "క్లెయిమ్ చేసిన వ్యక్తి పేరు",
    "claim.officialNamePlaceholder": "మీ అధికారిక పేరు",
    "claim.whatsappMobile": "వాట్సాప్ మొబైల్",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "వస్తువు వివరాలను ధృవీకరించండి",
    "claim.detailsPlaceholder": "దయచేసి వివరంగా చెప్పండి (గుర్తులు, లోపలి విషయాలు, బిల్లు వివరాలు మొదలైనవి)...",
    "claim.verificationRegistered": "ధృవీకరణ నమోదు చేయబడింది",
    "claim.detailsSavedSecurely": "మీ వివరాలు సురక్షితంగా భద్రపరచబడ్డాయి. మా AI వివరాలను సరిపోల్చింది.",
    "claim.verificationId": "ధృవీకరణ ID (క్లెయిమ్ ID)",
    "claim.aiMatchDetails": "AI సరిపోలిక వివరాలు",
    "claim.bookmarkLink": "ప్రత్యక్ష లింక్ (తరువాత చూడటానికి సేవ్ చేయండి)",
    "claim.doneAwaitSignoff": "పూర్తయింది & యజమాని ఆమోదం కోసం వేచి ఉండండి",
    "auth.recoverBelongings": "విశ్వసనీయ పౌరులు మరియు తెలివైన ధృవీకరణ ద్వారా పోగొట్టుకున్న వస్తువులను సురక్షితంగా తిరిగి పొందండి.",
    "auth.startEmail": "ఇమెయిల్‌తో ప్రారంభించండి",
    "auth.continuePhone": "ఫోన్‌తో కొనసాగండి",
    "auth.signIn": "సైన్ ఇన్ చేయండి",
    "auth.welcomeBack": "తిరిగి స్వాగతం",
    "auth.resumeTracking": "ట్రాకింగ్‌ను కొనసాగించడానికి మీ ఖాతాలోకి సైన్ ఇన్ చేయండి.",
    "auth.emailOrUsername": "ఇమెయిల్ లేదా యూజర్‌నేమ్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "auth.createAccount": "ఖాతాను సృష్టించండి",
    "auth.joinNetwork": "రక్షక నెట్‌వర్క్‌లో చేరండి.",
    "auth.fullName": "పూర్తి పేరు",
    "auth.username": "యూజర్‌నేమ్",
    "auth.emailAddress": "ఇమెయిల్ చిరునామా",
    "auth.confirmPassword": "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    "auth.acceptPolicy": "నేను గోప్యతా విధానాన్ని అంగీకరిస్తున్నాను మరియు ఎన్‌క్రిప్ట్ చేసిన డేటా భాగస్వామ్యానికి సమ్మతిస్తున్నాను.",
    "auth.resetPassword": "పాస్‌వర్డ్‌ను రీసెట్ చేయండి",
    "auth.resetNotice": "ఖాతాను తిరిగి పొందడానికి మేము సురక్షిత లింక్‌ను పంపుతాము.",
    "auth.sendResetLink": "రీసెట్ లింక్ పంపండి",
    "auth.returnSignIn": "సైన్ ఇన్ వద్దకు తిరిగి వెళ్లండి",
    "auth.setupProfile": "మీ ప్రొఫైల్‌ను సెటప్ చేయండి",
    "auth.setupNotice": "ఇతరులు మీతో సమన్వయం చేసుకోవడానికి మీ ప్రొఫైల్‌ను పూర్తి చేయండి.",
    "auth.takeSnapshot": "ఫోటో తీయండి",
    "auth.choosePhoto": "ఫోటోను ఎంచుకోండి",
    "auth.cityNeighborhood": "నగరం / ప్రాంతం (తప్పనిసరి)",
    "auth.shortBio": "సంక్షిప్త పరిచయం (ఐచ్ఛికం)",
    "auth.completeSetup": "సెటప్‌ను పూర్తి చేయండి",
    "dashboard.welcomeTitle": "మీ ప్రొఫైల్‌ను సెటప్ చేయండి",
    "dashboard.welcomeDesc": "LINCO-కి స్వాగతం. సురక్షిత అప్పగింతను సమన్వయం చేసుకోవడానికి మీ గురించి సంక్షిప్తంగా చెప్పండి.",
    "dashboard.chooseAvatar": "అవతార్‌ను ఎంచుకోండి",
    "dashboard.fullName": "పూర్తి పేరు",
    "dashboard.username": "యూజర్‌నేమ్",
    "dashboard.bio": "పరిచయం (ఐచ్ఛికం)",
    "dashboard.city": "నగరం",
    "dashboard.createProfile": "ప్రొఫైల్‌ను సృష్టించండి",
    "dashboard.skipForNow": "ప్రస్తుతానికి దాటవేయి",
    "dashboard.changeCover": "కవర్‌ను మార్చండి",
    "dashboard.editProfile": "ప్రొఫైల్‌ను సవరించండి",
    "dashboard.shareProfile": "ప్రొఫైల్‌ను షేర్ చేయండి",
    "dashboard.settings": "సెట్టింగ్‌లు",
    "dashboard.editDetails": "వివరాలను సవరించండి",
    "dashboard.accountSection": "ఖాతా",
    "dashboard.email": "ఇమెయిల్",
    "dashboard.password": "పాస్‌వర్డ్",
    "dashboard.privacySection": "గోప్యత",
    "dashboard.blockedUsers": "బ్లాక్ చేయబడిన వినియోగదారులు",
    "dashboard.downloadData": "నా డేటాను డౌన్‌లోడ్ చేయండి",
    "dashboard.deleteAccount": "ఖాతాను తొలగించండి",
    "dashboard.notifSection": "నోటిఫికేషన్‌లు",
    "dashboard.pushNotifs": "పుష్ నోటిఫికేషన్‌లు",
    "dashboard.pushDesc": "తక్షణ సరిపోలికలు మరియు చాట్ కోసం నోటిఫికేషన్‌లు",
    "dashboard.emailReports": "ఇమెయిల్ నివేదికలు",
    "dashboard.emailDesc": "క్లెయిమ్ చేయని వస్తువుల వారపు సారాంశం",
    "dashboard.appearanceSection": "రూపం",
    "dashboard.theme": "థీమ్",
    "dashboard.language": "భాష",
    "dashboard.supportSection": "మద్దతు",
    "dashboard.help": "సహాయం",
    "dashboard.contact": "సంప్రదించండి",
    "dashboard.about": "గురించి",
    "dashboard.logout": "లాగ్ అవుట్ చేయండి",
    "dashboard.updateEmail": "ఇమెయిల్‌ను అప్‌డేట్ చేయండి",
    "dashboard.saveEmail": "ఇమెయిల్‌ను సేవ్ చేయండి",
    "dashboard.changePassword": "పాస్‌వర్డ్‌ను మార్చండి",
    "dashboard.unblock": "అన్‌బ్లాక్ చేయండి",
    "dashboard.noBlocked": "బ్లాక్ చేయబడిన వినియోగదారులు ఎవరూ లేరు.",
    "dashboard.contactSupport": "మద్దతును సంప్రదించండి",
    "dashboard.supportDesc": "సహాయం లేదా ప్రశ్నల కోసం మా బృందాన్ని సంప్రదించండి:",
    "dashboard.aboutLinco": "LINCO గురించి",
    "dashboard.aboutDesc": "LINCO అనేది జెమినీ AI ఉపయోగించి పోగొట్టుకున్న వస్తువులను కనుగొనడంలో సహాయపడే సురక్షితమైన యాప్.",
    "dashboard.appVersion": "యాప్ వెర్షన్: v1.3.0",
    "dashboard.capturePhoto": "ఫోటో తీయండి",
    "dashboard.useCamera": "కెమెరాను ఉపయోగించండి",
    "dashboard.chooseGallery": "గ్యాలరీ నుండి ఎంచుకోండి",
    "dashboard.confirmDeletion": "తొలగింపును నిర్ధారించండి",
    "dashboard.deletionWarning": "ఈ చర్య శాశ్వతమైనది. మీ మొత్తం డేటా తొలగించబడుతుంది.",
    "dashboard.typePasswordConfirm": "నిర్ధారించడానికి మీ పాస్‌వర్డ్‌ను టైప్ చేయండి",
    "dashboard.typeDeletePrompt": "ఖాతాను శాశ్వతంగా తొలగించడానికి క్రింద DELETE అని టైప్ చేయండి.",
    "ownerClaims.controlBoard": "క్లెయిమ్ నియంత్రణ బోర్డు",
    "ownerClaims.enterPin": "భద్రతా పిన్‌ను నమోదు చేయండి",
    "ownerClaims.pinDesc": "నమోదు సమయంలో ఇచ్చిన 4 అంకెల పిన్‌ను నమోదు చేయండి.",
    "ownerClaims.clear": "క్లియర్ చేయండి",
    "ownerClaims.authenticating": "ధృవీకరిస్తోంది...",
    "ownerClaims.integrityScore": "జెమినీ సమగ్రత స్కోరు",
    "ownerClaims.reviewNotice": "సమాధానాలను సమీక్షించండి. ఆమోదించడం వల్ల సురక్షిత రికవరీ గది సక్రియం అవుతుంది.",
    "ownerClaims.completeHandover": "అప్పగింతను పూర్తి చేయండి",
    "ownerClaims.postClosed": "ఈ పోస్ట్ మూసివేయబడింది. మునుపటి క్లెయిమ్‌ల చరిత్ర క్రింద ఉంది.",
    "ownerClaims.closeWindow": "విండోను మూసివేయండి",
    "ownerClaims.approved": "ఆమోదించబడింది",
    "ownerClaims.resolved": "పరిష్కరించబడింది",
    "ownerClaims.youReturned": "మీరు తిరిగి ఇచ్చారు:",
    "ownerClaims.meetingCoords": "సురక్షిత సమావేశ వివరాలను నమోదు చేయండి...",
    "pin.title": "భద్రతా పిన్ నమోదు",
    "pin.passcode": "4 అంకెల పాస్‌కోడ్",
    "pin.verifying": "ధృవీకరిస్తోంది...",
    "pin.clear": "క్లియర్ చేయండి",
    "pin.unlock": "సంప్రదింపులను అన్‌లాక్ చేయండి",
    "pin.promise": "మీ పిన్ మీ వ్యక్తిగత సమాచారాన్ని బహిరంగంగా వెల్లడి కాకుండా రక్షిస్తుంది.",
    "communityFound.title": "ఈ వస్తువు నా దగ్గర ఉంది",
    "communityFound.protocol": "జీరో-ట్రస్ట్ ప్రోటోకాల్",
    "communityFound.verifyFinding": "కనుగొనడాన్ని ధృవీకరించండి",
    "communityFound.withoutLeaking": "వ్యక్తిగత సమాచారాన్ని లీక్ చేయకుండా",
    "communityFound.lostReported": "పోయిన వస్తువు నమోదు",
    "communityFound.whereFound": "మీకు ఇది ఎక్కడ దొరికింది?",
    "communityFound.insideContents": "లోపలి విషయాలు / నిర్దిష్ట అంశాలు (ఐచ్ఛికం)",
    "communityFound.secretDetails": "ప్రత్యేక లక్షణాలు / రహస్య వివరాలు",
    "communityFound.createPin": "మీ భద్రతా పిన్‌ను సృష్టించండి",
    "communityFound.reward": "బహుమతి",
    "communityFound.registeredNotice": "నమోదు చేయబడింది. యజమానికి మీ సమాధానాలు తెలియజేయబడ్డాయి.",
    "claimTracker.title": "రికవరీ స్థితి కాలక్రమం",
    "claimTracker.protocols": "సురక్షిత రికవరీ ప్రోటోకాల్స్",
    "claimTracker.publicSpaces": "మెట్రో స్టేషన్ లేదా కేఫ్ వంటి బహిరంగ, వెలుతురు ఉన్న ప్రదేశాలలో కలవండి.",
    "claimTracker.verifyCarefully": "బహుమతి ఇచ్చే ముందు వస్తువును జాగ్రత్తగా తనిఖీ చేయండి.",
    "claimTracker.documentDetails": "సమావేశ వివరాలను రికార్డ్ చేయడానికి మా సురక్షిత చాట్‌ను ఉపయోగించండి.",
    "claimTracker.lookupAnother": "మరొకదాన్ని వెతకండి",
    "claimTracker.unsuccessful": "క్లెయిమ్ మూల్యాంకనం విఫలమైంది",
    "claimTracker.trustCheck": "పరస్పర నమ్మకం తనిఖీ",
    "claimTracker.awaitingApproval": "కనుగొన్న వ్యక్తి ఆమోదం కోసం వేచి ఉంది",
    "claimTracker.recoveryRoom": "సురక్షిత రికవరీ గది",
    "claimTracker.enterRoom": "రికవరీ గదిలోకి ప్రవేశించండి",
    "claimTracker.discussion": "సమన్వయ అప్పగింత చర్చ",
    "recovery.transmissionSecured": "డేటా సురక్షితం",
    "recovery.reportIndexed": "నివేదిక విజయవంతంగా సూచిక చేయబడింది",
    "recovery.dossierActive": "మీ ధృవీకరణ ఫైల్ సక్రియంగా ఉంది. జెమినీ సూచికలను విశ్లేషిస్తోంది.",
    "recovery.engineTitle": "AI రికవరీ సంభావ్యత ఇంజిన్",
    "recovery.retrievalLikelihood": "రికవరీ అవకాశం:",
    "recovery.analyzedFactors": "విశ్లేషించబడిన రికవరీ కారకాలు",
    "recovery.semanticNotice": "మా మోడల్ సరిపోల్చడానికి బ్రాండ్, రంగు మరియు గుర్తులను సంగ్రహిస్తుంది.",
    "recovery.uniqueIdentifier": "ప్రత్యేకమైన గుర్తింపు పూర్తి ధృవీకరించబడిన సరిపోలికను అనుమతిస్తుంది.",
    "recovery.setReward": "బహుమతిని నిర్ణయించండి",
    "reward.fairRange": "సముచిత పరిధి",
    "reward.suggestReward": "బహుమతిని సూచించండి",
    "reward.customReward": "అనుకూల బహుమతి మొత్తం",
    "privacy.complianceProtocols": "వర్తింపు, గోప్యత & నమ్మకం ప్రోటోకాల్స్",
    "privacy.title": "నమ్మకం & వర్తింపు కేంద్రం",
    "privacy.subtitle": "మేము వినియోగదారు భద్రత మరియు పారదర్శకత యొక్క అత్యున్నత ప్రమాణాలను పాటిస్తాము.",
    "privacy.exitSection": "విభాగం నుండి నిష్క్రమించండి",
    "privacy.privacyPolicy": "గోప్యతా విధానం",
    "privacy.lastUpdated": "చివరి అప్‌డేట్: జూలై 7, 2026. డేటా కనిష్టత మా పునాది.",
    "privacy.dataAcquisition": "పోయిన వస్తువులను కనుగొనడానికి అవసరమైన డేటాను మాత్రమే మేము సేకరిస్తాము:",
    "privacy.spatiotemporalTags": "ప్రదేశ-సమయ ట్యాగ్‌లు:",
    "privacy.coldStorage": "స్వయంచాలక నిల్వకు ముందు గరిష్ట పరిమితి.",
    "privacy.cookiePreferences": "కుకీ ప్రాధాన్యతలను నిర్వహించండి.",
    "privacy.purgeBrowser": "కుకీలు మరియు కాష్ చేసిన డేటాను వెంటనే తొలగించండి.",
    "privacy.hereToHelp": "సహాయం చేయడానికి మేము ఇక్కడ ఉన్నాము.",
    "privacy.connectFounder": "అభిప్రాయం లేదా సహాయం కోసం మా ప్రొఫైల్‌ను సంప్రదించండి.",
    "cookie.title": "గోప్యతా సార్వభౌమత్వం",
    "cookie.message": "వస్తువులను తిరిగి పొందడానికి అవసరమైన సమాచారాన్ని మాత్రమే మేము సేకరిస్తాము.",
    "cookie.trackingNotice": "యాజమాన్యం నిరూపించబడే వరకు మీ గుర్తింపు ప్రైవేట్‌గా ఉంటుంది. ట్రాకింగ్ లేదు.",
    "cookie.acceptAll": "అన్నింటినీ అంగీకరించండి",
    "cookie.learnMore": "మరింత తెలుసుకోండి",
    "about.tagline": "కమ్యూనిటీలను అనుసంధానించడం, వస్తువులను తిరిగి పొందడం",
    "about.mission": "LINCO నైతిక AI మరియు కమ్యూనిటీ నమ్మకం ద్వారా పోగొట్టుకున్న వస్తువులను నిజమైన యజమానులకు చేర్చడానికి అంకితమైంది.",
    "notifications.title": "నోటిఫికేషన్‌లు",
    "notifications.empty": "కొత్త నోటిఫికేషన్‌లు లేవు",
    "notifications.markAllRead": "అన్నింటినీ చదివినట్లు గుర్తించండి",
    "notifications.clearAll": "అన్నింటినీ క్లియర్ చేయండి",
    "notifications.matchFoundTitle": "సంభావ్య సరిపోలిక దొరికింది",
    "notifications.matchFoundMsg": "మా AI సరిపోలిక ఇంజిన్ ద్వారా సంభావ్య సరిపోలిక కనుగొనబడింది.",
    "notifications.claimReceivedTitle": "కొత్త క్లెయిమ్ సమర్పించబడింది",
    "notifications.claimReceivedMsg": "ఒక వినియోగదారు మీ జాబితా కోసం ధృవీకరణ సమాధానాలను సమర్పించారు.",
    "notifications.claimApprovedTitle": "క్లెయిమ్ ఆమోదించబడింది",
    "notifications.claimApprovedMsg": "మీ క్లెయిమ్ యజమాని ద్వారా ధృవీకరించబడి ఆమోదించబడింది.",
    "notifications.chatMessageTitle": "రికవరీ గదిలో కొత్త సందేశం",
    "notifications.chatMessageMsg": "మీ రికవరీ సమన్వయం గురించి ఒక కొత్త సందేశం వచ్చింది.",
    "notifications.handoverDoneTitle": "అప్పగింత నిర్ధారించబడింది",
    "notifications.handoverDoneMsg": "వస్తువు తిరిగి పొందడం నిర్ధారించబడింది మరియు కేసు పరిష్కరించబడింది.",
    "enhance.button": "AI వివరణను మెరుగుపరచండి",
    "enhance.loading": "జెమినీ AI మీ వివరణను క్రమబద్ధీకరిస్తోంది...",
    "enhance.apply": "మెరుగుపరచిన వివరణను ఉపయోగించండి",
    "enhance.discard": "అసలు వివరణను ఉంచండి",
    "enhance.rewardTitle": "AI న్యాయమైన బహుమతి సూచన",
    "enhance.rewardCalculated": "సూచించిన బహుమతి: ₹",
    "enhance.rewardReason": "వస్తువు వర్గం, బ్రాండ్ విలువ మరియు కమ్యూనిటీ ప్రమాణాల ఆధారంగా.",
    "timeline.reconstruct": "టైమ్‌లైన్‌ను పునర్నిర్మించండి",
    "timeline.loading": "ప్రయాణ మార్గం మరియు చెక్‌పాయింట్‌లు విశ్లేషించబడుతున్నాయి...",
    "timeline.spotLikelihood": "పోగొట్టుకున్న సంభావ్య ప్రదేశం:",
    "timeline.window": "సంభావ్య సమయ పరిధి:",
    "timeline.analysis": "పూర్తి ప్రయాణ విశ్లేషణ:",
    "timeline.confidence": "మార్గ విశ్వసనీయత:",
    "timeline.addPoint": "చెక్‌పాయింట్‌ను జోడించండి",
    "timeline.pointName": "చెక్‌పాయింట్ పేరు / స్టేషన్",
    "chat.assistant": "AI సహాయకుడు",
    "chat.subtitle": "మీ సంభాషణ సహచరుడు",
    "chat.description": "పోగొట్టుకున్న లేదా దొరికిన వస్తువును 60 సెకన్లలో నివేదించండి. మాట్లాడండి లేదా టైప్ చేయండి.",
    "chat.startAssistant": "AI నివేదిక సహాయకుడిని ప్రారంభించండి",
    "chat.location": "ప్రదేశం:",
    "chat.securityPin": "భద్రతా పిన్:",
    "chat.skipPhoto": "ఫోటోను దాటవేయి",
    "chat.item": "వస్తువు:",
    "chat.errorLoading": "సహాయకుడిని లోడ్ చేయడంలో లోపం ఏర్పడింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    "chat.welcomeMessage": "LINCO Saathii కి స్వాగతం! ఏం పోయింది లేదా దొరికిందో చెప్పండి.",
    "chat.networkError": "నెట్‌వర్క్ సమస్య ఏర్పడింది. దయచేసి మళ్లీ ప్రయత్నించండి!",
    "chat.understoodError": "స్పష్టంగా అర్థం కాలేదు. మరిన్ని వివరాలు అందించగలరా?",
    "feed.lostOnly": "పోయిన వస్తువులు",
    "feed.foundOnly": "దొరికిన వస్తువులు",
    "feed.filterByCategory": "వర్గం",
    "feed.filterByCity": "నగరం",
    "feed.filterByUrgency": "అత్యవసర స్థాయి",
    "feed.empty": "శోధన ప్రమాణాలకు సరిపోయే వస్తువులు ఏవీ లేవు.",
    "feed.emptyAction": "కొత్త వస్తువును నివేదించండి",
    "matches.contactFinder": "కనుగొన్న వ్యక్తిని సంప్రదించండి",
    "matches.contactOwner": "యజమానిని సంప్రదించండి",
    "matches.verifyOwnership": "యాజమాన్యాన్ని ధృవీకరించండి",
    "claim.title": "యాజమాన్య క్లెయిమ్‌ను సమర్పించండి",
    "claim.subtitle": "సంప్రదింపు వివరాలు లీక్ కాకుండా AI భద్రతతో యాజమాన్యాన్ని ధృవీకరించండి.",
    "claim.questionsTitle": "ధృవీకరణ ప్రశ్నలు",
    "claim.questionsSubtitle": "నిజమైన యాజమాన్యాన్ని నిరూపించడానికి ప్రశ్నలకు సమాధానం ఇవ్వండి:",
    "claim.answerPlaceholder": "ఈ ప్రశ్నకు మీ సమాధానం...",
    "claim.submit": "సమీక్ష కోసం సమర్పించండి",
    "claim.submitting": "ధృవీకరణ వివరాలు సమర్పించబడుతున్నాయి...",
    "claim.success": "క్లెయిమ్ సమర్పించబడింది! యజమాని మీ సమాధానాలను సమీక్షిస్తారు.",
    "dashboard.myReports": "నా నివేదికలు",
    "dashboard.myClaims": "నా క్లెయిమ్‌లు",
    "dashboard.savedPosts": "సేవ్ చేసిన పోస్ట్‌లు",
    "help.title": "తరచుగా అడిగే ప్రశ్నలు",
    "help.q1": "LINCO నా గోప్యతను ఎలా రక్షిస్తుంది?",
    "help.a1": "LINCO మీ సంప్రదింపు వివరాలను ఎప్పుడూ బహిర్గతం చేయదు. ధృవీకరణ తర్వాతే అది అన్‌లాక్ అవుతుంది.",
    "help.q2": "నేను పోగొట్టుకున్న వస్తువును నివేదించినప్పుడు ఏమి జరుగుతుంది?",
    "help.a2": "మా AI మీ నివేదికను వివిధ నగరాల్లో దొరికిన వస్తువులతో పోల్చుతుంది.",
    "help.q3": "యాజమాన్య ధృవీకరణ ఎలా పనిచేస్తుంది?",
    "help.a3": "నిజమైన యజమానికి మాత్రమే తెలిసిన రహస్య ప్రశ్నలకు సమాధానం ఇవ్వాలి.",
    "help.q4": "LINCO ఉపయోగించడానికి ఉచితమా?",
    "help.a4": "అవును, LINCO పూర్తిగా ఉచితం మరియు కమ్యూనిటీ ఆధారితం.",
    "home.heroTitle": "AI & ధృవీకరించబడిన నమ్మకంతో పోగొట్టుకున్న వస్తువులను తిరిగి పొందండి",
    "home.heroSubtitle": "భారతదేశ కమ్యూనిటీ ఆధారిత ప్లాట్‌ఫారమ్. సురక్షితమైనది మరియు జెమినీ AI మద్దతు కలది.",
    "home.statsRecovered": "తిరిగి పొందిన వస్తువులు",
    "home.statsActive": "క్రియాశీల పౌరులు",
    "home.statsCities": "కవర్ చేయబడిన నగరాలు",
    "home.howItWorks": "LINCO ఎలా పనిచేస్తుంది",
    "home.step1Title": "1. సెకన్లలో నివేదించండి",
    "home.step1Desc": "39 భాషల్లో వాయిస్, టెక్స్ట్ లేదా ఫోటో ద్వారా నమోదు చేయండి.",
    "home.step2Title": "2. స్మార్ట్ AI సరిపోలిక",
    "home.step2Desc": "జెమినీ దృశ్య లక్షణాలు మరియు వివరణలను పోలుస్తుంది.",
    "home.step3Title": "3. ధృవీకరించబడిన అప్పగింత",
    "home.step3Desc": "రహస్య ప్రశ్నల ద్వారా ధృవీకరించి సురక్షితంగా వస్తువును పొందండి.",
}
'''

KN_CODE = '''
KN_NEW = {
    "category.Wallet / Purse": "ವಾಲೆಟ್ / ಪರ್ಸ್",
    "category.Bag / Luggage": "ಬ್ಯಾಗ್ / ಲಗೇಜ್",
    "category.ID / Card": "ಗುರುತಿನ ಚೀಟಿ / ಕಾರ್ಡ್",
    "urgency.Contains ID": "ಗುರುತಿನ ಚೀಟಿ ಒಳಗೊಂಡಿದೆ",
    "voice.stop": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
    "voice.error": "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆಯಲ್ಲಿ ದೋಷ ಕಂಡುಬಂದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "voice.hint": "ವಸ್ತುವಿನ ಬ್ರ್ಯಾಂಡ್, ಬಣ್ಣ, ಸ್ಥಳ ಮತ್ತು ದಿನಾಂಕದಂತಹ ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ.",
    "report.title": "ವಸ್ತುವನ್ನು ವರದಿ ಮಾಡಿ",
    "report.subtitle": "ಕಳೆದುಹೋದ ಅಥವಾ ಕಂಡುಬಂದ ವಸ್ತುವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ನೋಂದಾಯಿಸಿ.",
    "report.type": "ವರದಿಯ ಪ್ರಕಾರ",
    "report.typeLost": "ನನ್ನ ವಸ್ತು ಕಳೆದುಹೋಗಿದೆ",
    "report.typeFound": "ನನಗೆ ಒಂದು ವಸ್ತು ಸಿಕ್ಕಿದೆ",
    "report.stepBasics": "1. ಮೂಲ ವಿವರಗಳು",
    "report.stepLocation": "2. ಸ್ಥಳ & ದಿನಾಂಕ",
    "report.stepPhotos": "3. ಫೋಟೋಗಳು & ಸುಳಿವುಗಳು",
    "report.stepSecurity": "4. ಭದ್ರತೆ & ಸಂಪರ್ಕ",
    "report.itemTitle": "ವಸ್ತುವಿನ ಹೆಸರು",
    "report.itemTitlePlaceholder": "ಉದಾ. ಕಪ್ಪು ಲೆದರ್ ಟೈಟಾನ್ ವಾಚ್, ನೀಲಿ ವೈಲ್ಡ್‌ಕ್ರಾಫ್ಟ್ ಬ್ಯಾಗ್",
    "report.category": "ವರ್ಗ",
    "report.selectCategory": "ವಸ್ತುವಿನ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "report.description": "ವಿವರವಾದ ವಿವರಣೆ",
    "report.descriptionPlaceholder": "ಬಣ್ಣ, ಮಾದರಿ, ಗುರುತುಗಳು, ಒಳಗಿನ ವಸ್ತುಗಳು ಇತ್ಯಾದಿಗಳನ್ನು ತಿಳಿಸಿ...",
    "report.location": "ಸ್ಥಳ (ಸಿಕ್ಕಿದ / ಕಳೆದುಹೋದ ಸ್ಥಳ)",
    "report.locationPlaceholder": "ಉದಾ. ಮೆಜೆಸ್ಟಿಕ್ ಮೆಟ್ರೋ ನಿಲ್ದಾಣ ಗೇಟ್ 2, ಬೆಂಗಳೂರು",
    "report.date": "ದಿನಾಂಕ & ಅಂದಾಜು ಸಮಯ",
    "report.urgency": "ತುರ್ತು ಮಟ್ಟ",
    "report.urgencyNormal": "ಸಾಮಾನ್ಯ",
    "report.urgencyUrgent": "ತುರ್ತು",
    "report.urgencyMedical": "ವೈದ್ಯಕೀಯ / ಅತ್ಯಂತ ಮಹತ್ವದ",
    "report.photos": "ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "report.photosHint": "ಸ್ಪಷ್ಟ ಫೋಟೋಗಳು AI ಹೊಂದಾಣಿಕೆಯನ್ನು ಹೆಚ್ಚು ನಿಖರಗೊಳಿಸುತ್ತವೆ.",
    "report.reward": "ಬಹುಮಾನದ ಮೊತ್ತ (ಐಚ್ಛಿಕ)",
    "report.rewardPlaceholder": "₹ ಮೊತ್ತ ರೂಪಾಯಿಗಳಲ್ಲಿ",
    "report.contact": "ವಾಟ್ಸಾಪ್ / ಫೋನ್ ಸಂಪರ್ಕ",
    "report.contactPlaceholder": "10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    "report.pin": "4 ಅಂಕಿಗಳ ಭದ್ರತಾ ಪಿನ್",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "ನಂತರ ಸಂಪಾದಿಸಲು ಅಥವಾ ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲು ಅಗತ್ಯವಿದೆ.",
    "report.submit": "ವರದಿಯನ್ನು ಪ್ರಕಟಿಸಿ",
    "report.submitting": "ಸುರಕ್ಷಿತ ರಿಜಿಸ್ಟ್ರಿಯಲ್ಲಿ ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ...",
    "report.success": "ನಿಮ್ಮ ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕಟಗೊಂಡಿದೆ!",
    "report.viewListing": "ಪಟ್ಟಿಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ",
    "report.brand": "ಬ್ರ್ಯಾಂಡ್ / ತಯಾರಕ",
    "report.brandPlaceholder": "ಉದಾ. ಆಪಲ್, ಸ್ಯಾಮ್‌ಸಂಗ್, ಟೈಟಾನ್, ವೈಲ್ಡ್‌ಕ್ರಾಫ್ಟ್",
    "report.primaryColor": "ಮುಖ್ಯ ಬಣ್ಣ",
    "report.secondaryColor": "ದ್ವಿತೀಯ ಬಣ್ಣ",
    "report.landmark": "ಹತ್ತಿರದ ಹೆಗ್ಗುರುತು",
    "report.landmarkPlaceholder": "ಉದಾ. ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ 3 ಎಸ್ಕಲೇಟರ್ ಹತ್ತಿರ, ಕೆಫೆ ಎದುರು",
    "report.secretClue": "ರಹಸ್ಯ ಗುರುತಿನ ಸುಳಿವು (ಪರಿಶೀಲನೆಗಾಗಿ)",
    "report.secretCluePlaceholder": "ಉದಾ. ಒಳಗಿನ ಜೇಬಿನಲ್ಲಿ ಕೆಂಪು ಕೀಚೈನ್, 'RS' ಎಂದು ಕೆತ್ತಿದ ಹೆಸರು",
    "feed.searchPlaceholder": "ವಸ್ತುಗಳು, ಟ್ಯಾಗ್‌ಗಳು, ಬಣ್ಣಗಳು, ನಗರಗಳನ್ನು ಹುಡುಕಿ...",
    "feed.filters": "ಫಿಲ್ಟರ್‌ಗಳು",
    "feed.applyFilters": "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ",
    "feed.recentSearches": "ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು",
    "feed.savedSearches": "ಉಳಿಸಿದ ಹುಡುಕಾಟಗಳು",
    "feed.listingRegistry": "ಪಟ್ಟಿಯ ರಿಜಿಸ್ಟ್ರಿ",
    "feed.category": "ವರ್ಗ",
    "feed.allCategories": "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    "feed.city": "ನಗರ",
    "feed.allCities": "ಎಲ್ಲಾ ನಗರಗಳು",
    "feed.dateRange": "ದಿನಾಂಕ ಶ್ರೇಣಿ",
    "feed.proximity": "ದೂರದ ತ್ರಿಜ್ಯ",
    "feed.allProximities": "ಎಲ್ಲಾ ದೂರಗಳು (ಯಾವುದೇ ತ್ರಿಜ್ಯ)",
    "feed.within5km": "5 ಕಿ.ಮೀ ಒಳಗೆ",
    "feed.within15km": "15 ಕಿ.ಮೀ ಒಳಗೆ",
    "feed.within30km": "30 ಕಿ.ಮೀ ಒಳಗೆ",
    "feed.within50km": "50 ಕಿ.ಮೀ ಒಳಗೆ",
    "feed.sortCatalog": "ವಿಂಗಡಿಸಿ",
    "feed.colorSwatch": "ಬಣ್ಣದ ಪ್ಯಾಲೆಟ್",
    "feed.allColors": "ಎಲ್ಲಾ ಬಣ್ಣಗಳು",
    "feed.hardwareBrand": "ಬ್ರ್ಯಾಂಡ್ ತಯಾರಕ",
    "feed.allBrands": "ಎಲ್ಲಾ ಬ್ರ್ಯಾಂಡ್‌ಗಳು",
    "feed.resetFilters": "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ",
    "feed.viewList": "ಪಟ್ಟಿ",
    "feed.viewMap": "ನಕ್ಷೆ",
    "feed.noMatchesFound": "ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    "feed.noMatchesDesc": "ಈ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಯಾವುದೇ ವಸ್ತುಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ. ಹುಡುಕಾಟ ಪದಗಳನ್ನು ಬದಲಾಯಿಸಿ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ.",
    "feed.reportItem": "ಕಳೆದುಹೋದ/ಕಂಡುಬಂದ ವಸ್ತುವನ್ನು ವರದಿ ಮಾಡಿ",
    "feed.saveParameters": "ಹುಡುಕಾಟ ನಿಯತಾಂಕಗಳನ್ನು ಉಳಿಸಿ",
    "feed.deleteSavedSearch": "ಉಳಿಸಿದ ಹುಡುಕಾಟವನ್ನು ಅಳಿಸಿ",
    "feed.universalSearchBar": "ಸಾರ್ವತ್ರಿಕ ಹುಡುಕಾಟ ಪಟ್ಟಿ",
    "feed.clearSearch": "ಹುಡುಕಾಟವನ್ನು ತೆರವುಗೊಳಿಸಿ",
    "feed.toggleFilters": "ಸುಧಾರಿತ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಆನ್/ಆಫ್ ಮಾಡಿ",
    "feed.newestFirst": "ಹೊಸತು ಮೊದಲು",
    "feed.oldestFirst": "ಹಳೆಯದು ಮೊದಲು",
    "feed.highestReward": "ಹೆಚ್ಚಿನ ಬಹುಮಾನ",
    "feed.closestDistance": "ಹತ್ತಿರದ ದೂರ",
    "postcard.unlockConnection": "ಸಂಪರ್ಕವನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    "postcard.iHaveThisItem": "ಈ ವಸ್ತು ನನ್ನಲ್ಲಿದೆ",
    "postcard.reclaimed": "ಮರಳಿ ಪಡೆಯಲಾಗಿದೆ & ಹಸ್ತಾಂತರಿಸಲಾಗಿದೆ",
    "postcard.claims": "ಹಕ್ಕುಗಳು",
    "postcard.image": "ಚಿತ್ರ",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI ಹೊಂದಾಣಿಕೆ",
    "postcard.geminiMatches": "ಜೆಮಿನಿ ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಕಂಡುಕೊಂಡಿದೆ!",
    "postcard.contactOwner": "ಮಾಲೀಕರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "postcard.creatorNotice": "ಪರಿಶೀಲಿಸಿದ ಸೃಷ್ಟಿಕರ್ತರು ಮಾತ್ರ ಹೊಂದಾಣಿಕೆ ವಿವರಗಳನ್ನು ನೋಡಬಹುದು.",
    "postcard.markResolved": "ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    "postcard.deleteListing": "ಪಟ್ಟಿಯನ್ನು ಅಳಿಸಿ",
    "postcard.unlockWithPin": "ಭದ್ರತಾ ಪಿನ್‌ನೊಂದಿಗೆ ಸಂಪರ್ಕವನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    "postcard.manageClaims": "ಹಕ್ಕುಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಅನುಮೋದಿಸಿ/ತಿರಸ್ಕರಿಸಿ",
    "postcard.shareTemplate": "ಹಂಚಿಕೆ ಪಠ್ಯವನ್ನು ನಕಲಿಸಿ",
    "postcard.downloadCard": "ಕಾರ್ಡ್ ಅನ್ನು ಚಿತ್ರವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "postcard.qrSettings": "QR & ಮುದ್ರಣ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "postcard.postedOn": "ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ",
    "postcard.reward": "ಬಹುಮಾನ",
    "postcard.secureHandover": "ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರ",
    "matches.title": "AI ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆಗಳು & ಪರಸ್ಪರ ಪರಿಶೀಲನೆ",
    "matches.subtitle": "ಜೆಮಿನಿ ಕಳೆದುಹೋದ ಮತ್ತು ಸಿಕ್ಕಿದ ಪಟ್ಟಿಗಳನ್ನು ಹೋಲಿಸುತ್ತದೆ. ಚಾಟ್ ಮಾಡುವ ಮೊದಲು ಪರಸ್ಪರ ಪರಿಶೀಲನೆ ಕಡ್ಡಾಯವಾಗಿದೆ.",
    "matches.myMatches": "ನನ್ನ ಹೊಂದಾಣಿಕೆಗಳು",
    "matches.publicMatches": "ಸಾರ್ವಜನಿಕ ಹೊಂದಾಣಿಕೆಗಳು",
    "matches.threshold": "ಕನಿಷ್ಠ ಮಿತಿ:",
    "matches.security": "ಭದ್ರತೆ:",
    "matches.mutualApprovalRequired": "ಪರಸ್ಪರ ಅನುಮೋದನೆ ಅಗತ್ಯವಿದೆ",
    "matches.noMatchesFound": "ಯಾವುದೇ ಸಂಭಾವ್ಯ ಹೊಂದಾಣಿಕೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    "matches.improveReport": "ನಿಮ್ಮ ವರದಿಯನ್ನು ಸುಧಾರಿಸಿ",
    "matches.noPhoto": "ಫೋಟೋ ಇಲ್ಲ",
    "matches.chatLive": "ಲೈವ್ ಚಾಟ್",
    "matches.chatLocked": "ಚಾಟ್ ಲಾಕ್ ಆಗಿದೆ",
    "matches.inspectReview": "ಪರಿಶೀಲಿಸಿ & ವಿಮರ್ಶಿಸಿ",
    "matches.openChatLive": "ಲೈವ್ ಚಾಟ್ ತೆರೆಯಿರಿ",
    "matches.verifyApprove": "ಪರಿಶೀಲಿಸಿ & ಅನುಮೋದಿಸಿ",
    "matches.approvalNotice": "ಚಾಟ್ ಅನ್‌ಲಾಕ್ ಆಗುವ ಮೊದಲು ಮಾಲೀಕರು ಮತ್ತು ಪತ್ತೆದಾರರು ಇಬ್ಬರೂ ಪರಿಶೀಲನೆಯನ್ನು ಅನುಮೋದಿಸಬೇಕು.",
    "matches.tabComparison": "ಹೋಲಿಕೆ",
    "matches.tabVerification": "ಪರಿಶೀಲನೆ",
    "matches.tabTrust": "ನಂಬಿಕೆ & ವಾಟ್ಸಾಪ್",
    "matches.tabHandover": "ಹಸ್ತಾಂತರ",
    "matches.noImageProvided": "ಯಾವುದೇ ಚಿತ್ರವನ್ನು ಒದಗಿಸಲಾಗಿಲ್ಲ",
    "matches.itemName": "ವಸ್ತುವಿನ ಹೆಸರು",
    "matches.category": "ವರ್ಗ",
    "matches.reward": "ಬಹುಮಾನ",
    "matches.locationAddress": "ಸ್ಥಳ & ವಿಳಾಸ",
    "matches.detailsDescription": "ವಿವರವಾದ ಮಾಹಿತಿ",
    "matches.finderContact": "ಪತ್ತೆದಾರರ ಸಂಪರ್ಕ",
    "matches.matchStatus": "ಹೊಂದಾಣಿಕೆಯ ಸ್ಥಿತಿ:",
    "matches.mutualConfirmed": "ಪರಸ್ಪರ ಅನುಮೋದನೆ ದೃಢಪಟ್ಟಿದೆ. ಎರಡೂ ಕಡೆಯವರು ಪರಿಶೀಲನೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ.",
    "matches.mutualProtocol": "ಪರಸ್ಪರ ಪರಿಶೀಲನಾ ಪ್ರೋಟೋಕಾಲ್",
    "matches.protocolNotice": "ವಂಚನೆಯನ್ನು ತಡೆಯಲು ಎರಡೂ ಕಡೆಯವರು ಪರಿಶೀಲನಾ ವಿವರಗಳನ್ನು ಸಲ್ಲಿಸುತ್ತಾರೆ. ಅನುಮೋದಿಸುವವರೆಗೆ ಚಾಟ್ ಲಾಕ್ ಆಗಿರುತ್ತದೆ.",
    "matches.ownerStatus": "ಮಾಲೀಕರ ಸ್ಥಿತಿ",
    "matches.submittedBy": "ಸಲ್ಲಿಸಿದವರು:",
    "matches.aiScore": "AI ಪರಿಶೀಲನಾ ಸ್ಕೋರ್:",
    "matches.ownerNotSubmitted": "ಮಾಲೀಕರು ಇನ್ನೂ ಪರಿಶೀಲನಾ ಉತ್ತರಗಳನ್ನು ಸಲ್ಲಿಸಿಲ್ಲ.",
    "matches.finderStatus": "ಪತ್ತೆದಾರರ ಸ್ಥಿತಿ",
    "matches.finderNotSubmitted": "ಪತ್ತೆದಾರರು ಇನ್ನೂ ಉತ್ತರಗಳನ್ನು ಸಲ್ಲಿಸಿಲ್ಲ.",
    "matches.actionControls": "ಕ್ರಮ ನಿಯಂತ್ರಣಗಳು",
    "matches.selectRole": "ವಿವರಗಳನ್ನು ಸಲ್ಲಿಸಲು ಅಥವಾ ಪರಿಶೀಲಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    "matches.iAmOwner": "ನಾನು ಮಾಲೀಕ",
    "matches.iAmFinder": "ನನಗೆ ಈ ವಸ್ತು ಸಿಕ್ಕಿದೆ",
    "matches.yourName": "ನಿಮ್ಮ ಹೆಸರು",
    "matches.contactWhatsApp": "ವಾಟ್ಸಾಪ್ / ಸಂಪರ್ಕ",
    "matches.forensicQuestions": "ವಿಧಿವಿಜ್ಞಾನ ಪರಿಶೀಲನಾ ಪ್ರಶ್ನೆಗಳು",
    "matches.trustTitle": "ಪರಸ್ಪರ ನಂಬಿಕೆ & ಸುರಕ್ಷಿತ ವಾಟ್ಸಾಪ್ ಸಂಪರ್ಕ",
    "matches.trustNotice": "ಭದ್ರತೆಗಾಗಿ, ಇಬ್ಬರೂ ಬಳಕೆದಾರರು \"ನಾನು ಈ ವ್ಯಕ್ತಿಯನ್ನು ನಂಬುತ್ತೇನೆ\" ಎಂದು ಕ್ಲಿಕ್ ಮಾಡಿದ ನಂತರವೇ ಫೋನ್ ಸಂಖ್ಯೆಗಳು ಗೋಚರಿಸುತ್ತವೆ.",
    "matches.ownerTrust": "ಮಾಲೀಕರ ನಂಬಿಕೆ",
    "matches.finderTrust": "ಪತ್ತೆದಾರರ ನಂಬಿಕೆ",
    "matches.unlocked": "ಅನ್‌ಲಾಕ್ ಮಾಡಲಾಗಿದೆ",
    "matches.masked": "ಮರೆಮಾಡಲಾಗಿದೆ",
    "matches.contactAlias": "ಸಂಪರ್ಕ ಹೆಸರು / ಅಡ್ಡಹೆಸರು",
    "matches.phoneWhatsApp": "ಫೋನ್ / ವಾಟ್ಸಾಪ್",
    "matches.openWhatsApp": "ವಾಟ್ಸಾಪ್ ಚಾಟ್ ತೆರೆಯಿರಿ",
    "matches.directCall": "ನೇರ ಕರೆ",
    "matches.trustInstructions": "ವಾಟ್ಸಾಪ್ ಲಿಂಕ್ ಮತ್ತು ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನೋಡಲು ಕೆಳಗಿನ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    "matches.trustConsent": "ನಂಬಿಕೆಯನ್ನು ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ, ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರಕ್ಕಾಗಿ ಸಂಪರ್ಕ ವಿವರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ನೀವು ಸಮ್ಮತಿಸುತ್ತೀರಿ.",
    "matches.reunitedResolved": "ವಸ್ತು ಯಶಸ್ವಿಯಾಗಿ ಹಸ್ತಾಂತರಗೊಂಡಿದೆ ಮತ್ತು ಪ್ರಕರಣ ಇತ್ಯರ್ಥವಾಗಿದೆ!",
    "matches.reunitedNotice": "ಮಾಲೀಕರು ಮತ್ತು ಪತ್ತೆದಾರರು ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರವನ್ನು ದೃಢಪಡಿಸಿದ್ದಾರೆ.",
    "matches.handoverProtocol": "ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರ ಪ್ರೋಟೋಕಾಲ್",
    "matches.handoverNotice": "ಸಾರ್ವಜನಿಕ ಸ್ಥಳದಲ್ಲಿ ಭೇಟಿಯಾಗಲು ಯೋಜಿಸಿ (ಉದಾ. ಮೆಟ್ರೋ ನಿಲ್ದಾಣ ಅಥವಾ ಪೊಲೀಸ್ ಠಾಣೆ). ಹಸ್ತಾಂತರಿಸಿದ ನಂತರ ಇಬ್ಬರೂ ದೃಢೀಕರಿಸಿ.",
    "matches.handoverSchedule": "ಹಸ್ತಾಂತರ ಸಮಯ & ಸ್ಥಳ",
    "matches.publicMeetingSpot": "ಸಾರ್ವಜನಿಕ ಭೇಟಿಯ ಸ್ಥಳ",
    "matches.scheduledDateTime": "ನಿಗದಿತ ದಿನಾಂಕ / ಸಮಯ",
    "matches.confirmHandover": "ಹಸ್ತಾಂತರವನ್ನು ದೃಢೀಕರಿಸಿ ಮತ್ತು ಪ್ರಕರಣವನ್ನು ಮುಕ್ತಾಯಗೊಳಿಸಿ",
    "matches.confirmHandoverDesc": "ವಸ್ತುವನ್ನು ಸ್ವೀಕರಿಸಿದ ನಂತರ, ಪ್ರಕ್ರಿಯೆಯನ್ನು ಅಂತಿಮಗೊಳಿಸಲು ದೃಢೀಕರಿಸಿ.",
    "matches.iHandedOver": "ನಾನು ಈ ವಸ್ತುವನ್ನು ಹಸ್ತಾಂತರಿಸಿದ್ದೇನೆ",
    "matches.iReceived": "ನನಗೆ ನನ್ನ ವಸ್ತು ಸಿಕ್ಕಿದೆ",
    "matches.chatUnlocksAfter": "ಪರಿಶೀಲನೆಯ ನಂತರ ಸುರಕ್ಷಿತ ಚಾಟ್ ಅನ್‌ಲಾಕ್ ಆಗುತ್ತದೆ",
    "matches.chatUnlocksDesc": "ಹಕ್ಕು ಪರಿಶೀಲನೆಯ ನಂತರ ಎರಡೂ ಕಡೆಯವರ ನಡುವೆ ಸುರಕ್ಷಿತ ಚಾಟ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ತೆರೆಯುತ್ತದೆ.",
    "matches.goToVerification": "ಪರಿಶೀಲನಾ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ",
    "matches.secureHandoverChat": "ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರ ಚಾಟ್",
    "matches.connectionVerified": "ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ! ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರಕ್ಕಾಗಿ ಸಂದೇಶ ಕಳುಹಿಸಿ.",
    "matches.dismissMatch": "ಹೊಂದಾಣಿಕೆಯನ್ನು ತಿರಸ್ಕರಿಸಿ",
    "matches.shareMatch": "ಹಂಚಿಕೊಳ್ಳಿ",
    "matches.directClaim": "ನೇರ ಹಕ್ಕು",
    "claim.ownershipIndex": "ಮಾಲೀಕತ್ವದ ವಿಶ್ವಾಸಾರ್ಹತೆ ಸೂಚ್ಯಂಕ",
    "claim.safeVerification": "ಸುರಕ್ಷಿತ ಮಾಲೀಕತ್ವ ಪರಿಶೀಲನೆ",
    "claim.stepsNotice": "ಹಸ್ತಾಂತರವನ್ನು ಸುರಕ್ಷಿತ ಮತ್ತು ನೈಜವಾಗಿಸಲು ನಾವು ಖಾಸಗಿ ಹಂತಗಳನ್ನು ಬಳಸುತ್ತೇವೆ.",
    "claim.protectedContact": "ನಿಮ್ಮ ಸಂಪರ್ಕ ವಿವರಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿವೆ. ಪರಿಶೀಲಿಸಿದ ವ್ಯಕ್ತಿ ಮಾತ್ರ ನೋಡಬಹುದು.",
    "claim.unlockedMutual": "ಪರಸ್ಪರ ಪರಿಶೀಲನೆಯ ನಂತರವೇ ಸಂಪರ್ಕ ಆಯ್ಕೆಗಳು ತೆರೆಯಲ್ಪಡುತ್ತವೆ. ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಸಾರ್ವಜನಿಕವಾಗುವುದಿಲ್ಲ.",
    "claim.aiEvaluationNotice": "ವಂಚನೆಯನ್ನು ತಡೆಯಲು ನಮ್ಮ AI ಹಕ್ಕುಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ.",
    "claim.trackingNotice": "ವಿಶಿಷ್ಟ ಟ್ರ್ಯಾಕಿಂಗ್ ಕೋಡ್‌ಗಳು ಎರಡೂ ಕಡೆಯವರನ್ನು ರಕ್ಷಿಸುತ್ತವೆ.",
    "claim.modalDescription": "ವಸ್ತು ನಿಜವಾದ ಮಾಲೀಕರನ್ನು ತಲುಪಲು, ಸಂಪರ್ಕವನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಮೊದಲು ನಾವು ಹೊಂದಾಣಿಕೆಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತೇವೆ.",
    "claim.aiPreparingQuestions": "AI ನಿಮ್ಮ ಪರಿಶೀಲನಾ ಪ್ರಶ್ನೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ...",
    "claim.claimantName": "ಹಕ್ಕುದಾರರ ಹೆಸರು",
    "claim.officialNamePlaceholder": "ನಿಮ್ಮ ಅಧಿಕೃತ ಹೆಸರು",
    "claim.whatsappMobile": "ವಾಟ್ಸಾಪ್ ಮೊಬೈಲ್",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "ವಸ್ತುವಿನ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    "claim.detailsPlaceholder": "ದಯವಿಟ್ಟು ವಿವರವಾಗಿ ತಿಳಿಸಿ (ಗುರುತುಗಳು, ಒಳಗಿನ ವಸ್ತುಗಳು, ಬಿಲ್ ವಿವರಗಳು ಇತ್ಯಾದಿ)...",
    "claim.verificationRegistered": "ಪರಿಶೀಲನೆ ನೋಂದಾಯಿಸಲಾಗಿದೆ",
    "claim.detailsSavedSecurely": "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಉಳಿಸಲಾಗಿದೆ. ನಮ್ಮ AI ವಿವರಗಳನ್ನು ಹೋಲಿಸಿದೆ.",
    "claim.verificationId": "ಪರಿಶೀಲನಾ ID (ಹಕ್ಕು ID)",
    "claim.aiMatchDetails": "AI ಹೊಂದಾಣಿಕೆ ವಿವರಗಳು",
    "claim.bookmarkLink": "ನೇರ ಲಿಂಕ್ (ನಂತರ ನೋಡಲು ಉಳಿಸಿ)",
    "claim.doneAwaitSignoff": "ಪೂರ್ಣಗೊಂಡಿದೆ & ಮಾಲೀಕರ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಿರಿ",
    "auth.recoverBelongings": "ವಿಶ್ವಾಸಾರ್ಹ ನಾಗರಿಕರು ಮತ್ತು ಬುದ್ಧಿವಂತ ಪರಿಶೀಲನೆಯ ಮೂಲಕ ಕಳೆದುಹೋದ ವಸ್ತುಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಮರಳಿ ಪಡೆಯಿರಿ.",
    "auth.startEmail": "ಇಮೇಲ್ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ",
    "auth.continuePhone": "ಫೋನ್ ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ",
    "auth.signIn": "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "auth.welcomeBack": "ಮತ್ತೆ ಸುಸ್ವಾಗತ",
    "auth.resumeTracking": "ಟ್ರ್ಯಾಕಿಂಗ್ ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    "auth.emailOrUsername": "ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರಹೆಸರು",
    "auth.password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth.forgotPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
    "auth.createAccount": "ಖಾತೆಯನ್ನು ರಚಿಸಿ",
    "auth.joinNetwork": "ರಕ್ಷಕರ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ.",
    "auth.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "auth.username": "ಬಳಕೆದಾರಹೆಸರು",
    "auth.emailAddress": "ಇಮೇಲ್ ವಿಳಾಸ",
    "auth.confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    "auth.acceptPolicy": "ನಾನು ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೇನೆ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ ಡೇಟಾ ಹಂಚಿಕೆಗೆ ಸಮ್ಮತಿಸುತ್ತೇನೆ.",
    "auth.resetPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
    "auth.resetNotice": "ಖಾತೆಯನ್ನು ಮರಳಿ ಪಡೆಯಲು ನಾವು ಸುರಕ್ಷಿತ ಲಿಂಕ್ ಕಳುಹಿಸುತ್ತೇವೆ.",
    "auth.sendResetLink": "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
    "auth.returnSignIn": "ಸೈನ್ ಇನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "auth.setupProfile": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ",
    "auth.setupNotice": "ಇತರರು ನಿಮ್ಮೊಂದಿಗೆ ಸಮನ್ವಯ ಸಾಧಿಸಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ.",
    "auth.takeSnapshot": "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    "auth.choosePhoto": "ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ",
    "auth.cityNeighborhood": "ನಗರ / ಪ್ರದೇಶ (ಅಗತ್ಯ)",
    "auth.shortBio": "ಸಂಕ್ಷಿಪ್ತ ಪರಿಚಯ (ಐಚ್ಛಿಕ)",
    "auth.completeSetup": "ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    "dashboard.welcomeTitle": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ",
    "dashboard.welcomeDesc": "LINCO-ಗೆ ಸುಸ್ವಾಗತ. ಸುರಕ್ಷಿತ ಹಸ್ತಾಂತರವನ್ನು ಸಂಘಟಿಸಲು ನಿಮ್ಮ ಬಗ್ಗೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ತಿಳಿಸಿ.",
    "dashboard.chooseAvatar": "ಅವತಾರವನ್ನು ಆರಿಸಿ",
    "dashboard.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "dashboard.username": "ಬಳಕೆದಾರಹೆಸರು",
    "dashboard.bio": "ಪರಿಚಯ (ಐಚ್ಛಿಕ)",
    "dashboard.city": "ನಗರ",
    "dashboard.createProfile": "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    "dashboard.skipForNow": "ಸದ್ಯಕ್ಕೆ ಬಿಟ್ಟುಬಿಡಿ",
    "dashboard.changeCover": "ಕವರ್ ಬದಲಾಯಿಸಿ",
    "dashboard.editProfile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    "dashboard.shareProfile": "ಪ್ರೊಫೈಲ್ ಹಂಚಿಕೊಳ್ಳಿ",
    "dashboard.settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "dashboard.editDetails": "ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    "dashboard.accountSection": "ಖಾತೆ",
    "dashboard.email": "ಇಮೇಲ್",
    "dashboard.password": "ಪಾಸ್‌ವರ್ಡ್",
    "dashboard.privacySection": "ಗೌಪ್ಯತೆ",
    "dashboard.blockedUsers": "ನಿರ್ಬಂಧಿಸಿದ ಬಳಕೆದಾರರು",
    "dashboard.downloadData": "ನನ್ನ ಡೇಟಾ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "dashboard.deleteAccount": "ಖಾತೆಯನ್ನು ಅಳಿಸಿ",
    "dashboard.notifSection": "ಅಧಿಸೂಚನೆಗಳು",
    "dashboard.pushNotifs": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    "dashboard.pushDesc": "ತ್ವರಿತ ಹೊಂದಾಣಿಕೆಗಳು ಮತ್ತು ಚಾಟ್‌ಗಾಗಿ ಅಧಿಸೂಚನೆಗಳು",
    "dashboard.emailReports": "ಇಮೇಲ್ ವರದಿಗಳು",
    "dashboard.emailDesc": "ಕ್ಲೈಮ್ ಮಾಡದ ವಸ್ತುಗಳ ಸಾಪ್ತಾಹಿಕ ಸಾರಾಂಶ",
    "dashboard.appearanceSection": "ಗೋಚರತೆ",
    "dashboard.theme": "ಥೀಮ್",
    "dashboard.language": "ಭಾಷೆ",
    "dashboard.supportSection": "ಬೆಂಬಲ",
    "dashboard.help": "ಸಹಾಯ",
    "dashboard.contact": "ಸಂಪರ್ಕಿಸಿ",
    "dashboard.about": "ಬಗ್ಗೆ",
    "dashboard.logout": "ಲಾಗ್ ಔಟ್ ಮಾಡಿ",
    "dashboard.updateEmail": "ಇಮೇಲ್ ನವೀಕರಿಸಿ",
    "dashboard.saveEmail": "ಇಮೇಲ್ ಉಳಿಸಿ",
    "dashboard.changePassword": "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
    "dashboard.unblock": "ಅನ್‌ಬ್ಲಾಕ್ ಮಾಡಿ",
    "dashboard.noBlocked": "ಯಾವುದೇ ನಿರ್ಬಂಧಿತ ಬಳಕೆದಾರರಿಲ್ಲ.",
    "dashboard.contactSupport": "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "dashboard.supportDesc": "ಸಹಾಯ ಅಥವಾ ಪ್ರಶ್ನೆಗಳಿಗಾಗಿ ನಮ್ಮ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ:",
    "dashboard.aboutLinco": "LINCO ಬಗ್ಗೆ",
    "dashboard.aboutDesc": "LINCO ಎಂಬುದು ಜೆಮಿನಿ AI ಬಳಸಿ ಕಳೆದುಹೋದ ವಸ್ತುಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುವ ಸುರಕ್ಷಿತ ಅಪ್ಲಿಕೇಶನ್ ಆಗಿದೆ.",
    "dashboard.appVersion": "ಅಪ್ಲಿಕೇಶನ್ ಆವೃತ್ತಿ: v1.3.0",
    "dashboard.capturePhoto": "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    "dashboard.useCamera": "ಕ್ಯಾಮರಾ ಬಳಸಿ",
    "dashboard.chooseGallery": "ಗ್ಯಾಲರಿಯಿಂದ ಆರಿಸಿ",
    "dashboard.confirmDeletion": "ಅಳಿಸುವಿಕೆಯನ್ನು ದೃಢೀಕರಿಸಿ",
    "dashboard.deletionWarning": "ಈ ಕ್ರಿಯೆಯು ಶಾಶ್ವತವಾಗಿದೆ. ನಿಮ್ಮ ಎಲ್ಲಾ ಡೇಟಾ ಅಳಿಸಲ್ಪಡುತ್ತದೆ.",
    "dashboard.typePasswordConfirm": "ದೃಢೀಕರಿಸಲು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಟೈಪ್ ಮಾಡಿ",
    "dashboard.typeDeletePrompt": "ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲು ಕೆಳಗೆ DELETE ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    "ownerClaims.controlBoard": "ಹಕ್ಕು ನಿಯಂತ್ರಣ ಮಂಡಳಿ",
    "ownerClaims.enterPin": "ಭದ್ರತಾ ಪಿನ್ ನಮೂದಿಸಿ",
    "ownerClaims.pinDesc": "ನೋಂದಣಿ ಸಮಯದಲ್ಲಿ ನೀಡಲಾದ 4 ಅಂಕಿಗಳ ಪಿನ್ ನಮೂದಿಸಿ.",
    "ownerClaims.clear": "ತೆರವುಗೊಳಿಸಿ",
    "ownerClaims.authenticating": "ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
    "ownerClaims.integrityScore": "ಜೆಮಿನಿ ಸಮಗ್ರತೆ ಸ್ಕೋರ್",
    "ownerClaims.reviewNotice": "ಉತ್ತರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ. ಅನುಮೋದಿಸುವುದು ಸುರಕ್ಷಿತ ಮರುಪಡೆಯುವಿಕೆ ಕೊಠಡಿಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ.",
    "ownerClaims.completeHandover": "ಹಸ್ತಾಂತರವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ",
    "ownerClaims.postClosed": "ಈ ಪೋಸ್ಟ್ ಮುಚ್ಚಲಾಗಿದೆ. ಹಿಂದಿನ ಹಕ್ಕುಗಳ ಇತಿಹಾಸ ಕೆಳಗಿದೆ.",
    "ownerClaims.closeWindow": "ವಿಂಡೋ ಮುಚ್ಚಿ",
    "ownerClaims.approved": "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    "ownerClaims.resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "ownerClaims.youReturned": "ನೀವು ಹಿಂತಿರುಗಿಸಿದ್ದೀರಿ:",
    "ownerClaims.meetingCoords": "ಸುರಕ್ಷಿತ ಸಭೆಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ...",
    "pin.title": "ಭದ್ರತಾ ಪಿನ್ ಪ್ರವೇಶ",
    "pin.passcode": "4 ಅಂಕಿಗಳ ಪಾಸ್‌ಕೋಡ್",
    "pin.verifying": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "pin.clear": "ತೆರವುಗೊಳಿಸಿ",
    "pin.unlock": "ಸಂಪರ್ಕವನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    "pin.promise": "ನಿಮ್ಮ ಪಿನ್ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಸಾರ್ವಜನಿಕ ಪ್ರವೇಶದಿಂದ ರಕ್ಷಿಸುತ್ತದೆ.",
    "communityFound.title": "ಈ ವಸ್ತು ನನ್ನಲ್ಲಿದೆ",
    "communityFound.protocol": "ಶೂನ್ಯ-ನಂಬಿಕೆ ಪ್ರೋಟೋಕಾಲ್",
    "communityFound.verifyFinding": "ಕಂಡುಹಿಡಿದಿದ್ದನ್ನು ಪರಿಶೀಲಿಸಿ",
    "communityFound.withoutLeaking": "ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಸೋರಿಕೆ ಮಾಡದೆ",
    "communityFound.lostReported": "ಕಳೆದುಹೋದ ವಸ್ತುವಿನ ವರದಿ",
    "communityFound.whereFound": "ಇದು ನಿಮಗೆ ಎಲ್ಲಿ ಸಿಕ್ಕಿತು?",
    "communityFound.insideContents": "ಒಳಗಿನ ವಸ್ತುಗಳು / ನಿರ್ದಿಷ್ಟ ಅಂಶಗಳು (ಐಚ್ಛಿಕ)",
    "communityFound.secretDetails": "ವಿಶಿಷ್ಟ ಲಕ್ಷಣಗಳು / ರಹಸ್ಯ ವಿವರಗಳು",
    "communityFound.createPin": "ನಿಮ್ಮ ಭದ್ರತಾ ಪಿನ್ ರಚಿಸಿ",
    "communityFound.reward": "ಬಹುಮಾನ",
    "communityFound.registeredNotice": "ನೋಂದಾಯಿಸಲಾಗಿದೆ. ಮಾಲೀಕರಿಗೆ ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ತಿಳಿಸಲಾಗಿದೆ.",
    "claimTracker.title": "ಮರುಪಡೆಯುವಿಕೆ ಸ್ಥಿತಿ ಟೈಮ್‌ಲೈನ್",
    "claimTracker.protocols": "ಸುರಕ್ಷಿತ ಮರುಪಡೆಯುವಿಕೆ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು",
    "claimTracker.publicSpaces": "ಮೆಟ್ರೋ ನಿಲ್ದಾಣ ಅಥವಾ ಕೆಫೆಯಂತಹ ಸಾರ್ವಜನಿಕ ಮತ್ತು ಬೆಳಕಿರುವ ಸ್ಥಳಗಳಲ್ಲಿ ಭೇಟಿಯಾಗಿ.",
    "claimTracker.verifyCarefully": "ಬಹುಮಾನ ನೀಡುವ ಮೊದಲು ವಸ್ತುವನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಪರಿಶೀಲಿಸಿ.",
    "claimTracker.documentDetails": "ಸಭೆಯ ವಿವರಗಳನ್ನು ದಾಖಲಿಸಲು ನಮ್ಮ ಸುರಕ್ಷಿತ ಚಾಟ್ ಬಳಸಿ.",
    "claimTracker.lookupAnother": "ಮತ್ತೊಂದನ್ನು ಹುಡುಕಿ",
    "claimTracker.unsuccessful": "ಹಕ್ಕು ಮೌಲ್ಯಮಾಪನ ವಿಫಲವಾಗಿದೆ",
    "claimTracker.trustCheck": "ಪರಸ್ಪರ ನಂಬಿಕೆ ತಪಾಸಣೆ",
    "claimTracker.awaitingApproval": "ಪತ್ತೆದಾರರ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    "claimTracker.recoveryRoom": "ಸುರಕ್ಷಿತ ಮರುಪಡೆಯುವಿಕೆ ಕೊಠಡಿ",
    "claimTracker.enterRoom": "ಕೊಠಡಿಯನ್ನು ಪ್ರವೇಶಿಸಿ",
    "claimTracker.discussion": "ಸಂಘಟಿತ ಹಸ್ತಾಂತರ ಚರ್ಚೆ",
    "recovery.transmissionSecured": "ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ",
    "recovery.reportIndexed": "ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಸೂಚ್ಯಂಕಗೊಂಡಿದೆ",
    "recovery.dossierActive": "ನಿಮ್ಮ ಪರಿಶೀಲನಾ ಫೈಲ್ ಸಕ್ರಿಯವಾಗಿದೆ. ಜೆಮಿನಿ ಸೂಚ್ಯಂಕಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ.",
    "recovery.engineTitle": "AI ಮರುಪಡೆಯುವಿಕೆ ಸಂಭವನೀಯತೆ ಎಂಜಿನ್",
    "recovery.retrievalLikelihood": "ಮರುಪಡೆಯುವಿಕೆಯ ಸಂಭವನೀಯತೆ:",
    "recovery.analyzedFactors": "ವಿಶ್ಲೇಷಿಸಿದ ಅಂಶಗಳು",
    "recovery.semanticNotice": "ನಮ್ಮ ಮಾದರಿಯು ಹೊಂದಾಣಿಕೆಗಾಗಿ ಬ್ರ್ಯಾಂಡ್, ಬಣ್ಣ ಮತ್ತು ಗುರುತುಗಳನ್ನು ಹೊರತೆಗೆಯುತ್ತದೆ.",
    "recovery.uniqueIdentifier": "ವಿಶಿಷ್ಟ ಗುರುತಿಸುವಿಕೆಯು ಪೂರ್ಣ ಪರಿಶೀಲಿಸಿದ ಹೊಂದಾಣಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ.",
    "recovery.setReward": "ಬಹುಮಾನವನ್ನು ನಿಗದಿಪಡಿಸಿ",
    "reward.fairRange": "ಸಮಂಜಸವಾದ ವ್ಯಾಪ್ತಿ",
    "reward.suggestReward": "ಬಹುಮಾನವನ್ನು ಸೂಚಿಸಿ",
    "reward.customReward": "ಕಸ್ಟಮ್ ಬಹುಮಾನ ಮೊತ್ತ",
    "privacy.complianceProtocols": "ಅನುಸರಣೆ, ಗೌಪ್ಯತೆ & ನಂಬಿಕೆ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು",
    "privacy.title": "ನಂಬಿಕೆ & ಅನುಸರಣೆ ಕೇಂದ್ರ",
    "privacy.subtitle": "ನಾವು ಬಳಕೆದಾರರ ಸುರಕ್ಷತೆ ಮತ್ತು ಪಾರದರ್ಶಕತೆಯ ಅತ್ಯುನ್ನತ ಮಾನದಂಡಗಳನ್ನು ಅನುಸರಿಸುತ್ತೇವೆ.",
    "privacy.exitSection": "ವಿಭಾಗದಿಂದ ನಿರ್ಗಮಿಸಿ",
    "privacy.privacyPolicy": "ಗೌಪ್ಯತಾ ನೀತಿ",
    "privacy.lastUpdated": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್: ಜುಲೈ 7, 2026. ಡೇಟಾ ಕನಿಷ್ಠೀಕರಣ ನಮ್ಮ ಅಡಿಪಾಯ.",
    "privacy.dataAcquisition": "ಕಳೆದುಹೋದ ವಸ್ತುಗಳನ್ನು ಹುಡುಕಲು ಅಗತ್ಯವಿರುವ ಡೇಟಾವನ್ನು ಮಾತ್ರ ನಾವು ಸಂಗ್ರಹಿಸುತ್ತೇವೆ:",
    "privacy.spatiotemporalTags": "ಸ್ಥಳ-ಸಮಯದ ಟ್ಯಾಗ್‌ಗಳು:",
    "privacy.coldStorage": "ಸ್ವಯಂಚಾಲಿತ ಸಂಗ್ರಹಣೆಗೆ ಮುಂಚಿನ ಗರಿಷ್ಠ ಮಿತಿ.",
    "privacy.cookiePreferences": "ಕುಕೀ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    "privacy.purgeBrowser": "ಕುಕೀಗಳು ಮತ್ತು ಕ್ಯಾಶ್ ಡೇಟಾವನ್ನು ತಕ್ಷಣ ತೆರವುಗೊಳಿಸಿ.",
    "privacy.hereToHelp": "ನಾವು ಸಹಾಯ ಮಾಡಲು ಇಲ್ಲಿದ್ದೇವೆ.",
    "privacy.connectFounder": "ಪ್ರತಿಕ್ರಿಯೆ ಅಥವಾ ಸಹಾಯಕ್ಕಾಗಿ ನಮ್ಮ ಪ್ರೊಫೈಲ್ ಸಂಪರ್ಕಿಸಿ.",
    "cookie.title": "ಗೌಪ್ಯತೆ ಸಾರ್ವಭೌಮತ್ವ",
    "cookie.message": "ವಸ್ತುಗಳನ್ನು ಮರಳಿ ಪಡೆಯಲು ಅಗತ್ಯವಿರುವ ಮಾಹಿತಿಯನ್ನು ಮಾತ್ರ ನಾವು ಸಂಗ್ರಹಿಸುತ್ತೇವೆ.",
    "cookie.trackingNotice": "ಮಾಲೀಕತ್ವ ಸಾಬೀತಾಗುವವರೆಗೆ ನಿಮ್ಮ ಗುರುತು ಖಾಸಗಿಯಾಗಿರುತ್ತದೆ. ಯಾವುದೇ ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ.",
    "cookie.acceptAll": "ಎಲ್ಲವನ್ನೂ ಒಪ್ಪಿಕೊಳ್ಳಿ",
    "cookie.learnMore": "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
    "about.tagline": "ಸಮುದಾಯಗಳನ್ನು ಸಂಪರ್ಕಿಸುವುದು, ವಸ್ತುಗಳನ್ನು ಮರಳಿ ಪಡೆಯುವುದು",
    "about.mission": "LINCO ನೈತಿಕ AI ಮತ್ತು ಸಮುದಾಯದ ನಂಬಿಕೆಯನ್ನು ಬಳಸಿಕೊಂಡು ಕಳೆದುಹೋದ ವಸ್ತುಗಳನ್ನು ಮಾಲೀಕರಿಗೆ ಮರಳಿಸಲು ಬದ್ಧವಾಗಿದೆ.",
    "notifications.title": "ಅಧಿಸೂಚನೆಗಳು",
    "notifications.empty": "ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
    "notifications.markAllRead": "ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    "notifications.clearAll": "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
    "notifications.matchFoundTitle": "ಸಂಭಾವ್ಯ ಹೊಂದಾಣಿಕೆ ಕಂಡುಬಂದಿದೆ",
    "notifications.matchFoundMsg": "ನಮ್ಮ AI ಹೊಂದಾಣಿಕೆ ಎಂಜಿನ್ ಮೂಲಕ ಸಂಭಾವ್ಯ ಹೊಂದಾಣಿಕೆಯನ್ನು ಗುರುತಿಸಲಾಗಿದೆ.",
    "notifications.claimReceivedTitle": "ಹೊಸ ಹಕ್ಕು ಸಲ್ಲಿಕೆಯಾಗಿದೆ",
    "notifications.claimReceivedMsg": "ಬಳಕೆದಾರರೊಬ್ಬರು ನಿಮ್ಮ ಪಟ್ಟಿಗೆ ಪರಿಶೀಲನಾ ಉತ್ತರಗಳನ್ನು ಸಲ್ಲಿಸಿದ್ದಾರೆ.",
    "notifications.claimApprovedTitle": "ಹಕ್ಕು ಅನುಮೋದಿಸಲಾಗಿದೆ",
    "notifications.claimApprovedMsg": "ನಿಮ್ಮ ಹಕ್ಕನ್ನು ಮಾಲೀಕರು ಪರಿಶೀಲಿಸಿ ಅನುಮೋದಿಸಿದ್ದಾರೆ.",
    "notifications.chatMessageTitle": "ಮರುಪಡೆಯುವಿಕೆ ಕೊಠಡಿಯಲ್ಲಿ ಹೊಸ ಸಂದೇಶ",
    "notifications.chatMessageMsg": "ನಿಮ್ಮ ಸಮನ್ವಯದ ಕುರಿತು ಹೊಸ ಸಂದೇಶ ಬಂದಿದೆ.",
    "notifications.handoverDoneTitle": "ಹಸ್ತಾಂತರ ದೃಢಪಟ್ಟಿದೆ",
    "notifications.handoverDoneMsg": "ವಸ್ತು ಮರಳಿ ಪಡೆದಿರುವುದು ದೃಢಪಟ್ಟಿದೆ ಮತ್ತು ಪ್ರಕರಣ ಇತ್ಯರ್ಥವಾಗಿದೆ.",
    "enhance.button": "AI ವಿವರಣೆಯನ್ನು ಸುಧಾರಿಸಿ",
    "enhance.loading": "ಜೆಮಿನಿ AI ವಿವರಣೆಯನ್ನು ಸರಿಹೊಂದಿಸುತ್ತಿದೆ...",
    "enhance.apply": "ಸುಧಾರಿತ ವಿವರಣೆಯನ್ನು ಬಳಸಿ",
    "enhance.discard": "ಮೂಲ ವಿವರಣೆಯನ್ನು ಉಳಿಸಿಕೊಳ್ಳಿ",
    "enhance.rewardTitle": "AI ನ್ಯಾಯಯುತ ಬಹುಮಾನ ಸಲಹೆ",
    "enhance.rewardCalculated": "ಸೂಚಿಸಲಾದ ಬಹುಮಾನ: ₹",
    "enhance.rewardReason": "ವಸ್ತುವಿನ ವರ್ಗ, ಬ್ರ್ಯಾಂಡ್ ಮೌಲ್ಯ ಮತ್ತು ಸಮುದಾಯ ಮಾನದಂಡಗಳ ಆಧಾರದ ಮೇಲೆ.",
    "timeline.reconstruct": "ಟೈಮ್‌ಲೈನ್‌ ಮರುನಿರ್ಮಾಣ ಮಾಡಿ",
    "timeline.loading": "ಪ್ರಯಾಣದ ಹಾದಿ ಮತ್ತು ಚೆಕ್‌ಪಾಯಿಂಟ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    "timeline.spotLikelihood": "ಕಳೆದುಹೋಗಿರಬಹುದಾದ ಸ್ಥಳ:",
    "timeline.window": "ಸಂಭಾವ್ಯ ಸಮಯದ ಮಿತಿ:",
    "timeline.analysis": "ಸಂಪೂರ್ಣ ಪ್ರಯಾಣದ ವಿಶ್ಲೇಷಣೆ:",
    "timeline.confidence": "ಹಾದಿಯ ವಿಶ್ವಾಸಾರ್ಹತೆ:",
    "timeline.addPoint": "ಚೆಕ್‌ಪಾಯಿಂಟ್‌ ಸೇರಿಸಿ",
    "timeline.pointName": "ಚೆಕ್‌ಪಾಯಿಂಟ್ ಹೆಸರು / ನಿಲ್ದಾಣ",
    "chat.assistant": "AI ಸಹಾಯಕ",
    "chat.subtitle": "ನಿಮ್ಮ ಸಂಭಾಷಣಾ ಸಂಗಾತಿ",
    "chat.description": "ಕಳೆದುಹೋದ ಅಥವಾ ಕಂಡುಬಂದ ವಸ್ತುವನ್ನು 60 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ವರದಿ ಮಾಡಿ. ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.",
    "chat.startAssistant": "AI ವರದಿ ಸಹಾಯಕರನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "chat.location": "ಸ್ಥಳ:",
    "chat.securityPin": "ಭದ್ರತಾ ಪಿನ್:",
    "chat.skipPhoto": "ಫೋಟೋ ಬಿಟ್ಟುಬಿಡಿ",
    "chat.item": "ವಸ್ತು:",
    "chat.errorLoading": "ಸಹಾಯಕರನ್ನು ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ ಕಂಡುಬಂದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "chat.welcomeMessage": "LINCO Saathii ಗೆ ಸುಸ್ವಾಗತ! ಏನು ಕಳೆದುಹೋಗಿದೆ ಅಥವಾ ಸಿಕ್ಕಿದೆ ಎಂದು ಹೇಳಿ.",
    "chat.networkError": "ನೆಟ್‌ವರ್ಕ್ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ!",
    "chat.understoodError": "ಸ್ಪಷ್ಟವಾಗಿ ಅರ್ಥವಾಗಲಿಲ್ಲ. ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ನೀಡಲು ಸಾಧ್ಯವೇ?",
    "feed.lostOnly": "ಕಳೆದುಹೋದ ವಸ್ತುಗಳು",
    "feed.foundOnly": "ಕಂಡುಬಂದ ವಸ್ತುಗಳು",
    "feed.filterByCategory": "ವರ್ಗ",
    "feed.filterByCity": "ನಗರ",
    "feed.filterByUrgency": "ತುರ್ತು ಮಟ್ಟ",
    "feed.empty": "ಹುಡುಕಾಟದ ಮಾನದಂಡಗಳಿಗೆ ಯಾವುದೇ ವಸ್ತುಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.",
    "feed.emptyAction": "ಹೊಸ ವಸ್ತುವನ್ನು ವರದಿ ಮಾಡಿ",
    "matches.contactFinder": "ಪತ್ತೆದಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "matches.contactOwner": "ಮಾಲೀಕರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "matches.verifyOwnership": "ಮಾಲೀಕತ್ವವನ್ನು ಪರಿಶೀಲಿಸಿ",
    "claim.title": "ಮಾಲೀಕತ್ವದ ಹಕ್ಕನ್ನು ಸಲ್ಲಿಸಿ",
    "claim.subtitle": "ಸಂಪರ್ಕ ಸೋರಿಕೆಯಾಗದಂತೆ AI ಭದ್ರತೆಯೊಂದಿಗೆ ಮಾಲೀಕತ್ವವನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "claim.questionsTitle": "ಪರಿಶೀಲನಾ ಪ್ರಶ್ನೆಗಳು",
    "claim.questionsSubtitle": "ನಿಜವಾದ ಮಾಲೀಕತ್ವವನ್ನು ಸಾಬೀತುಪಡಿಸಲು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ:",
    "claim.answerPlaceholder": "ಈ ಪ್ರಶ್ನೆಗೆ ನಿಮ್ಮ ಉತ್ತರ...",
    "claim.submit": "ವಿಮರ್ಶೆಗಾಗಿ ಸಲ್ಲಿಸಿ",
    "claim.submitting": "ಪರಿಶೀಲನಾ ವಿವರಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    "claim.success": "ಹಕ್ಕು ಸಲ್ಲಿಕೆಯಾಗಿದೆ! ಮಾಲೀಕರು ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.",
    "dashboard.myReports": "ನನ್ನ ವರದಿಗಳು",
    "dashboard.myClaims": "ನನ್ನ ಹಕ್ಕುಗಳು",
    "dashboard.savedPosts": "ಉಳಿಸಿದ ಪೋಸ್ಟ್‌ಗಳು",
    "help.title": "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    "help.q1": "LINCO ನನ್ನ ಗೌಪ್ಯತೆಯನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತದೆ?",
    "help.a1": "LINCO ನಿಮ್ಮ ಸಂಪರ್ಕ ವಿವರಗಳನ್ನು ಎಂದಿಗೂ ಬಹಿರಂಗಪಡಿಸುವುದಿಲ್ಲ. ಪರಿಶೀಲನೆಯ ನಂತರವೇ ಅದು ಅನ್‌ಲಾಕ್ ಆಗುತ್ತದೆ.",
    "help.q2": "ನಾನು ವಸ್ತುವನ್ನು ವರದಿ ಮಾಡಿದಾಗ ಏನಾಗುತ್ತದೆ?",
    "help.a2": "ನಮ್ಮ AI ನಿಮ್ಮ ವರದಿಯನ್ನು ನಗರಗಳಲ್ಲಿ ಸಿಕ್ಕಿದ ವಸ್ತುಗಳೊಂದಿಗೆ ಹೋಲಿಸುತ್ತದೆ.",
    "help.q3": "ಮಾಲೀಕತ್ವ ಪರಿಶೀಲನೆ ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ?",
    "help.a3": "ನಿಜವಾದ ಮಾಲೀಕರಿಗೆ ಮಾತ್ರ ತಿಳಿದಿರುವ ರಹಸ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಬೇಕು.",
    "help.q4": "LINCO ಬಳಸಲು ಉಚಿತವೇ?",
    "help.a4": "ಹೌದು, LINCO ಸಂಪೂರ್ಣವಾಗಿ ಉಚಿತ ಮತ್ತು ಸಮುದಾಯ ಆಧಾರಿತವಾಗಿದೆ.",
    "home.heroTitle": "AI & ಪರಿಶೀಲಿಸಿದ ನಂಬಿಕೆಯೊಂದಿಗೆ ಕಳೆದುಹೋದ ವಸ್ತುಗಳನ್ನು ಮರಳಿ ಪಡೆಯಿರಿ",
    "home.heroSubtitle": "ಭಾರತದ ಸಮುದಾಯ ಆಧಾರಿತ ವೇದಿಕೆ. ಸುರಕ್ಷಿತ ಮತ್ತು ಜೆಮಿನಿ AI ಬೆಂಬಲಿತ.",
    "home.statsRecovered": "ಮರಳಿ ಪಡೆದ ವಸ್ತುಗಳು",
    "home.statsActive": "ಸಕ್ರಿಯ ನಾಗರಿಕರು",
    "home.statsCities": "ವ್ಯಾಪಿಸಿದ ನಗರಗಳು",
    "home.howItWorks": "LINCO ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    "home.step1Title": "1. ಕ್ಷಣಾರ್ಧದಲ್ಲಿ ವರದಿ ಮಾಡಿ",
    "home.step1Desc": "39 ಭಾಷೆಗಳಲ್ಲಿ ಧ್ವನಿ, ಪಠ್ಯ ಅಥವಾ ಫೋಟೋ ಮೂಲಕ ನೋಂದಾಯಿಸಿ.",
    "home.step2Title": "2. ಸ್ಮಾರ್ಟ್ AI ಹೊಂದಾಣಿಕೆ",
    "home.step2Desc": "ಜೆಮಿನಿ ದೃಶ್ಯ ವೈಶಿಷ್ಟ್ಯಗಳು ಮತ್ತು ವಿವರಣೆಗಳನ್ನು ಹೋಲಿಸುತ್ತದೆ.",
    "home.step3Title": "3. ಪರಿಶೀಲಿಸಿದ ಹಸ್ತಾಂತರ",
    "home.step3Desc": "ರಹಸ್ಯ ಪ್ರಶ್ನೆಗಳ ಮೂಲಕ ಪರಿಶೀಲಿಸಿ ಸುರಕ್ಷಿತವಾಗಿ ವಸ್ತುವನ್ನು ಪಡೆಯಿರಿ.",
}
'''

ML_CODE = '''
ML_NEW = {
    "category.Wallet / Purse": "വാലറ്റ് / പേഴ്സ്",
    "category.Bag / Luggage": "ബാഗ് / ലഗേജ്",
    "category.ID / Card": "തിരിച്ചറിയൽ കാർഡ്",
    "urgency.Contains ID": "തിരിച്ചറിയൽ കാർഡ് അടങ്ങിയിരിക്കുന്നു",
    "voice.stop": "റെക്കോർഡിംഗ് നിർത്തുക",
    "voice.error": "ശബ്ദം തിരിച്ചറിയുന്നതിൽ പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "voice.hint": "സാധനത്തിന്റെ ബ്രാൻഡ്, നിറം, സ്ഥലം, തീയതി തുടങ്ങിയ വിവരങ്ങൾ പറയുക.",
    "report.title": "സാധനം റിപ്പോർട്ട് ചെയ്യുക",
    "report.subtitle": "നഷ്ടപ്പെട്ടതോ കണ്ടെത്തിയതോ ആയ സാധനങ്ങൾ സുരക്ഷിതമായി രജിസ്റ്റർ ചെയ്യുക.",
    "report.type": "റിപ്പോർട്ട് തരം",
    "report.typeLost": "എന്റെ സാധനം നഷ്ടപ്പെട്ടു",
    "report.typeFound": "എനിക്ക് ഒരു സാധനം ലഭിച്ചു",
    "report.stepBasics": "1. അടിസ്ഥാന വിവരങ്ങൾ",
    "report.stepLocation": "2. സ്ഥലവും തീയതിയും",
    "report.stepPhotos": "3. ഫോട്ടോകളും തെളിവുകളും",
    "report.stepSecurity": "4. സുരക്ഷയും കോൺടാക്റ്റും",
    "report.itemTitle": "സാധനത്തിന്റെ പേര്",
    "report.itemTitlePlaceholder": "ഉദാ. കറുത്ത ലെതർ ടൈറ്റൻ വാച്ച്, നീല വൈൽഡ്ക്രാഫ്റ്റ് ബാഗ്",
    "report.category": "വിഭാഗം",
    "report.selectCategory": "സാധനത്തിന്റെ വിഭാഗം തിരഞ്ഞെടുക്കുക",
    "report.description": "വിശദമായ വിവരണം",
    "report.descriptionPlaceholder": "നിറം, മോഡൽ, പാടുകൾ, ഉള്ളിലെ സാധനങ്ങൾ മുതലായവ രേഖപ്പെടുത്തുക...",
    "report.location": "സ്ഥലം (ലഭിച്ച / നഷ്ടപ്പെട്ട സ്ഥലം)",
    "report.locationPlaceholder": "ഉദാ. എറണാകുളം സൗത്ത് റെയിൽവേ സ്റ്റേഷൻ ഗേറ്റ് 2",
    "report.date": "തീയതിയും ഏകദേശ സമയവും",
    "report.urgency": "അടിയന്തിര പ്രാധാന്യം",
    "report.urgencyNormal": "സാധാരണ",
    "report.urgencyUrgent": "അടിയന്തിരം",
    "report.urgencyMedical": "ചികിത്സാപരമായ / അതീവ പ്രാധാന്യമുള്ളത്",
    "report.photos": "ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക",
    "report.photosHint": "വ്യക്തമായ ഫോട്ടോകൾ AI പൊരുത്തപ്പെടുത്തൽ കൂടുതൽ കൃത്യമാക്കുന്നു.",
    "report.reward": "പ്രതിഫലത്തുക (നിർബന്ധമില്ല)",
    "report.rewardPlaceholder": "₹ തുക രൂപയിൽ",
    "report.contact": "വാട്ട്‌സ്ആപ്പ് / ഫോൺ നമ്പർ",
    "report.contactPlaceholder": "10 അക്ക മൊബൈൽ നമ്പർ",
    "report.pin": "4 അക്ക സുരക്ഷാ പിൻ",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "പിന്നീട് എഡിറ്റ് ചെയ്യാനോ പരിഹരിച്ചതായി അടയാളപ്പെടുത്താനോ ആവശ്യമാണ്.",
    "report.submit": "കമ്മ്യൂണിറ്റിയിലേക്ക് സമർപ്പിക്കുക",
    "report.submitting": "സുരക്ഷിത രജിസ്ട്രിയിൽ പ്രസിദ്ധീകരിക്കുന്നു...",
    "report.success": "നിങ്ങളുടെ റിപ്പോർട്ട് വിജയകരമായി പ്രസിദ്ധീകരിച്ചു!",
    "report.viewListing": "പട്ടികയിൽ കാണുക",
    "report.brand": "ബ്രാൻഡ് / നിർമ്മാതാവ്",
    "report.brandPlaceholder": "ഉദാ. ആപ്പിൾ, സാംസങ്, ടൈറ്റൻ, വൈൽഡ്ക്രാഫ്റ്റ്",
    "report.primaryColor": "പ്രധാന നിറം",
    "report.secondaryColor": "രണ്ടാമത്തെ നിറം",
    "report.landmark": "അടുത്തുള്ള അടയാളം",
    "report.landmarkPlaceholder": "ഉദാ. പ്ലാറ്റ്‌ഫോം 3 എസ്കലേറ്ററിന് സമീപം, കഫേയ്ക്ക് എതിർവശം",
    "report.secretClue": "രഹസ്യ തിരിച്ചറിയൽ അടയാളം (പരിശോധനയ്ക്കായി)",
    "report.secretCluePlaceholder": "ഉദാ. ഉള്ളിലെ പോക്കറ്റിൽ ചുവന്ന കീചെയിൻ, 'RS' എന്ന് കൊത്തിയ പേര്",
    "feed.searchPlaceholder": "സാധനങ്ങൾ, ടാഗുകൾ, നിറങ്ങൾ, നഗരങ്ങൾ തിരയുക...",
    "feed.filters": "ഫിൽട്ടറുകൾ",
    "feed.applyFilters": "ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക",
    "feed.recentSearches": "സമീപകാല തിരയലുകൾ",
    "feed.savedSearches": "സേവ് ചെയ്ത തിരയലുകൾ",
    "feed.listingRegistry": "രജിസ്ട്രി ലിസ്റ്റിംഗ്",
    "feed.category": "വിഭാഗം",
    "feed.allCategories": "എല്ലാ വിഭാഗങ്ങളും",
    "feed.city": "നഗരം",
    "feed.allCities": "എല്ലാ നഗരങ്ങളും",
    "feed.dateRange": "തീയതി പരിധി",
    "feed.proximity": "ദൂര പരിധി",
    "feed.allProximities": "എല്ലാ ദൂരങ്ങളും (ഏത് പരിധിയും)",
    "feed.within5km": "5 കിലോമീറ്ററിനുള്ളിൽ",
    "feed.within15km": "15 കിലോമീറ്ററിനുള്ളിൽ",
    "feed.within30km": "30 കിലോമീറ്ററിനുള്ളിൽ",
    "feed.within50km": "50 കിലോമീറ്ററിനുള്ളിൽ",
    "feed.sortCatalog": "ക്രമീകരിക്കുക",
    "feed.colorSwatch": "നിറങ്ങൾ",
    "feed.allColors": "എല്ലാ നിറങ്ങളും",
    "feed.hardwareBrand": "ബ്രാൻഡ് നിർമ്മാതാവ്",
    "feed.allBrands": "എല്ലാ ബ്രാൻഡുകളും",
    "feed.resetFilters": "ഫിൽട്ടറുകൾ പുനഃസജ്ജമാക്കുക",
    "feed.viewList": "പട്ടിക",
    "feed.viewMap": "മാപ്പ്",
    "feed.noMatchesFound": "പൊരുത്തങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    "feed.noMatchesDesc": "ഈ ഫിൽട്ടറുകൾക്ക് അനുയോജ്യമായ സാധനങ്ങളൊന്നും കണ്ടെത്തിയില്ല. തിരയൽ മാറ്റുക അല്ലെങ്കിൽ ഫിൽട്ടറുകൾ മാറ്റുക.",
    "feed.reportItem": "സാധനം റിപ്പോർട്ട് ചെയ്യുക",
    "feed.saveParameters": "തിരയൽ വിവരങ്ങൾ സേവ് ചെയ്യുക",
    "feed.deleteSavedSearch": "സേവ് ചെയ്ത തിരയൽ ഒഴിവാക്കുക",
    "feed.universalSearchBar": "തിരയൽ ബാർ",
    "feed.clearSearch": "തിരയൽ മായ്‌ക്കുക",
    "feed.toggleFilters": "വിപുലമായ ഫിൽട്ടറുകൾ",
    "feed.newestFirst": "പുതിയവ ആദ്യം",
    "feed.oldestFirst": "പഴയവ ആദ്യം",
    "feed.highestReward": "ഉയർന്ന പ്രതിഫലം",
    "feed.closestDistance": "ഏറ്റവും അടുത്തുള്ളത്",
    "postcard.unlockConnection": "ബന്ധപ്പെടാൻ അൺലോക്ക് ചെയ്യുക",
    "postcard.iHaveThisItem": "ഈ സാധനം എന്റെ പക്കലുണ്ട്",
    "postcard.reclaimed": "കണ്ടെത്തി കൈമാറി",
    "postcard.claims": "അവകാശവാദങ്ങൾ",
    "postcard.image": "ചിത്രം",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI പൊരുത്തം",
    "postcard.geminiMatches": "ജെമിനി അനുയോജ്യമായ പൊരുത്തങ്ങൾ കണ്ടെത്തി!",
    "postcard.contactOwner": "ഉടമയെ ബന്ധപ്പെടുക",
    "postcard.creatorNotice": "സ്ഥിരീകരിച്ച ഉപയോക്താക്കൾക്ക് മാത്രമേ പൊരുത്തങ്ങൾ കാണാൻ കഴിയൂ.",
    "postcard.markResolved": "പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക",
    "postcard.deleteListing": "ലിസ്റ്റിംഗ് നീക്കം ചെയ്യുക",
    "postcard.unlockWithPin": "പിൻ ഉപയോഗിച്ച് അൺലോക്ക് ചെയ്യുക",
    "postcard.manageClaims": "അവകാശവാദങ്ങൾ കൈകാര്യം ചെയ്യുക",
    "postcard.shareTemplate": "വിവരങ്ങൾ പകർത്തുക",
    "postcard.downloadCard": "കാർഡ് ചിത്രമായി ഡൗൺലോഡ് ചെയ്യുക",
    "postcard.qrSettings": "QR ക്രമീകരണങ്ങൾ",
    "postcard.postedOn": "പോസ്റ്റ് ചെയ്തത്",
    "postcard.reward": "പ്രതിഫലം",
    "postcard.secureHandover": "സുരക്ഷിത കൈമാറ്റം",
    "matches.title": "AI പൊരുത്തപ്പെടുത്തലും പരസ്പര പരിശോധനയും",
    "matches.subtitle": "നഷ്ടപ്പെട്ടതും ലഭിച്ചതുമായ ലിസ്റ്റുകൾ ജെമിനി ഒത്തുനോക്കുന്നു. ചാറ്റിന് മുമ്പ് പരസ്പര പരിശോധന നിർബന്ധമാണ്.",
    "matches.myMatches": "എന്റെ പൊരുത്തങ്ങൾ",
    "matches.publicMatches": "പൊതു പൊരുത്തങ്ങൾ",
    "matches.threshold": "കുറഞ്ഞ പരിധി:",
    "matches.security": "സുരക്ഷ:",
    "matches.mutualApprovalRequired": "ഇരുവിഭാഗത്തിന്റെയും അനുമതി വേണം",
    "matches.noMatchesFound": "പൊരുത്തങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    "matches.improveReport": "റിപ്പോർട്ട് മെച്ചപ്പെടുത്തുക",
    "matches.noPhoto": "ഫോട്ടോ ലഭ്യമല്ല",
    "matches.chatLive": "ലൈവ് ചാറ്റ്",
    "matches.chatLocked": "ചാറ്റ് ലോക്ക് ചെയ്തിരിക്കുന്നു",
    "matches.inspectReview": "പരിശോധിക്കുക",
    "matches.openChatLive": "ലൈവ് ചാറ്റ് തുറക്കുക",
    "matches.verifyApprove": "പരിശോധിച്ച് അംഗീകരിക്കുക",
    "matches.approvalNotice": "ചാറ്റ് അൺലോക്ക് ചെയ്യുന്നതിന് മുമ്പ് ഉടമയും കണ്ടെത്തിയ ആളും പരിശോധന അംഗീകരിക്കണം.",
    "matches.tabComparison": "താരതമ്യം",
    "matches.tabVerification": "പരിശോധന",
    "matches.tabTrust": "വിശ്വാസവും വാട്ട്‌സ്ആപ്പും",
    "matches.tabHandover": "കൈമാറ്റം",
    "matches.noImageProvided": "ചിത്രം നൽകിയിട്ടില്ല",
    "matches.itemName": "സാധനത്തിന്റെ പേര്",
    "matches.category": "വിഭാഗം",
    "matches.reward": "പ്രതിഫലം",
    "matches.locationAddress": "സ്ഥലവും വിലാസവും",
    "matches.detailsDescription": "വിശദാംശങ്ങൾ",
    "matches.finderContact": "കണ്ടെത്തിയ ആളുടെ കോൺടാക്റ്റ്",
    "matches.matchStatus": "പൊരുത്ത നില:",
    "matches.mutualConfirmed": "ഇരുപക്ഷവും പരിശോധന പൂർത്തിയാക്കി അംഗീകരിച്ചു.",
    "matches.mutualProtocol": "പരസ്പര പരിശോധനാ പ്രോട്ടോക്കോൾ",
    "matches.protocolNotice": "തട്ടിപ്പുകൾ ഒഴിവാക്കാൻ ഇരുവിഭാഗവും പരിശോധനാ വിവരങ്ങൾ സമർപ്പിക്കുന്നു. അംഗീകരിക്കുന്നതുവരെ ചാറ്റ് ലോക്ക് ആയിരിക്കും.",
    "matches.ownerStatus": "ഉടമയുടെ നില",
    "matches.submittedBy": "സമർപ്പിച്ചത്:",
    "matches.aiScore": "AI പരിശോധനാ സ്കോർ:",
    "matches.ownerNotSubmitted": "ഉടമ ഇതുവരെ ഉത്തരങ്ങൾ സമർപ്പിച്ചിട്ടില്ല.",
    "matches.finderStatus": "കണ്ടെത്തിയ ആളുടെ നില",
    "matches.finderNotSubmitted": "കണ്ടെത്തിയ ആൾ ഉത്തരങ്ങൾ സമർപ്പിച്ചിട്ടില്ല.",
    "matches.actionControls": "നിയന്ത്രണങ്ങൾ",
    "matches.selectRole": "നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക.",
    "matches.iAmOwner": "ഞാൻ ഉടമയാണ്",
    "matches.iAmFinder": "എനിക്ക് ഈ സാധനം ലഭിച്ചു",
    "matches.yourName": "നിങ്ങളുടെ പേര്",
    "matches.contactWhatsApp": "വാട്ട്‌സ്ആപ്പ് / കോൺടാക്റ്റ്",
    "matches.forensicQuestions": "ഫോറൻസിക് പരിശോധനാ ചോദ്യങ്ങൾ",
    "matches.trustTitle": "പരസ്പര വിശ്വാസവും സുരക്ഷിത വാട്ട്‌സ്ആപ്പ് ബന്ധപ്പെടലും",
    "matches.trustNotice": "സുരക്ഷയ്ക്കായി, രണ്ട് ഉപയോക്താക്കളും അംഗീകരിച്ചതിനുശേഷം മാത്രമേ ഫോൺ നമ്പറുകൾ കാണിക്കൂ.",
    "matches.ownerTrust": "ഉടമയുടെ വിശ്വാസം",
    "matches.finderTrust": "കണ്ടെത്തിയ ആളുടെ വിശ്വാസം",
    "matches.unlocked": "അൺലോക്ക് ചെയ്തു",
    "matches.masked": "മറച്ചിരിക്കുന്നു",
    "matches.contactAlias": "പേര് / വിളിപ്പേര്",
    "matches.phoneWhatsApp": "ഫോൺ / വാട്ട്‌സ്ആപ്പ്",
    "matches.openWhatsApp": "വാട്ട്‌സ്ആപ്പ് തുറക്കുക",
    "matches.directCall": "നേരിട്ട് വിളിക്കുക",
    "matches.trustInstructions": "വാട്ട്‌സ്ആപ്പ് ലിങ്കും ഫോൺ നമ്പറും കാണാൻ താഴെയുള്ള ബട്ടൺ ക്ലിക്ക് ചെയ്യുക.",
    "matches.trustConsent": "വിശ്വാസം ക്ലിക്ക് ചെയ്യുന്നതിലൂടെ, സുരക്ഷിത കൈമാറ്റത്തിനായി വിവരങ്ങൾ പങ്കിടാൻ നിങ്ങൾ സമ്മതിക്കുന്നു.",
    "matches.reunitedResolved": "സാധനം വിജയകരമായി കൈമാറി കേസ് തീർപ്പാക്കി!",
    "matches.reunitedNotice": "ഉടമയും കണ്ടെത്തിയ ആളും സുരക്ഷിത കൈമാറ്റം സ്ഥിരീകരിച്ചു.",
    "matches.handoverProtocol": "സുരക്ഷിത കൈമാറ്റ പ്രോട്ടോക്കോൾ",
    "matches.handoverNotice": "പൊതുസ്ഥലത്ത് വെച്ച് കാണാൻ തീരുമാനിക്കുക (ഉദാ. മെട്രോ സ്റ്റേഷൻ അല്ലെങ്കിൽ പോലീസ് സ്റ്റേഷൻ). നൽകിയ ശേഷം ഇരുവരും സ്ഥിരീകരിക്കുക.",
    "matches.handoverSchedule": "കൈമാറ്റ സമയവും സ്ഥലവും",
    "matches.publicMeetingSpot": "കണ്ടുമുട്ടുന്ന പൊതുസ്ഥലം",
    "matches.scheduledDateTime": "നിശ്ചയിച്ച തീയതി / സമയം",
    "matches.confirmHandover": "കൈമാറ്റം സ്ഥിരീകരിച്ച് അവസാനിപ്പിക്കുക",
    "matches.confirmHandoverDesc": "സാധനം ലഭിച്ച ശേഷം, കൈമാറ്റം പൂർത്തിയാക്കാൻ സ്ഥിരീകരിക്കുക.",
    "matches.iHandedOver": "ഞാൻ ഈ സാധനം കൈമാറി",
    "matches.iReceived": "എന്റെ സാധനം എനിക്ക് തിരികെ ലഭിച്ചു",
    "matches.chatUnlocksAfter": "പരിശോധനയ്ക്ക് ശേഷം സുരക്ഷിത ചാറ്റ് അൺലോക്ക് ആകും",
    "matches.chatUnlocksDesc": "പരിശോധനയ്ക്ക് ശേഷം ഇരുവിഭാഗങ്ങൾക്കുമിടയിൽ സുരക്ഷിത ചാറ്റ് സ്വയമേവ തുറക്കും.",
    "matches.goToVerification": "പരിശോധനാ ടാബിലേക്ക് പോകുക",
    "matches.secureHandoverChat": "സുരക്ഷിത കൈമാറ്റ ചാറ്റ്",
    "matches.connectionVerified": "ബന്ധം സ്ഥിരീകരിച്ചു! കൈമാറ്റത്തിനായി സന്ദേശം അയക്കുക.",
    "matches.dismissMatch": "പൊരുത്തം ഒഴിവാക്കുക",
    "matches.shareMatch": "പങ്കുവെക്കുക",
    "matches.directClaim": "നേരിട്ടുള്ള അവകാശവാദം",
    "claim.ownershipIndex": "ഉടമസ്ഥതാ സൂചിക",
    "claim.safeVerification": "സുരക്ഷിത ഉടമസ്ഥതാ പരിശോധന",
    "claim.stepsNotice": "കൈമാറ്റം സുരക്ഷിതവും വിശ്വസനീയവുമാക്കാൻ ഞങ്ങൾ സ്വകാര്യ ഘട്ടങ്ങൾ ഉപയോഗിക്കുന്നു.",
    "claim.protectedContact": "നിങ്ങളുടെ കോൺടാക്റ്റ് വിവരങ്ങൾ പൂർണ്ണമായും സുരക്ഷിതമാണ്. പരിശോധിച്ച ആൾക്ക് മാത്രമേ കാണാൻ കഴിയൂ.",
    "claim.unlockedMutual": "പരസ്പര പരിശോധനയ്ക്ക് ശേഷം മാത്രമേ ഫോൺ നമ്പർ കാണിക്കൂ. നമ്പർ പരസ്യപ്പെടുത്തില്ല.",
    "claim.aiEvaluationNotice": "തട്ടിപ്പുകൾ തടയാൻ AI അവകാശവാദങ്ങൾ വിലയിരുത്തുന്നു.",
    "claim.trackingNotice": "പ്രത്യേക ട്രാക്കിംഗ് കോഡുകൾ ഇരുപക്ഷത്തെയും സംരക്ഷിക്കുന്നു.",
    "claim.modalDescription": "സാധനം യഥാർത്ഥ ഉടമസ്ഥനിലേക്ക് എത്തുന്നു എന്ന് ഉറപ്പാക്കാൻ, ഞങ്ങൾ പൊരുത്തം പരിശോധിക്കുന്നു.",
    "claim.aiPreparingQuestions": "AI നിങ്ങളുടെ പരിശോധനാ ചോദ്യങ്ങൾ തയ്യാറാക്കുന്നു...",
    "claim.claimantName": "അവകാശവാദിയുടെ പേര്",
    "claim.officialNamePlaceholder": "ഔദ്യോഗിക പേര്",
    "claim.whatsappMobile": "വാട്ട്‌സ്ആപ്പ് മൊബൈൽ",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "സാധനത്തിന്റെ വിവരങ്ങൾ സ്ഥിരീകരിക്കുക",
    "claim.detailsPlaceholder": "ദയവായി വിശദീകരിക്കുക (അടയാളങ്ങൾ, ഉള്ളിലെ സാധനങ്ങൾ, ബിൽ വിവരങ്ങൾ മുതലായവ)...",
    "claim.verificationRegistered": "പരിശോധന രജിസ്റ്റർ ചെയ്തു",
    "claim.detailsSavedSecurely": "വിവരങ്ങൾ സുരക്ഷിതമായി സൂക്ഷിച്ചിരിക്കുന്നു. AI വിവരങ്ങൾ ഒത്തുനോക്കി.",
    "claim.verificationId": "പരിശോധനാ ID (ക്ലെയിം ID)",
    "claim.aiMatchDetails": "AI പൊരുത്തപ്പെടുത്തൽ വിവരങ്ങൾ",
    "claim.bookmarkLink": "ലിങ്ക് (പിന്നീട് കാണാൻ സേവ് ചെയ്യുക)",
    "claim.doneAwaitSignoff": "പൂർത്തിയായി & ഉടമയുടെ അനുമതിക്കായി കാത്തിരിക്കുക",
    "auth.recoverBelongings": "വിശ്വസ്തരായ ആളുകളിലൂടെയും വിവേകപൂർണ്ണമായ പരിശോധനയിലൂടെയും നഷ്ടപ്പെട്ട സാധനങ്ങൾ വീണ്ടെടുക്കുക.",
    "auth.startEmail": "ഇമെയിൽ വഴി ആരംഭിക്കുക",
    "auth.continuePhone": "ഫോൺ വഴി തുടരുക",
    "auth.signIn": "സൈൻ ഇൻ ചെയ്യുക",
    "auth.welcomeBack": "സ്വാഗതം",
    "auth.resumeTracking": "ട്രാക്കിംഗ് തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.",
    "auth.emailOrUsername": "ഇമെയിൽ അല്ലെങ്കിൽ ഉപയോക്തൃനാമം",
    "auth.password": "പാസ്‌വേഡ്",
    "auth.forgotPassword": "പാസ്‌വേഡ് മറന്നോ?",
    "auth.createAccount": "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    "auth.joinNetwork": "നെറ്റ്‌വർക്കിൽ ചേരുക.",
    "auth.fullName": "മുഴുവൻ പേര്",
    "auth.username": "ഉപയോക്തൃനാമം",
    "auth.emailAddress": "ഇമെയിൽ വിലാസം",
    "auth.confirmPassword": "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    "auth.acceptPolicy": "ഞാൻ സ്വകാര്യതാ നയം അംഗീകരിക്കുകയും എൻക്രിപ്റ്റ് ചെയ്ത വിവരങ്ങൾ പങ്കിടാൻ സമ്മതിക്കുകയും ചെയ്യുന്നു.",
    "auth.resetPassword": "പാസ്‌വേഡ് പുനഃസജ്ജമാക്കുക",
    "auth.resetNotice": "അക്കൗണ്ട് വീണ്ടെടുക്കാൻ സുരക്ഷിതമായ ലിങ്ക് അയക്കും.",
    "auth.sendResetLink": "റീസെറ്റ് ലിങ്ക് അയക്കുക",
    "auth.returnSignIn": "സൈൻ ഇന്നിലേക്ക് മടങ്ങുക",
    "auth.setupProfile": "പ്രൊഫൈൽ സജ്ജമാക്കുക",
    "auth.setupNotice": "മറ്റുള്ളവർക്ക് നിങ്ങളുമായി ആശയവിനിമയം നടത്താൻ പ്രൊഫൈൽ പൂർത്തിയാക്കുക.",
    "auth.takeSnapshot": "ഫോട്ടോ എടുക്കുക",
    "auth.choosePhoto": "ഫോട്ടോ തിരഞ്ഞെടുക്കുക",
    "auth.cityNeighborhood": "നഗരം / പ്രദേശം (നിർബന്ധം)",
    "auth.shortBio": "ചെറിയ വിവരണം (നിർബന്ധമില്ല)",
    "auth.completeSetup": "സജ്ജീകരണം പൂർത്തിയാക്കുക",
    "dashboard.welcomeTitle": "പ്രൊഫൈൽ സജ്ജമാക്കുക",
    "dashboard.welcomeDesc": "LINCO-ലേക്ക് സ്വാഗതം. സുരക്ഷിതമായ കൈമാറ്റത്തിനായി നിങ്ങളെക്കുറിച്ച് രേഖപ്പെടുത്തുക.",
    "dashboard.chooseAvatar": "അവതാരകം തിരഞ്ഞെടുക്കുക",
    "dashboard.fullName": "മുഴുവൻ പേര്",
    "dashboard.username": "ഉപയോക്തൃനാമം",
    "dashboard.bio": "വിവരണം (നിർബന്ധമില്ല)",
    "dashboard.city": "നഗരം",
    "dashboard.createProfile": "പ്രൊഫൈൽ ഉണ്ടാക്കുക",
    "dashboard.skipForNow": "ഇപ്പോഴത്തേക്ക് ഒഴിവാക്കുക",
    "dashboard.changeCover": "കവർ മാറ്റുക",
    "dashboard.editProfile": "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    "dashboard.shareProfile": "പ്രൊഫൈൽ പങ്കിടുക",
    "dashboard.settings": "ക്രമീകരണങ്ങൾ",
    "dashboard.editDetails": "വിവരങ്ങൾ എഡിറ്റ് ചെയ്യുക",
    "dashboard.accountSection": "അക്കൗണ്ട്",
    "dashboard.email": "ഇമെയിൽ",
    "dashboard.password": "പാസ്‌വേഡ്",
    "dashboard.privacySection": "സ്വകാര്യത",
    "dashboard.blockedUsers": "തടഞ്ഞ ഉപയോക്താക്കൾ",
    "dashboard.downloadData": "വിവരങ്ങൾ ഡൗൺലോഡ് ചെയ്യുക",
    "dashboard.deleteAccount": "അക്കൗണ്ട് ഒഴിവാക്കുക",
    "dashboard.notifSection": "അറിയിപ്പുകൾ",
    "dashboard.pushNotifs": "പുഷ് അറിയിപ്പുകൾ",
    "dashboard.pushDesc": "പൊരുത്തങ്ങളും ചാറ്റുകളും സംബന്ധിച്ച അറിയിപ്പുകൾ",
    "dashboard.emailReports": "ഇമെയിൽ റിപ്പോർട്ടുകൾ",
    "dashboard.emailDesc": "അവകാശികളില്ലാത്ത സാധനങ്ങളുടെ വിവരങ്ങൾ",
    "dashboard.appearanceSection": "രൂപം",
    "dashboard.theme": "തീം",
    "dashboard.language": "ഭാഷ",
    "dashboard.supportSection": "സഹായം",
    "dashboard.help": "സഹായം",
    "dashboard.contact": "ബന്ധപ്പെടുക",
    "dashboard.about": "കുറിച്ച്",
    "dashboard.logout": "ലോഗ് ഔട്ട്",
    "dashboard.updateEmail": "ഇമെയിൽ പുതുക്കുക",
    "dashboard.saveEmail": "ഇമെയിൽ സേവ് ചെയ്യുക",
    "dashboard.changePassword": "പാസ്‌വേഡ് മാറ്റുക",
    "dashboard.unblock": "തടഞ്ഞത് മാറ്റുക",
    "dashboard.noBlocked": "തടഞ്ഞ ഉപയോക്താക്കളില്ല.",
    "dashboard.contactSupport": "സഹായത്തിനായി ബന്ധപ്പെടുക",
    "dashboard.supportDesc": "സംശയങ്ങൾക്കായി ഞങ്ങളുടെ ടീമുമായി ബന്ധപ്പെടുക:",
    "dashboard.aboutLinco": "LINCO-യെ കുറിച്ച്",
    "dashboard.aboutDesc": "ജെമിനി AI ഉപയോഗിച്ച് നഷ്ടപ്പെട്ട സാധനങ്ങൾ കണ്ടെത്താൻ സഹായിക്കുന്ന ഒരു സുരക്ഷിത ആപ്പാണ് LINCO.",
    "dashboard.appVersion": "ആപ്പ് പതിപ്പ്: v1.3.0",
    "dashboard.capturePhoto": "ഫോട്ടോ എടുക്കുക",
    "dashboard.useCamera": "ക്യാമറ ഉപയോഗിക്കുക",
    "dashboard.chooseGallery": "ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക",
    "dashboard.confirmDeletion": "നീക്കംചെയ്യൽ സ്ഥിരീകരിക്കുക",
    "dashboard.deletionWarning": "ഈ നടപടി ശാശ്വതമാണ്. നിങ്ങളുടെ എല്ലാ വിവരങ്ങളും ഇല്ലാതാകും.",
    "dashboard.typePasswordConfirm": "സ്ഥിരീകരിക്കാൻ പാസ്‌വേഡ് ടൈപ്പ് ചെയ്യുക",
    "dashboard.typeDeletePrompt": "അക്കൗണ്ട് പൂർണ്ണമായി നീക്കം ചെയ്യാൻ DELETE എന്ന് ടൈപ്പ് ചെയ്യുക.",
    "ownerClaims.controlBoard": "കൺട്രോൾ ബോർഡ്",
    "ownerClaims.enterPin": "സുരക്ഷാ പിൻ നൽകുക",
    "ownerClaims.pinDesc": "രജിസ്ട്രേഷൻ സമയത്ത് നൽകിയ 4 അക്ക പിൻ നൽകുക.",
    "ownerClaims.clear": "മായ്ക്കുക",
    "ownerClaims.authenticating": "സ്ഥിരീകരിക്കുന്നു...",
    "ownerClaims.integrityScore": "ജെമിനി സ്കോർ",
    "ownerClaims.reviewNotice": "ഉത്തരങ്ങൾ പരിശോധിക്കുക. അംഗീകരിക്കുന്നത് റിക്കവറി റൂം തുറക്കും.",
    "ownerClaims.completeHandover": "കൈമാറ്റം പൂർത്തിയാക്കുക",
    "ownerClaims.postClosed": "ഈ പോസ്റ്റ് അവസാനിപ്പിച്ചു.",
    "ownerClaims.closeWindow": "വിൻഡോ അടയ്ക്കുക",
    "ownerClaims.approved": "അംഗീകരിച്ചു",
    "ownerClaims.resolved": "പരിഹരിച്ചു",
    "ownerClaims.youReturned": "നിങ്ങൾ തിരികെ നൽകി:",
    "ownerClaims.meetingCoords": "കണ്ടുമുട്ടേണ്ട വിവരങ്ങൾ നൽകുക...",
    "pin.title": "സുരക്ഷാ പിൻ നൽകുക",
    "pin.passcode": "4 അക്ക പാസ്‌കോഡ്",
    "pin.verifying": "പരിശോധിക്കുന്നു...",
    "pin.clear": "മായ്ക്കുക",
    "pin.unlock": "അൺലോക്ക് ചെയ്യുക",
    "pin.promise": "നിങ്ങളുടെ പിൻ നിങ്ങളുടെ സ്വകാര്യ വിവരങ്ങളെ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു.",
    "communityFound.title": "ഈ സാധനം എന്റെ പക്കലുണ്ട്",
    "communityFound.protocol": "സുരക്ഷാ പ്രോട്ടോക്കോൾ",
    "communityFound.verifyFinding": "ലഭിച്ചത് സ്ഥിരീകരിക്കുക",
    "communityFound.withoutLeaking": "സ്വകാര്യ വിവരങ്ങൾ വെളിപ്പെടുത്താതെ",
    "communityFound.lostReported": "നഷ്ടപ്പെട്ട സാധനത്തിന്റെ രജിസ്ട്രേഷൻ",
    "communityFound.whereFound": "ഇത് എവിടെ നിന്നാണ് ലഭിച്ചത്?",
    "communityFound.insideContents": "ഉള്ളിലെ സാധനങ്ങൾ (നിർബന്ധമില്ല)",
    "communityFound.secretDetails": "പ്രത്യേകതകൾ / രഹസ്യ വിവരങ്ങൾ",
    "communityFound.createPin": "സുരക്ഷാ പിൻ ഉണ്ടാക്കുക",
    "communityFound.reward": "പ്രതിഫലം",
    "communityFound.registeredNotice": "രജിസ്റ്റർ ചെയ്തു. നിങ്ങളുടെ ഉത്തരങ്ങൾ ഉടമയെ അറിയിച്ചിട്ടുണ്ട്.",
    "claimTracker.title": "സ്ഥിതി വിവരങ്ങൾ",
    "claimTracker.protocols": "സുരക്ഷിത വീണ്ടെടുക്കൽ രീതികൾ",
    "claimTracker.publicSpaces": "മെട്രോ സ്റ്റേഷൻ പോലുള്ള വെളിച്ചമുള്ള പൊതുസ്ഥലങ്ങളിൽ കണ്ടുമുട്ടുക.",
    "claimTracker.verifyCarefully": "പ്രതിഫലം നൽകുന്നതിന് മുമ്പ് സാധനം ശ്രദ്ധാപൂർവ്വം പരിശോധിക്കുക.",
    "claimTracker.documentDetails": "വിവരങ്ങൾ രേഖപ്പെടുത്താൻ സുരക്ഷിത ചാറ്റ് ഉപയോഗിക്കുക.",
    "claimTracker.lookupAnother": "മറ്റൊന്ന് തിരയുക",
    "claimTracker.unsuccessful": "പരിശോധന പരാജയപ്പെട്ടു",
    "claimTracker.trustCheck": "വിശ്വാസ്യത പരിശോധന",
    "claimTracker.awaitingApproval": "അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു",
    "claimTracker.recoveryRoom": "സുരക്ഷിത റൂം",
    "claimTracker.enterRoom": "റൂമിലേക്ക് പ്രവേശിക്കുക",
    "claimTracker.discussion": "കൈമാറ്റ ചർച്ച",
    "recovery.transmissionSecured": "ഡാറ്റ സുരക്ഷിതമാണ്",
    "recovery.reportIndexed": "റിപ്പോർട്ട് സൂചികയിൽ ചേർത്തു",
    "recovery.dossierActive": "ഫയൽ സജീവമാണ്. ജെമിനി വിവരങ്ങൾ വിശകലനം ചെയ്യുന്നു.",
    "recovery.engineTitle": "AI റിക്കവറി എഞ്ചിൻ",
    "recovery.retrievalLikelihood": "ലഭിക്കാനുള്ള സാധ്യത:",
    "recovery.analyzedFactors": "വിശകലനം ചെയ്ത ഘടകങ്ങൾ",
    "recovery.semanticNotice": "ഞങ്ങളുടെ മോഡൽ ബ്രാൻഡ്, നിറം എന്നിവ വിശകലനം ചെയ്യുന്നു.",
    "recovery.uniqueIdentifier": "പ്രത്യേക അടയാളങ്ങൾ പൊരുത്തം ഉറപ്പാക്കാൻ സഹായിക്കുന്നു.",
    "recovery.setReward": "പ്രതിഫലം നിശ്ചയിക്കുക",
    "reward.fairRange": "ഉചിതമായ തുക",
    "reward.suggestReward": "തുക നിർദ്ദേശിക്കുക",
    "reward.customReward": "മറ്റ് തുക",
    "privacy.complianceProtocols": "സ്വകാര്യതാ പ്രോട്ടോക്കോളുകൾ",
    "privacy.title": "വിശ്വാസ്യത & സുരക്ഷാ കേന്ദ്രം",
    "privacy.subtitle": "ഉയർന്ന സുരക്ഷാ മാനദണ്ഡങ്ങൾ ഞങ്ങൾ പാലിക്കുന്നു.",
    "privacy.exitSection": "പുറത്തുകടക്കുക",
    "privacy.privacyPolicy": "സ്വകാര്യതാ നയം",
    "privacy.lastUpdated": "അവസാനം പുതുക്കിയത്: ജൂലൈ 7, 2026.",
    "privacy.dataAcquisition": "ആവശ്യമായ വിവരങ്ങൾ മാത്രമേ ഞങ്ങൾ ശേഖരിക്കാറുള്ളൂ:",
    "privacy.spatiotemporalTags": "സ്ഥല-സമയ വിവരങ്ങൾ:",
    "privacy.coldStorage": "യാന്ത്രിക സംഭരണത്തിന് മുമ്പുള്ള പരിധി.",
    "privacy.cookiePreferences": "കുക്കി ക്രമീകരണങ്ങൾ കൈകാര്യം ചെയ്യുക.",
    "privacy.purgeBrowser": "ഡാറ്റ ഉടൻ ഒഴിവാക്കുക.",
    "privacy.hereToHelp": "ഞങ്ങൾ സഹായിക്കാൻ തയ്യാറാണ്.",
    "privacy.connectFounder": "സഹായത്തിനായി ഞങ്ങളുടെ പ്രൊഫൈലുമായി ബന്ധപ്പെടുക.",
    "cookie.title": "സ്വകാര്യതാ സംരക്ഷണം",
    "cookie.message": "സാധനങ്ങൾ കണ്ടെത്താൻ ആവശ്യമായ വിവരങ്ങൾ മാത്രമേ ഞങ്ങൾ ശേഖരിക്കൂ.",
    "cookie.trackingNotice": "ഉടമസ്ഥത തെളിയിക്കുന്നതുവരെ വിവരങ്ങൾ സ്വകാര്യമായിരിക്കും.",
    "cookie.acceptAll": "എല്ലാം സ്വീകരിക്കുക",
    "cookie.learnMore": "കൂടുതലറിയുക",
    "about.tagline": "സമൂഹങ്ങളെ ബന്ധിപ്പിക്കുന്നു, സാധനങ്ങൾ വീണ്ടെടുക്കുന്നു",
    "about.mission": "സാങ്കേതികവിദ്യയും ജനങ്ങളുടെ വിശ്വാസവും ഉപയോഗിച്ച് നഷ്ടപ്പെട്ട സാധനങ്ങൾ ഉടമകൾക്ക് തിരികെ നൽകാൻ LINCO പ്രവർത്തിക്കുന്നു.",
    "notifications.title": "അറിയിപ്പുകൾ",
    "notifications.empty": "പുതിയ അറിയിപ്പുകളില്ല",
    "notifications.markAllRead": "വായിച്ചതായി അടയാളപ്പെടുത്തുക",
    "notifications.clearAll": "എല്ലാം ഒഴിവാക്കുക",
    "notifications.matchFoundTitle": "പൊരുത്തം കണ്ടെത്തി",
    "notifications.matchFoundMsg": "AI വഴി ഒരു പൊരുത്തം കണ്ടെത്തിയിട്ടുണ്ട്.",
    "notifications.claimReceivedTitle": "പുതിയ അവകാശവാദം ലഭിച്ചു",
    "notifications.claimReceivedMsg": "നിങ്ങളുടെ പോസ്റ്റിലേക്ക് പരിശോധനാ വിവരങ്ങൾ ലഭിച്ചിട്ടുണ്ട്.",
    "notifications.claimApprovedTitle": "അവകാശവാദം അംഗീകരിച്ചു",
    "notifications.claimApprovedMsg": "നിങ്ങളുടെ അവകാശവാദം ഉടമ അംഗീകരിച്ചു.",
    "notifications.chatMessageTitle": "റൂമിൽ പുതിയ സന്ദേശം",
    "notifications.chatMessageMsg": "കൈമാറ്റം സംബന്ധിച്ച് ഒരു പുതിയ സന്ദേശം ലഭിച്ചു.",
    "notifications.handoverDoneTitle": "കൈമാറ്റം സ്ഥിരീകരിച്ചു",
    "notifications.handoverDoneMsg": "സാധനം തിരികെ ലഭിച്ചതായി സ്ഥിരീകരിച്ചു.",
    "enhance.button": "വിവരണം മെച്ചപ്പെടുത്തുക",
    "enhance.loading": "വിവരണം തയ്യാറാക്കുന്നു...",
    "enhance.apply": "പുതിയ വിവരണം ഉപയോഗിക്കുക",
    "enhance.discard": "പഴയത് നിലനിർത്തുക",
    "enhance.rewardTitle": "പ്രതിഫല നിർദ്ദേശം",
    "enhance.rewardCalculated": "നിർദ്ദേശിച്ച തുക: ₹",
    "enhance.rewardReason": "സാധനത്തിന്റെ സ്വഭാവം അടിസ്ഥാനമാക്കി.",
    "timeline.reconstruct": "ടൈംലൈൻ ഉണ്ടാക്കുക",
    "timeline.loading": "വഴികൾ വിശകലനം ചെയ്യുന്നു...",
    "timeline.spotLikelihood": "നഷ്ടപ്പെടാൻ സാധ്യതയുള്ള സ്ഥലം:",
    "timeline.window": "സാധ്യമായ സമയം:",
    "timeline.analysis": "യാത്രാ വിശകലനം:",
    "timeline.confidence": "വിശ്വാസ്യത:",
    "timeline.addPoint": "പോയിന്റ് ചേർക്കുക",
    "timeline.pointName": "സ്ഥലത്തിന്റെ പേര്",
    "chat.assistant": "AI സഹായി",
    "chat.subtitle": "നിങ്ങളുടെ സഹായി",
    "chat.description": "60 സെക്കൻഡിനുള്ളിൽ വിവരങ്ങൾ നൽകുക. സംസാരിക്കുകയോ ടൈപ്പ് ചെയ്യുകയോ ചെയ്യാം.",
    "chat.startAssistant": "സഹായിയെ തുടങ്ങുക",
    "chat.location": "സ്ഥലം:",
    "chat.securityPin": "സുരക്ഷാ പിൻ:",
    "chat.skipPhoto": "ഫോട്ടോ ഒഴിവാക്കുക",
    "chat.item": "സാധനം:",
    "chat.errorLoading": "ലോഡ് ചെയ്യുന്നതിൽ പിശക്. വീണ്ടും ശ്രമിക്കുക.",
    "chat.welcomeMessage": "LINCO Saathii-ലേക്ക് സ്വാഗതം! എന്ത് വിവരമാണ് നൽകാനുള്ളത്?",
    "chat.networkError": "നെറ്റ്‌വർക്ക് പ്രശ്നം. വീണ്ടും ശ്രമിക്കുക!",
    "chat.understoodError": "വ്യക്തമായില്ല. കൂടുതൽ വിവരങ്ങൾ നൽകാമോ?",
    "feed.lostOnly": "നഷ്ടപ്പെട്ടവ",
    "feed.foundOnly": "ലഭിച്ചവ",
    "feed.filterByCategory": "വിഭാഗം",
    "feed.filterByCity": "നഗരം",
    "feed.filterByUrgency": "പ്രാധാന്യം",
    "feed.empty": "സാധനങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    "feed.emptyAction": "പുതിയ സാധനം രേഖപ്പെടുത്തുക",
    "matches.contactFinder": "ലഭിച്ച ആളുമായി ബന്ധപ്പെടുക",
    "matches.contactOwner": "ഉടമയുമായി ബന്ധപ്പെടുക",
    "matches.verifyOwnership": "ഉടമസ്ഥത പരിശോധിക്കുക",
    "claim.title": "അവകാശവാദം ഉന്നയിക്കുക",
    "claim.subtitle": "സുരക്ഷിതമായി ഉടമസ്ഥത ഉറപ്പാക്കുക.",
    "claim.questionsTitle": "ചോദ്യങ്ങൾ",
    "claim.questionsSubtitle": "ഉടമസ്ഥത തെളിയിക്കാൻ ചോദ്യങ്ങൾക്ക് മറുപടി നൽകുക:",
    "claim.answerPlaceholder": "നിങ്ങളുടെ ഉത്തരം...",
    "claim.submit": "സമർപ്പിക്കുക",
    "claim.submitting": "സമർപ്പിക്കുന്നു...",
    "claim.success": "സമർപ്പിച്ചു! ഉടമ പരിശോധിക്കുന്നതാണ്.",
    "dashboard.myReports": "എന്റെ റിപ്പോർട്ടുകൾ",
    "dashboard.myClaims": "എന്റെ അവകാശവാദങ്ങൾ",
    "dashboard.savedPosts": "സേവ് ചെയ്തവ",
    "help.title": "സംശയങ്ങൾ",
    "help.q1": "LINCO സ്വകാര്യത സംരക്ഷിക്കുന്നത് എങ്ങനെ?",
    "help.a1": "ഫോൺ നമ്പർ പരസ്യപ്പെടുത്തില്ല. പരസ്പര അനുമതിക്ക് ശേഷം മാത്രമേ ബന്ധപ്പെടാനാകൂ.",
    "help.q2": "റിപ്പോർട്ട് ചെയ്താൽ എന്ത് സംഭവിക്കും?",
    "help.a2": "ലഭിച്ച സാധനങ്ങളുമായി AI നിങ്ങളുടെ വിവരങ്ങൾ ഒത്തുനോക്കും.",
    "help.q3": "ഉടമസ്ഥത ഉറപ്പാക്കുന്നത് എങ്ങനെ?",
    "help.a3": "യഥാർത്ഥ ഉടമയ്ക്ക് മാത്രം അറിയാവുന്ന രഹസ്യ ചോദ്യങ്ങൾക്ക് മറുപടി നൽകണം.",
    "help.q4": "സൗജന്യമാണോ?",
    "help.a4": "അതെ, പൂർണ്ണമായും സൗജന്യമാണ്.",
    "home.heroTitle": "നഷ്ടപ്പെട്ട സാധനങ്ങൾ സുരക്ഷിതമായി തിരികെ നേടുക",
    "home.heroSubtitle": "സുരക്ഷിതവും AI അധിഷ്ഠിതവുമായ പ്ലാറ്റ്ഫോം.",
    "home.statsRecovered": "കണ്ടെത്തിയവ",
    "home.statsActive": "സജീവ ഉപയോക്താക്കൾ",
    "home.statsCities": "നഗരങ്ങൾ",
    "home.howItWorks": "പ്രവർത്തനം എങ്ങനെ",
    "home.step1Title": "1. വിവരങ്ങൾ നൽകുക",
    "home.step1Desc": "ശബ്ദത്തിലൂടെയോ എഴുത്തിലൂടെയോ രേഖപ്പെടുത്തുക.",
    "home.step2Title": "2. AI പൊരുത്തപ്പെടുത്തൽ",
    "home.step2Desc": "വിവരങ്ങളും ഫോട്ടോകളും AI ഒത്തുനോക്കുന്നു.",
    "home.step3Title": "3. കൈമാറ്റം",
    "home.step3Desc": "പരിശോധിച്ച് സുരക്ഷിതമായി സാധനങ്ങൾ തിരികെ വാങ്ങുക.",
}
'''

with open('scripts/dict_south_indic.py', 'a', encoding='utf-8') as f:
    f.write(TE_CODE)
    f.write(KN_CODE)
    f.write(ML_CODE)

print("Appended TE, KN, ML to dict_south_indic.py successfully.")
