# -*- coding: utf-8 -*-
"""Authentic Indonesian (ID), Vietnamese (VI), and Thai (TH) translations for all 269 UI keys."""

ID_269 = {
  "app.tagline": "Pusat Barang Hilang dan Temuan AI India",
  "app.subtitle": "Temukan kembali barang berharga Anda dengan privasi terjamin dan kepercayaan terverifikasi.",
  "nav.home": "Beranda",
  "nav.report": "Buat Laporan",
  "nav.feed": "Kanal Komunitas",
  "nav.matches": "Kecocokan AI",
  "nav.activity": "Aktivitas",
  "nav.profile": "Profil",
  "nav.about": "Tentang Kami",
  "nav.privacyTrust": "Privasi & Kepercayaan",
  "nav.language": "Bahasa",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Kembali",
  "common.next": "Lanjut",
  "common.cancel": "Batal",
  "common.save": "Simpan",
  "common.submit": "Kirim",
  "common.edit": "Ubah",
  "common.delete": "Hapus",
  "common.close": "Tutup",
  "common.loading": "Memuat...",
  "common.success": "Berhasil",
  "common.error": "Kesalahan",
  "common.search": "Cari",
  "common.filter": "Filter",
  "common.clear": "Bersihkan",
  "common.optional": "Opsional",
  "common.required": "Wajib",
  "common.viewAll": "Lihat Semua",
  "common.details": "Detail",
  "common.status": "Status",
  "lang.heading": "Pilih Bahasa Anda",
  "lang.subheading": "Gunakan LINCO dalam bahasa yang paling nyaman bagi Anda.",
  "lang.note": "Anda dapat mengubah pilihan bahasa kapan saja melalui Pengaturan.",
  "lang.continue": "Lanjutkan ke LINCO",
  "lang.searchPlaceholder": "Cari bahasa (cth: Bahasa Indonesia, English, Hindi)...",
  "lang.tabAll": "Semua Bahasa",
  "lang.tabIndian": "Bahasa India (22)",
  "lang.tabInternational": "Bahasa Internasional",
  "lang.supportedBadge": "Didukung Penuh",
  "lang.previewBadge": "Pratinjau / Beta",
  "voice.button": "Input Suara",
  "voice.listening": "Mendengarkan... Silakan berbicara dalam bahasa pilihan Anda",
  "voice.processing": "Memproses rekaman suara...",
  "voice.transcribing": "Mengubah suara menjadi teks...",
  "voice.reviewTitle": "Tinjau Laporan Suara",
  "voice.reviewSubtitle": "Periksa rincian yang terdeteksi sebelum menerapkannya.",
  "voice.apply": "Terapkan Rincian",
  "voice.retry": "Coba Lagi",
  "voice.cancel": "Batal",
  "voice.notSupported": "Fitur pengenalan suara tidak didukung oleh peramban ini.",
  "voice.permissionDenied": "Izin mikrofon ditolak. Harap izinkan melalui pengaturan peramban.",
  "notifications.centerTitle": "Pusat Aktivitas",
  "notifications.centerSubtitle": "Kecocokan waktu nyata, klaim kepemilikan, dan proses pengembalian.",
  "notifications.readAll": "Tandai semua telah dibaca",
  "notifications.unread": "Belum dibaca",
  "notifications.emptyTitle": "Belum ada notifikasi",
  "notifications.emptySubtitle": "Kami akan memberi tahu Anda segera setelah ada pembaruan tentang laporan Anda.",
  "notifications.networkFooter": "Jaringan Notifikasi Pintar LINCO",
  "notifications.listingAlert": "Pemberitahuan Laporan Baru",
  "notifications.matchFound": "Potensi Kecocokan Ditemukan",
  "notifications.claimReceived": "Klaim Kepemilikan Diterima",
  "notifications.ownerApproved": "Dikonfirmasi oleh Pemilik",
  "notifications.finderVerified": "Diverifikasi oleh Penemu",
  "notifications.verificationComplete": "Verifikasi Bersama Selesai",
  "notifications.newMessage": "Pesan Aman Baru",
  "notifications.trustUpdate": "Tingkat Kepercayaan Diperbarui",
  "notifications.handoverUpdate": "Status Serah Terima Diperbarui",
  "notifications.itemReceived": "Barang Telah Diterima",
  "notifications.itemReunited": "Barang Berhasil Kembali ke Pemilik",
  "notifications.actions.viewMatch": "Lihat Kecocokan",
  "notifications.actions.reviewClaim": "Tinjau Klaim",
  "notifications.actions.viewVerification": "Lihat Verifikasi",
  "notifications.actions.openChat": "Buka Obrolan",
  "notifications.actions.confirmHandover": "Konfirmasi Serah Terima",
  "notifications.actions.viewCase": "Lihat Kasus",
  "notifications.actions.viewDetails": "Lihat Detail",
  "notifications.actions.confirmTrust": "Konfirmasi Kepercayaan",
  "notifications.matchFoundMsg": "Kami menemukan kecocokan dengan tingkat kepastian tinggi untuk laporan Anda.",
  "notifications.claimReceivedMsg": "Seseorang telah mengajukan klaim kepemilikan untuk barang ini.",
  "notifications.claimApprovedMsg": "Klaim Anda telah ditinjau dan disetujui oleh pihak lawan.",
  "notifications.ownerApprovedMsg": "Pemilik telah mengonfirmasi bahwa barang ini kemungkinan miliknya.",
  "notifications.finderVerifiedMsg": "Penemu telah mengonfirmasi bahwa jawaban klaim cocok dengan barang yang ditemukan.",
  "notifications.bothApprovedMsg": "Kedua pihak telah mengonfirmasi kecocokan. Ruang obrolan aman kini dibuka.",
  "notifications.newMessageMsg": "Anda menerima pesan baru di ruang obrolan aman.",
  "notifications.trustUpdateMsg": "Kepercayaan timbal balik dikonfirmasi! Kontak WhatsApp telah dibuka.",
  "notifications.handoverUpdateMsg": "Protokol serah terima barang yang aman telah dimulai.",
  "notifications.itemReceivedMsg": "Penerimaan barang telah berhasil dikonfirmasi.",
  "notifications.itemReunitedMsg": "Barang berhasil dikembalikan ke pemiliknya! Kasus resmi ditutup.",
  "help.notSure": "Bingung harus menulis apa?",
  "help.askLinco": "Tanyakan ke LINCO",
  "help.listen": "Dengarkan Bantuan",
  "help.stopListen": "Berhenti",
  "help.itemName": "Sebutkan nama barang yang umum (cth: Dompet kulit, iPhone 14).",
  "help.location": "Sebutkan stasiun kereta atau tengara terdekat.",
  "help.time": "Pilih perkiraan jam dan bagian hari kejadian.",
  "help.description": "Jelaskan warna, merek, bahan, dan isi di dalamnya.",
  "help.identifying": "Sebutkan ciri khusus tersembunyi yang hanya diketahui oleh pemilik asli.",
  "help.timeline": "Ingat kembali perjalanan hari Anda untuk mempersempit area pencarian.",
  "report.badge": "Laporan Cerdas",
  "report.titleLost": "Laporkan Barang Hilang",
  "report.titleFound": "Laporkan Barang Ditemukan",
  "report.step1.title": "Informasi Dasar",
  "report.step1.typeLost": "Saya Kehilangan Barang",
  "report.step1.typeFound": "Saya Menemukan Barang",
  "report.step1.itemName": "Nama Barang",
  "report.step1.itemNamePlaceholder": "cth: Dompet Kulit Hitam Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "Kategori",
  "report.step1.urgency": "Tingkat Urgensi",
  "report.step2.title": "Lokasi",
  "report.step2.location": "Lokasi atau Patokan Terdekat",
  "report.step2.locationPlaceholder": "cth: Stasiun Pusat Pintu 2, Perpustakaan Kampus",
  "report.step2.useGps": "Gunakan Lokasi GPS Saat Ini",
  "report.step2.pinMap": "Tandai di Peta",
  "report.step3.title": "Tanggal & Waktu",
  "report.step3.date": "Tanggal",
  "report.step3.time": "Perkiraan Waktu",
  "report.step3.quickToday": "Hari Ini",
  "report.step3.quickYesterday": "Kemarin",
  "report.step3.quickMorning": "Pagi",
  "report.step3.quickAfternoon": "Siang",
  "report.step3.quickEvening": "Sore",
  "report.step3.quickNight": "Malam",
  "report.step4.title": "Deskripsi & Ciri Khusus",
  "report.step4.desc": "Deskripsi Rinci",
  "report.step4.descPlaceholder": "Jelaskan warna, merek, model, dan kondisi fisik...",
  "report.step4.aiEnhance": "Sempurnakan dengan AI",
  "report.step4.timelineBuilder": "Asisten Jejak Rute",
  "report.step4.identifyingMarks": "Ciri Pengenal Khusus (Rahasia)",
  "report.step4.identifyingPlaceholder": "cth: Goresan di sudut kanan, stiker NASA, 2 anak kunci di dalam",
  "report.step4.photo": "Foto Barang",
  "report.step5.title": "Kontak & Privasi",
  "report.step5.contact": "Nomor Telepon / WhatsApp",
  "report.step5.contactPlaceholder": "10 digit nomor telepon seluler",
  "report.step5.contactNotice": "Nomor Anda tidak akan pernah dipublikasikan di feed umum.",
  "report.step6.title": "Hadiah & Kode PIN",
  "report.step6.reward": "Hadiah Temuan (Opsional)",
  "report.step6.aiReward": "Saran Hadiah oleh AI",
  "report.step6.pin": "4 Digit PIN Keamanan",
  "report.step6.pinNotice": "Simpan kode PIN ini untuk mengedit atau menutup laporan Anda nanti.",
  "feed.title": "Kanal Komunitas",
  "feed.subtitle": "Laporan barang hilang dan ditemukan terbaru di sekitar wilayah Anda.",
  "feed.all": "Semua",
  "feed.lost": "Barang Hilang",
  "feed.found": "Barang Temuan",
  "feed.resolved": "Terselesaikan",
  "feed.listView": "Tampilan Daftar",
  "feed.mapView": "Tampilan Peta",
  "feed.searchPlaceholder": "Cari berdasarkan nama, lokasi, atau kategori...",
  "feed.noResults": "Tidak ada laporan yang cocok dengan kriteria pencarian.",
  "feed.claimButton": "Ini Milik Saya",
  "feed.foundButton": "Saya Menemukannya",
  "feed.viewMatches": "Lihat Kecocokan",
  "matches.title": "Pusat Pencocokan AI",
  "matches.subtitle": "Pencocokan semantik otomatis antara laporan barang hilang dan temuan.",
  "matches.allMatches": "Semua Kecocokan",
  "matches.mutualApprovals": "Persetujuan Bersama",
  "matches.pendingVerification": "Menunggu Verifikasi",
  "matches.resolved": "Selesai",
  "matches.threshold": "Batas Kecocokan",
  "matches.confidence": "Tingkat Keyakinan",
  "matches.score": "Skor",
  "matches.reason": "Alasan Kecocokan",
  "matches.lostReport": "Laporan Kehilangan",
  "matches.foundReport": "Laporan Penemuan",
  "matches.openChat": "Buka Obrolan Aman",
  "matches.verifyApprove": "Verifikasi & Setujui",
  "matches.modalTitle": "Rincian Kecocokan",
  "matches.notFoundTitle": "Tidak ada kecocokan ditemukan",
  "matches.notFoundDesc": "Belum ada kecocokan yang sesuai dengan filter yang dipilih saat ini.",
  "matches.backToActivity": "Kembali ke Aktivitas",
  "chat.title": "Obrolan Pengembalian Aman",
  "chat.trustButton": "Konfirmasi Kepercayaan",
  "chat.whatsapp": "Lanjutkan di WhatsApp",
  "chat.handover": "Mulai Serah Terima Aman",
  "chat.received": "Saya Sudah Menerima Barang",
  "chat.resolved": "Kasus Ditutup",
  "chat.placeholder": "Ketik pesan yang aman...",
  "chat.send": "Kirim",
  "chat.safetyWarning": "Tips Keamanan: Selalu bertemu di tempat umum yang ramai. Jangan pernah mentransfer uang terlebih dahulu.",
  "enhance.modalTitle": "Penyempurnaan Teks dengan AI",
  "enhance.aiBadge": "Dihasilkan oleh AI",
  "enhance.original": "Deskripsi Asli",
  "enhance.enhanced": "Deskripsi Disempurnakan",
  "enhance.structuredHeading": "Atribut Terstruktur",
  "enhance.accept": "Terapkan Perubahan",
  "enhance.edit": "Ubah",
  "enhance.tryAgain": "Hasilkan Ulang",
  "enhance.keepOriginal": "Simpan Teks Asli",
  "enhance.suggestions": "Saran Tambahan",
  "timeline.title": "Rekonstruksi Jejak Waktu AI",
  "timeline.subtitle": "Ingat kembali perjalanan Anda untuk menentukan perkiraan waktu dan tempat secara akurat.",
  "timeline.userProvided": "Diisi oleh Pengguna",
  "timeline.aiInferred": "Kesimpulan AI",
  "timeline.unknown": "Tidak Diketahui",
  "timeline.likelyLocation": "Area Paling Mungkin",
  "timeline.timeWindow": "Rentang Waktu",
  "timeline.reasoning": "Analisis AI",
  "timeline.applyLocation": "Gunakan Lokasi Ini",
  "timeline.editEvent": "Ubah Titik",
  "timeline.addEvent": "Tambah Titik",
  "home.heroTag": "Temukan • Verifikasi • Pulihkan",
  "home.heroTitle1": "Identitas Anda tetap terlindungi.",
  "home.heroTitle2": "Barang berharga Anda kembali.",
  "home.heroSubtitle1": "Jangan pernah putus asa menemukan milik Anda.",
  "home.heroSubtitle2": "Didukung oleh komunitas. Dilindungi oleh kecerdasan buatan.",
  "home.heroDesc": "Buat laporan kehilangan atau temuan dalam waktu kurang dari satu menit. Privasi Anda terlindungi hingga kepemilikan terverifikasi bersama.",
  "home.reportLost": "Laporkan Kehilangan",
  "home.reportFound": "Laporkan Penemuan",
  "home.findItem": "Cari Barang",
  "home.viewMatches": "Lihat Kecocokan AI",
  "home.startReport": "Mulai Laporan",
  "home.browseFeed": "Jelajahi Feed Komunitas",
  "home.statsTotal": "Total Laporan",
  "home.statsLost": "Barang Hilang",
  "home.statsFound": "Barang Ditemukan",
  "home.statsResolved": "Telah Dikembalikan",
  "home.trustTitle": "Mengapa Memilih LINCO",
  "home.trustSubtitle": "Dibangun dengan privasi tanpa pengungkapan, verifikasi kepemilikan ketat, dan panduan serah terima aman.",
  "home.trustPrivacyTitle": "Identitas Terlindungi",
  "home.trustPrivacyDesc": "Nomor telepon dan data pribadi Anda tidak akan pernah muncul di feed publik.",
  "home.trustProofTitle": "Bukti Kepemilikan Kuat",
  "home.trustProofDesc": "Pertanyaan verifikasi khusus buatan AI mencegah klaim palsu sebelum Anda bertemu langsung.",
  "home.trustRecoveryTitle": "Jaringan Pengembalian Aman",
  "home.trustRecoveryDesc": "Koordinasikan pengembalian melalui pesan terenkripsi, persetujuan ganda, dan langkah serah terima terpandu.",
  "home.timelineShowcaseTitle": "Rekonstruksi Perjalanan Hari dengan AI",
  "home.timelineShowcaseSubtitle": "Ingat perhentian hari Anda untuk memperkirakan waktu dan lokasi kehilangan secara tepat.",
  "home.timelineTryPrompt": "Coba contoh:",
  "home.faqTitle": "Pertanyaan yang Sering Diajukan",
  "home.faqSubtitle": "Segala hal yang perlu Anda ketahui tentang cara kerja LINCO.",
  "dashboard.title": "Dasbor Warga",
  "dashboard.subtitle": "Kelola laporan aktif Anda, ruang pengembalian, dan pengaturan keamanan.",
  "dashboard.tabReports": "Laporan Saya",
  "dashboard.tabClaims": "Klaim Saya",
  "dashboard.tabRecovery": "Ruang Pengembalian",
  "dashboard.tabSettings": "Pengaturan",
  "dashboard.noReports": "Anda belum membuat laporan apa pun saat ini.",
  "dashboard.noClaims": "Tidak ada klaim kepemilikan yang aktif saat ini.",
  "dashboard.noRecovery": "Tidak ada ruang pengembalian yang aktif.",
  "dashboard.accountDetails": "Detail Akun",
  "dashboard.fullName": "Nama Lengkap",
  "dashboard.phoneNumber": "Nomor Telepon",
  "dashboard.city": "Kota",
  "dashboard.languagePreference": "Bahasa Pilihan",
  "dashboard.changeLanguage": "Ganti Bahasa",
  "dashboard.saveSettings": "Simpan Pengaturan",
  "dashboard.settingsSaved": "Pengaturan berhasil disimpan.",
  "claim.modalTitle": "Klaim Kepemilikan Barang Ini",
  "claim.modalSubtitle": "Buktikan bahwa Anda adalah pemilik sah dengan menjawab pertanyaan verifikasi.",
  "claim.verifyIdentity": "Verifikasi Kepemilikan",
  "claim.questionsPrompt": "Harap jawab pertanyaan verifikasi berikut dengan jujur:",
  "claim.proofDetails": "Ciri Khas atau Bukti Kepemilikan",
  "claim.proofPlaceholder": "Jelaskan isi rahasia, goresan tertentu, atau nomor seri...",
  "claim.submitClaim": "Kirimkan Klaim",
  "claim.statusPending": "Dalam Peninjauan",
  "claim.statusApproved": "Klaim Disetujui",
  "claim.statusRejected": "Klaim Ditolak",
  "claim.statusResolved": "Kasus Berhasil Diselesaikan",
  "category.Electronics": "Elektronik",
  "category.Documents": "Dokumen & Kartu",
  "category.Keys": "Kunci",
  "category.Pet": "Hewan Peliharaan",
  "category.Jewelry": "Perhiasan & Jam Tangan",
  "category.Vehicle": "Kendaraan",
  "category.Clothing": "Pakaian & Tas",
  "category.Other": "Barang Lainnya",
  "urgency.Normal": "Biasa",
  "urgency.Urgent": "Mendesak",
  "urgency.Medical": "Medis / Sangat Kritis"
}

VI_269 = {
  "app.tagline": "Trung tâm Thất lạc & Nhặt được AI Ấn Độ",
  "app.subtitle": "Tìm lại đồ đạc thất lạc với sự riêng tư tuyệt đối và xác minh tin cậy.",
  "nav.home": "Trang chủ",
  "nav.report": "Đăng tin",
  "nav.feed": "Bảng tin Cộng đồng",
  "nav.matches": "Khớp nối AI",
  "nav.activity": "Hoạt động",
  "nav.profile": "Hồ sơ",
  "nav.about": "Về chúng tôi",
  "nav.privacyTrust": "Bảo mật & Tin cậy",
  "nav.language": "Ngôn ngữ",
  "nav.saathii": "Trợ lý LINCO",
  "common.back": "Quay lại",
  "common.next": "Tiếp theo",
  "common.cancel": "Hủy",
  "common.save": "Lưu",
  "common.submit": "Gửi đi",
  "common.edit": "Chỉnh sửa",
  "common.delete": "Xóa",
  "common.close": "Đóng",
  "common.loading": "Đang tải...",
  "common.success": "Thành công",
  "common.error": "Lỗi",
  "common.search": "Tìm kiếm",
  "common.filter": "Lọc",
  "common.clear": "Xóa lọc",
  "common.optional": "Không bắt buộc",
  "common.required": "Bắt buộc",
  "common.viewAll": "Xem tất cả",
  "common.details": "Chi tiết",
  "common.status": "Trạng thái",
  "lang.heading": "Chọn ngôn ngữ của bạn",
  "lang.subheading": "Sử dụng LINCO bằng ngôn ngữ mà bạn cảm thấy thoải mái nhất.",
  "lang.note": "Bạn có thể thay đổi ngôn ngữ bất kỳ lúc nào trong phần Cài đặt.",
  "lang.continue": "Tiếp tục với LINCO",
  "lang.searchPlaceholder": "Tìm kiếm ngôn ngữ (vd: Tiếng Việt, English, Hindi)...",
  "lang.tabAll": "Tất cả ngôn ngữ",
  "lang.tabIndian": "Ngôn ngữ Ấn Độ (22)",
  "lang.tabInternational": "Ngôn ngữ quốc tế",
  "lang.supportedBadge": "Hỗ trợ đầy đủ",
  "lang.previewBadge": "Bản xem trước / Thử nghiệm",
  "voice.button": "Nhập bằng giọng nói",
  "voice.listening": "Đang lắng nghe... Hãy nói tự nhiên bằng ngôn ngữ của bạn",
  "voice.processing": "Đang xử lý bản ghi âm...",
  "voice.transcribing": "Đang chuyển giọng nói thành văn bản...",
  "voice.reviewTitle": "Xem lại nội dung ghi âm",
  "voice.reviewSubtitle": "Kiểm tra các chi tiết đã nhận diện trước khi áp dụng.",
  "voice.apply": "Áp dụng chi tiết",
  "voice.retry": "Nói lại",
  "voice.cancel": "Hủy",
  "voice.notSupported": "Trình duyệt này không hỗ trợ tính năng nhận diện giọng nói.",
  "voice.permissionDenied": "Quyền truy cập micro đã bị từ chối. Vui lòng bật trong cài đặt.",
  "notifications.centerTitle": "Trung tâm Hoạt động",
  "notifications.centerSubtitle": "Khớp nối theo thời gian thực, yêu cầu nhận đồ và tiến trình trao trả.",
  "notifications.readAll": "Đánh dấu tất cả là đã đọc",
  "notifications.unread": "Chưa đọc",
  "notifications.emptyTitle": "Chưa có thông báo mới",
  "notifications.emptySubtitle": "Chúng tôi sẽ thông báo cho bạn ngay khi có cập nhật về tin đăng của bạn.",
  "notifications.networkFooter": "Mạng lưới Thông báo Thông minh LINCO",
  "notifications.listingAlert": "Thông báo tin đăng mới",
  "notifications.matchFound": "Đã tìm thấy đồ vật tương đồng",
  "notifications.claimReceived": "Đã nhận được yêu cầu nhận lại đồ",
  "notifications.ownerApproved": "Người làm mất đã xác nhận",
  "notifications.finderVerified": "Người nhặt được đã đối chiếu",
  "notifications.verificationComplete": "Xác minh hai chiều hoàn tất",
  "notifications.newMessage": "Tin nhắn bảo mật mới",
  "notifications.trustUpdate": "Mức độ tin cậy đã được cập nhật",
  "notifications.handoverUpdate": "Trạng thái bàn giao đã cập nhật",
  "notifications.itemReceived": "Đã nhận được đồ vật",
  "notifications.itemReunited": "Trao trả đồ vật thành công",
  "notifications.actions.viewMatch": "Xem kết quả khớp",
  "notifications.actions.reviewClaim": "Xem xét yêu cầu",
  "notifications.actions.viewVerification": "Xem xác minh",
  "notifications.actions.openChat": "Mở trò chuyện",
  "notifications.actions.confirmHandover": "Xác nhận bàn giao",
  "notifications.actions.viewCase": "Xem hồ sơ",
  "notifications.actions.viewDetails": "Xem chi tiết",
  "notifications.actions.confirmTrust": "Xác nhận tin cậy",
  "notifications.matchFoundMsg": "Hệ thống đã tìm thấy một đồ vật có độ tương đồng rất cao với tin của bạn.",
  "notifications.claimReceivedMsg": "Đã có người gửi yêu cầu nhận quyền sở hữu đối với đồ vật này.",
  "notifications.claimApprovedMsg": "Yêu cầu nhận lại đồ của bạn đã được đối phương xác minh và chấp thuận.",
  "notifications.ownerApprovedMsg": "Người làm mất xác nhận đây rất có thể là đồ vật của họ.",
  "notifications.finderVerifiedMsg": "Người nhặt xác nhận câu trả lời của bạn trùng khớp với đặc điểm đồ vật.",
  "notifications.bothApprovedMsg": "Hai bên đã xác nhận khớp nối. Phòng trò chuyện bảo mật hiện đã mở.",
  "notifications.newMessageMsg": "Bạn nhận được một tin nhắn mới trong phòng trò chuyện bảo mật.",
  "notifications.trustUpdateMsg": "Xác thực tin cậy thành công! Thông tin liên lạc WhatsApp đã được mở khóa.",
  "notifications.handoverUpdateMsg": "Quy trình bàn giao trực tiếp an toàn đã được kích hoạt.",
  "notifications.itemReceivedMsg": "Đã xác nhận nhận lại đồ vật thành công.",
  "notifications.itemReunitedMsg": "Đồ vật đã được trao lại cho chủ sở hữu! Hồ sơ chính thức khép lại.",
  "help.notSure": "Bạn chưa biết nên viết gì?",
  "help.askLinco": "Hỏi LINCO",
  "help.listen": "Nghe hướng dẫn",
  "help.stopListen": "Dừng",
  "help.itemName": "Điền tên thông dụng của đồ vật (vd: Ví da, iPhone 14).",
  "help.location": "Ghi rõ nhà ga hoặc địa danh nổi bật gần nhất.",
  "help.time": "Chọn khoảng giờ và buổi trong ngày.",
  "help.description": "Mô tả màu sắc, thương hiệu, chất liệu và đồ bên trong.",
  "help.identifying": "Nêu một đặc điểm kín mà chỉ chủ sở hữu thực sự mới biết.",
  "help.timeline": "Nhớ lại lộ trình di chuyển trong ngày để thu hẹp phạm vi tìm kiếm.",
  "report.badge": "Báo cáo thông minh",
  "report.titleLost": "Báo mất đồ",
  "report.titleFound": "Báo nhặt được đồ",
  "report.step1.title": "Thông tin cơ bản",
  "report.step1.typeLost": "Tôi bị mất đồ",
  "report.step1.typeFound": "Tôi nhặt được đồ",
  "report.step1.itemName": "Tên đồ vật",
  "report.step1.itemNamePlaceholder": "vd: Ví da nam Tommy Hilfiger màu đen, iPhone 15 Pro",
  "report.step1.category": "Danh mục",
  "report.step1.urgency": "Mức độ khẩn cấp",
  "report.step2.title": "Vị trí",
  "report.step2.location": "Địa điểm hoặc mốc nhận biết",
  "report.step2.locationPlaceholder": "vd: Ga trung tâm cổng số 2, Thư viện trường đại học",
  "report.step2.useGps": "Dùng vị trí GPS hiện tại",
  "report.step2.pinMap": "Ghim vị trí trên bản đồ",
  "report.step3.title": "Ngày & Giờ",
  "report.step3.date": "Ngày",
  "report.step3.time": "Thời gian ước tính",
  "report.step3.quickToday": "Hôm nay",
  "report.step3.quickYesterday": "Hôm qua",
  "report.step3.quickMorning": "Buổi sáng",
  "report.step3.quickAfternoon": "Buổi chiều",
  "report.step3.quickEvening": "Buổi tối",
  "report.step3.quickNight": "Ban đêm",
  "report.step4.title": "Mô tả & Đặc điểm nhận dạng",
  "report.step4.desc": "Mô tả chi tiết",
  "report.step4.descPlaceholder": "Mô tả màu sắc, nhãn hiệu, tình trạng bên ngoài...",
  "report.step4.aiEnhance": "Tối ưu hóa bằng AI",
  "report.step4.timelineBuilder": "Trợ lý dựng lại lộ trình",
  "report.step4.identifyingMarks": "Dấu hiệu nhận biết bí mật (Riêng tư)",
  "report.step4.identifyingPlaceholder": "vd: Vết xước ở góc phải, dán tem NASA, có 2 chìa khóa bên trong",
  "report.step4.photo": "Ảnh chụp đồ vật",
  "report.step5.title": "Liên hệ & Quyền riêng tư",
  "report.step5.contact": "Số điện thoại / WhatsApp",
  "report.step5.contactPlaceholder": "Số điện thoại 10 chữ số",
  "report.step5.contactNotice": "Số điện thoại của bạn không bao giờ hiển thị trên bảng tin công khai.",
  "report.step6.title": "Tiền chuộc/hậu tạ & Mã PIN",
  "report.step6.reward": "Tiền hậu tạ (Không bắt buộc)",
  "report.step6.aiReward": "Mức hậu tạ gợi ý bởi AI",
  "report.step6.pin": "Mã PIN bảo mật 4 chữ số",
  "report.step6.pinNotice": "Hãy lưu giữ mã PIN này để chỉnh sửa hoặc hoàn tất tin đăng sau này.",
  "feed.title": "Bảng tin Cộng đồng",
  "feed.subtitle": "Tin tức mới nhất về đồ thất lạc và nhặt được tại khu vực của bạn.",
  "feed.all": "Tất cả",
  "feed.lost": "Đồ thất lạc",
  "feed.found": "Đồ nhặt được",
  "feed.resolved": "Đã trao trả",
  "feed.listView": "Dạng danh sách",
  "feed.mapView": "Dạng bản đồ",
  "feed.searchPlaceholder": "Tìm theo tên đồ, vị trí hoặc danh mục...",
  "feed.noResults": "Không tìm thấy tin đăng phù hợp với điều kiện tìm kiếm.",
  "feed.claimButton": "Đây là của tôi",
  "feed.foundButton": "Tôi đã nhặt được",
  "feed.viewMatches": "Xem kết quả khớp",
  "matches.title": "Trung tâm Khớp nối AI",
  "matches.subtitle": "Tự động phân tích ngữ nghĩa và kết nối đồ thất lạc với đồ nhặt được.",
  "matches.allMatches": "Tất cả kết quả",
  "matches.mutualApprovals": "Xác nhận song phương",
  "matches.pendingVerification": "Chờ xác minh",
  "matches.resolved": "Đã hoàn tất",
  "matches.threshold": "Ngưỡng tương đồng",
  "matches.confidence": "Độ tin cậy",
  "matches.score": "Điểm số",
  "matches.reason": "Lý do trùng khớp",
  "matches.lostReport": "Tin báo mất",
  "matches.foundReport": "Tin báo nhặt được",
  "matches.openChat": "Bắt đầu trò chuyện an toàn",
  "matches.verifyApprove": "Xác minh & Phê duyệt",
  "matches.modalTitle": "Chi tiết đối chiếu",
  "matches.notFoundTitle": "Không có kết quả khớp",
  "matches.notFoundDesc": "Hiện chưa có kết quả nào phù hợp với bộ lọc bạn chọn.",
  "matches.backToActivity": "Quay lại Hoạt động",
  "chat.title": "Phòng Trò chuyện Trao trả An toàn",
  "chat.trustButton": "Xác nhận tin cậy",
  "chat.whatsapp": "Tiếp tục trên WhatsApp",
  "chat.handover": "Bắt đầu bàn giao an toàn",
  "chat.received": "Tôi đã nhận lại đồ",
  "chat.resolved": "Đã đóng vụ việc",
  "chat.placeholder": "Gửi tin nhắn bảo mật...",
  "chat.send": "Gửi",
  "chat.safetyWarning": "Lưu ý an toàn: Luôn gặp gỡ tại nơi công cộng đông người. Tuyệt đối không chuyển tiền trước.",
  "enhance.modalTitle": "Tối ưu hóa mô tả bằng AI",
  "enhance.aiBadge": "Tạo bởi AI",
  "enhance.original": "Mô tả ban đầu",
  "enhance.enhanced": "Mô tả đã tối ưu",
  "enhance.structuredHeading": "Thuộc tính được trích xuất",
  "enhance.accept": "Áp dụng nội dung này",
  "enhance.edit": "Chỉnh sửa",
  "enhance.tryAgain": "Tạo lại",
  "enhance.keepOriginal": "Giữ nguyên bản gốc",
  "enhance.suggestions": "Gợi ý thêm",
  "timeline.title": "Dựng lại Dòng thời gian bằng AI",
  "timeline.subtitle": "Nhớ lại các điểm dừng trong ngày để khoanh vùng chính xác thời gian và địa điểm.",
  "timeline.userProvided": "Thông tin bạn cung cấp",
  "timeline.aiInferred": "Phân tích suy luận từ AI",
  "timeline.unknown": "Chưa rõ",
  "timeline.likelyLocation": "Khu vực có khả năng nhất",
  "timeline.timeWindow": "Khung thời gian",
  "timeline.reasoning": "Lập luận của AI",
  "timeline.applyLocation": "Sử dụng vị trí này",
  "timeline.editEvent": "Sửa mốc",
  "timeline.addEvent": "Thêm mốc",
  "home.heroTag": "Tìm kiếm • Xác minh • Trao trả",
  "home.heroTitle1": "Danh tính của bạn luôn được bảo vệ.",
  "home.heroTitle2": "Đồ đạc thất lạc sẽ tìm về với chủ.",
  "home.heroSubtitle1": "Đừng bao giờ từ bỏ những món đồ thuộc về bạn.",
  "home.heroSubtitle2": "Được xây dựng bởi cộng đồng. Được bảo vệ bởi AI.",
  "home.heroDesc": "Đăng tin báo mất hoặc nhặt được chỉ trong một phút. Thông tin riêng tư của bạn luôn được bảo mật cho đến khi xác minh sở hữu thành công.",
  "home.reportLost": "Báo mất đồ",
  "home.reportFound": "Báo nhặt được",
  "home.findItem": "Tìm đồ thất lạc",
  "home.viewMatches": "Xem AI khớp nối",
  "home.startReport": "Tạo tin báo",
  "home.browseFeed": "Xem bảng tin",
  "home.statsTotal": "Tổng tin đăng",
  "home.statsLost": "Đồ báo mất",
  "home.statsFound": "Đồ nhặt được",
  "home.statsResolved": "Đã trao trả lại",
  "home.trustTitle": "Vì sao chọn LINCO",
  "home.trustSubtitle": "Xây dựng trên nền tảng bảo mật Zero-knowledge, bằng chứng sở hữu chắc chắn và bàn giao an toàn.",
  "home.trustPrivacyTitle": "Bảo mật danh tính",
  "home.trustPrivacyDesc": "Số điện thoại và thông tin cá nhân của bạn không bao giờ hiển thị trên bảng tin công khai.",
  "home.trustProofTitle": "Xác minh sở hữu chặt chẽ",
  "home.trustProofDesc": "Câu hỏi bảo mật do AI tạo ra giúp ngăn chặn hành vi nhận vơ lừa đảo trước khi gặp mặt.",
  "home.trustRecoveryTitle": "Mạng lưới trao trả an toàn",
  "home.trustRecoveryDesc": "Trao đổi qua phòng chat mã hóa, xác nhận song phương và quy trình bàn giao có hướng dẫn.",
  "home.timelineShowcaseTitle": "Dựng lại lộ trình trong ngày bằng AI",
  "home.timelineShowcaseSubtitle": "Nhớ lại các điểm dừng trong ngày để suy luận chính xác địa điểm và thời gian làm rơi đồ.",
  "home.timelineTryPrompt": "Thử một ví dụ:",
  "home.faqTitle": "Câu hỏi Thường gặp",
  "home.faqSubtitle": "Mọi thông tin bạn cần biết về cách LINCO hoạt động và bảo vệ bạn.",
  "dashboard.title": "Bảng Điều khiển Cá nhân",
  "dashboard.subtitle": "Quản lý tin đăng, phòng trao trả và thiết lập bảo mật của bạn.",
  "dashboard.tabReports": "Tin của tôi",
  "dashboard.tabClaims": "Yêu cầu nhận đồ",
  "dashboard.tabRecovery": "Phòng trao trả",
  "dashboard.tabSettings": "Cài đặt",
  "dashboard.noReports": "Bạn chưa đăng thông tin nào.",
  "dashboard.noClaims": "Hiện không có yêu cầu nhận đồ nào đang xử lý.",
  "dashboard.noRecovery": "Không có phòng trao trả nào đang hoạt động.",
  "dashboard.accountDetails": "Thông tin tài khoản",
  "dashboard.fullName": "Họ và tên",
  "dashboard.phoneNumber": "Số điện thoại",
  "dashboard.city": "Thành phố",
  "dashboard.languagePreference": "Ngôn ngữ ưa thích",
  "dashboard.changeLanguage": "Đổi ngôn ngữ",
  "dashboard.saveSettings": "Lưu cài đặt",
  "dashboard.settingsSaved": "Đã lưu cài đặt thành công.",
  "claim.modalTitle": "Gửi yêu cầu nhận lại đồ vật này",
  "claim.modalSubtitle": "Chứng minh bạn là chủ sở hữu hợp pháp bằng cách trả lời các câu hỏi xác minh.",
  "claim.verifyIdentity": "Xác minh danh tính & sở hữu",
  "claim.questionsPrompt": "Vui lòng trả lời chính xác các câu hỏi xác minh sau:",
  "claim.proofDetails": "Dấu hiệu riêng biệt hoặc bằng chứng sở hữu",
  "claim.proofPlaceholder": "Mô tả chi tiết ẩn bên trong, vết trầy xước đặc trưng hoặc số sê-ri...",
  "claim.submitClaim": "Gửi yêu cầu nhận lại",
  "claim.statusPending": "Đang chờ xem xét",
  "claim.statusApproved": "Yêu cầu đã được duyệt",
  "claim.statusRejected": "Yêu cầu bị từ chối",
  "claim.statusResolved": "Vụ việc đã giải quyết xong",
  "category.Electronics": "Thiết bị điện tử",
  "category.Documents": "Giấy tờ & Thẻ",
  "category.Keys": "Chìa khóa",
  "category.Pet": "Thú cưng",
  "category.Jewelry": "Trang sức & Đồng hồ",
  "category.Vehicle": "Phương tiện giao thông",
  "category.Clothing": "Quần áo & Túi xách",
  "category.Other": "Đồ dùng khác",
  "urgency.Normal": "Bình thường",
  "urgency.Urgent": "Khẩn cấp",
  "urgency.Medical": "Y tế / Tối khẩn"
}

TH_269 = {
  "app.tagline": "ศูนย์แจ้งของหายและพบของ AI อินเดีย",
  "app.subtitle": "ตามหาของหายด้วยการปกป้องความเป็นส่วนตัวและความน่าเชื่อถือที่ตรวจสอบได้",
  "nav.home": "หน้าแรก",
  "nav.report": "แจ้งเรื่อง",
  "nav.feed": "กระดานชุมชน",
  "nav.matches": "รายการจับคู่ AI",
  "nav.activity": "กิจกรรม",
  "nav.profile": "โปรไฟล์",
  "nav.about": "เกี่ยวกับเรา",
  "nav.privacyTrust": "ความเป็นส่วนตัวและความปลอดภัย",
  "nav.language": "ภาษา",
  "nav.saathii": "ผู้ช่วย LINCO",
  "common.back": "ย้อนกลับ",
  "common.next": "ถัดไป",
  "common.cancel": "ยกเลิก",
  "common.save": "บันทึก",
  "common.submit": "ส่งข้อมูล",
  "common.edit": "แก้ไข",
  "common.delete": "ลบ",
  "common.close": "ปิด",
  "common.loading": "กำลังโหลด...",
  "common.success": "สำเร็จ",
  "common.error": "เกิดข้อผิดพลาด",
  "common.search": "ค้นหา",
  "common.filter": "กรองข้อมูล",
  "common.clear": "ล้างข้อมูล",
  "common.optional": "ไม่บังคับ",
  "common.required": "จำเป็นต้องระบุ",
  "common.viewAll": "ดูทั้งหมด",
  "common.details": "รายละเอียด",
  "common.status": "สถานะ",
  "lang.heading": "เลือกภาษาของคุณ",
  "lang.subheading": "ใช้งาน LINCO ด้วยภาษาที่คุณถนัดและสะดวกใจที่สุด",
  "lang.note": "คุณสามารถเปลี่ยนภาษาได้ตลอดเวลาในการตั้งค่า",
  "lang.continue": "ดำเนินการต่อด้วย LINCO",
  "lang.searchPlaceholder": "ค้นหาภาษา (เช่น ภาษาไทย, English, Hindi)...",
  "lang.tabAll": "ทุกภาษา",
  "lang.tabIndian": "ภาษาทางการของอินเดีย (22)",
  "lang.tabInternational": "ภาษานานาชาติ",
  "lang.supportedBadge": "รองรับอย่างสมบูรณ์",
  "lang.previewBadge": "เวอร์ชันตัวอย่าง / เบต้า",
  "voice.button": "ป้อนข้อมูลด้วยเสียง",
  "voice.listening": "กำลังฟัง... พูดด้วยภาษาของคุณได้อย่างเป็นธรรมชาติ",
  "voice.processing": "กำลังประมวลผลเสียงบันทึก...",
  "voice.transcribing": "กำลังแปลงเสียงเป็นข้อความ...",
  "voice.reviewTitle": "ตรวจสอบข้อมูลจากเสียง",
  "voice.reviewSubtitle": "โปรดตรวจสอบความถูกต้องของข้อมูลที่ระบบตรวจจับก่อนนำไปใช้",
  "voice.apply": "นำข้อมูลไปใช้",
  "voice.retry": "พูดใหม่อีกครั้ง",
  "voice.cancel": "ยกเลิก",
  "voice.notSupported": "เบราว์เซอร์นี้ยังไม่รองรับระบบตรวจจับเสียงพูด",
  "voice.permissionDenied": "การเข้าถึงไมโครโฟนถูกปฏิเสธ กรุณาอนุญาตในการตั้งค่า",
  "notifications.centerTitle": "ศูนย์กิจกรรมและการแจ้งเตือน",
  "notifications.centerSubtitle": "การจับคู่แบบเรียลไทม์ การขอรับของคืน และความคืบหน้าการส่งมอบ",
  "notifications.readAll": "ทำเครื่องหมายว่าอ่านแล้วทั้งหมด",
  "notifications.unread": "ยังไม่ได้อ่าน",
  "notifications.emptyTitle": "ยังไม่มีการแจ้งเตือนใหม่",
  "notifications.emptySubtitle": "เราจะแจ้งให้คุณทราบทันทีที่มีความคืบหน้าเกี่ยวกับประกาศของคุณ",
  "notifications.networkFooter": "เครือข่ายแจ้งเตือนอัจฉริยะ LINCO",
  "notifications.listingAlert": "แจ้งเตือนประกาศใหม่",
  "notifications.matchFound": "พบรายการที่อาจตรงกัน",
  "notifications.claimReceived": "ได้รับคำขอแสดงความเป็นเจ้าของ",
  "notifications.ownerApproved": "เจ้าของของที่หายยืนยันแล้ว",
  "notifications.finderVerified": "ผู้พบของได้ตรวจสอบแล้ว",
  "notifications.verificationComplete": "การตรวจสอบร่วมกันเสร็จสมบูรณ์",
  "notifications.newMessage": "ข้อความปลอดภัยใหม่",
  "notifications.trustUpdate": "ระดับความน่าเชื่อถือได้รับการอัปเดต",
  "notifications.handoverUpdate": "อัปเดตสถานะการส่งมอบ",
  "notifications.itemReceived": "ได้รับสิ่งของเรียบร้อยแล้ว",
  "notifications.itemReunited": "ส่งคืนสิ่งของให้เจ้าของสำเร็จ",
  "notifications.actions.viewMatch": "ดูรายการจับคู่",
  "notifications.actions.reviewClaim": "ตรวจสอบคำขอ",
  "notifications.actions.viewVerification": "ดูการยืนยัน",
  "notifications.actions.openChat": "เปิดห้องสนทนา",
  "notifications.actions.confirmHandover": "ยืนยันการส่งมอบ",
  "notifications.actions.viewCase": "ดูกรณีนี้",
  "notifications.actions.viewDetails": "ดูรายละเอียด",
  "notifications.actions.confirmTrust": "ยืนยันความไว้วางใจ",
  "notifications.matchFoundMsg": "เราพบรายการที่มีความตรงกันสูงมากกับประกาศของคุณ",
  "notifications.claimReceivedMsg": "มีผู้ส่งคำขอแสดงความเป็นเจ้าของสำหรับสิ่งของชิ้นนี้",
  "notifications.claimApprovedMsg": "คำขอแสดงความเป็นเจ้าของของคุณได้รับการตรวจสอบและอนุมัติแล้ว",
  "notifications.ownerApprovedMsg": "เจ้าของยืนยันว่าสิ่งนี้น่าจะเป็นของที่ตนทำหาย",
  "notifications.finderVerifiedMsg": "ผู้พบของยืนยันว่าคำตอบของคุณตรงกับสิ่งของที่พบ",
  "notifications.bothApprovedMsg": "ทั้งสองฝ่ายยืนยันการจับคู่แล้ว ห้องสนทนาปลอดภัยพร้อมใช้งาน",
  "notifications.newMessageMsg": "คุณมีข้อความใหม่ในห้องสนทนาความปลอดภัยสูง",
  "notifications.trustUpdateMsg": "ยืนยันความไว้วางใจร่วมกันแล้ว! ข้อมูลติดต่อ WhatsApp ปลดล็อกแล้ว",
  "notifications.handoverUpdateMsg": "ขั้นตอนการนัดรับสิ่งของอย่างปลอดภัยได้เริ่มขึ้นแล้ว",
  "notifications.itemReceivedMsg": "ยืนยันการรับสิ่งของเรียบร้อยแล้ว",
  "notifications.itemReunitedMsg": "ส่งคืนสิ่งของถึงมือเจ้าของเรียบร้อย! ปิดกรณีอย่างเป็นทางการ",
  "help.notSure": "ไม่แน่ใจว่าจะเขียนอย่างไร?",
  "help.askLinco": "ปรึกษาผู้ช่วย LINCO",
  "help.listen": "ฟังคำแนะนำ",
  "help.stopListen": "หยุด",
  "help.itemName": "ระบุชื่อเรียกทั่วไปของสิ่งของ (เช่น กระเป๋าสตางค์หนัง, iPhone 14)",
  "help.location": "ระบุสถานีรถไฟหรือจุดสังเกตสำคัญที่อยู่ใกล้ที่สุด",
  "help.time": "เลือกเวลาและช่วงเวลาโดยประมาณของวัน",
  "help.description": "อธิบายสี ยี่ห้อ วัสดุ และสิ่งของที่อยู่ข้างใน",
  "help.identifying": "ระบุจุดสังเกตเฉพาะที่เป็นความลับซึ่งมีเพียงเจ้าของตัวจริงเท่านั้นที่รู้",
  "help.timeline": "ทบทวนการเดินทางในวันนั้นเพื่อจำกัดขอบเขตพื้นที่ให้แคบลง",
  "report.badge": "ระบบแจ้งข้อมูลอัจฉริยะ",
  "report.titleLost": "แจ้งของหาย",
  "report.titleFound": "แจ้งพบของ",
  "report.step1.title": "ข้อมูลเบื้องต้น",
  "report.step1.typeLost": "ฉันทำของหาย",
  "report.step1.typeFound": "ฉันเก็บของได้",
  "report.step1.itemName": "ชื่อสิ่งของ",
  "report.step1.itemNamePlaceholder": "เช่น กระเป๋าสตางค์หนังสีดำ Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "หมวดหมู่",
  "report.step1.urgency": "ระดับความเร่งด่วน",
  "report.step2.title": "สถานที่",
  "report.step2.location": "สถานที่หรือจุดสังเกตใกล้เคียง",
  "report.step2.locationPlaceholder": "เช่น ทางออก 2 สถานีกลาง, คาเฟ่ห้องสมุดมหาวิทยาลัย",
  "report.step2.useGps": "ใช้พิกัด GPS ปัจจุบัน",
  "report.step2.pinMap": "ปักหมุดบนแผนที่",
  "report.step3.title": "วันและเวลา",
  "report.step3.date": "วันที่",
  "report.step3.time": "เวลาโดยประมาณ",
  "report.step3.quickToday": "วันนี้",
  "report.step3.quickYesterday": "เมื่อวานนี้",
  "report.step3.quickMorning": "ช่วงเช้า",
  "report.step3.quickAfternoon": "ช่วงบ่าย",
  "report.step3.quickEvening": "ช่วงเย็น",
  "report.step3.quickNight": "เวลากลางคืน",
  "report.step4.title": "รายละเอียดและจุดสังเกต",
  "report.step4.desc": "คำอธิบายอย่างละเอียด",
  "report.step4.descPlaceholder": "ระบุสี รุ่น สภาพภายนอกอย่างละเอียด...",
  "report.step4.aiEnhance": "ปรับแต่งข้อความด้วย AI",
  "report.step4.timelineBuilder": "ผู้ช่วยจำลองเส้นทาง",
  "report.step4.identifyingMarks": "จุดสังเกตเฉพาะทาง (ข้อมูลลับ)",
  "report.step4.identifyingPlaceholder": "เช่น รอยขูดที่มุมขวา, สติกเกอร์ NASA, กุญแจ 2 ดอกด้านใน",
  "report.step4.photo": "รูปถ่ายสิ่งของ",
  "report.step5.title": "การติดต่อและความเป็นส่วนตัว",
  "report.step5.contact": "เบอร์โทรศัพท์ / WhatsApp",
  "report.step5.contactPlaceholder": "หมายเลขโทรศัพท์ 10 หลัก",
  "report.step5.contactNotice": "เบอร์โทรศัพท์ของคุณจะไม่แสดงบนกระดานชุมชนสาธารณะเด็ดขาด",
  "report.step6.title": "สินน้ำใจและรหัส PIN",
  "report.step6.reward": "สินน้ำใจตอบแทน (ไม่บังคับ)",
  "report.step6.aiReward": "จำนวนสินน้ำใจที่ AI แนะนำ",
  "report.step6.pin": "รหัส PIN ความปลอดภัย 4 หลัก",
  "report.step6.pinNotice": "กรุณาจดจำรหัส PIN นี้เพื่อใช้แก้ไขหรือปิดประกาศในภายหลัง",
  "feed.title": "กระดานชุมชน",
  "feed.subtitle": "รายการแจ้งของหายและพบของล่าสุดในพื้นที่ของคุณ",
  "feed.all": "ทั้งหมด",
  "feed.lost": "ของหาย",
  "feed.found": "พบของ",
  "feed.resolved": "ส่งคืนสำเร็จ",
  "feed.listView": "มุมมองรายการ",
  "feed.mapView": "มุมมองแผนที่",
  "feed.searchPlaceholder": "ค้นหาตามชื่อสิ่งของ สถานที่ หรือหมวดหมู่...",
  "feed.noResults": "ไม่พบรายการที่ตรงกับเงื่อนไขการค้นหา",
  "feed.claimButton": "นี่คือของฉัน",
  "feed.foundButton": "ฉันพบสิ่งนี้",
  "feed.viewMatches": "ดูรายการที่ตรงกัน",
  "matches.title": "ศูนย์จับคู่ด้วย AI",
  "matches.subtitle": "จับคู่ความสอดคล้องตามหลักความหมายระหว่างของหายและของที่พบโดยอัตโนมัติ",
  "matches.allMatches": "รายการจับคู่ทั้งหมด",
  "matches.mutualApprovals": "ยืนยันร่วมกันแล้ว",
  "matches.pendingVerification": "รอการตรวจสอบ",
  "matches.resolved": "เสร็จสิ้น",
  "matches.threshold": "เกณฑ์ความแม่นยำ",
  "matches.confidence": "ระดับความเชื่อมั่น",
  "matches.score": "คะแนน",
  "matches.reason": "เหตุผลที่ตรงกัน",
  "matches.lostReport": "ประกาศของหาย",
  "matches.foundReport": "ประกาศพบของ",
  "matches.openChat": "เปิดการสนทนาปลอดภัย",
  "matches.verifyApprove": "ตรวจสอบและอนุมัติ",
  "matches.modalTitle": "รายละเอียดการจับคู่",
  "matches.notFoundTitle": "ไม่พบรายการที่ตรงกัน",
  "matches.notFoundDesc": "ขณะนี้ยังไม่มีรายการที่ตรงกับตัวกรองที่คุณเลือก",
  "matches.backToActivity": "กลับไปยังกิจกรรม",
  "chat.title": "ห้องสนทนาส่งมอบอย่างปลอดภัย",
  "chat.trustButton": "ยืนยันความไว้วางใจ",
  "chat.whatsapp": "คุยต่อทาง WhatsApp",
  "chat.handover": "เริ่มการส่งมอบอย่างปลอดภัย",
  "chat.received": "ฉันได้รับสิ่งของแล้ว",
  "chat.resolved": "ปิดเรื่องเรียบร้อย",
  "chat.placeholder": "พิมพ์ข้อความที่ปลอดภัย...",
  "chat.send": "ส่ง",
  "chat.safetyWarning": "คำแนะนำด้านความปลอดภัย: นัดพบในที่สาธารณะที่มีคนพลุกพล่านเสมอ ห้ามโอนเงินล่วงหน้าเด็ดขาด",
  "enhance.modalTitle": "ปรับแต่งข้อความด้วย AI",
  "enhance.aiBadge": "สร้างโดย AI",
  "enhance.original": "คำอธิบายเดิม",
  "enhance.enhanced": "คำอธิบายที่ปรับปรุงแล้ว",
  "enhance.structuredHeading": "คุณลักษณะที่จัดโครงสร้างแล้ว",
  "enhance.accept": "ยอมรับและนำไปใช้",
  "enhance.edit": "แก้ไขเพิ่มเติม",
  "enhance.tryAgain": "สร้างใหม่อีกครั้ง",
  "enhance.keepOriginal": "ใช้ข้อความเดิม",
  "enhance.suggestions": "ข้อเสนอแนะเพิ่มเติม",
  "timeline.title": "จำลองไทม์ไลน์การเดินทางด้วย AI",
  "timeline.subtitle": "ทบทวนการเดินทางเพื่อระบุเวลาและสถานที่ที่ของตกหายได้อย่างแม่นยำ",
  "timeline.userProvided": "ข้อมูลที่คุณระบุ",
  "timeline.aiInferred": "การวิเคราะห์ของ AI",
  "timeline.unknown": "ไม่ระบุ",
  "timeline.likelyLocation": "พื้นที่ที่มีโอกาสเป็นไปได้มากที่สุด",
  "timeline.timeWindow": "ช่วงเวลาที่คาดการณ์",
  "timeline.reasoning": "เหตุผลเชิงวิเคราะห์ของ AI",
  "timeline.applyLocation": "ใช้ตำแหน่งนี้",
  "timeline.editEvent": "แก้ไขจุดแวะ",
  "timeline.addEvent": "เพิ่มจุดแวะ",
  "home.heroTag": "ค้นหา • ยืนยัน • ส่งคืน",
  "home.heroTitle1": "ตัวตนของคุณจะได้รับการปกป้องอย่างสมบูรณ์",
  "home.heroTitle2": "สิ่งของสำคัญจะกลับคืนสู่เจ้าของ",
  "home.heroSubtitle1": "อย่าหมดหวังที่จะได้ของสำคัญของคุณคืน",
  "home.heroSubtitle2": "ขับเคลื่อนด้วยพลังชุมชน ปกป้องความปลอดภัยด้วย AI",
  "home.heroDesc": "แจ้งของหายหรือพบของได้ภายในเวลาไม่ถึงหนึ่งนาที ข้อมูลส่วนตัวของคุณจะถูกเก็บเป็นความลับจนกว่าจะยืนยันความเป็นเจ้าของร่วมกันสำเร็จ",
  "home.reportLost": "แจ้งของหาย",
  "home.reportFound": "แจ้งพบของ",
  "home.findItem": "ค้นหาสิ่งของ",
  "home.viewMatches": "ดูรายการจับคู่ AI",
  "home.startReport": "เริ่มสร้างประกาศ",
  "home.browseFeed": "ดูกระดานชุมชน",
  "home.statsTotal": "ประกาศทั้งหมด",
  "home.statsLost": "ของที่แจ้งหาย",
  "home.statsFound": "ของที่แจ้งพบ",
  "home.statsResolved": "ส่งคืนสำเร็จแล้ว",
  "home.trustTitle": "ทำไมต้องเลือก LINCO",
  "home.trustSubtitle": "สร้างขึ้นด้วยระบบความเป็นส่วนตัวแบบ Zero-knowledge การพิสูจน์ความเป็นเจ้าของที่รัดกุม และการส่งมอบอย่างปลอดภัย",
  "home.trustPrivacyTitle": "ปกป้องตัวตนผู้ใช้",
  "home.trustPrivacyDesc": "เบอร์โทรศัพท์และข้อมูลส่วนตัวของคุณจะไม่ถูกเปิดเผยบนกระดานสาธารณะอย่างแน่นอน",
  "home.trustProofTitle": "พิสูจน์ความเป็นเจ้าของจริง",
  "home.trustProofDesc": "คำถามคัดกรองลับจาก AI ช่วยป้องกันการแอบอ้างสวมสิทธิ์ก่อนการนัดพบจริง",
  "home.trustRecoveryTitle": "เครือข่ายการส่งคืนที่ปลอดภัย",
  "home.trustRecoveryDesc": "ประสานงานผ่านห้องแชตเข้ารหัส การยินยอมสองฝ่าย และขั้นตอนการส่งมอบที่มีคำแนะนำชัดเจน",
  "home.timelineShowcaseTitle": "จำลองเส้นทางประจำวันด้วย AI",
  "home.timelineShowcaseSubtitle": "นึกถึงสถานที่ที่คุณแวะระหว่างวันเพื่อค้นหาจุดและเวลาที่ทำของหายได้อย่างแม่นยำ",
  "home.timelineTryPrompt": "ลองดูตัวอย่าง:",
  "home.faqTitle": "คำถามที่พบบ่อย",
  "home.faqSubtitle": "ทุกสิ่งที่คุณควรรู้เกี่ยวกับการทำงานและความปลอดภัยของ LINCO",
  "dashboard.title": "แดชบอร์ดพลเมือง",
  "dashboard.subtitle": "จัดการประกาศของคุณ ห้องส่งมอบของ และการตั้งค่าความปลอดภัย",
  "dashboard.tabReports": "ประกาศของฉัน",
  "dashboard.tabClaims": "คำขอรับของของฉัน",
  "dashboard.tabRecovery": "ห้องส่งมอบ",
  "dashboard.tabSettings": "การตั้งค่า",
  "dashboard.noReports": "คุณยังไม่มีประกาศในขณะนี้",
  "dashboard.noClaims": "ไม่มีคำขอรับของที่กำลังดำเนินการอยู่",
  "dashboard.noRecovery": "ไม่มีห้องส่งมอบที่กำลังเปิดอยู่",
  "dashboard.accountDetails": "ข้อมูลบัญชี",
  "dashboard.fullName": "ชื่อ-นามสกุล",
  "dashboard.phoneNumber": "หมายเลขโทรศัพท์",
  "dashboard.city": "เมือง",
  "dashboard.languagePreference": "ภาษาที่ต้องการใช้งาน",
  "dashboard.changeLanguage": "เปลี่ยนภาษา",
  "dashboard.saveSettings": "บันทึกการตั้งค่า",
  "dashboard.settingsSaved": "บันทึกการตั้งค่าเรียบร้อยแล้ว",
  "claim.modalTitle": "ยื่นคำขอแสดงความเป็นเจ้าของสิ่งนี้",
  "claim.modalSubtitle": "พิสูจน์ว่าคุณเป็นเจ้าของตัวจริงโดยตอบคำถามยืนยันให้ถูกต้อง",
  "claim.verifyIdentity": "การตรวจสอบความเป็นเจ้าของ",
  "claim.questionsPrompt": "โปรดตอบคำถามต่อไปนี้อย่างละเอียดและตรงกับความจริง:",
  "claim.proofDetails": "ลักษณะเฉพาะหรือหลักฐานยืนยัน",
  "claim.proofPlaceholder": "ระบุสิ่งของที่ซ่อนอยู่ด้านใน รอยตำหนิเฉพาะ หรือหมายเลขซีเรียล...",
  "claim.submitClaim": "ส่งคำขอแสดงความเป็นเจ้าของ",
  "claim.statusPending": "อยู่ระหว่างการตรวจสอบ",
  "claim.statusApproved": "อนุมัติคำขอแล้ว",
  "claim.statusRejected": "ปฏิเสธคำขอ",
  "claim.statusResolved": "ส่งคืนสำเร็จเสร็จสิ้น",
  "category.Electronics": "อุปกรณ์อิเล็กทรอนิกส์",
  "category.Documents": "เอกสารและบัตรต่างๆ",
  "category.Keys": "พวงกุญแจ",
  "category.Pet": "สัตว์เลี้ยง",
  "category.Jewelry": "เครื่องประดับและนาฬิกา",
  "category.Vehicle": "ยานพาหนะ",
  "category.Clothing": "เสื้อผ้าและกระเป๋า",
  "category.Other": "สิ่งของอื่นๆ",
  "urgency.Normal": "ปกติ",
  "urgency.Urgent": "เร่งด่วน",
  "urgency.Medical": "การแพทย์ / วิกฤตสำคัญ"
}
