# -*- coding: utf-8 -*-
"""Authentic German (DE) and Dutch (NL) translations for all 269 UI keys."""

DE_269 = {
  "app.tagline": "KI Fundbüro Indien",
  "app.subtitle": "Verlorene Gegenstände mit Privatsphäre und verifiziertem Vertrauen wiederfinden.",
  "nav.home": "Startseite",
  "nav.report": "Meldung Erfassen",
  "nav.feed": "Community-Feed",
  "nav.matches": "KI-Treffer",
  "nav.activity": "Aktivität",
  "nav.profile": "Profil",
  "nav.about": "Über Uns",
  "nav.privacyTrust": "Datenschutz & Vertrauen",
  "nav.language": "Sprache",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Zurück",
  "common.next": "Weiter",
  "common.cancel": "Abbrechen",
  "common.save": "Speichern",
  "common.submit": "Absenden",
  "common.edit": "Bearbeiten",
  "common.delete": "Löschen",
  "common.close": "Schließen",
  "common.loading": "Wird geladen...",
  "common.success": "Erfolgreich",
  "common.error": "Fehler",
  "common.search": "Suchen",
  "common.filter": "Filtern",
  "common.clear": "Zurücksetzen",
  "common.optional": "Optional",
  "common.required": "Erforderlich",
  "common.viewAll": "Alle Anzeigen",
  "common.details": "Details",
  "common.status": "Status",
  "lang.heading": "Wählen Sie Ihre Sprache",
  "lang.subheading": "Nutzen Sie LINCO in der Sprache, mit der Sie sich am wohlsten fühlen.",
  "lang.note": "Sie können die Sprache jederzeit in den Einstellungen ändern.",
  "lang.continue": "Mit LINCO fortfahren",
  "lang.searchPlaceholder": "Sprachen durchsuchen (z. B. Deutsch, English, Hindi)...",
  "lang.tabAll": "Alle Sprachen",
  "lang.tabIndian": "Indische Sprachen (22)",
  "lang.tabInternational": "Internationale Sprachen",
  "lang.supportedBadge": "Vollständig Unterstützt",
  "lang.previewBadge": "Vorschau / Beta",
  "voice.button": "Spracheingabe",
  "voice.listening": "Höre zu... Sprechen Sie ganz natürlich in Ihrer Sprache",
  "voice.processing": "Sprachnachricht wird verarbeitet...",
  "voice.transcribing": "Wird transkribiert...",
  "voice.reviewTitle": "Sprachmeldung Überprüfen",
  "voice.reviewSubtitle": "Prüfen Sie die erkannten Details vor der Übernahme.",
  "voice.apply": "Details Übernehmen",
  "voice.retry": "Erneut Sprechen",
  "voice.cancel": "Abbrechen",
  "voice.notSupported": "Spracherkennung wird von diesem Browser leider nicht unterstützt.",
  "voice.permissionDenied": "Mikrofonzugriff verweigert. Bitte in den Einstellungen erlauben.",
  "notifications.centerTitle": "Aktivitätszentrale",
  "notifications.centerSubtitle": "Echtzeit-Treffer, Eigentumsansprüche und Rückgabestatus.",
  "notifications.readAll": "Alle als gelesen markieren",
  "notifications.unread": "Ungelesen",
  "notifications.emptyTitle": "Keine neuen Benachrichtigungen",
  "notifications.emptySubtitle": "Wir benachrichtigen Sie, sobald es Neuigkeiten zu Ihren Einträgen gibt.",
  "notifications.networkFooter": "LINCO Intelligentes Benachrichtigungsnetzwerk",
  "notifications.listingAlert": "Neuer Eintrag Gemeldet",
  "notifications.matchFound": "Möglicher Treffer Gefunden",
  "notifications.claimReceived": "Eigentumsanspruch Eingegangen",
  "notifications.ownerApproved": "Vom Eigentümer Bestätigt",
  "notifications.finderVerified": "Vom Finder Verifiziert",
  "notifications.verificationComplete": "Gegenseitige Verifizierung Abgeschlossen",
  "notifications.newMessage": "Neue Sichere Nachricht",
  "notifications.trustUpdate": "Vertrauensstufe Aktualisiert",
  "notifications.handoverUpdate": "Übergabestatus Aktualisiert",
  "notifications.itemReceived": "Gegenstand Erhalten",
  "notifications.itemReunited": "Erfolgreich Zurückgegeben",
  "notifications.actions.viewMatch": "Treffer Ansehen",
  "notifications.actions.reviewClaim": "Anspruch Prüfen",
  "notifications.actions.viewVerification": "Verifizierung Prüfen",
  "notifications.actions.openChat": "Chat Öffnen",
  "notifications.actions.confirmHandover": "Übergabe Bestätigen",
  "notifications.actions.viewCase": "Fall Anzeigen",
  "notifications.actions.viewDetails": "Details Anzeigen",
  "notifications.actions.confirmTrust": "Vertrauen Bestätigen",
  "notifications.matchFoundMsg": "Wir haben einen sehr wahrscheinlichen Treffer für Ihre Meldung gefunden.",
  "notifications.claimReceivedMsg": "Jemand hat einen Eigentumsanspruch für diesen Gegenstand eingereicht.",
  "notifications.claimApprovedMsg": "Ihr Anspruch wurde von der Gegenseite geprüft und bestätigt.",
  "notifications.ownerApprovedMsg": "Der Eigentümer hat bestätigt, dass es sich um seinen Gegenstand handeln könnte.",
  "notifications.finderVerifiedMsg": "Der Finder hat bestätigt, dass Ihre Angaben zum Fundstück passen.",
  "notifications.bothApprovedMsg": "Beide Parteien haben den Treffer bestätigt. Der sichere Chat ist nun freigeschaltet.",
  "notifications.newMessageMsg": "Sie haben eine neue Nachricht im sicheren Chat erhalten.",
  "notifications.trustUpdateMsg": "Gegenseitiges Vertrauen bestätigt! WhatsApp-Kontaktdaten wurden freigegeben.",
  "notifications.handoverUpdateMsg": "Der geschützte Übergabeprozess wurde gestartet.",
  "notifications.itemReceivedMsg": "Der Empfang des Gegenstands wurde erfolgreich bestätigt.",
  "notifications.itemReunitedMsg": "Gegenstand erfolgreich zurückgegeben! Der Fall ist offiziell abgeschlossen.",
  "help.notSure": "Unsicher, was Sie schreiben sollen?",
  "help.askLinco": "LINCO Fragen",
  "help.listen": "Hilfe Vorlesen",
  "help.stopListen": "Stopp",
  "help.itemName": "Geben Sie die genaue Bezeichnung an (z. B. Ledergeldbörse, iPhone 14).",
  "help.location": "Nennen Sie den nächsten Bahnhof oder bekannten Orientierungspunkt.",
  "help.time": "Geben Sie die ungefähre Uhrzeit und Tageszeit an.",
  "help.description": "Beschreiben Sie Farbe, Material, Marke und Inneninhalt.",
  "help.identifying": "Nennen Sie ein Merkmal, das nur der wahre Eigentümer wissen kann.",
  "help.timeline": "Rekonstruieren Sie Ihren Tagesablauf Schritt für Schritt.",
  "report.badge": "Smarte Meldung",
  "report.titleLost": "Verlorenen Gegenstand Melden",
  "report.titleFound": "Gefundenen Gegenstand Melden",
  "report.step1.title": "Basisinformationen",
  "report.step1.typeLost": "Ich Habe Etwas Verloren",
  "report.step1.typeFound": "Ich Habe Etwas Gefunden",
  "report.step1.itemName": "Bezeichnung des Gegenstands",
  "report.step1.itemNamePlaceholder": "z. B. Schwarze Tommy Hilfiger Geldbörse, iPhone 15 Pro",
  "report.step1.category": "Kategorie",
  "report.step1.urgency": "Dringlichkeitsstufe",
  "report.step2.title": "Ort",
  "report.step2.location": "Fundort oder Orientierungspunkt",
  "report.step2.locationPlaceholder": "z. B. Hauptbahnhof Gleis 4, Universitätsbibliothek",
  "report.step2.useGps": "Aktuellen GPS-Standort Nutzen",
  "report.step2.pinMap": "Auf Karte Markieren",
  "report.step3.title": "Datum und Uhrzeit",
  "report.step3.date": "Datum",
  "report.step3.time": "Ungefähre Uhrzeit",
  "report.step3.quickToday": "Heute",
  "report.step3.quickYesterday": "Gestern",
  "report.step3.quickMorning": "Morgens",
  "report.step3.quickAfternoon": "Nachmittags",
  "report.step3.quickEvening": "Abends",
  "report.step3.quickNight": "Nachts",
  "report.step4.title": "Beschreibung & Merkmale",
  "report.step4.desc": "Detaillierte Beschreibung",
  "report.step4.descPlaceholder": "Beschreiben Sie Farbe, Marke, Modell und Zustand...",
  "report.step4.aiEnhance": "Mit KI Präzisieren",
  "report.step4.timelineBuilder": "Routen-Assistent",
  "report.step4.identifyingMarks": "Kennzeichnende Merkmale (Vertraulich)",
  "report.step4.identifyingPlaceholder": "z. B. Kratzer an rechter Ecke, NASA-Sticker, 2 Schlüssel innen",
  "report.step4.photo": "Foto des Gegenstands",
  "report.step5.title": "Kontakt & Privatsphäre",
  "report.step5.contact": "Telefonnummer / WhatsApp",
  "report.step5.contactPlaceholder": "10-stellige Handynummer",
  "report.step5.contactNotice": "Ihre Rufnummer wird niemals öffentlich im Feed angezeigt.",
  "report.step6.title": "Finderlohn & PIN-Code",
  "report.step6.reward": "Ausgelobter Finderlohn (Optional)",
  "report.step6.aiReward": "KI-Empfohlener Finderlohn",
  "report.step6.pin": "4-Stelliger Sicherheits-PIN",
  "report.step6.pinNotice": "Bewahren Sie diesen PIN auf, um Ihren Eintrag später zu bearbeiten oder zu schließen.",
  "feed.title": "Community-Feed",
  "feed.subtitle": "Aktuelle Meldungen über verlorene und gefundene Dinge in Ihrer Region.",
  "feed.all": "Alle",
  "feed.lost": "Verloren",
  "feed.found": "Gefunden",
  "feed.resolved": "Erledigt",
  "feed.listView": "Listenansicht",
  "feed.mapView": "Kartenansicht",
  "feed.searchPlaceholder": "Nach Gegenstand, Ort oder Kategorie suchen...",
  "feed.noResults": "Keine Einträge für diese Suchkriterien gefunden.",
  "feed.claimButton": "Das Gehört Mir",
  "feed.foundButton": "Habe Ich Gefunden",
  "feed.viewMatches": "Treffer Ansehen",
  "matches.title": "KI-Abgleichzentrale",
  "matches.subtitle": "Automatische semantische Verknüpfung von Verlust- und Fundmeldungen.",
  "matches.allMatches": "Alle Treffer",
  "matches.mutualApprovals": "Gegenseitige Bestätigungen",
  "matches.pendingVerification": "Ausstehende Prüfung",
  "matches.resolved": "Abgeschlossen",
  "matches.threshold": "Übereinstimmungsschwelle",
  "matches.confidence": "Konfidenzwert",
  "matches.score": "Punktzahl",
  "matches.reason": "Trefferbegründung",
  "matches.lostReport": "Verlustmeldung",
  "matches.foundReport": "Fundmeldung",
  "matches.openChat": "Sicheren Chat Starten",
  "matches.verifyApprove": "Prüfen & Freigeben",
  "matches.modalTitle": "Treffer-Details",
  "matches.notFoundTitle": "Keine Treffer gefunden",
  "matches.notFoundDesc": "Aktuell liegen keine Treffer für die gewählten Filter vor.",
  "matches.backToActivity": "Zurück zur Aktivität",
  "chat.title": "Geschützter Rückgabe-Chat",
  "chat.trustButton": "Vertrauen Bestätigen",
  "chat.whatsapp": "Auf WhatsApp Fortsetzen",
  "chat.handover": "Sichere Übergabe Einleiten",
  "chat.received": "Gegenstand Erhalten",
  "chat.resolved": "Fall Abgeschlossen",
  "chat.placeholder": "Sichere Nachricht schreiben...",
  "chat.send": "Senden",
  "chat.safetyWarning": "Sicherheitshinweis: Treffen Sie sich stets an belebten öffentlichen Orten. Überweisen Sie niemals Geld vorab.",
  "enhance.modalTitle": "Textoptimierung mit KI",
  "enhance.aiBadge": "KI-Generiert",
  "enhance.original": "Ursprüngliche Beschreibung",
  "enhance.enhanced": "Optimierte Beschreibung",
  "enhance.structuredHeading": "Extrahierte Merkmale",
  "enhance.accept": "Änderungen Übernehmen",
  "enhance.edit": "Bearbeiten",
  "enhance.tryAgain": "Neu Generieren",
  "enhance.keepOriginal": "Original Beibehalten",
  "enhance.suggestions": "Empfehlungen",
  "timeline.title": "KI-Routenrekonstruktion",
  "timeline.subtitle": "Rekonstruieren Sie Ihre Schritte, um Ort und Zeit präzise einzugrenzen.",
  "timeline.userProvided": "Benutzerangaben",
  "timeline.aiInferred": "KI-Schlussfolgerung",
  "timeline.unknown": "Unbekannt",
  "timeline.likelyLocation": "Wahrscheinlichster Bereich",
  "timeline.timeWindow": "Zeitfenster",
  "timeline.reasoning": "KI-Begründung",
  "timeline.applyLocation": "Diesen Ort Nutzen",
  "timeline.editEvent": "Schritt Bearbeiten",
  "timeline.addEvent": "Schritt Hinzufügen",
  "home.heroTag": "Finden • Prüfen • Wiedersehen",
  "home.heroTitle1": "Ihre Identität bleibt geschützt.",
  "home.heroTitle2": "Ihr Eigentum kehrt zurück.",
  "home.heroSubtitle1": "Verlieren Sie nie wieder, was Ihnen gehört.",
  "home.heroSubtitle2": "Gemeinschaftlich getragen. Durch KI geschützt.",
  "home.heroDesc": "Erfassen Sie Verlust- oder Fundmeldungen in unter einer Minute. Ihre Daten bleiben vertraulich, bis die Eigentümerschaft nachgewiesen ist.",
  "home.reportLost": "Verlorenes Melden",
  "home.reportFound": "Gefundenes Melden",
  "home.findItem": "Gegenstand Suchen",
  "home.viewMatches": "KI-Treffer Ansehen",
  "home.startReport": "Meldung Starten",
  "home.browseFeed": "Feed Durchstöbern",
  "home.statsTotal": "Gesamtmeldungen",
  "home.statsLost": "Verlorene Dinge",
  "home.statsFound": "Gefundene Dinge",
  "home.statsResolved": "Erfolgreich Zurückgegeben",
  "home.trustTitle": "Warum LINCO Einzigartig Ist",
  "home.trustSubtitle": "Entwickelt auf Basis von Zero-Knowledge-Datenschutz, verlässlichem Eigentumsnachweis und sicherer Übergabe.",
  "home.trustPrivacyTitle": "Geschützte Identität",
  "home.trustPrivacyDesc": "Ihre Rufnummer und privaten Daten erscheinen niemals im öffentlichen Feed.",
  "home.trustProofTitle": "Verlässlicher Eigentumsnachweis",
  "home.trustProofDesc": "Spezifische Kontrollfragen verhindern betrügerische Ansprüche im Vorfeld eines Treffens.",
  "home.trustRecoveryTitle": "Sicheres Rückgabenetzwerk",
  "home.trustRecoveryDesc": "Kommunizieren Sie über verschlüsselte Chats, gegenseitige Bestätigungen und geführte Übergaben.",
  "home.timelineShowcaseTitle": "KI-Tagesrouten-Rekonstruktion",
  "home.timelineShowcaseSubtitle": "Erinnern Sie sich an Ihre Tagesstationen, um Ort und Zeit des Verlusts genau einzugrenzen.",
  "home.timelineTryPrompt": "Beispiel ausprobieren:",
  "home.faqTitle": "Häufig Gestellte Fragen",
  "home.faqSubtitle": "Alles Wissenswerte über die Funktionsweise von LINCO.",
  "dashboard.title": "Bürger-Dashboard",
  "dashboard.subtitle": "Verwalten Sie Ihre aktiven Meldungen, Rückgaberäume und Sicherheitseinstellungen.",
  "dashboard.tabReports": "Meine Meldungen",
  "dashboard.tabClaims": "Meine Ansprüche",
  "dashboard.tabRecovery": "Rückgaberäume",
  "dashboard.tabSettings": "Einstellungen",
  "dashboard.noReports": "Sie haben bisher noch keine Meldungen erfasst.",
  "dashboard.noClaims": "Aktuell liegen keine Eigentumsansprüche vor.",
  "dashboard.noRecovery": "Keine aktiven Rückgaberäume vorhanden.",
  "dashboard.accountDetails": "Kontoinformationen",
  "dashboard.fullName": "Vollständiger Name",
  "dashboard.phoneNumber": "Telefonnummer",
  "dashboard.city": "Stadt",
  "dashboard.languagePreference": "Bevorzugte Sprache",
  "dashboard.changeLanguage": "Sprache Ändern",
  "dashboard.saveSettings": "Einstellungen Speichern",
  "dashboard.settingsSaved": "Einstellungen erfolgreich gespeichert.",
  "claim.modalTitle": "Eigentumsanspruch Erheben",
  "claim.modalSubtitle": "Weisen Sie nach, dass Sie der rechtmäßige Eigentümer sind, indem Sie die Kontrollfragen beantworten.",
  "claim.verifyIdentity": "Identitätsprüfung",
  "claim.questionsPrompt": "Bitte beantworten Sie die folgenden Fragen sorgfältig:",
  "claim.proofDetails": "Besondere Merkmale oder Nachweise",
  "claim.proofPlaceholder": "Beschreiben Sie verdeckte Details, Gebrauchsspuren oder Seriennummern...",
  "claim.submitClaim": "Anspruch Einreichen",
  "claim.statusPending": "Prüfung Ausstehend",
  "claim.statusApproved": "Anspruch Bestätigt",
  "claim.statusRejected": "Anspruch Abgelehnt",
  "claim.statusResolved": "Fall Abgeschlossen",
  "category.Electronics": "Elektronik",
  "category.Documents": "Dokumente & Karten",
  "category.Keys": "Schlüssel",
  "category.Pet": "Haustiere",
  "category.Jewelry": "Schmuck & Uhren",
  "category.Vehicle": "Fahrzeuge",
  "category.Clothing": "Kleidung & Taschen",
  "category.Other": "Sonstige Gegenstände",
  "urgency.Normal": "Normal",
  "urgency.Urgent": "Dringend",
  "urgency.Medical": "Medizinisch / Kritisch"
}

NL_269 = {
  "app.tagline": "AI Gevonden en Verloren Voorwerpen India",
  "app.subtitle": "Vind verloren spullen terug met privacy en geverifieerd vertrouwen.",
  "nav.home": "Home",
  "nav.report": "Melding Plaatsen",
  "nav.feed": "Community-Overzicht",
  "nav.matches": "AI-Matches",
  "nav.activity": "Activiteit",
  "nav.profile": "Profiel",
  "nav.about": "Over Ons",
  "nav.privacyTrust": "Privacy & Veiligheid",
  "nav.language": "Taal",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Terug",
  "common.next": "Volgende",
  "common.cancel": "Annuleren",
  "common.save": "Opslaan",
  "common.submit": "Verzenden",
  "common.edit": "Bewerken",
  "common.delete": "Verwijderen",
  "common.close": "Sluiten",
  "common.loading": "Laden...",
  "common.success": "Succes",
  "common.error": "Fout",
  "common.search": "Zoeken",
  "common.filter": "Filteren",
  "common.clear": "Wissen",
  "common.optional": "Optioneel",
  "common.required": "Verplicht",
  "common.viewAll": "Alles Bekijken",
  "common.details": "Details",
  "common.status": "Status",
  "lang.heading": "Kies uw taal",
  "lang.subheading": "Gebruik LINCO in de taal waarin u zich het prettigst voelt.",
  "lang.note": "U kunt uw taal op elk gewenst moment wijzigen via de Instellingen.",
  "lang.continue": "Doorgaan met LINCO",
  "lang.searchPlaceholder": "Zoek talen (bijv. Nederlands, English, Hindi)...",
  "lang.tabAll": "Alle Talen",
  "lang.tabIndian": "Indiase Talen (22)",
  "lang.tabInternational": "Internationale Talen",
  "lang.supportedBadge": "Volledig Ondersteund",
  "lang.previewBadge": "Voorvertoning / Bèta",
  "voice.button": "Spraakinvoer",
  "voice.listening": "Luisteren... Spreek op natuurlijke wijze in uw eigen taal",
  "voice.processing": "Spraakbericht verwerken...",
  "voice.transcribing": "Transcriberen...",
  "voice.reviewTitle": "Spraakmelding Controleren",
  "voice.reviewSubtitle": "Controleer de herkende gegevens voordat u ze toepast.",
  "voice.apply": "Gegevens Toepassen",
  "voice.retry": "Opnieuw Spreken",
  "voice.cancel": "Annuleren",
  "voice.notSupported": "Spraakherkenning wordt helaas niet ondersteund door deze browser.",
  "voice.permissionDenied": "Microfoontoegang geweigerd. Schakel dit in via de instellingen.",
  "notifications.centerTitle": "Activiteitencentrum",
  "notifications.centerSubtitle": "Realtime matches, claims en voortgang van teruggaven.",
  "notifications.readAll": "Alles als gelezen markeren",
  "notifications.unread": "Ongelezen",
  "notifications.emptyTitle": "Geen nieuwe meldingen",
  "notifications.emptySubtitle": "We laten het u weten zodra er nieuws is over uw meldingen.",
  "notifications.networkFooter": "LINCO Slim Notificatienetwerk",
  "notifications.listingAlert": "Nieuwe Melding Geplaatst",
  "notifications.matchFound": "Mogelijke Match Gevonden",
  "notifications.claimReceived": "Eigendomsclaim Ontvangen",
  "notifications.ownerApproved": "Bevestigd door Eigenaar",
  "notifications.finderVerified": "Geverifieerd door Vinder",
  "notifications.verificationComplete": "Wederzijdse Verificatie Voltooid",
  "notifications.newMessage": "Nieuw Veilig Bericht",
  "notifications.trustUpdate": "Vertrouwensniveau Bijgewerkt",
  "notifications.handoverUpdate": "Overdrachtstatus Bijgewerkt",
  "notifications.itemReceived": "Voorwerp Ontvangen",
  "notifications.itemReunited": "Succesvol Terugbezorgd",
  "notifications.actions.viewMatch": "Match Bekijken",
  "notifications.actions.reviewClaim": "Claim Beoordelen",
  "notifications.actions.viewVerification": "Verificatie Bekijken",
  "notifications.actions.openChat": "Chat Openen",
  "notifications.actions.confirmHandover": "Overdracht Bevestigen",
  "notifications.actions.viewCase": "Dossier Bekijken",
  "notifications.actions.viewDetails": "Details Bekijken",
  "notifications.actions.confirmTrust": "Vertrouwen Bevestigen",
  "notifications.matchFoundMsg": "We hebben een match met hoge betrouwbaarheid voor uw melding gevonden.",
  "notifications.claimReceivedMsg": "Iemand heeft een eigendomsclaim ingediend voor dit voorwerp.",
  "notifications.claimApprovedMsg": "Uw claim is geverifieerd en goedgekeurd door de tegenpartij.",
  "notifications.ownerApprovedMsg": "De eigenaar heeft bevestigd dat dit mogelijk het gezochte voorwerp is.",
  "notifications.finderVerifiedMsg": "De vinder heeft bevestigd dat uw claim overeenkomt met het gevonden voorwerp.",
  "notifications.bothApprovedMsg": "Beide partijen hebben de match bevestigd. De veilige chat is nu geopend.",
  "notifications.newMessageMsg": "U heeft een nieuw bericht ontvangen in de veilige chat.",
  "notifications.trustUpdateMsg": "Wederzijds vertrouwen bevestigd! WhatsApp-contactgegevens zijn ontgrendeld.",
  "notifications.handoverUpdateMsg": "Het veilige overdrachtsproces is gestart.",
  "notifications.itemReceivedMsg": "De ontvangst van het voorwerp is bevestigd.",
  "notifications.itemReunitedMsg": "Voorwerp succesvol herenigd! Het dossier is officieel gesloten.",
  "help.notSure": "Weet u niet wat u moet invullen?",
  "help.askLinco": "Vraag het LINCO",
  "help.listen": "Hulp Beluisteren",
  "help.stopListen": "Stoppen",
  "help.itemName": "Noem het voorwerp duidelijk (bijv. Leren portemonnee, iPhone 14).",
  "help.location": "Vermeld het dichtstbijzijnde station of herkenningspunt.",
  "help.time": "Geef een indicatie van het tijdstip en het deel van de dag.",
  "help.description": "Beschrijf kleuren, merk, materiaal en de inhoud.",
  "help.identifying": "Noem een verborgen detail dat alleen de echte eigenaar kent.",
  "help.timeline": "Reconstrueer uw stappen van vandaag om het zoekgebied te verkleinen.",
  "report.badge": "Slimme Melding",
  "report.titleLost": "Verloren Voorwerp Melden",
  "report.titleFound": "Gevonden Voorwerp Melden",
  "report.step1.title": "Basisgegevens",
  "report.step1.typeLost": "Ik Ben Iets Verloren",
  "report.step1.typeFound": "Ik Heb Iets Gevonden",
  "report.step1.itemName": "Naam van het Voorwerp",
  "report.step1.itemNamePlaceholder": "bijv. Zwarte leren Tommy Hilfiger portemonnee, iPhone 15 Pro",
  "report.step1.category": "Categorie",
  "report.step1.urgency": "Urgentieniveau",
  "report.step2.title": "Locatie",
  "report.step2.location": "Locatie of Herkenningspunt",
  "report.step2.locationPlaceholder": "bijv. Centraal Station Spoor 4, Universiteitsbibliotheek",
  "report.step2.useGps": "Huidige GPS-locatie Gebruiken",
  "report.step2.pinMap": "Plaatsen op Kaart",
  "report.step3.title": "Datum en Tijd",
  "report.step3.date": "Datum",
  "report.step3.time": "Geschatte Tijd",
  "report.step3.quickToday": "Vandaag",
  "report.step3.quickYesterday": "Gisteren",
  "report.step3.quickMorning": "Ochtend",
  "report.step3.quickAfternoon": "Middag",
  "report.step3.quickEvening": "Avond",
  "report.step3.quickNight": "Nacht",
  "report.step4.title": "Beschrijving & Kenmerken",
  "report.step4.desc": "Gedetailleerde Omschrijving",
  "report.step4.descPlaceholder": "Beschrijf kleur, merk, model en uiterlijke kenmerken...",
  "report.step4.aiEnhance": "Verbeteren met AI",
  "report.step4.timelineBuilder": "Route-Assistent",
  "report.step4.identifyingMarks": "Herkenningstekens (Vertrouwelijk)",
  "report.step4.identifyingPlaceholder": "bijv. Krasje op de hoek, NASA-sticker, 2 sleutels binnenin",
  "report.step4.photo": "Foto van het Voorwerp",
  "report.step5.title": "Contact & Privacy",
  "report.step5.contact": "Telefoonnummer / WhatsApp",
  "report.step5.contactPlaceholder": "10-cijferig telefoonnummer",
  "report.step5.contactNotice": "Uw telefoonnummer wordt nooit openbaar gedeeld in het overzicht.",
  "report.step6.title": "Vindvergoeding & Pincode",
  "report.step6.reward": "Aangeboden Vergoeding (Optioneel)",
  "report.step6.aiReward": "Door AI voorgestelde vergoeding",
  "report.step6.pin": "4-Cijferige Beveiligingspincode",
  "report.step6.pinNotice": "Bewaar deze pincode om de melding later te bewerken of af te sluiten.",
  "feed.title": "Community-Overzicht",
  "feed.subtitle": "Recente meldingen van verloren en gevonden voorwerpen in uw buurt.",
  "feed.all": "Alles",
  "feed.lost": "Verloren",
  "feed.found": "Gevonden",
  "feed.resolved": "Opgelost",
  "feed.listView": "Lijstweergave",
  "feed.mapView": "Kaartweergave",
  "feed.searchPlaceholder": "Zoeken op voorwerp, locatie of categorie...",
  "feed.noResults": "Geen meldingen gevonden voor deze zoekopdracht.",
  "feed.claimButton": "Dit Is van Mij",
  "feed.foundButton": "Ik Heb Dit Gevonden",
  "feed.viewMatches": "Matches Bekijken",
  "matches.title": "AI-Matchingscentrum",
  "matches.subtitle": "Geautomatiseerde semantische koppeling tussen verloren en gevonden zaken.",
  "matches.allMatches": "Alle Matches",
  "matches.mutualApprovals": "Wederzijdse Goedkeuringen",
  "matches.pendingVerification": "In Afwachting van Controle",
  "matches.resolved": "Afgehandeld",
  "matches.threshold": "Overeenkomstgrens",
  "matches.confidence": "Betrouwbaarheidsscore",
  "matches.score": "Score",
  "matches.reason": "Reden voor Match",
  "matches.lostReport": "Verliesmelding",
  "matches.foundReport": "Vondstmelding",
  "matches.openChat": "Veilige Chat Starten",
  "matches.verifyApprove": "Controleren & Goedkeuren",
  "matches.modalTitle": "Match-Details",
  "matches.notFoundTitle": "Geen matches gevonden",
  "matches.notFoundDesc": "Er zijn op dit moment geen matches voor de geselecteerde filters.",
  "matches.backToActivity": "Terug naar Activiteit",
  "chat.title": "Beveiligde Herenigingschat",
  "chat.trustButton": "Vertrouwen Bevestigen",
  "chat.whatsapp": "Doorgaan op WhatsApp",
  "chat.handover": "Veilige Overdracht Starten",
  "chat.received": "Ik Heb Mijn Spullen Ontvangen",
  "chat.resolved": "Zaak Afgesloten",
  "chat.placeholder": "Typ een beveiligd bericht...",
  "chat.send": "Verzenden",
  "chat.safetyWarning": "Veiligheidstip: Spreek altijd af op een drukke openbare locatie. Maak nooit vooraf geld over.",
  "enhance.modalTitle": "Tekstverbetering met AI",
  "enhance.aiBadge": "Door AI Gegenereerd",
  "enhance.original": "Oorspronkelijke Omschrijving",
  "enhance.enhanced": "Verbeterde Omschrijving",
  "enhance.structuredHeading": "Gestructureerde Eigenschappen",
  "enhance.accept": "Wijzigingen Toepassen",
  "enhance.edit": "Bewerken",
  "enhance.tryAgain": "Opnieuw Genereren",
  "enhance.keepOriginal": "Origineel Behouden",
  "enhance.suggestions": "Suggesties",
  "timeline.title": "AI-Tijdlijnreconstructie",
  "timeline.subtitle": "Reconstrueer uw route om het precieze tijdstip en de locatie te achterhalen.",
  "timeline.userProvided": "Ingevuld door Gebruiker",
  "timeline.aiInferred": "Afgeleid door AI",
  "timeline.unknown": "Onbekend",
  "timeline.likelyLocation": "Meest Waarschijnlijke Gebied",
  "timeline.timeWindow": "Tijdsvenster",
  "timeline.reasoning": "AI-Redenering",
  "timeline.applyLocation": "Deze Locatie Gebruiken",
  "timeline.editEvent": "Stap Bewerken",
  "timeline.addEvent": "Stap Toevoegen",
  "home.heroTag": "Zoeken • Verifiëren • Herenigen",
  "home.heroTitle1": "Uw identiteit blijft beschermd.",
  "home.heroTitle2": "Uw eigendommen keren terug.",
  "home.heroSubtitle1": "Verlies nooit meer wat van u is.",
  "home.heroSubtitle2": "Gedreven door de gemeenschap. Beveiligd met AI.",
  "home.heroDesc": "Plaats binnen een minuut een melding. Uw privacy blijft gewaarborgd totdat het eigendom wederzijds is geverifieerd.",
  "home.reportLost": "Verloren Voorwerp Melden",
  "home.reportFound": "Gevonden Voorwerp Melden",
  "home.findItem": "Voorwerpen Zoeken",
  "home.viewMatches": "AI-Matches Bekijken",
  "home.startReport": "Start een Melding",
  "home.browseFeed": "Bekijk het Overzicht",
  "home.statsTotal": "Totaal Aantal Meldingen",
  "home.statsLost": "Verloren Voorwerpen",
  "home.statsFound": "Gevonden Voorwerpen",
  "home.statsResolved": "Herenigde Voorwerpen",
  "home.trustTitle": "Waarom LINCO Uniek Is",
  "home.trustSubtitle": "Gebouwd op zero-knowledge privacy, betrouwbaar eigendomsbewijs en veilige teruggave.",
  "home.trustPrivacyTitle": "Beschermde Identiteit",
  "home.trustPrivacyDesc": "Uw contactgegevens worden nooit getoond in het openbare overzicht.",
  "home.trustProofTitle": "Sluitend Eigendomsbewijs",
  "home.trustProofDesc": "Door AI gegenereerde controleantwoorden voorkomen valse claims voordat u elkaar ontmoet.",
  "home.trustRecoveryTitle": "Veilig Herenigingsnetwerk",
  "home.trustRecoveryDesc": "Regel de teruggave via versleutelde chat, wederzijdse goedkeuring en begeleide overdracht.",
  "home.timelineShowcaseTitle": "AI-Routereconstructie",
  "home.timelineShowcaseSubtitle": "Denk terug aan uw dagelijkse tussenstops om locatie en tijd van het verlies vast te stellen.",
  "home.timelineTryPrompt": "Probeer een voorbeeld:",
  "home.faqTitle": "Veelgestelde Vragen",
  "home.faqSubtitle": "Alles wat u moet weten over het gebruik van LINCO.",
  "dashboard.title": "Burgerdashboard",
  "dashboard.subtitle": "Beheer uw actieve meldingen, teruggavekamers en beveiligingsinstellingen.",
  "dashboard.tabReports": "Mijn Meldingen",
  "dashboard.tabClaims": "Mijn Claims",
  "dashboard.tabRecovery": "Teruggavekamers",
  "dashboard.tabSettings": "Instellingen",
  "dashboard.noReports": "U heeft nog geen meldingen geplaatst.",
  "dashboard.noClaims": "Geen actieve claims op dit moment.",
  "dashboard.noRecovery": "Geen actieve teruggavekamers aanwezig.",
  "dashboard.accountDetails": "Accountgegevens",
  "dashboard.fullName": "Volledige Naam",
  "dashboard.phoneNumber": "Telefoonnummer",
  "dashboard.city": "Woonplaats",
  "dashboard.languagePreference": "Voorkeurstaal",
  "dashboard.changeLanguage": "Taal Wijzigen",
  "dashboard.saveSettings": "Instellingen Opslaan",
  "dashboard.settingsSaved": "Instellingen succesvol opgeslagen.",
  "claim.modalTitle": "Eigendom van dit Voorwerp Claimen",
  "claim.modalSubtitle": "Toon aan dat u de rechtmatige eigenaar bent door de controleantwoorden in te vullen.",
  "claim.verifyIdentity": "Identiteitsverificatie",
  "claim.questionsPrompt": "Beantwoord alstublieft de volgende vragen over het voorwerp:",
  "claim.proofDetails": "Specifieke Kenmerken of Aankoopbewijs",
  "claim.proofPlaceholder": "Beschrijf specifieke krasjes, verborgen inhoud of serienummers...",
  "claim.submitClaim": "Claim Indienen",
  "claim.statusPending": "In Beoordeling",
  "claim.statusApproved": "Claim Goedgekeurd",
  "claim.statusRejected": "Claim Afgewezen",
  "claim.statusResolved": "Dossier Afgesloten",
  "category.Electronics": "Elektronica",
  "category.Documents": "Documenten & Pasjes",
  "category.Keys": "Sleutels",
  "category.Pet": "Huisdieren",
  "category.Jewelry": "Sieraden & Horloges",
  "category.Vehicle": "Voertuigen",
  "category.Clothing": "Kleding & Tassen",
  "category.Other": "Overige Voorwerpen",
  "urgency.Normal": "Normaal",
  "urgency.Urgent": "Urgent",
  "urgency.Medical": "Medisch / Kritiek"
}
