# -*- coding: utf-8 -*-
"""Authentic Arabic (AR), Russian (RU), and Turkish (TR) translations for all 269 UI keys."""

AR_269 = {
  "app.tagline": "المفقودات والموجودات بالذكاء الاصطناعي في الهند",
  "app.subtitle": "استعادة الممتلكات المفقودة بخصوصية تامة وموثوقية مؤكدة.",
  "nav.home": "الرئيسية",
  "nav.report": "نشر بلاغ",
  "nav.feed": "سجل المجتمع",
  "nav.matches": "تطابقات الذكاء الاصطناعي",
  "nav.activity": "النشاط",
  "nav.profile": "الملف الشخصي",
  "nav.about": "من نحن",
  "nav.privacyTrust": "الخصوصية والأمان",
  "nav.language": "اللغة",
  "nav.saathii": "لينكو ساثي",
  "common.back": "رجوع",
  "common.next": "التالي",
  "common.cancel": "إلغاء",
  "common.save": "حفظ",
  "common.submit": "إرسال",
  "common.edit": "تعديل",
  "common.delete": "حذف",
  "common.close": "إغلاق",
  "common.loading": "جارٍ التحميل...",
  "common.success": "تم بنجاح",
  "common.error": "خطأ",
  "common.search": "بحث",
  "common.filter": "تصفية",
  "common.clear": "مسح",
  "common.optional": "اختياري",
  "common.required": "مطلوب",
  "common.viewAll": "عرض الكل",
  "common.details": "التفاصيل",
  "common.status": "الحالة",
  "lang.heading": "اختر لغتك",
  "lang.subheading": "استخدم لينكو باللغة التي تفضلها وتشعر بالراحة معها.",
  "lang.note": "يمكنك تغيير اللغة في أي وقت من الإعدادات.",
  "lang.continue": "المتابعة مع لينكو",
  "lang.searchPlaceholder": "ابحث عن اللغات (مثل العربية، English، Hindi)...",
  "lang.tabAll": "جميع اللغات",
  "lang.tabIndian": "اللغات الهندية (22)",
  "lang.tabInternational": "اللغات الدولية",
  "lang.supportedBadge": "مدعوم بالكامل",
  "lang.previewBadge": "معاينة / تجريبي",
  "voice.button": "الإدخال الصوتي",
  "voice.listening": "جارٍ الاستماع... تحدث بوضوح بلغتك الطبيعية",
  "voice.processing": "جارٍ معالجة التسجيل الصوتي...",
  "voice.transcribing": "جارٍ تحويل الصوت إلى نص...",
  "voice.reviewTitle": "مراجعة البلاغ الصوتي",
  "voice.reviewSubtitle": "تحقق من التفاصيل المكتشفة قبل تطبيقها.",
  "voice.apply": "تطبيق التفاصيل",
  "voice.retry": "إعادة المحاولة",
  "voice.cancel": "إلغاء",
  "voice.notSupported": "متصفحك لا يدعم خاصية التعرف على الصوت.",
  "voice.permissionDenied": "تم رفض إذن الميكروفون. يرجى تفعيله في الإعدادات.",
  "notifications.centerTitle": "مركز الإشعارات والأنشطة",
  "notifications.centerSubtitle": "التطابقات اللحظية والمطالبات ومتابعة الاسترداد.",
  "notifications.readAll": "تحديد الكل كمقروء",
  "notifications.unread": "غير مقروءة",
  "notifications.emptyTitle": "لا توجد إشعارات بعد",
  "notifications.emptySubtitle": "سنخطرك فور حدوث أي تفاعل مع بلاغاتك.",
  "notifications.networkFooter": "شبكة لينكو الذكية للإشعارات",
  "notifications.listingAlert": "تنبيه ببلاغ جديد",
  "notifications.matchFound": "تم العثور على تطابق محتمل",
  "notifications.claimReceived": "تم استلام مطالبة ملكية",
  "notifications.ownerApproved": "تأكيد من المالك",
  "notifications.finderVerified": "تحقق من قبل من عثر على الغرض",
  "notifications.verificationComplete": "اكتمل التحقق المتبادل",
  "notifications.newMessage": "رسالة آمنة جديدة",
  "notifications.trustUpdate": "تحديث مستوى الثقة",
  "notifications.handoverUpdate": "تحديث حالة التسليم",
  "notifications.itemReceived": "تم استلام الغرض",
  "notifications.itemReunited": "تمت استعادة الغرض بنجاح",
  "notifications.actions.viewMatch": "عرض التطابق",
  "notifications.actions.reviewClaim": "مراجعة المطالبة",
  "notifications.actions.viewVerification": "عرض التحقق",
  "notifications.actions.openChat": "فتح المحادثة",
  "notifications.actions.confirmHandover": "تأكيد التسليم",
  "notifications.actions.viewCase": "عرض الحالة",
  "notifications.actions.viewDetails": "عرض التفاصيل",
  "notifications.actions.confirmTrust": "تأكيد الثقة",
  "notifications.matchFoundMsg": "عثرنا على تطابق عالي الدقة لبلاغك.",
  "notifications.claimReceivedMsg": "قدم شخص ما مطالبة ملكية لهذا الغرض.",
  "notifications.claimApprovedMsg": "تم التحقق من مطالبتك والموافقة عليها من الطرف الآخر.",
  "notifications.ownerApprovedMsg": "أكد المالك أن هذا قد يكون غرضه المفقود.",
  "notifications.finderVerifiedMsg": "أكد من عثر على الغرض أن إجاباتك تطابق مواصفات المعثور عليه.",
  "notifications.bothApprovedMsg": "أكد الطرفان صحة التطابق. المحادثة الآمنة متاحة الآن.",
  "notifications.newMessageMsg": "وصلتك رسالة جديدة في المحادثة الآمنة.",
  "notifications.trustUpdateMsg": "تم تأكيد الثقة المتبادلة! أصبحت بيانات واتساب متاحة الآن.",
  "notifications.handoverUpdateMsg": "بدأت إجراءات التسليم الآمن.",
  "notifications.itemReceivedMsg": "تم تأكيد استلام الغرض بنجاح.",
  "notifications.itemReunitedMsg": "تمت استعادة الغرض بنجاح! تم إغلاق الحالة رسمياً.",
  "help.notSure": "لست متأكداً مما تكتبه؟",
  "help.askLinco": "اسأل لينكو",
  "help.listen": "استماع للمساعدة",
  "help.stopListen": "إيقاف",
  "help.itemName": "اكتب الاسم الشائع للغرض (مثل محفظة جلدية، هاتف آيفون).",
  "help.location": "اذكر أقرب محطة أو معلم معروف.",
  "help.time": "حدد الوقت التقريبي وفترة اليوم.",
  "help.description": "صف اللون، العلامة التجارية، المحتويات الداخلية.",
  "help.identifying": "اذكر علامة سرية يعرفها المالك الحقيقي فقط.",
  "help.timeline": "أعد ترتيب خطوات يومك لتحديد مكان الفقدان بدقة.",
  "report.badge": "بلاغ ذكي",
  "report.titleLost": "الإبلاغ عن غرض مفقود",
  "report.titleFound": "الإبلاغ عن غرض معثور عليه",
  "report.step1.title": "المعلومات الأساسية",
  "report.step1.typeLost": "فقدت شيئاً",
  "report.step1.typeFound": "عثرت على شيء",
  "report.step1.itemName": "اسم الغرض",
  "report.step1.itemNamePlaceholder": "مثال: محفظة جلدية سوداء تومي هيلفيغر، آيفون 15 برو",
  "report.step1.category": "الفئة",
  "report.step1.urgency": "درجة الأهمية",
  "report.step2.title": "الموقع",
  "report.step2.location": "الموقع أو المعلم القريب",
  "report.step2.locationPlaceholder": "مثال: محطة القطار المركزية، بوابة 2، كافتيريا الكلية",
  "report.step2.useGps": "استخدام موقع GPS الحالي",
  "report.step2.pinMap": "تحديد على الخريطة",
  "report.step3.title": "التاريخ والوقت",
  "report.step3.date": "التاريخ",
  "report.step3.time": "الوقت التقريبي",
  "report.step3.quickToday": "اليوم",
  "report.step3.quickYesterday": "أمس",
  "report.step3.quickMorning": "صباحاً",
  "report.step3.quickAfternoon": "ظهراً",
  "report.step3.quickEvening": "مساءً",
  "report.step3.quickNight": "ليلاً",
  "report.step4.title": "الوصف والعلامات المميزة",
  "report.step4.desc": "وصف تفصيلي",
  "report.step4.descPlaceholder": "صف الألوان، الطراز، الحالة العامة...",
  "report.step4.aiEnhance": "تحسين الوصف بالذكاء الاصطناعي",
  "report.step4.timelineBuilder": "مساعد خط السير",
  "report.step4.identifyingMarks": "علامات سرية مميزة (خاصة)",
  "report.step4.identifyingPlaceholder": "مثال: خدش في الزاوية، ملصق وكالة ناسا، مفتاحان في الداخل",
  "report.step4.photo": "صورة الغرض",
  "report.step5.title": "الاتصال والخصوصية",
  "report.step5.contact": "رقم الهاتف / واتساب",
  "report.step5.contactPlaceholder": "رقم هاتف مكون من 10 أرقام",
  "report.step5.contactNotice": "لن يتم عرض رقم هاتفك أبداً في السجل العام.",
  "report.step6.title": "المكافأة ورمز الأمان",
  "report.step6.reward": "المكافأة المعروضة (اختياري)",
  "report.step6.aiReward": "مكافأة مقترحة بواسطة الذكاء الاصطناعي",
  "report.step6.pin": "رمز أمان PIN مكون من 4 أرقام",
  "report.step6.pinNotice": "احفظ هذا الرمز لتعديل البلاغ أو إغلاقه لاحقاً.",
  "feed.title": "سجل المجتمع",
  "feed.subtitle": "أحدث البلاغات عن المفقودات والمعثورات في منطقتك.",
  "feed.all": "الكل",
  "feed.lost": "مفقود",
  "feed.found": "معثور عليه",
  "feed.resolved": "تمت استعادته",
  "feed.listView": "عرض القائمة",
  "feed.mapView": "عرض الخريطة",
  "feed.searchPlaceholder": "ابحث بالاسم، الفئة أو المنطقة...",
  "feed.noResults": "لم يتم العثور على بلاغات مطابقة لمعايير البحث.",
  "feed.claimButton": "هذا ملكي",
  "feed.foundButton": "أنا عثرت عليه",
  "feed.viewMatches": "عرض التطابقات",
  "matches.title": "تطابقات الذكاء الاصطناعي",
  "matches.subtitle": "مطابقة دلالية ذكية بين المفقودات والمعثورات.",
  "matches.allMatches": "جميع التطابقات",
  "matches.mutualApprovals": "الموافقات المتبادلة",
  "matches.pendingVerification": "بانتظار التحقق",
  "matches.resolved": "المكتملة",
  "matches.threshold": "حد المطابقة",
  "matches.confidence": "نسبة الثقة",
  "matches.score": "النتيجة",
  "matches.reason": "سبب التطابق",
  "matches.lostReport": "بلاغ الفقدان",
  "matches.foundReport": "بلاغ العثور",
  "matches.openChat": "بدء محادثة آمنة",
  "matches.verifyApprove": "تحقق وموافقة",
  "matches.modalTitle": "تفاصيل التطابق",
  "matches.notFoundTitle": "لا توجد تطابقات",
  "matches.notFoundDesc": "لا تتوفر تطابقات مطابقة للتصفيات الحالية.",
  "matches.backToActivity": "العودة إلى النشاط",
  "chat.title": "المحادثة الآمنة للاسترداد",
  "chat.trustButton": "تأكيد الثقة",
  "chat.whatsapp": "المتابعة عبر واتساب",
  "chat.handover": "بدء التسليم الآمن",
  "chat.received": "استلمت غرضي",
  "chat.resolved": "تم إنهاء الحالة",
  "chat.placeholder": "اكتب رسالة آمنة...",
  "chat.send": "إرسال",
  "chat.safetyWarning": "نصيحة أمان: احرص دائماً على الالتقاء في أماكن عامة مزدحمة. لا تحول أموالاً مسبقاً أبداً.",
  "enhance.modalTitle": "تحسين النص بالذكاء الاصطناعي",
  "enhance.aiBadge": "مُنشأ بالذكاء الاصطناعي",
  "enhance.original": "الوصف الأصلي",
  "enhance.enhanced": "الوصف المحسن",
  "enhance.structuredHeading": "المواصفات المستخرجة",
  "enhance.accept": "قبول وتطبيق التعديل",
  "enhance.edit": "تعديل",
  "enhance.tryAgain": "إعادة المحاولة",
  "enhance.keepOriginal": "الإبقاء على النص الأصلي",
  "enhance.suggestions": "الاقتراحات",
  "timeline.title": "إعادة بناء خط السير بالذكاء الاصطناعي",
  "timeline.subtitle": "تتبع خطواتك خلال اليوم لتحديد الزمان والمكان بدقة.",
  "timeline.userProvided": "بيانات من المستخدم",
  "timeline.aiInferred": "استنتاج الذكاء الاصطناعي",
  "timeline.unknown": "غير محدد",
  "timeline.likelyLocation": "الموقع الأكثر ترجيحاً",
  "timeline.timeWindow": "النطاق الزمني",
  "timeline.reasoning": "تحليل الذكاء الاصطناعي",
  "timeline.applyLocation": "استخدام هذا الموقع",
  "timeline.editEvent": "تعديل النقطة",
  "timeline.addEvent": "إضافة نقطة",
  "home.heroTag": "ابحث • تحقق • استعد",
  "home.heroTitle1": "هويتك تظل محمية.",
  "home.heroTitle2": "ممتلكاتك تعود إليك.",
  "home.heroSubtitle1": "لا تفقد أبداً ما هو حقك.",
  "home.heroSubtitle2": "بدعم من المجتمع. ومحمي بالذكاء الاصطناعي.",
  "home.heroDesc": "أبلغ عن المفقودات والمعثورات في أقل من دقيقة. خصوصيتك مصونة بالكامل حتى إثبات الملكية المتبادل.",
  "home.reportLost": "الإبلاغ عن مفقود",
  "home.reportFound": "الإبلاغ عن معثور عليه",
  "home.findItem": "البحث عن أغراض",
  "home.viewMatches": "عرض تطابقات الذكاء الاصطناعي",
  "home.startReport": "ابدأ كتابة بلاغ",
  "home.browseFeed": "تصفح سجل المجتمع",
  "home.statsTotal": "إجمالي البلاغات",
  "home.statsLost": "أغراض مفقودة",
  "home.statsFound": "أغراض معثور عليها",
  "home.statsResolved": "أغراض تمت استعادتها",
  "home.trustTitle": "لماذا لينكو مختلف تماماً؟",
  "home.trustSubtitle": "مبني على الخصوصية الصفرية وإثبات الملكية الصارم والتسليم الآمن.",
  "home.trustPrivacyTitle": "هوية محمية",
  "home.trustPrivacyDesc": "رقم هاتفك وبياناتك الشخصية لا تظهر أبداً في السجل العام.",
  "home.trustProofTitle": "إثبات ملكية موثوق",
  "home.trustProofDesc": "أسئلة سرية يولدها الذكاء الاصطناعي تمنع المطالبات الكاذبة قبل أي لقاء.",
  "home.trustRecoveryTitle": "شبكة استرداد آمنة",
  "home.trustRecoveryDesc": "نسق استعادة أشيائك عبر محادثات مشفرة وموافقات متبادلة وتسليم موجه.",
  "home.timelineShowcaseTitle": "إعادة بناء خط السير بالذكاء الاصطناعي",
  "home.timelineShowcaseSubtitle": "تذكر محطات يومك لتحديد مكان ووقت فقدان الغرض بدقة بالغة.",
  "home.timelineTryPrompt": "جرب مثالاً:",
  "home.faqTitle": "الأسئلة الشائعة",
  "home.faqSubtitle": "كل ما تحتاج لمعرفته حول آلية عمل لينكو وكيف يساعدك.",
  "dashboard.title": "لوحة المواطن",
  "dashboard.subtitle": "إدارة بلاغاتك النشطة وغرف الاسترداد وتفضيلات الأمان الخاصة بك.",
  "dashboard.tabReports": "بلاغاتي",
  "dashboard.tabClaims": "مطالباتي",
  "dashboard.tabRecovery": "غرف الاسترداد",
  "dashboard.tabSettings": "الإعدادات",
  "dashboard.noReports": "لم تنشر أي بلاغات بعد.",
  "dashboard.noClaims": "لا توجد مطالبات نشطة لديك حالياً.",
  "dashboard.noRecovery": "لا توجد غرف استرداد نشطة حالياً.",
  "dashboard.accountDetails": "بيانات الحساب",
  "dashboard.fullName": "الاسم الكامل",
  "dashboard.phoneNumber": "رقم الهاتف",
  "dashboard.city": "المدينة",
  "dashboard.languagePreference": "اللغة المفضلة",
  "dashboard.changeLanguage": "تغيير اللغة",
  "dashboard.saveSettings": "حفظ الإعدادات",
  "dashboard.settingsSaved": "تم حفظ الإعدادات بنجاح.",
  "claim.modalTitle": "مطالبة ملكية لهذا الغرض",
  "claim.modalSubtitle": "أثبت أنك المالك الشرعي بالإجابة على أسئلة التحقق.",
  "claim.verifyIdentity": "التحقق من الهوية والملكية",
  "claim.questionsPrompt": "يرجى الإجابة بدقة على الأسئلة التالية:",
  "claim.proofDetails": "علامات سرية أو إثباتات خاصة",
  "claim.proofPlaceholder": "صف محتويات خفية، خدوشاً محددة، أو أرقاماً تسلسلية...",
  "claim.submitClaim": "إرسال المطالبة",
  "claim.statusPending": "قيد المراجعة والتحقق",
  "claim.statusApproved": "تمت الموافقة على المطالبة",
  "claim.statusRejected": "تم رفض المطالبة",
  "claim.statusResolved": "تمت تسوية الحالة بنجاح",
  "category.Electronics": "إلكترونيات",
  "category.Documents": "مستندات وبطاقات",
  "category.Keys": "مفاتيح",
  "category.Pet": "حيوانات أليفة",
  "category.Jewelry": "مجوهرات وساعات",
  "category.Vehicle": "مركبات",
  "category.Clothing": "ملابس وحقائب",
  "category.Other": "أغراض أخرى",
  "urgency.Normal": "عادي",
  "urgency.Urgent": "عاجل",
  "urgency.Medical": "طبي / بالغ الأهمية"
}

RU_269 = {
  "app.tagline": "ИИ Бюро Находок Индия",
  "app.subtitle": "Возврат потерянных вещей с соблюдением конфиденциальности и надежной проверкой.",
  "nav.home": "Главная",
  "nav.report": "Опубликовать",
  "nav.feed": "Лента Сообщества",
  "nav.matches": "ИИ-Совпадения",
  "nav.activity": "Активность",
  "nav.profile": "Профиль",
  "nav.about": "О Нас",
  "nav.privacyTrust": "Безопасность и Доверие",
  "nav.language": "Язык",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Назад",
  "common.next": "Далее",
  "common.cancel": "Отмена",
  "common.save": "Сохранить",
  "common.submit": "Отправить",
  "common.edit": "Редактировать",
  "common.delete": "Удалить",
  "common.close": "Закрыть",
  "common.loading": "Загрузка...",
  "common.success": "Успешно",
  "common.error": "Ошибка",
  "common.search": "Поиск",
  "common.filter": "Фильтр",
  "common.clear": "Очистить",
  "common.optional": "Необязательно",
  "common.required": "Обязательно",
  "common.viewAll": "Смотреть Все",
  "common.details": "Подробности",
  "common.status": "Статус",
  "lang.heading": "Выберите язык",
  "lang.subheading": "Используйте LINCO на том языке, на котором вам удобнее всего общаться.",
  "lang.note": "Вы можете изменить язык в любое время в Настройках.",
  "lang.continue": "Продолжить с LINCO",
  "lang.searchPlaceholder": "Поиск языков (напр., Русский, English, Hindi)...",
  "lang.tabAll": "Все Языки",
  "lang.tabIndian": "Языки Индии (22)",
  "lang.tabInternational": "Международные Языки",
  "lang.supportedBadge": "Полная Поддержка",
  "lang.previewBadge": "Предпросмотр / Бета",
  "voice.button": "Голосовой Ввод",
  "voice.listening": "Слушаю... Говорите естественно на своем языке",
  "voice.processing": "Обработка голосовой записи...",
  "voice.transcribing": "Преобразование в текст...",
  "voice.reviewTitle": "Проверка Голосового Заявления",
  "voice.reviewSubtitle": "Проверьте распознанные данные перед их сохранением.",
  "voice.apply": "Применить Данные",
  "voice.retry": "Повторить",
  "voice.cancel": "Отмена",
  "voice.notSupported": "Распознавание речи не поддерживается в данном браузере.",
  "voice.permissionDenied": "Доступ к микрофону отклонен. Пожалуйста, включите его в настройках.",
  "notifications.centerTitle": "Центр Уведомлений",
  "notifications.centerSubtitle": "Совпадения в реальном времени, заявки на возврат и статус дел.",
  "notifications.readAll": "Отметить все как прочитанные",
  "notifications.unread": "Непрочитанные",
  "notifications.emptyTitle": "Пока нет уведомлений",
  "notifications.emptySubtitle": "Мы оповестим вас, как только появятся новости о ваших объявлениях.",
  "notifications.networkFooter": "Интеллектуальная Сеть Оповещений LINCO",
  "notifications.listingAlert": "Новое Объявление в Ленте",
  "notifications.matchFound": "Найдено Возможное Совпадение",
  "notifications.claimReceived": "Поступила Заявка на Возврат",
  "notifications.ownerApproved": "Подтверждено Владельцем",
  "notifications.finderVerified": "Проверено Нашедшим",
  "notifications.verificationComplete": "Взаимная Проверка Завершена",
  "notifications.newMessage": "Новое Защищенное Сообщение",
  "notifications.trustUpdate": "Уровень Доверия Обновлен",
  "notifications.handoverUpdate": "Статус Передачи Обновлен",
  "notifications.itemReceived": "Предмет Получен",
  "notifications.itemReunited": "Успешный Возврат Завершен",
  "notifications.actions.viewMatch": "Посмотреть Совпадение",
  "notifications.actions.reviewClaim": "Рассмотреть Заявку",
  "notifications.actions.viewVerification": "Посмотреть Проверку",
  "notifications.actions.openChat": "Открыть Чат",
  "notifications.actions.confirmHandover": "Подтвердить Передачу",
  "notifications.actions.viewCase": "Открыть Дело",
  "notifications.actions.viewDetails": "Подробнее",
  "notifications.actions.confirmTrust": "Подтвердить Доверие",
  "notifications.matchFoundMsg": "Мы нашли очень точное совпадение для вашего объявления.",
  "notifications.claimReceivedMsg": "Кто-то подал заявку на право владения этой вещью.",
  "notifications.claimApprovedMsg": "Ваша заявка проверена и одобрена второй стороной.",
  "notifications.ownerApprovedMsg": "Владелец подтвердил, что это может быть его вещь.",
  "notifications.finderVerifiedMsg": "Нашедший подтвердил, что ваши ответы соответствуют найденной вещи.",
  "notifications.bothApprovedMsg": "Обе стороны подтвердили совпадение. Защищенный чат теперь доступен.",
  "notifications.newMessageMsg": "Вам пришло новое сообщение в защищенном чате.",
  "notifications.trustUpdateMsg": "Взаимное доверие подтверждено! Контактные данные WhatsApp разблокированы.",
  "notifications.handoverUpdateMsg": "Начался процесс безопасной передачи вещи.",
  "notifications.itemReceivedMsg": "Получение предмета успешно подтверждено.",
  "notifications.itemReunitedMsg": "Вещь успешно возвращена законному владельцу! Дело закрыто.",
  "help.notSure": "Не знаете, что написать?",
  "help.askLinco": "Спросить LINCO",
  "help.listen": "Прослушать Подсказку",
  "help.stopListen": "Стоп",
  "help.itemName": "Укажите простое название вещи (напр., Кожаный кошелек, iPhone 14).",
  "help.location": "Укажите ближайшую станцию метро или ориентир.",
  "help.time": "Укажите примерное время и период суток.",
  "help.description": "Опишите цвет, материал, бренд и содержимое.",
  "help.identifying": "Назовите скрытую примету, известную только истинному хозяину.",
  "help.timeline": "Восстановите маршрут шаг за шагом, чтобы сузить зону поиска.",
  "report.badge": "Умная Заявка",
  "report.titleLost": "Заявить о Потере Вещи",
  "report.titleFound": "Заявить о Находке",
  "report.step1.title": "Основная Информация",
  "report.step1.typeLost": "Я Потерял Вещь",
  "report.step1.typeFound": "Я Нашел Вещь",
  "report.step1.itemName": "Название Предмета",
  "report.step1.itemNamePlaceholder": "напр., Черный кожаный кошелек Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "Категория",
  "report.step1.urgency": "Срочность",
  "report.step2.title": "Местоположение",
  "report.step2.location": "Место или Ориентир",
  "report.step2.locationPlaceholder": "напр., Главный вокзал, выход 2, кафетерий",
  "report.step2.useGps": "Использовать Текущий GPS",
  "report.step2.pinMap": "Отметить на Карте",
  "report.step3.title": "Дата и Время",
  "report.step3.date": "Дата",
  "report.step3.time": "Примерное Время",
  "report.step3.quickToday": "Сегодня",
  "report.step3.quickYesterday": "Вчера",
  "report.step3.quickMorning": "Утром",
  "report.step3.quickAfternoon": "Днем",
  "report.step3.quickEvening": "Вечером",
  "report.step3.quickNight": "Ночью",
  "report.step4.title": "Описание и Приметы",
  "report.step4.desc": "Подробное Описание",
  "report.step4.descPlaceholder": "Опишите цвет, бренд, модель и внешнее состояние...",
  "report.step4.aiEnhance": "Улучшить с Помощью ИИ",
  "report.step4.timelineBuilder": "Помощник Маршрута",
  "report.step4.identifyingMarks": "Особые Приметы (Конфиденциально)",
  "report.step4.identifyingPlaceholder": "напр., Царапина в углу, наклейка NASA, 2 ключа внутри",
  "report.step4.photo": "Фотография Вещи",
  "report.step5.title": "Контакты и Приватность",
  "report.step5.contact": "Номер Телефона / WhatsApp",
  "report.step5.contactPlaceholder": "10-значный номер телефона",
  "report.step5.contactNotice": "Ваш номер никогда не будет показан в открытом доступе.",
  "report.step6.title": "Вознаграждение и PIN-код",
  "report.step6.reward": "Вознаграждение (Необязательно)",
  "report.step6.aiReward": "Рекомендованное ИИ вознаграждение",
  "report.step6.pin": "4-значный Защитный PIN-код",
  "report.step6.pinNotice": "Сохраните этот PIN для редактирования или закрытия заявки в будущем.",
  "feed.title": "Лента Сообщества",
  "feed.subtitle": "Свежие объявления о потерянных и найденных вещах в вашем районе.",
  "feed.all": "Все",
  "feed.lost": "Потерянные",
  "feed.found": "Найденные",
  "feed.resolved": "Возвращенные",
  "feed.listView": "Списком",
  "feed.mapView": "На Карте",
  "feed.searchPlaceholder": "Поиск по вещи, месту или категории...",
  "feed.noResults": "Объявлений по заданным критериям не найдено.",
  "feed.claimButton": "Это Мое",
  "feed.foundButton": "Я Нашел Это",
  "feed.viewMatches": "Посмотреть Совпадения",
  "matches.title": "ИИ-Центр Сопоставления",
  "matches.subtitle": "Автоматическое семантическое сравнение объявлений о потерях и находках.",
  "matches.allMatches": "Все Совпадения",
  "matches.mutualApprovals": "Взаимные Подтверждения",
  "matches.pendingVerification": "Ожидают Проверки",
  "matches.resolved": "Завершенные",
  "matches.threshold": "Порог Сходства",
  "matches.confidence": "Уровень Уверенности",
  "matches.score": "Балл",
  "matches.reason": "Причина Совпадения",
  "matches.lostReport": "Объявление о Потере",
  "matches.foundReport": "Объявление о Находке",
  "matches.openChat": "Открыть Защищенный Чат",
  "matches.verifyApprove": "Проверить и Одобрить",
  "matches.modalTitle": "Детали Совпадения",
  "matches.notFoundTitle": "Совпадений не найдено",
  "matches.notFoundDesc": "Для выбранных фильтров пока нет подходящих результатов.",
  "matches.backToActivity": "Вернуться к Активности",
  "chat.title": "Защищенный Чат Возврата",
  "chat.trustButton": "Подтвердить Доверие",
  "chat.whatsapp": "Перейти в WhatsApp",
  "chat.handover": "Начать Безопасную Передачу",
  "chat.received": "Я Получил Свою Вещь",
  "chat.resolved": "Дело Завершено",
  "chat.placeholder": "Напишите защищенное сообщение...",
  "chat.send": "Отправить",
  "chat.safetyWarning": "Совет по безопасности: Встречайтесь в людных общественных местах. Никогда не переводите деньги заранее.",
  "enhance.modalTitle": "Улучшение Текста с ИИ",
  "enhance.aiBadge": "Сгенерировано ИИ",
  "enhance.original": "Исходное Описание",
  "enhance.enhanced": "Улучшенное Описание",
  "enhance.structuredHeading": "Выделенные Параметры",
  "enhance.accept": "Применить Изменения",
  "enhance.edit": "Изменить",
  "enhance.tryAgain": "Сгенерировать Заново",
  "enhance.keepOriginal": "Оставить Исходный Текст",
  "enhance.suggestions": "Рекомендации",
  "timeline.title": "ИИ-Реконструкция Маршрута",
  "timeline.subtitle": "Вспомните свои перемещения, чтобы точно определить время и место потери.",
  "timeline.userProvided": "Введено Пользователем",
  "timeline.aiInferred": "Предположено ИИ",
  "timeline.unknown": "Неизвестно",
  "timeline.likelyLocation": "Вероятный Район",
  "timeline.timeWindow": "Временной Интервал",
  "timeline.reasoning": "Логика ИИ",
  "timeline.applyLocation": "Использовать Это Место",
  "timeline.editEvent": "Изменить Точку",
  "timeline.addEvent": "Добавить Точку",
  "home.heroTag": "Найти • Проверить • Вернуть",
  "home.heroTitle1": "Ваша личность под защитой.",
  "home.heroTitle2": "Ваши вещи возвращаются домой.",
  "home.heroSubtitle1": "Никогда не теряйте то, что принадлежит вам.",
  "home.heroSubtitle2": "Создано сообществом. Защищено искусственным интеллектом.",
  "home.heroDesc": "Подайте заявление о потере или находке меньше чем за минуту. Ваши личные данные защищены до взаимного подтверждения владения.",
  "home.reportLost": "Подать о Потере",
  "home.reportFound": "Подать о Находке",
  "home.findItem": "Найти Вещь",
  "home.viewMatches": "Смотреть ИИ-Совпадения",
  "home.startReport": "Начать Заявление",
  "home.browseFeed": "Открыть Ленту",
  "home.statsTotal": "Всего Объявлений",
  "home.statsLost": "Потерянных Вещей",
  "home.statsFound": "Найденных Вещей",
  "home.statsResolved": "Возвращенных Вещей",
  "home.trustTitle": "Почему LINCO — Это Другой Уровень",
  "home.trustSubtitle": "Построен на принципах нулевого разглашения, надежного подтверждения владения и безопасного возврата.",
  "home.trustPrivacyTitle": "Защита Данных",
  "home.trustPrivacyDesc": "Ваш номер телефона и личные данные никогда не публикуются в открытой ленте.",
  "home.trustProofTitle": "Строгая Проверка Владения",
  "home.trustProofDesc": "Сгенерированные ИИ контрольные вопросы исключают мошенников до реальной встречи.",
  "home.trustRecoveryTitle": "Безопасная Сеть Возврата",
  "home.trustRecoveryDesc": "Договаривайтесь о встрече через защищенные чаты, взаимные подтверждения и инструкции.",
  "home.timelineShowcaseTitle": "Реконструкция Дня с ИИ",
  "home.timelineShowcaseSubtitle": "Вспомните ключевые точки своего дня, чтобы восстановить точное время и место потери.",
  "home.timelineTryPrompt": "Попробуйте пример:",
  "home.faqTitle": "Часто Задаваемые Вопросы",
  "home.faqSubtitle": "Все о том, как работает LINCO и помогает возвращать вещи.",
  "dashboard.title": "Личный Кабинет",
  "dashboard.subtitle": "Управляйте своими активными объявлениями, комнатами возврата и безопасностью.",
  "dashboard.tabReports": "Мои Заявления",
  "dashboard.tabClaims": "Мои Заявки на Возврат",
  "dashboard.tabRecovery": "Комнаты Возврата",
  "dashboard.tabSettings": "Настройки",
  "dashboard.noReports": "Вы пока не создали ни одного заявления.",
  "dashboard.noClaims": "У вас пока нет активных заявок.",
  "dashboard.noRecovery": "Активных комнат возврата пока нет.",
  "dashboard.accountDetails": "Данные Профиля",
  "dashboard.fullName": "Полное Имя",
  "dashboard.phoneNumber": "Номер Телефона",
  "dashboard.city": "Город",
  "dashboard.languagePreference": "Предпочитаемый Язык",
  "dashboard.changeLanguage": "Сменить Язык",
  "dashboard.saveSettings": "Сохранить Настройки",
  "dashboard.settingsSaved": "Настройки успешно сохранены.",
  "claim.modalTitle": "Заявить о Праве Владения Вещью",
  "claim.modalSubtitle": "Подтвердите, что вы являетесь законным хозяином, ответив на контрольные вопросы.",
  "claim.verifyIdentity": "Проверка Права Владения",
  "claim.questionsPrompt": "Пожалуйста, точно ответьте на контрольные вопросы:",
  "claim.proofDetails": "Особые Приметы или Доказательства",
  "claim.proofPlaceholder": "Опишите мелкие царапины, скрытое содержимое или серийные номера...",
  "claim.submitClaim": "Подать Заявку",
  "claim.statusPending": "На Проверке",
  "claim.statusApproved": "Заявка Одобрена",
  "claim.statusRejected": "Заявка Отклонена",
  "claim.statusResolved": "Дело Успешно Завершено",
  "category.Electronics": "Электроника",
  "category.Documents": "Документы и Карты",
  "category.Keys": "Ключи",
  "category.Pet": "Домашние Животные",
  "category.Jewelry": "Украшения и Часы",
  "category.Vehicle": "Транспорт",
  "category.Clothing": "Одежда и Сумки",
  "category.Other": "Другие Предметы",
  "urgency.Normal": "Обычная",
  "urgency.Urgent": "Срочная",
  "urgency.Medical": "Медицинская / Критическая"
}

TR_269 = {
  "app.tagline": "Yapay Zekâ Kayıp ve Buluntu Hindistan",
  "app.subtitle": "Kayıp eşyaları gizlilik ve doğrulanmış güvenle geri kazanın.",
  "nav.home": "Ana Sayfa",
  "nav.report": "Bildirim Yayınla",
  "nav.feed": "Topluluk Akışı",
  "nav.matches": "YZ Eşleşmeleri",
  "nav.activity": "Etkinlik",
  "nav.profile": "Profil",
  "nav.about": "Hakkımızda",
  "nav.privacyTrust": "Gizlilik ve Güven",
  "nav.language": "Dil",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Geri",
  "common.next": "İleri",
  "common.cancel": "İptal",
  "common.save": "Kaydet",
  "common.submit": "Gönder",
  "common.edit": "Düzenle",
  "common.delete": "Sil",
  "common.close": "Kapat",
  "common.loading": "Yükleniyor...",
  "common.success": "Başarılı",
  "common.error": "Hata",
  "common.search": "Ara",
  "common.filter": "Filtrele",
  "common.clear": "Temizle",
  "common.optional": "İsteğe Bağlı",
  "common.required": "Zorunlu",
  "common.viewAll": "Tümünü Gör",
  "common.details": "Ayrıntılar",
  "common.status": "Durum",
  "lang.heading": "Dilinizi seçin",
  "lang.subheading": "LINCO'yu kendinizi en rahat hissettiğiniz dilde kullanın.",
  "lang.note": "Dilediğiniz zaman Ayarlar bölümünden dili değiştirebilirsiniz.",
  "lang.continue": "LINCO ile Devam Et",
  "lang.searchPlaceholder": "Dillerde ara (örn. Türkçe, English, Hindi)...",
  "lang.tabAll": "Tüm Diller",
  "lang.tabIndian": "Hindistan Dilleri (22)",
  "lang.tabInternational": "Uluslararası Diller",
  "lang.supportedBadge": "Tam Destekli",
  "lang.previewBadge": "Önizleme / Beta",
  "voice.button": "Sesli Giriş",
  "voice.listening": "Dinleniyor... Kendi dilinizde doğal şekilde konuşun",
  "voice.processing": "Ses kaydı işleniyor...",
  "voice.transcribing": "Metne dönüştürülüyor...",
  "voice.reviewTitle": "Sesli Bildirimi İncele",
  "voice.reviewSubtitle": "Uygulamadan önce algılanan ayrıntıları doğrulayın.",
  "voice.apply": "Ayrıntıları Uygula",
  "voice.retry": "Yeniden Konuş",
  "voice.cancel": "İptal",
  "voice.notSupported": "Ses tanıma özelliği tarayıcınız tarafından desteklenmiyor.",
  "voice.permissionDenied": "Mikrofon izni reddedildi. Lütfen ayarlardan izin verin.",
  "notifications.centerTitle": "Etkinlik Merkezi",
  "notifications.centerSubtitle": "Gerçek zamanlı eşleşmeler, hak talepleri ve teslimat takibi.",
  "notifications.readAll": "Tümünü okundu işaretle",
  "notifications.unread": "Okunmamış",
  "notifications.emptyTitle": "Henüz bildirim yok",
  "notifications.emptySubtitle": "Bildirimlerinizle ilgili bir gelişme olduğunda sizi bilgilendireceğiz.",
  "notifications.networkFooter": "LINCO Akıllı Bildirim Ağı",
  "notifications.listingAlert": "Yeni İlan Bildirimi",
  "notifications.matchFound": "Olası Eşleşme Bulundu",
  "notifications.claimReceived": "Sahiplik Talebi Alındı",
  "notifications.ownerApproved": "Sahip Tarafından Onaylandı",
  "notifications.finderVerified": "Bulan Tarafından Doğrulandı",
  "notifications.verificationComplete": "Karşılıklı Doğrulama Tamamlandı",
  "notifications.newMessage": "Yeni Güvenli Mesaj",
  "notifications.trustUpdate": "Güven Seviyesi Güncellendi",
  "notifications.handoverUpdate": "Teslimat Durumu Güncellendi",
  "notifications.itemReceived": "Eşya Teslim Alındı",
  "notifications.itemReunited": "Kavuşma Başarıyla Tamamlandı",
  "notifications.actions.viewMatch": "Eşleşmeyi Gör",
  "notifications.actions.reviewClaim": "Talebi İncele",
  "notifications.actions.viewVerification": "Doğrulamayı Gör",
  "notifications.actions.openChat": "Sohbeti Aç",
  "notifications.actions.confirmHandover": "Teslimatı Onayla",
  "notifications.actions.viewCase": "Dosyayı Gör",
  "notifications.actions.viewDetails": "Ayrıntıları Gör",
  "notifications.actions.confirmTrust": "Güveni Onayla",
  "notifications.matchFoundMsg": "Bildiriminiz için yüksek doğrulukta bir eşleşme bulduk.",
  "notifications.claimReceivedMsg": "Biri bu eşya için sahiplik talebinde bulundu.",
  "notifications.claimApprovedMsg": "Talebiniz karşı tarafça incelendi ve onaylandı.",
  "notifications.ownerApprovedMsg": "Eşya sahibi bu eşyanın kendisine ait olabileceğini doğruladı.",
  "notifications.finderVerifiedMsg": "Bulan kişi, yanıtlarınızın bulunan eşyayla örtüştüğünü doğruladı.",
  "notifications.bothApprovedMsg": "Her iki taraf da eşleşmeyi doğruladı. Güvenli sohbet artık açık.",
  "notifications.newMessageMsg": "Güvenli sohbette yeni bir mesajınız var.",
  "notifications.trustUpdateMsg": "Karşılıklı güven onaylandı! WhatsApp iletişim bilgileri açıldı.",
  "notifications.handoverUpdateMsg": "Güvenli teslimat süreci başlatıldı.",
  "notifications.itemReceivedMsg": "Eşyanın teslim alındığı onaylandı.",
  "notifications.itemReunitedMsg": "Eşya sahibine başarıyla kavuştu! Dosya resmen kapatıldı.",
  "help.notSure": "Ne yazacağınızdan emin değil misiniz?",
  "help.askLinco": "LINCO'ya Sor",
  "help.listen": "Yardımı Dinle",
  "help.stopListen": "Durdur",
  "help.itemName": "Eşyanın bilinen adını belirtin (örn. Deri cüzdan, iPhone 14).",
  "help.location": "En yakın istasyon veya bilinen noktayı yazın.",
  "help.time": "Yaklaşık saat ve gün dilimini seçin.",
  "help.description": "Renk, marka, malzeme ve içindekileri açıklayın.",
  "help.identifying": "Yalnızca gerçek sahibinin bileceği gizli bir detay belirtin.",
  "help.timeline": "Arama alanını daraltmak için gününüzü adım adım hatırlayın.",
  "report.badge": "Akıllı Bildirim",
  "report.titleLost": "Kayıp Eşya Bildir",
  "report.titleFound": "Bulunan Eşya Bildir",
  "report.step1.title": "Temel Bilgiler",
  "report.step1.typeLost": "Bir Şey Kaybettim",
  "report.step1.typeFound": "Bir Şey Buldum",
  "report.step1.itemName": "Eşyanın Adı",
  "report.step1.itemNamePlaceholder": "örn. Siyah Tommy Hilfiger deri cüzdan, iPhone 15 Pro",
  "report.step1.category": "Kategori",
  "report.step1.urgency": "Aciliyet Seviyesi",
  "report.step2.title": "Konum",
  "report.step2.location": "Konum veya Bilinen Nokta",
  "report.step2.locationPlaceholder": "örn. Merkez Tren Garı 2. Peron, Üniversite Kütüphanesi",
  "report.step2.useGps": "Mevcut GPS Konumunu Kullan",
  "report.step2.pinMap": "Haritada İşaretle",
  "report.step3.title": "Tarih ve Saat",
  "report.step3.date": "Tarih",
  "report.step3.time": "Yaklaşık Saat",
  "report.step3.quickToday": "Bugün",
  "report.step3.quickYesterday": "Dün",
  "report.step3.quickMorning": "Sabah",
  "report.step3.quickAfternoon": "Öğleden Sonra",
  "report.step3.quickEvening": "Akşam",
  "report.step3.quickNight": "Gece",
  "report.step4.title": "Açıklama ve İşaretler",
  "report.step4.desc": "Detaylı Açıklama",
  "report.step4.descPlaceholder": "Renk, marka, model ve genel durumu açıklayın...",
  "report.step4.aiEnhance": "Yapay Zekâ ile İyileştir",
  "report.step4.timelineBuilder": "Güzergâh Yardımcısı",
  "report.step4.identifyingMarks": "Ayırt Edici İşaretler (Gizli)",
  "report.step4.identifyingPlaceholder": "örn. Köşesinde küçük çizik, NASA çıkartması, içinde 2 anahtar",
  "report.step4.photo": "Eşyanın Fotoğrafı",
  "report.step5.title": "İletişim ve Gizlilik",
  "report.step5.contact": "Telefon Numarası / WhatsApp",
  "report.step5.contactPlaceholder": "10 haneli telefon numarası",
  "report.step5.contactNotice": "Telefon numaranız asla herkese açık akışta gösterilmez.",
  "report.step6.title": "Ödül ve Güvenlik PIN'i",
  "report.step6.reward": "Teklif Edilen Ödül (İsteğe Bağlı)",
  "report.step6.aiReward": "YZ Önerili Ödül Miktarı",
  "report.step6.pin": "4 Haneli Güvenlik PIN Kodu",
  "report.step6.pinNotice": "Bu PIN kodunu bildirimi daha sonra düzenlemek veya kapatmak için saklayın.",
  "feed.title": "Topluluk Akışı",
  "feed.subtitle": "Bölgenizdeki güncel kayıp ve bulunan eşya bildirimleri.",
  "feed.all": "Tümü",
  "feed.lost": "Kayıp",
  "feed.found": "Bulunan",
  "feed.resolved": "Kavuştu",
  "feed.listView": "Liste Görünümü",
  "feed.mapView": "Harita Görünümü",
  "feed.searchPlaceholder": "Eşya, konum veya kategoriye göre ara...",
  "feed.noResults": "Arama kriterlerine uygun bildirim bulunamadı.",
  "feed.claimButton": "Bu Benim",
  "feed.foundButton": "Ben Buldum",
  "feed.viewMatches": "Eşleşmeleri Gör",
  "matches.title": "YZ Eşleştirme Merkezi",
  "matches.subtitle": "Kayıp ve buluntu ilanları arasında akıllı anlamsal eşleştirme.",
  "matches.allMatches": "Tüm Eşleşmeler",
  "matches.mutualApprovals": "Karşılıklı Onaylar",
  "matches.pendingVerification": "Doğrulama Bekleyenler",
  "matches.resolved": "Tamamlananlar",
  "matches.threshold": "Eşleşme Eşiği",
  "matches.confidence": "Güven Skoru",
  "matches.score": "Puan",
  "matches.reason": "Eşleşme Sebebi",
  "matches.lostReport": "Kayıp Bildirimi",
  "matches.foundReport": "Buluntu Bildirimi",
  "matches.openChat": "Güvenli Sohbet Başlat",
  "matches.verifyApprove": "Doğrula ve Onayla",
  "matches.modalTitle": "Eşleşme Ayrıntıları",
  "matches.notFoundTitle": "Eşleşme bulunamadı",
  "matches.notFoundDesc": "Seçilen filtrelere uygun henüz bir eşleşme bulunmuyor.",
  "matches.backToActivity": "Etkinliğe Dön",
  "chat.title": "Güvenli Teslimat Sohbeti",
  "chat.trustButton": "Güveni Onayla",
  "chat.whatsapp": "WhatsApp'ta Devam Et",
  "chat.handover": "Güvenli Teslimatı Başlat",
  "chat.received": "Eşyamı Teslim Aldım",
  "chat.resolved": "Dosya Kapatıldı",
  "chat.placeholder": "Güvenli bir mesaj yazın...",
  "chat.send": "Gönder",
  "chat.safetyWarning": "Güvenlik Tavsiyesi: Her zaman kalabalık halka açık yerlerde buluşun. Asla önceden para göndermeyin.",
  "enhance.modalTitle": "Yapay Zekâ ile Metin İyileştirme",
  "enhance.aiBadge": "YZ Tarafından Üretildi",
  "enhance.original": "İlk Açıklama",
  "enhance.enhanced": "Geliştirilmiş Açıklama",
  "enhance.structuredHeading": "Yapılandırılmış Nitelikler",
  "enhance.accept": "Değişiklikleri Uygula",
  "enhance.edit": "Düzenle",
  "enhance.tryAgain": "Yeniden Üret",
  "enhance.keepOriginal": "İlk Hali Koru",
  "enhance.suggestions": "Öneriler",
  "timeline.title": "YZ Güzergâh Rekonstrüksiyonu",
  "timeline.subtitle": "Zamanı ve konumu tam saptamak için gün içindeki adımlarınızı hatırlayın.",
  "timeline.userProvided": "Kullanıcı Girdisi",
  "timeline.aiInferred": "YZ Çıkarımı",
  "timeline.unknown": "Bilinmiyor",
  "timeline.likelyLocation": "En Olası Bölge",
  "timeline.timeWindow": "Zaman Aralığı",
  "timeline.reasoning": "YZ Akıl Yürütmesi",
  "timeline.applyLocation": "Bu Konumu Kullan",
  "timeline.editEvent": "Adımı Düzenle",
  "timeline.addEvent": "Adım Ekle",
  "home.heroTag": "Ara • Doğrula • Kavuş",
  "home.heroTitle1": "Kimliğiniz güvende kalır.",
  "home.heroTitle2": "Eşyalarınız size geri döner.",
  "home.heroSubtitle1": "Size ait olanı asla kaybetmeyin.",
  "home.heroSubtitle2": "İnsanlar tarafından yürütülen, YZ ile korunan ağ.",
  "home.heroDesc": "Bir dakikadan kısa sürede bildirimde bulunun. Sahiplik karşılıklı doğrulanana kadar gizliliğiniz korunur.",
  "home.reportLost": "Kayıp Eşya Bildir",
  "home.reportFound": "Bulunan Eşya Bildir",
  "home.findItem": "Eşya Ara",
  "home.viewMatches": "YZ Eşleşmelerini Gör",
  "home.startReport": "Bildirime Başla",
  "home.browseFeed": "Topluluk Akışına Göz At",
  "home.statsTotal": "Toplam Bildirim",
  "home.statsLost": "Kayıp Eşya",
  "home.statsFound": "Bulunan Eşya",
  "home.statsResolved": "Sahibine Kavuşan",
  "home.trustTitle": "LINCO Neden Farklı?",
  "home.trustSubtitle": "Sıfır bilgi gizliliği, güvenilir sahiplik kanıtı ve rehberli teslimat üzerine kuruldu.",
  "home.trustPrivacyTitle": "Korunan Kimlik",
  "home.trustPrivacyDesc": "Telefon numaranız ve kişisel bilgileriniz asla genel akışta paylaşılmaz.",
  "home.trustProofTitle": "Güvenilir Sahiplik Kanıtı",
  "home.trustProofDesc": "YZ tarafından oluşturulan gizli kontrol soruları, buluşmadan önce sahte hak iddialarını engeller.",
  "home.trustRecoveryTitle": "Güvenli Teslimat Ağı",
  "home.trustRecoveryDesc": "Şifreli sohbet, karşılıklı onay ve rehberli teslimat ile eşyanızı güvenle geri alın.",
  "home.timelineShowcaseTitle": "YZ ile Günlük Güzergâh Taraması",
  "home.timelineShowcaseSubtitle": "Kayıp anını ve yerini tam belirlemek için gün içindeki duraklarınızı hatırlayın.",
  "home.timelineTryPrompt": "Bir örnek deneyin:",
  "home.faqTitle": "Sıkça Sorulan Sorular",
  "home.faqSubtitle": "LINCO'nun nasıl çalıştığına dair merak ettiğiniz tüm ayrıntılar.",
  "dashboard.title": "Vatandaş Paneli",
  "dashboard.subtitle": "Aktif bildirimlerinizi, teslimat odalarınızı ve güvenlik ayarlarınızı yönetin.",
  "dashboard.tabReports": "Bildirimlerim",
  "dashboard.tabClaims": "Hak Taleplerim",
  "dashboard.tabRecovery": "Teslimat Odaları",
  "dashboard.tabSettings": "Ayarlar",
  "dashboard.noReports": "Henüz bir bildirimde bulunmadınız.",
  "dashboard.noClaims": "Şu anda aktif bir hak talebiniz yok.",
  "dashboard.noRecovery": "Aktif teslimat odası bulunmuyor.",
  "dashboard.accountDetails": "Hesap Bilgileri",
  "dashboard.fullName": "Ad Soyad",
  "dashboard.phoneNumber": "Telefon Numarası",
  "dashboard.city": "Şehir",
  "dashboard.languagePreference": "Tercih Edilen Dil",
  "dashboard.changeLanguage": "Dili Değiştir",
  "dashboard.saveSettings": "Ayarları Kaydet",
  "dashboard.settingsSaved": "Ayarlar başarıyla kaydedildi.",
  "claim.modalTitle": "Bu Eşya İçin Hak Talebinde Bulun",
  "claim.modalSubtitle": "Kontrol sorularını yanıtlayarak eşyanın gerçek sahibi olduğunuzu kanıtlayın.",
  "claim.verifyIdentity": "Kimlik ve Sahiplik Doğrulama",
  "claim.questionsPrompt": "Lütfen aşağıdaki soruları dikkatlice yanıtlayın:",
  "claim.proofDetails": "Belirgin Detaylar veya Kanıtlar",
  "claim.proofPlaceholder": "Belirli çizikleri, gizli bölmeleri veya seri numaralarını açıklayın...",
  "claim.submitClaim": "Talebi Gönder",
  "claim.statusPending": "İnceleme Bekleniyor",
  "claim.statusApproved": "Talep Onaylandı",
  "claim.statusRejected": "Talep Reddedildi",
  "claim.statusResolved": "Dosya Başarıyla Çözüldü",
  "category.Electronics": "Elektronik",
  "category.Documents": "Belgeler ve Kartlar",
  "category.Keys": "Anahtarlar",
  "category.Pet": "Evcil Hayvanlar",
  "category.Jewelry": "Takı ve Saat",
  "category.Vehicle": "Araçlar",
  "category.Clothing": "Giyim ve Çanta",
  "category.Other": "Diğer Eşyalar",
  "urgency.Normal": "Normal",
  "urgency.Urgent": "Acil",
  "urgency.Medical": "Tıbbi / Kritik"
}
