# -*- coding: utf-8 -*-
"""Authentic Urdu (Perso-Arabic), Kashmiri (Nastaliq/Perso-Arabic), and Sindhi (Arabic-Sindhi) 269 UI translations."""

UR_269 = {
  "app.tagline": "اے آئی گمشدہ اور ملا بھارت",
  "app.subtitle": "رازداری اور تصدیق شدہ اعتماد کے ساتھ گمشدہ اشیاء کی بازیابی۔",
  "nav.home": "ہوم",
  "nav.report": "رپورٹ درج کریں",
  "nav.feed": "کمیونٹی فیڈ",
  "nav.matches": "اے آئی میچز",
  "nav.activity": "سرگرمی",
  "nav.profile": "پروفائل",
  "nav.about": "ہمارے بارے میں",
  "nav.privacyTrust": "رازداری اور تحفظ",
  "nav.language": "زبان",
  "nav.saathii": "لنکو ساتھی",
  "common.back": "واپس",
  "common.next": "اگلا",
  "common.cancel": "منسوخ کریں",
  "common.save": "محفوظ کریں",
  "common.submit": "جمع کرائیں",
  "common.edit": "ترمیم کریں",
  "common.delete": "حذف کریں",
  "common.close": "بند کریں",
  "common.loading": "لوڈ ہو رہا ہے...",
  "common.success": "کامیابی",
  "common.error": "خرابی",
  "common.search": "تلاش کریں",
  "common.filter": "فلٹر",
  "common.clear": "صاف کریں",
  "common.optional": "اختیاری",
  "common.required": "لازمی",
  "common.viewAll": "سب دیکھیں",
  "common.details": "تفصیلات",
  "common.status": "حیثیت",
  "lang.heading": "اپنی زبان منتخب کریں",
  "lang.subheading": "لنکو کو اس زبان میں استعمال کریں جس میں آپ سب سے زیادہ پرسکون محسوس کرتے ہیں۔",
  "lang.note": "آپ ترتیبات سے کسی بھی وقت زبان تبدیل کر سکتے ہیں۔",
  "lang.continue": "لنکو کے ساتھ آگے بڑھیں",
  "lang.searchPlaceholder": "زبان تلاش کریں (مثلاً اردو، ہندی، وغیرہ)...",
  "lang.tabAll": "تمام زبانیں",
  "lang.tabIndian": "بھارتی زبانیں (22)",
  "lang.tabInternational": "بین الاقوامی زبانیں",
  "lang.supportedBadge": "مکمل طور پر معاون",
  "lang.previewBadge": "پیش نظارہ / بیٹا",
  "voice.button": "صوتی ان پٹ",
  "voice.listening": "سن رہا ہے... اپنی زبان میں قدرتی طور پر بولیں",
  "voice.processing": "صوتی نوٹ کا تجزیہ ہو رہا ہے...",
  "voice.transcribing": "تحریر میں تبدیل کیا جا رہا ہے...",
  "voice.reviewTitle": "صوتی رپورٹ کا جائزہ لیں",
  "voice.reviewSubtitle": "شامل کرنے سے پہلے تسلیم شدہ تفصیلات کی تصدیق کریں۔",
  "voice.apply": "تفصیلات شامل کریں",
  "voice.retry": "دوبارہ بولیں",
  "voice.cancel": "منسوخ کریں",
  "voice.notSupported": "آپ کے براؤزر میں آواز کی شناخت معاون نہیں ہے۔",
  "voice.permissionDenied": "مائیکروفون کی اجازت نہیں ملی۔ براہ کرم اجازت دیں۔",
  "notifications.centerTitle": "سرگرمی اور اطلاعات",
  "notifications.centerSubtitle": "ریئل ٹائم میچز، دعوے اور بحالی کی پیشرفت۔",
  "notifications.readAll": "سب پڑھا ہوا نشان زد کریں",
  "notifications.unread": "نہ پڑھی گئی",
  "notifications.emptyTitle": "کوئی اطلاع نہیں ہے",
  "notifications.emptySubtitle": "جب آپ کی پوسٹس پر کوئی کارروائی ہوگی تو آپ کو یہاں مطلع کیا جائے گا۔",
  "notifications.networkFooter": "لنکو سمارٹ نوٹیفکیشن نیٹ ورک",
  "notifications.listingAlert": "نئی لسٹنگ الرٹ",
  "notifications.matchFound": "ممکنہ میچ مل گیا",
  "notifications.claimReceived": "ملکیت کا نیا دعویٰ",
  "notifications.ownerApproved": "مالک نے تصدیق کی",
  "notifications.finderVerified": "تلاش کنندہ نے تصدیق کی",
  "notifications.verificationComplete": "باہمی تصدیق مکمل",
  "notifications.newMessage": "نیا محفوظ پیغام",
  "notifications.trustUpdate": "اعتماد کی تصدیق ہوئی",
  "notifications.handoverUpdate": "حوالگی کی اپ ڈیٹ",
  "notifications.itemReceived": "سامان موصول ہو گیا",
  "notifications.itemReunited": "کامیاب واپسی مکمل",
  "notifications.actions.viewMatch": "میچ دیکھیں",
  "notifications.actions.reviewClaim": "دعوے کا جائزہ لیں",
  "notifications.actions.viewVerification": "تصدیق دیکھیں",
  "notifications.actions.openChat": "چیٹ کھولیں",
  "notifications.actions.confirmHandover": "حوالگی کی تصدیق کریں",
  "notifications.actions.viewCase": "کیس دیکھیں",
  "notifications.actions.viewDetails": "تفصیلات دیکھیں",
  "notifications.actions.confirmTrust": "اعتماد کی تصدیق کریں",
  "notifications.matchFoundMsg": "ہمیں آپ کی رپورٹ کے لیے ایک اعلیٰ اعتماد والا میچ ملا ہے۔",
  "notifications.claimReceivedMsg": "کسی نے اس سامان پر ملکیت کا دعویٰ دائر کیا ہے۔",
  "notifications.claimApprovedMsg": "آپ کا دعویٰ دوسرے فریق کی جانب سے منظور کر لیا گیا ہے۔",
  "notifications.ownerApprovedMsg": "مالک نے تصدیق کی ہے کہ یہ ان کا سامان ہو سکتا ہے۔",
  "notifications.finderVerifiedMsg": "تلاش کنندہ نے تصدیق کی ہے کہ دعویٰ برآمد شدہ سامان سے مطابقت رکھتا ہے۔",
  "notifications.bothApprovedMsg": "دونوں فریقوں نے میچ کی تصدیق کی۔ محفوظ چیٹ اب دستیاب ہے۔",
  "notifications.newMessageMsg": "محفوظ چیٹ میں نیا پیغام موصول ہوا ہے۔",
  "notifications.trustUpdateMsg": "باہمی اعتماد کی تصدیق! واٹس ایپ رابطہ اب کھل گیا ہے۔",
  "notifications.handoverUpdateMsg": "محفوظ حوالگی کا عمل شروع کر دیا گیا ہے۔",
  "notifications.itemReceivedMsg": "سامان کی وصولی کی تصدیق کر دی گئی ہے۔",
  "notifications.itemReunitedMsg": "سامان کامیابی سے مل گیا! کیس باضابطہ طور پر حل ہو گیا۔",
  "help.notSure": "یقین نہیں ہے کہ کیا لکھیں؟",
  "help.askLinco": "لنکو سے مدد لیں",
  "help.listen": "آواز سے سنیں",
  "help.stopListen": "سننا بند کریں",
  "help.itemName": "سامان کا عام نام بتائیں (جیسے بٹوہ، گھڑی، فون)۔",
  "help.location": "قریبی اہم مقام یا اسٹیشن درج کریں۔",
  "help.time": "تقریبی وقت اور دن منتخب کریں۔",
  "help.description": "کوئی خاص نشان، رنگ یا اندرونی سامان بیان کریں۔",
  "help.identifying": "کوئی خفیہ نشانی جو صرف اصلی مالک کو معلوم ہو۔",
  "help.timeline": "اپنے دن کے واقعات کو یاد کرنے کے لیے ٹائم لائن بنائیں۔",
  "report.badge": "حفاظتی انتباہ",
  "report.titleLost": "گمشدہ سامان کی رپورٹ درج کریں",
  "report.titleFound": "ملنے والے سامان کی رپورٹ درج کریں",
  "report.step1.title": "بنیادی معلومات",
  "report.step1.typeLost": "میرا سامان گم ہوا ہے",
  "report.step1.typeFound": "مجھے سامان ملا ہے",
  "report.step1.itemName": "سامان کا نام",
  "report.step1.itemNamePlaceholder": "مثلاً کالا لیدر بٹوہ، ٹائٹن گھڑی، وغیرہ",
  "report.step1.category": "زمرہ",
  "report.step1.urgency": "اہمیت کی سطح",
  "report.step2.title": "مقام کی تفصیلات",
  "report.step2.location": "مقام",
  "report.step2.locationPlaceholder": "علاقہ، قریبی اسٹیشن یا مشہور جگہ درج کریں",
  "report.step2.useGps": "موجودہ GPS مقام استعمال کریں",
  "report.step2.pinMap": "نقشے پر پن لگائیں",
  "report.step3.title": "تاریخ اور وقت",
  "report.step3.date": "تاریخ",
  "report.step3.time": "وقت",
  "report.step3.quickToday": "آج",
  "report.step3.quickYesterday": "کل",
  "report.step3.quickMorning": "صبح",
  "report.step3.quickAfternoon": "دوپہر",
  "report.step3.quickEvening": "شام",
  "report.step3.quickNight": "رات",
  "report.step4.title": "تفصیل اور شناخت",
  "report.step4.desc": "سامان کی تفصیل",
  "report.step4.descPlaceholder": "رنگ، برانڈ، ماڈل اور دیگر نشانیاں بیان کریں...",
  "report.step4.aiEnhance": "اے آئی سے تفصیل بہتر بنائیں",
  "report.step4.timelineBuilder": "ٹائم لائن بلڈر کا استعمال کریں",
  "report.step4.identifyingMarks": "شناختی نشانات",
  "report.step4.identifyingPlaceholder": "خروںچ، اسٹیکرز یا دیگر مخصوص علامات",
  "report.step4.photo": "تصویر اپ لوڈ کریں",
  "report.step5.title": "رابطے کی تفصیلات",
  "report.step5.contact": "موبائل یا واٹس ایپ نمبر",
  "report.step5.contactPlaceholder": "10 ہندسوں کا موبائل نمبر",
  "report.step5.contactNotice": "آپ کا فون نمبر عوامی طور پر ظاہر نہیں کیا جائے گا۔",
  "report.step6.title": "انعام اور سیکیورٹی پن",
  "report.step6.reward": "انعام کی رقم (اختیاری)",
  "report.step6.aiReward": "تجویز کردہ انعام",
  "report.step6.pin": "4 ہندسوں کا سیکیورٹی پن",
  "report.step6.pinNotice": "رپورٹ میں ترمیم یا حذف کرنے کے لیے یہ پن درکار ہوگا۔",
  "feed.title": "کمیونٹی فیڈ",
  "feed.subtitle": "اپنے علاقے میں گمشدہ اور ملنے والے سامان کی تازہ لسٹنگ دیکھیں۔",
  "feed.all": "سب",
  "feed.lost": "گمشدہ",
  "feed.found": "ملنے والا",
  "feed.resolved": "حل شدہ",
  "feed.listView": "فہرست کا منظر",
  "feed.mapView": "نقشے کا منظر",
  "feed.searchPlaceholder": "سامان یا مقام تلاش کریں...",
  "feed.noResults": "کوئی لسٹنگ نہیں ملی۔",
  "feed.claimButton": "یہ میرا ہے",
  "feed.foundButton": "مجھے ملا ہے",
  "feed.viewMatches": "میچز دیکھیں",
  "matches.title": "اے آئی میچز",
  "matches.subtitle": "ہمارا الگورتھم خودکار طریقے سے گمشدہ اور ملنے والی اشیاء کو ملاتا ہے۔",
  "matches.allMatches": "تمام میچز",
  "matches.mutualApprovals": "باہمی منظوری",
  "matches.pendingVerification": "تصدیق کے منتظر",
  "matches.resolved": "حل شدہ",
  "matches.threshold": "مماثلت کی حد",
  "matches.confidence": "اعتماد کا اسکور",
  "matches.score": "اسکور",
  "matches.reason": "میچ کی وجہ",
  "matches.lostReport": "گمشدگی کی رپورٹ",
  "matches.foundReport": "ملنے کی رپورٹ",
  "matches.openChat": "محفوظ چیٹ شروع کریں",
  "matches.verifyApprove": "تصدیق اور منظوری دیں",
  "matches.modalTitle": "میچ کی تفصیلی تصدیق",
  "matches.notFoundTitle": "کوئی میچ نہیں ملا",
  "matches.notFoundDesc": "فی الحال ان فلٹرز کے مطابق کوئی مماثلت دستیاب نہیں ہے۔",
  "matches.backToActivity": "سرگرمی پر واپس جائیں",
  "chat.title": "محفوظ چیٹ",
  "chat.trustButton": "اعتماد کی تصدیق کریں",
  "chat.whatsapp": "واٹس ایپ پر بات کریں",
  "chat.handover": "محفوظ حوالگی کا آغاز کریں",
  "chat.received": "مجھے سامان مل گیا ہے",
  "chat.resolved": "کیس حل ہو گیا",
  "chat.placeholder": "محفوظ پیغام ٹائپ کریں...",
  "chat.send": "بھیجیں",
  "chat.safetyWarning": "احتیاط: کسی کو تصدیق سے پہلے رقم منتقل نہ کریں۔ محفوظ عوامی جگہ پر ملیں۔",
  "enhance.modalTitle": "اے آئی تفصیل بہتر بنائیں",
  "enhance.aiBadge": "اے آئی سے تیار کردہ",
  "enhance.original": "اصل تفصیل",
  "enhance.enhanced": "بہتر تفصیل",
  "enhance.structuredHeading": "منظم خاکہ",
  "enhance.accept": "قبول کریں اور لاگو کریں",
  "enhance.edit": "ترمیم کریں",
  "enhance.tryAgain": "دوبارہ کوشش کریں",
  "enhance.keepOriginal": "اصل رکھیں",
  "enhance.suggestions": "تجاویز",
  "timeline.title": "ٹائم لائن ریکنسٹرکشن",
  "timeline.subtitle": "اپنے اقدامات کی تاریخ وار ترتیب بنائیں تاکہ درست جگہ کا تعین ہو سکے۔",
  "timeline.userProvided": "صارف کا درج کردہ",
  "timeline.aiInferred": "اے آئی کا اندازہ",
  "timeline.unknown": "نامعلوم",
  "timeline.likelyLocation": "ممکنہ مقام",
  "timeline.timeWindow": "وقت کا دائرہ",
  "timeline.reasoning": "اے آئی منطق",
  "timeline.applyLocation": "یہ مقام استعمال کریں",
  "timeline.editEvent": "واقعہ میں ترمیم کریں",
  "timeline.addEvent": "نیا واقعہ شامل کریں",
  "home.heroTag": "تلاش • تصدیق • واپسی",
  "home.heroTitle1": "آپ کی شناخت محفوظ ہے۔",
  "home.heroTitle2": "آپ کا سامان نہیں۔",
  "home.heroSubtitle1": "جو آپ کا ہے وہ کبھی نہ کھوئیں۔",
  "home.heroSubtitle2": "لوگوں کے ذریعے چلنے والا۔ اے آئی کے ذریعے محفوظ۔",
  "home.heroDesc": "ایک منٹ میں گمشدہ یا ملنے والے سامان کی رپورٹ کریں۔ رازداری مکمل طور پر محفوظ رہتی ہے۔",
  "home.reportLost": "گمشدہ سامان کی رپورٹ کریں",
  "home.reportFound": "ملنے والے سامان کی رپورٹ کریں",
  "home.findItem": "سامان تلاش کریں",
  "home.viewMatches": "اے آئی میچز دیکھیں",
  "home.startReport": "رپورٹ شروع کریں",
  "home.browseFeed": "کمیونٹی فیڈ دیکھیں",
  "home.statsTotal": "کل رپورٹس",
  "home.statsLost": "گمشدہ اشیاء",
  "home.statsFound": "ملنے والی اشیاء",
  "home.statsResolved": "واپس کی گئی اشیاء",
  "home.trustTitle": "لنکو پر اعتماد کیوں کریں؟",
  "home.trustSubtitle": "زیرو نالج پرائیویسی اور تصدیق شدہ شناخت پر مبنی محفوظ نیٹ ورک۔",
  "home.trustPrivacyTitle": "مکمل رازداری",
  "home.trustPrivacyDesc": "آپ کا فون نمبر اور ذاتی تفصیلات عوام پر کبھی ظاہر نہیں کی جاتیں۔",
  "home.trustProofTitle": "ملکیت کا ٹھوس ثبوت",
  "home.trustProofDesc": "ملاقات سے پہلے اے آئی کے سمارٹ سوالات جھوٹے دعووں کو روکتے ہیں۔",
  "home.trustRecoveryTitle": "محفوظ بحالی نیٹ ورک",
  "home.trustRecoveryDesc": "محفوظ چیٹ، باہمی منظوری اور گائیڈڈ ہینڈ اوور کے ساتھ واپسی ممکن بنائیں۔",
  "home.timelineShowcaseTitle": "اے آئی ٹائم لائن سسٹم",
  "home.timelineShowcaseSubtitle": "اپنے روٹ کو یاد کریں تاکہ درست مقام اور وقت سامنے آسکے۔",
  "home.timelineTryPrompt": "ایک مثال آزمائیں:",
  "home.faqTitle": "اکثر پوچھے جانے والے سوالات",
  "home.faqSubtitle": "جانیں کہ لنکو کس طرح کام کرتا ہے اور آپ کا سامان کیسے واپس ملتا ہے۔",
  "dashboard.title": "میرا ڈیش بورڈ",
  "dashboard.subtitle": "اپنی رپورٹس، دعوے اور حفاظتی ترتیبات کا انتظام کریں۔",
  "dashboard.tabReports": "میری رپورٹس",
  "dashboard.tabClaims": "میرے دعوے",
  "dashboard.tabRecovery": "بحالی کے کمرے",
  "dashboard.tabSettings": "ترتیبات",
  "dashboard.noReports": "ابھی تک کوئی رپورٹ درج نہیں کی گئی۔",
  "dashboard.noClaims": "ابھی تک کوئی دعویٰ دائر نہیں کیا گیا۔",
  "dashboard.noRecovery": "کوئی فعال ریکوری روم نہیں ہے۔",
  "dashboard.accountDetails": "اکاؤنٹ کی تفصیلات",
  "dashboard.fullName": "پورا نام",
  "dashboard.phoneNumber": "فون نمبر",
  "dashboard.city": "شہر",
  "dashboard.languagePreference": "ترجیحی زبان",
  "dashboard.changeLanguage": "زبان تبدیل کریں",
  "dashboard.saveSettings": "ترتیبات محفوظ کریں",
  "dashboard.settingsSaved": "ترتیبات کامیابی سے محفوظ ہو گئیں۔",
  "claim.modalTitle": "ملکیت کا دعویٰ درج کریں",
  "claim.modalSubtitle": "ثبوت فراہم کریں کہ یہ برآمد شدہ سامان آپ کا ہے۔",
  "claim.verifyIdentity": "شناخت کی تصدیق",
  "claim.questionsPrompt": "براہ کرم درج ذیل سوالات کے درست جوابات دیں:",
  "claim.proofDetails": "مخصوص ثبوت یا اندرونی راز",
  "claim.proofPlaceholder": "کوئی خاص خراش، اندرونی سامان یا سیریل نمبر جو صرف مالک کو معلوم ہو...",
  "claim.submitClaim": "دعویٰ جمع کرائیں",
  "claim.statusPending": "تصدیق کے منتظر",
  "claim.statusApproved": "دعویٰ منظور ہو گیا",
  "claim.statusRejected": "دعویٰ مسترد کر دیا گیا",
  "claim.statusResolved": "کامیابی سے حل ہو گیا",
  "category.Electronics": "الیکٹرانکس",
  "category.Documents": "دستاویزات",
  "category.Keys": "چابیاں",
  "category.Pet": "پالتو جانور",
  "category.Jewelry": "زیورات",
  "category.Vehicle": "گاڑی",
  "category.Clothing": "کپڑے",
  "category.Other": "دیگر",
  "urgency.Normal": "عام",
  "urgency.Urgent": "ضروری",
  "urgency.Medical": "طبی / انتہائی اہم"
}

KS_269 = {
  "app.tagline": "اے آئی رُوٹھمُت تہٕ لَبمُت ہِنٛدوستان",
  "app.subtitle": "رازدارِی تہٕ تصدیق شُدٕ اِعتبارَس سٟتؠ رُوٹھمٕژ چیٖزن ہٕنٛز واپٔسی۔",
  "nav.home": "گَرٕ",
  "nav.report": "رِپورٹ دَرٕج کٔرِو",
  "nav.feed": "بایچاری فیٖڑ",
  "nav.matches": "اے آئی جوڈٕ",
  "nav.activity": "سرگرمی",
  "nav.profile": "پروفائل",
  "nav.about": "سأنؠ مُتعلِق",
  "nav.privacyTrust": "رازداری تہٕ تحَفُظ",
  "nav.language": "زبان",
  "nav.saathii": "لِنکو ساتھی",
  "common.back": "واپَس",
  "common.next": "برٛونٛہہ",
  "common.cancel": "مَنسوٗخ",
  "common.save": "محفوٗظ کٔرِو",
  "common.submit": "جمہٕ کٔرِو",
  "common.edit": "تبدیٖل کٔرِو",
  "common.delete": "مِٹٲوِو",
  "common.close": "بَنٛد کٔرِو",
  "common.loading": "لوڈ گژھان چھُ...",
  "common.success": "کامیابی",
  "common.error": "خرابی",
  "common.search": "تَلاش کٔرِو",
  "common.filter": "فِلٹَر",
  "common.clear": "صاف کٔرِو",
  "common.optional": "اِختیاری",
  "common.required": "لازمی",
  "common.viewAll": "سٲری وُچھِو",
  "common.details": "تفصیٖلات",
  "common.status": "حیثیت",
  "lang.heading": "پَنٕنؠ زبان ژارِو",
  "lang.subheading": "لِنکو اَمَلَس انِو اَتھ زبانہِ مَنٛز یَتھ مَنٛز تُہؠ آسانی پٲٹھؠ پَروَرِش کٔرِو۔",
  "lang.note": "تُہؠ ہیکِو ترتیبات مَنٛز کُنہِ تہِ وقتہٕ زبان بَدلٲوِتھ۔",
  "lang.continue": "لِنکو سٟتؠ برٛونٛہہ پَکِو",
  "lang.searchPlaceholder": "زبان تلاش کٔرِو (مِثال: کٲشُر، اُردوٗ، وغیرہ)...",
  "lang.tabAll": "سٲری زبانَن",
  "lang.tabIndian": "ہِندوستٲنؠ زبانَن (22)",
  "lang.tabInternational": "بین الاقوٲمی زبانَن",
  "lang.supportedBadge": "پوٗرٕ سَہولِیَتھ",
  "lang.previewBadge": "پیش نظارہٕ / بیٖٹا",
  "voice.button": "آواز اِن پُٹ",
  "voice.listening": "بوزان چھُ... پَنٕنہِ زبان مَنٛز صَفٲیی سٟتؠ کَتھ کٔرِو",
  "voice.processing": "آواز ہُند تجزِیَہ گژھان چھُ...",
  "voice.transcribing": "لِکھتَس مَنٛز تبدِیل گژھان چھُ...",
  "voice.reviewTitle": "صوتی رپورٹُک جائزہٕ نِیو",
  "voice.reviewSubtitle": "درج کرنہٕ برٛونٛہہ صٔحیح تفصیٖلات تصدیٖق کٔرِو۔",
  "voice.apply": "تفصیٖلات شٲمِل کٔرِو",
  "voice.retry": "دوبارٕ کَتھ کٔرِو",
  "voice.cancel": "مَنسوٗخ",
  "voice.notSupported": "تُہنٛدِس براؤزرس مَنٛز چھُنہٕ آواز سُنٛد سَہولِیَتھ۔",
  "voice.permissionDenied": "مائیکروفونک اِجازت مِلیو نہٕ۔ مہرَبٲنی کٔرِتھ اِجازت دِیو۔",
  "notifications.centerTitle": "سرگرمی تہٕ اِطلاعَن",
  "notifications.centerSubtitle": "ریئل ٹائم جوڈٕ، دعوے تہٕ واپٔسی ہٕنٛز پیش رفت۔",
  "notifications.readAll": "سٲری پَرِمٕژ نِشان لَگٲوِو",
  "notifications.unread": "نہٕ پَرِمٕژ",
  "notifications.emptyTitle": "کانٛہہ اِطلاع چھُنہٕ",
  "notifications.emptySubtitle": "ییلہِ تُہنٛدِس رپورٹَس پؠٹھ کانہہ کارروٲیی گژھِ، تُہؠ یِیو یَتھ پؠٹھ باخَبَر کَرنہٕ۔",
  "notifications.networkFooter": "لِنکو سمارٹ نوٹیفکیشن نیٹ ورک",
  "notifications.listingAlert": "نوؠ لِسٹِنٛگ اَلَرٹ",
  "notifications.matchFound": "ممکنہٕ جوڈٕ لَبنہٕ آو",
  "notifications.claimReceived": "ملکیتُک نوٚو دعویٰ",
  "notifications.ownerApproved": "مالکَن کٔر تصدیٖق",
  "notifications.finderVerified": "لبن وٲلؠ کٔر تصدیٖق",
  "notifications.verificationComplete": "باہمی تصدیٖق مکمل",
  "notifications.newMessage": "نوٚو محفوٗظ سُنیہہ",
  "notifications.trustUpdate": "اِعتبارُک تصدیٖق گۆو",
  "notifications.handoverUpdate": "حوالگی ہُند اَپڈیٹ",
  "notifications.itemReceived": "چیٖز حٲصِل گۆو",
  "notifications.itemReunited": "کامیاب واپٔسی مکمل",
  "notifications.actions.viewMatch": "جوڈٕ وُچھِو",
  "notifications.actions.reviewClaim": "دعوے ہُند جائزہٕ نِیو",
  "notifications.actions.viewVerification": "تصدیٖق وُچھِو",
  "notifications.actions.openChat": "چیٹ کھولِو",
  "notifications.actions.confirmHandover": "حوالگی ہٕنٛز تصدیٖق کٔرِو",
  "notifications.actions.viewCase": "کیٖس وُچھِو",
  "notifications.actions.viewDetails": "تفصیٖلات وُچھِو",
  "notifications.actions.confirmTrust": "اِعتبارُک تصدیٖق کٔرِو",
  "notifications.matchFoundMsg": "أسی لبؠ تُہنٛدِس رپورٹَس خٲطرٕ اَکھ اَصٕل جوڈٕ۔",
  "notifications.claimReceivedMsg": "کانٛہہ شخصَن کٔر اَتھ چیٖزَس پؠٹھ ملکیتُک دعویٰ۔",
  "notifications.claimApprovedMsg": "تُہنٛد دعویٰ آو دۆیمہِ طرفہٕ تصدیٖق تہٕ منظور کَرنہٕ۔",
  "notifications.ownerApprovedMsg": "مالکَن کٔر تصدیٖق زِ یہِ ہیکہِ تِہنٛز چیٖز ٲسِتھ۔",
  "notifications.finderVerifiedMsg": "لبن وٲلؠ کٔر تصدیٖق زِ دعویٰ چھُ لبنہٕ آمٕژ چیٖز سٟتؠ رَلان۔",
  "notifications.bothApprovedMsg": "دۄشوونی فریقن کٔر جوڈٕ تصدیٖق۔ محفوٗظ چیٹ چھُ وۄنؠ دستیاب۔",
  "notifications.newMessageMsg": "محفوٗظ چیٹَس مَنٛز آو نوٚو سُنیہہ۔",
  "notifications.trustUpdateMsg": "باہمی اِعتبار تصدیٖق گۆو! واٹس ایپ رابطہٕ گوٚو اَن لاک۔",
  "notifications.handoverUpdateMsg": "محفوٗظ حوالگی ہُنٛد عمل گوٚو شُروع۔",
  "notifications.itemReceivedMsg": "چیٖز حٲصِل گژھنُک تصدیٖق آو کرنہٕ۔",
  "notifications.itemReunitedMsg": "چیٖز آو کامیابی سٟتؠ واپَس مِلنہٕ! کیٖس گوٚو حل۔",
  "help.notSure": "معلوٗم چھُنہٕ کِیاہ لؠکھوٗن؟",
  "help.askLinco": "لِنکو سٟتؠ مَدَتھ مَنٛگِو",
  "help.listen": "آواز سٟتؠ بوزِو",
  "help.stopListen": "بوزُن بَنٛد کٔرِو",
  "help.itemName": "چیٖزُک عام ناو لؠکھِو (مِثال: ویلیٹ، گھڑی، فون)۔",
  "help.location": "قریبی مشہوٗر جاے یا اِسٹیشن درج کٔرِو۔",
  "help.time": "تقریبی وقت تہٕ دوہ ژارِو۔",
  "help.description": "کانٛہہ خاص نِشان، رَنٛگ یا اَنٛدروٗنی سامانہٕ بٔیٲن کٔرِو۔",
  "help.identifying": "کانٛہہ خوٗفیہٕ نِشانی یۄس صِرف اَصلی مالکَس مَلوٗم آسِہ۔",
  "help.timeline": "پَنٕنؠ دۄہ کؠن واقعن یاد کرنہٕ خٲطرٕ ٹائم لائن بناوِو۔",
  "report.badge": "تحَفُظ اِنتِباہ",
  "report.titleLost": "رُوٹھمُت چیٖز درج کٔرِو",
  "report.titleFound": "لَبمُت چیٖز درج کٔرِو",
  "report.step1.title": "بنیادی معلوٗمات",
  "report.step1.typeLost": "میٛون چیٖز چھُ رُوٹھمُت",
  "report.step1.typeFound": "میٛےٚ چھُ چیٖز لَبمُت",
  "report.step1.itemName": "چیٖزُک ناو",
  "report.step1.itemNamePlaceholder": "مِثال: کٔجُر چمڑُک ویلیٹ، ٹائٹن گھڑی، وغیرہ",
  "report.step1.category": "زُمرٕ",
  "report.step1.urgency": "ضرورت ہٕنٛز سَطَح",
  "report.step2.title": "جاے ہٕنٛز تفصیٖلات",
  "report.step2.location": "جاے",
  "report.step2.locationPlaceholder": "علاقہٕ، مشہوٗر مقام یا اِسٹیشن درج کٔرِو",
  "report.step2.useGps": "موجودٕ GPS جاے اِستعمال کٔرِو",
  "report.step2.pinMap": "نقشَس پؠٹھ پن لَگٲوِو",
  "report.step3.title": "تٲریخ تہٕ وقت",
  "report.step3.date": "تٲریخ",
  "report.step3.time": "وقت",
  "report.step3.quickToday": "اَز",
  "report.step3.quickYesterday": "راٹھ",
  "report.step3.quickMorning": "صُبحَس",
  "report.step3.quickAfternoon": "دۄپہارس",
  "report.step3.quickEvening": "شامَس",
  "report.step3.quickNight": "راتَس",
  "report.step4.title": "تفصیٖل تہٕ شَناخَتھ",
  "report.step4.desc": "چیٖزٕچ تفصیٖل",
  "report.step4.descPlaceholder": "رَنٛگ، برانٛڈ، ماڈل تہٕ باقی نِشانات بیان کٔرِو...",
  "report.step4.aiEnhance": "اے آئی سٟتؠ تفصیٖل بہتر بناوِو",
  "report.step4.timelineBuilder": "ٹائم لائن بلڈر اِستعمال کٔرِو",
  "report.step4.identifyingMarks": "شَناخٕتی نِشانات",
  "report.step4.identifyingPlaceholder": "خرٛوش، اِسٹِکَر یا دیگر خاص علامات",
  "report.step4.photo": "فوٹو اَپلوڈ کٔرِو",
  "report.step5.title": "رابطہٕ تفصیٖلات",
  "report.step5.contact": "موبائل یا واٹس ایپ نمبر",
  "report.step5.contactPlaceholder": "10 ہِندسَن ہُنٛد موبائل نمبر",
  "report.step5.contactNotice": "تُہنٛد فون نمبر یِیہِ نہٕ عوٲمی طور پٲٹھؠ ظٲہر کَرنہٕ۔",
  "report.step6.title": "اِنعام تہٕ سیکیورٹی پِن",
  "report.step6.reward": "اِنعامُک رقم (اِختیاری)",
  "report.step6.aiReward": "تجویز کَردٕ اِنعام",
  "report.step6.pin": "4 ہِندسَن ہُنٛد سیکیورٹی پِن",
  "report.step6.pinNotice": "رپورٹَس مَنٛز تبدِیلی یا مِٹاونہٕ خٲطرٕ پییہِ یہِ پِن ضروٗرت۔",
  "feed.title": "بایچاری فیٖڑ",
  "feed.subtitle": "پَننِس علاقَس مَنٛز رُوٹھمٕژ تہٕ لَبمٕژ چیٖزن ہٕنٛز تازی لِسٹِنٛگ وُچھِو۔",
  "feed.all": "سٲری",
  "feed.lost": "رُوٹھمُت",
  "feed.found": "لَبمُت",
  "feed.resolved": "حل شُدٕ",
  "feed.listView": "فہرستُک نظارہٕ",
  "feed.mapView": "نقشُک نظارہٕ",
  "feed.searchPlaceholder": "چیٖز یا جاے تَلاش کٔرِو...",
  "feed.noResults": "کانٛہہ لِسٹِنٛگ مِلیو نہٕ۔",
  "feed.claimButton": "یہِ چھُ میٛون",
  "feed.foundButton": "میٛےٚ چھُ لَبمُت",
  "feed.viewMatches": "جوڈٕ وُچھِو",
  "matches.title": "اے آئی جوڈٕ",
  "matches.subtitle": "سأنؠ الگورتھم چھِ خودکار طریقہٕ سٟتؠ رُوٹھمٕژ تہٕ لَبمٕژ چیٖز مِلاوان۔",
  "matches.allMatches": "سٲری جوڈٕ",
  "matches.mutualApprovals": "باہمی منظوری",
  "matches.pendingVerification": "تصدیٖق ہٕنٛز اِنتظاری",
  "matches.resolved": "حل شُدٕ",
  "matches.threshold": "مماثلت ہٕنٛز سَطَح",
  "matches.confidence": "اعتمادُک اِسکور",
  "matches.score": "اِسکور",
  "matches.reason": "جوڈٕ ہٕنٛز وجہ",
  "matches.lostReport": "رُوٹھنُک رپورٹ",
  "matches.foundReport": "لَبنُک رپورٹ",
  "matches.openChat": "محفوٗظ چیٹ شُروع کٔرِو",
  "matches.verifyApprove": "تصدیٖق تہٕ منظوری دِیو",
  "matches.modalTitle": "جوڈٕ ہٕنٛز تفصیٖلی تصدیٖق",
  "matches.notFoundTitle": "کانٛہہ جوڈٕ مِلیو نہٕ",
  "matches.notFoundDesc": "فی الحال چھُنہٕ اِمَن فلٹرَن مُطٲبِق کانٛہہ جوڈٕ۔",
  "matches.backToActivity": "سرگرمی پؠٹھ واپَس گژھِو",
  "chat.title": "محفوٗظ چیٹ",
  "chat.trustButton": "اِعتبارُک تصدیٖق کٔرِو",
  "chat.whatsapp": "واٹس ایپ پؠٹھ کَتھ کٔرِو",
  "chat.handover": "محفوٗظ حوالگی شُروع کٔرِو",
  "chat.received": "میٛےٚ مِلیو چیٖز",
  "chat.resolved": "کیٖس حل گۆو",
  "chat.placeholder": "محفوٗظ سُنیہہ لؠکھِو...",
  "chat.send": "سوزِو",
  "chat.safetyWarning": "احتیاط: کُنہِ تہِ شخصَس تصدیٖق برٛونٛہہ پونٛسہٕ مَہ دِیو۔ محفوٗظ عوٲمی جاے پؠٹھ مِلِو۔",
  "enhance.modalTitle": "اے آئی تفصیٖل بہتر بناوِو",
  "enhance.aiBadge": "اے آئی ہُنٛد بناوِمُت",
  "enhance.original": "اصلی تفصیٖل",
  "enhance.enhanced": "بہتر تفصیٖل",
  "enhance.structuredHeading": "منظم خاکہٕ",
  "enhance.accept": "قبول کٔرِو تہٕ لاگوٗ کٔرِو",
  "enhance.edit": "تبدیٖل کٔرِو",
  "enhance.tryAgain": "دوبارٕ کوٗشِش کٔرِو",
  "enhance.keepOriginal": "اصلی تھاوِو",
  "enhance.suggestions": "تجاویز",
  "timeline.title": "ٹائم لائن ریکنسٹرکشن",
  "timeline.subtitle": "پَننؠن قدمن ہٕنٛز تاریخ وار ترتیب بناوِو تاکہِ صٔحیح جاے مَلوٗم گژھِ۔",
  "timeline.userProvided": "صارف سُنٛد درج کٔرمُت",
  "timeline.aiInferred": "اے آئی سُنٛد اندازٕ",
  "timeline.unknown": "نامعلوٗم",
  "timeline.likelyLocation": "ممکنہٕ جاے",
  "timeline.timeWindow": "وقتُک دائرٕ",
  "timeline.reasoning": "اے آئی منطق",
  "timeline.applyLocation": "یہِ جاے اِستعمال کٔرِو",
  "timeline.editEvent": "واقعس مَنٛز تبدِیلی کٔرِو",
  "timeline.addEvent": "نوٚو واقعہٕ شٲمِل کٔرِو",
  "home.heroTag": "تَلاش • تصدیٖق • واپٔسی",
  "home.heroTitle1": "تُہنٛز پَژھ چھِ محفوٗظ۔",
  "home.heroTitle2": "تُہنٛد سامان نہٕ۔",
  "home.heroSubtitle1": "یُس تُہنٛد چھُ سُہ مَہ کٔدِیو زانٛہہ۔",
  "home.heroSubtitle2": "لوٗکن ہٕنٛدِ ذٔریعہٕ چَلن وول۔ اے آئی ہٕنٛدِ ذٔریعہٕ محفوٗظ۔",
  "home.heroDesc": "اَکھ مِنٹَس مَنٛز رُوٹھمٕژ یا لَبمٕژ چیٖزن ہٕنٛز رپورٹ کٔرِو۔ رازداری چھِ پوٗرٕ محفوٗظ۔",
  "home.reportLost": "رُوٹھمُت چیٖز درج کٔرِو",
  "home.reportFound": "لَبمُت چیٖز درج کٔرِو",
  "home.findItem": "چیٖز تَلاش کٔرِو",
  "home.viewMatches": "اے آئی جوڈٕ وُچھِو",
  "home.startReport": "رپورٹ شُروع کٔرِو",
  "home.browseFeed": "بایچاری فیٖڑ وُچھِو",
  "home.statsTotal": "کُل رپورٹس",
  "home.statsLost": "رُوٹھمٕژ چیٖزَن",
  "home.statsFound": "لَبمٕژ چیٖزَن",
  "home.statsResolved": "واپَس مِلمٕژ چیٖزَن",
  "home.trustTitle": "لِنکو پؠٹھ اِعتبار کیٛازِ کَروٗن؟",
  "home.trustSubtitle": "زیرو نالج پرائیویسی تہٕ تصدیق شُدٕ پَژھ پؠٹھ محفوٗظ نیٹ ورک۔",
  "home.trustPrivacyTitle": "پوٗرٕ رازداری",
  "home.trustPrivacyDesc": "تُہنٛد فون نمبر تہٕ نجی معلوٗمات یِیہِ نہٕ زانٛہہ عوٲمی طور پؠٹھ ظٲہر کَرنہٕ۔",
  "home.trustProofTitle": "ملکیتُک پۄختہٕ ثبوٗت",
  "home.trustProofDesc": "مِلاقاتہٕ برٛونٛہہ اے آئی ہُند سمارٹ سوال چھِ غلَط دعوَن روکان۔",
  "home.trustRecoveryTitle": "محفوٗظ واپٔسی نیٹ ورک",
  "home.trustRecoveryDesc": "محفوٗظ چیٹ، باہمی منظوری تہٕ رَہنمٲیی سٟتؠ حوالگی ممکن بناوِو۔",
  "home.timelineShowcaseTitle": "اے آئی ٹائم لائن سِسٹَم",
  "home.timelineShowcaseSubtitle": "پَنُن سفر یاد کٔرِو تاکہِ صٔحیح جاے تہٕ وقت پتا لَگِہ۔",
  "home.timelineTryPrompt": "اَکھ مِثال آزمٲوِو:",
  "home.faqTitle": "عام طور پُچھنہٕ ینہٕ وٲلؠ سوالات",
  "home.faqSubtitle": "زانِو زِ لِنکو کِتھ پٲٹھؠ کٲم چھُ کَران تہٕ تُہنٛد سامان کِتھ پٲٹھؠ چھُ واپَس مِلان۔",
  "dashboard.title": "میٛون ڈیش بورڈ",
  "dashboard.subtitle": "پَننؠن رپورٹس، دعوَن تہٕ حفاظتی ترتیباتُک اِنتظام کٔرِو۔",
  "dashboard.tabReports": "مؠأنؠ رپورٹس",
  "dashboard.tabClaims": "مؠأنؠ دعوے",
  "dashboard.tabRecovery": "واپٔسی رُوم",
  "dashboard.tabSettings": "ترتیبات",
  "dashboard.noReports": "وُنہِ تام کانٛہہ رپورٹ درج کَرنہٕ آمُژ نہٕ۔",
  "dashboard.noClaims": "وُنہِ تام کانٛہہ دعویٰ کَرنہٕ آمُت نہٕ۔",
  "dashboard.noRecovery": "کانٛہہ فعال رِکوری رُوم چھُنہٕ۔",
  "dashboard.accountDetails": "کھاتُک تفصیٖلات",
  "dashboard.fullName": "پوٗرٕ ناو",
  "dashboard.phoneNumber": "فون نمبر",
  "dashboard.city": "شہر",
  "dashboard.languagePreference": "پسندیدٕ زبان",
  "dashboard.changeLanguage": "زبان بَدلٲوِو",
  "dashboard.saveSettings": "ترتیبات محفوٗظ کٔرِو",
  "dashboard.settingsSaved": "ترتیبات آیہِ کامیابی سٟتؠ محفوٗظ کَرنہٕ۔",
  "claim.modalTitle": "ملکیتُک دعویٰ درج کٔرِو",
  "claim.modalSubtitle": "ثبوٗت فراہم کٔرِو زِ یہِ لبنہٕ آمُژ چیٖز چھِ تُہنٛز۔",
  "claim.verifyIdentity": "پَژھ ہٕنٛز تصدیٖق",
  "claim.questionsPrompt": "مہرَبٲنی کٔرِتھ دِیو بۄنِمؠن سوالَن ہٕنٛد صٔحیح جواب:",
  "claim.proofDetails": "خاص ثبوٗت یا اَنٛدروٗنی راز",
  "claim.proofPlaceholder": "کانٛہہ خاص خرٛوش، اَنٛدروٗنی سامان یا سیریل نمبر یُس صِرف مالکَس مَلوٗم آسِہ...",
  "claim.submitClaim": "دعویٰ جمع کٔرِو",
  "claim.statusPending": "تصدیٖق ہٕنٛز اِنتظاری",
  "claim.statusApproved": "دعویٰ آو منظور کَرنہٕ",
  "claim.statusRejected": "دعویٰ آو رَد کَرنہٕ",
  "claim.statusResolved": "کامیابی سٟتؠ حل گۆو",
  "category.Electronics": "الیکٹرانکس",
  "category.Documents": "دستاویزات",
  "category.Keys": "کُنٛجین",
  "category.Pet": "پالتو جانور",
  "category.Jewelry": "زیوَرَات",
  "category.Vehicle": "گاڈی",
  "category.Clothing": "پلو",
  "category.Other": "باقی",
  "urgency.Normal": "عام",
  "urgency.Urgent": "ضروری",
  "urgency.Medical": "طبی / نَہایت اہم"
}

SD_269 = {
  "app.tagline": "اي آءِ گم ٿيل ۽ مليل ڀارت",
  "app.subtitle": "رازداري ۽ تصديق ٿيل ڀروسي سان گم ٿيل سامان جي واپسي.",
  "nav.home": "گهر",
  "nav.report": "رپورٽ داخل ڪريو",
  "nav.feed": "ڪميونٽي فيڊ",
  "nav.matches": "اي آءِ جوڙا",
  "nav.activity": "سرگرمي",
  "nav.profile": "پروفائل",
  "nav.about": "اسان بابت",
  "nav.privacyTrust": "رازداري ۽ سيڪيورٽي",
  "nav.language": "ٻولي",
  "nav.saathii": "لنڪو ساٿي",
  "common.back": "واپس",
  "common.next": "اڳيان",
  "common.cancel": "منسوخ",
  "common.save": "محفوظ ڪريو",
  "common.submit": "جمع ڪريو",
  "common.edit": "ترميم ڪريو",
  "common.delete": "خارج ڪريو",
  "common.close": "بند ڪريو",
  "common.loading": "لوڊ ٿي رهيو آهي...",
  "common.success": "ڪاميابي",
  "common.error": "غلطي",
  "common.search": "ڳوليو",
  "common.filter": "فلٽر",
  "common.clear": "صاف ڪريو",
  "common.optional": "اختياري",
  "common.required": "لازمي",
  "common.viewAll": "سڀ ڏسو",
  "common.details": "تفصيل",
  "common.status": "حالت",
  "lang.heading": "پنهنجي ٻولي چونڊيو",
  "lang.subheading": "لنڪو کي ان ٻوليءَ ۾ استعمال ڪريو جنهن ۾ توهان تمام آسان محسوس ڪريو.",
  "lang.note": "توهان سيٽنگن مان ڪنهن به وقت ٻولي تبديل ڪري سگهو ٿا.",
  "lang.continue": "لنڪو سان اڳتي وڌو",
  "lang.searchPlaceholder": "ٻولي ڳوليو (مثال: سنڌي، اردو، هندي)...",
  "lang.tabAll": "سڀ ٻوليون",
  "lang.tabIndian": "هندستاني ٻوليون (22)",
  "lang.tabInternational": "بين الاقوامي ٻوليون",
  "lang.supportedBadge": "مڪمل سپورٽ ٿيل",
  "lang.previewBadge": "پيش نظارو / بيٽا",
  "voice.button": "صوتي ان پٽ",
  "voice.listening": "ٻڌي رهيو آهي... پنهنجي ٻوليءَ ۾ چٽائيءَ سان ڳالهايو",
  "voice.processing": "صوتي پيغام جي جاچ ٿي رهي آهي...",
  "voice.transcribing": "تحرير ۾ تبديل ٿي رهيو آهي...",
  "voice.reviewTitle": "صوتي رپورٽ جو جائزو وٺو",
  "voice.reviewSubtitle": "شامل ڪرڻ کان اڳ مليل تفصيلن جي تصديق ڪريو.",
  "voice.apply": "تفصيل شامل ڪريو",
  "voice.retry": "ٻيهر ڳالهايو",
  "voice.cancel": "منسوخ",
  "voice.notSupported": "توهان جي برائوزر ۾ آواز سڃاڻڻ جي سهولت ناهي.",
  "voice.permissionDenied": "مائڪروفيون جي اجازت نه ملي. مهرباني ڪري اجازت ڏيو.",
  "notifications.centerTitle": "سرگرمي ۽ اطلاع",
  "notifications.centerSubtitle": "ريئل ٽائيم ميچ، دعوائون ۽ بحاليءَ جي پيش رفت.",
  "notifications.readAll": "سڀ پڙهيل نشان لڳايو",
  "notifications.unread": "اڻ پڙهيل",
  "notifications.emptyTitle": "ڪو نئون اطلاع ناهي",
  "notifications.emptySubtitle": "جڏهن توهان جي رپورٽ تي ڪا ڪارروائي ٿيندي ته توهان کي هتي آگاهي ڏني ويندي.",
  "notifications.networkFooter": "لنڪو سمارٽ نوٽيفڪيشن نيٽ ورڪ",
  "notifications.listingAlert": "نئين لسٽنگ جو اطلاع",
  "notifications.matchFound": "امڪاني ميچ ملي ويو",
  "notifications.claimReceived": "ملڪيت جي نئين دعويٰ",
  "notifications.ownerApproved": "مالڪ تصديق ڪئي",
  "notifications.finderVerified": "ڳوليندڙ تصديق ڪئي",
  "notifications.verificationComplete": "ٻطرفي تصديق مڪمل",
  "notifications.newMessage": "نئون محفوظ نياپو",
  "notifications.trustUpdate": "ڀروسي جي تصديق ٿي وئي",
  "notifications.handoverUpdate": "حوالگي جي اپڊيٽ",
  "notifications.itemReceived": "سامان ملي ويو",
  "notifications.itemReunited": "ڪامياب واپسي مڪمل",
  "notifications.actions.viewMatch": "ميچ ڏسو",
  "notifications.actions.reviewClaim": "دعويٰ جو جائزو وٺو",
  "notifications.actions.viewVerification": "تصديق ڏسو",
  "notifications.actions.openChat": "چيٽ کوليو",
  "notifications.actions.confirmHandover": "حوالگي جي تصديق ڪريو",
  "notifications.actions.viewCase": "ڪيس ڏسو",
  "notifications.actions.viewDetails": "تفصيل ڏسو",
  "notifications.actions.confirmTrust": "ڀروسي جي تصديق ڪريو",
  "notifications.matchFoundMsg": "اسان کي توهان جي رپورٽ لاءِ اعليٰ اعتماد جو هڪ ميچ مليو آهي.",
  "notifications.claimReceivedMsg": "ڪنهن هن سامان تي پنهنجي ملڪيت جي دعويٰ داخل ڪئي آهي.",
  "notifications.claimApprovedMsg": "توهان جي دعويٰ ٻئي ڌر پاران منظور ڪئي وئي آهي.",
  "notifications.ownerApprovedMsg": "مالڪ تصديق ڪئي آهي ته هي سامان سندن ٿي سگهي ٿو.",
  "notifications.finderVerifiedMsg": "ڳوليندڙ تصديق ڪئي آهي ته دعويٰ مليل سامان سان ملندڙ آهي.",
  "notifications.bothApprovedMsg": "ٻنهي ڌرين ميچ جي تصديق ڪئي. محفوظ چيٽ هاڻي دستياب آهي.",
  "notifications.newMessageMsg": "محفوظ چيٽ ۾ نئون نياپو آيو آهي.",
  "notifications.trustUpdateMsg": "ٻطرفي ڀروسي جي تصديق! واٽس ايپ رابطو کلي ويو آهي.",
  "notifications.handoverUpdateMsg": "محفوظ حوالگي جو عمل شروع ڪيو ويو آهي.",
  "notifications.itemReceivedMsg": "سامان جي وصوليءَ جي تصديق ڪئي وئي آهي.",
  "notifications.itemReunitedMsg": "سامان ڪاميابيءَ سان ملي ويو! ڪيس باضابطه طور حل ٿي ويو.",
  "help.notSure": "خبر ناهي ڇا لکجي؟",
  "help.askLinco": "لنڪو کان مدد وٺو",
  "help.listen": "آواز سان ٻڌو",
  "help.stopListen": "ٻڌڻ بند ڪريو",
  "help.itemName": "سامان جو عام نالو ٻڌايو (جهڙوڪ والٽ، گهڙي، فون).",
  "help.location": "ويجهو مشهور هنڌ يا اسٽيشن درج ڪريو.",
  "help.time": "اندازي وارو وقت ۽ ڏينهن چونڊيو.",
  "help.description": "ڪو خاص نشان، رنگ يا اندروني سامان بيان ڪريو.",
  "help.identifying": "ڪو ڳجهو نشان جيڪو رڳو اصلي مالڪ کي خبر هجي.",
  "help.timeline": "پنهنجي ڏينهن جو وقت وار احوال ياد ڪرڻ لاءِ ٽائم لائن ٺاهيو.",
  "report.badge": "حفاظتي آگاهي",
  "report.titleLost": "گم ٿيل سامان جي رپورٽ ڪريو",
  "report.titleFound": "مليل سامان جي رپورٽ ڪريو",
  "report.step1.title": "بنيادي معلومات",
  "report.step1.typeLost": "منهنجو سامان گم ٿيو آهي",
  "report.step1.typeFound": "مون کي سامان مليو آهي",
  "report.step1.itemName": "سامان جو نالو",
  "report.step1.itemNamePlaceholder": "مثال: ڪارو چمڙي جو والٽ، ٽائيٽن گهڙي، وغيره",
  "report.step1.category": "زمرو",
  "report.step1.urgency": "ضرورت جي سطح",
  "report.step2.title": "هنڌ جا تفصيل",
  "report.step2.location": "هنڌ",
  "report.step2.locationPlaceholder": "علائقو، مشهور هنڌ يا اسٽيشن درج ڪريو",
  "report.step2.useGps": "موجوده GPS هنڌ استعمال ڪريو",
  "report.step2.pinMap": "نقشي تي پن لڳايو",
  "report.step3.title": "تاريخ ۽ وقت",
  "report.step3.date": "تاريخ",
  "report.step3.time": "وقت",
  "report.step3.quickToday": "اڄ",
  "report.step3.quickYesterday": "ڪالهه",
  "report.step3.quickMorning": "صبح جو",
  "report.step3.quickAfternoon": "منجهند جو",
  "report.step3.quickEvening": "شام جو",
  "report.step3.quickNight": "رات جو",
  "report.step4.title": "تفصيل ۽ سڃاڻپ",
  "report.step4.desc": "سامان جي وضاحت",
  "report.step4.descPlaceholder": "رنگ، برانڊ، ماڊل ۽ ٻيا نشان بيان ڪريو...",
  "report.step4.aiEnhance": "اي آءِ سان تفصيل بهتر ڪريو",
  "report.step4.timelineBuilder": "ٽائم لائن بلڊر استعمال ڪريو",
  "report.step4.identifyingMarks": "سڃاڻپ جا نشان",
  "report.step4.identifyingPlaceholder": "ڇِڪون، اسٽيڪر يا ٻيا خاص نشان",
  "report.step4.photo": "تصوير اپلوڊ ڪريو",
  "report.step5.title": "رابطي جا تفصيل",
  "report.step5.contact": "موبائل يا واٽس ايپ نمبر",
  "report.step5.contactPlaceholder": "10 انگن وارو موبائل نمبر",
  "report.step5.contactNotice": "توهان جو فون نمبر عوامي طور تي ظاهر نه ڪيو ويندو.",
  "report.step6.title": "انعام ۽ سيڪيورٽي پن",
  "report.step6.reward": "انعام جي رقم (اختياري)",
  "report.step6.aiReward": "تجويز ڪيل انعام",
  "report.step6.pin": "4 انگن واري سيڪيورٽي پن",
  "report.step6.pinNotice": "رپورٽ ۾ ترميم يا خارج ڪرڻ لاءِ هي پن گهربل هوندو.",
  "feed.title": "ڪميونٽي فيڊ",
  "feed.subtitle": "پنهنجي علائقي ۾ گم ٿيل ۽ مليل سامان جون تازيون لسٽنگون ڏسو.",
  "feed.all": "سڀ",
  "feed.lost": "گم ٿيل",
  "feed.found": "مليل",
  "feed.resolved": "حل ٿيل",
  "feed.listView": "فهرست جو ڏيک",
  "feed.mapView": "نقشي جو ڏيک",
  "feed.searchPlaceholder": "سامان يا هنڌ ڳوليو...",
  "feed.noResults": "ڪا به لسٽنگ نه ملي.",
  "feed.claimButton": "هي منهنجو آهي",
  "feed.foundButton": "مون کي مليو آهي",
  "feed.viewMatches": "جوڙا ڏسو",
  "matches.title": "اي آءِ جوڙا",
  "matches.subtitle": "اسان جو الگورٿم پاڻمرادو گم ٿيل ۽ مليل شين کي ملائي ٿو.",
  "matches.allMatches": "سڀ جوڙا",
  "matches.mutualApprovals": "ٻطرفي منظوري",
  "matches.pendingVerification": "تصديق جي انتظار ۾",
  "matches.resolved": "حل ٿيل",
  "matches.threshold": "هڪجهڙائيءَ جي حد",
  "matches.confidence": "اعتماد جو اسڪور",
  "matches.score": "اسڪور",
  "matches.reason": "ميچ جو سبب",
  "matches.lostReport": "گم ٿيڻ جي رپورٽ",
  "matches.foundReport": "ملڻ جي رپورٽ",
  "matches.openChat": "محفوظ چيٽ شروع ڪريو",
  "matches.verifyApprove": "تصديق ۽ منظوري ڏيو",
  "matches.modalTitle": "ميچ جي تفصيلي تصديق",
  "matches.notFoundTitle": "ڪو ميچ نه مليو",
  "matches.notFoundDesc": "هن وقت انهن فلٽرن مطابق ڪا هڪجهڙائي دستياب ناهي.",
  "matches.backToActivity": "سرگرمي ڏانهن واپس وڃو",
  "chat.title": "محفوظ چيٽ",
  "chat.trustButton": "ڀروسي جي تصديق ڪريو",
  "chat.whatsapp": "واٽس ايپ تي ڳالهايو",
  "chat.handover": "محفوظ حوالگي شروع ڪريو",
  "chat.received": "مون کي سامان ملي ويو",
  "chat.resolved": "ڪيس حل ٿي ويو",
  "chat.placeholder": "محفوظ نياپو لکو...",
  "chat.send": "موڪليو",
  "chat.safetyWarning": "احتياط: تصديق کان اڳ ڪنهن کي رقم نه موڪليو. ڪنهن محفوظ عوامي هنڌ تي ملو.",
  "enhance.modalTitle": "اي آءِ تفصيل بهتر ڪريو",
  "enhance.aiBadge": "اي آءِ پاران تيار ڪيل",
  "enhance.original": "اصل تفصيل",
  "enhance.enhanced": "بهتر تفصيل",
  "enhance.structuredHeading": "ترتيب ڏنل خاڪو",
  "enhance.accept": "قبول ڪريو ۽ لاڳو ڪريو",
  "enhance.edit": "ترميم ڪريو",
  "enhance.tryAgain": "ٻيهر ڪوشش ڪريو",
  "enhance.keepOriginal": "اصل رکو",
  "enhance.suggestions": "تجويزون",
  "timeline.title": "ٽائم لائن تعمير نو",
  "timeline.subtitle": "پنهنجي قدمن جي تاريخ وار ترتيب ٺاهيو ته جيئن صحيح هنڌ معلوم ٿي سگهي.",
  "timeline.userProvided": "استعمال ڪندڙ پاران ڏنل",
  "timeline.aiInferred": "اي آءِ جو اندازو",
  "timeline.unknown": "نامعلوم",
  "timeline.likelyLocation": "امڪاني هنڌ",
  "timeline.timeWindow": "وقت جو دائرو",
  "timeline.reasoning": "اي آءِ منطق",
  "timeline.applyLocation": "هي هنڌ استعمال ڪريو",
  "timeline.editEvent": "واقعي ۾ ترميم ڪريو",
  "timeline.addEvent": "نئون واقعو شامل ڪريو",
  "home.heroTag": "ڳوليو • تصديق ڪريو • واپس وٺو",
  "home.heroTitle1": "توهان جي سڃاڻپ محفوظ آهي.",
  "home.heroTitle2": "توهان جو سامان ناهي.",
  "home.heroSubtitle1": "جيڪو توهان جو آهي، اهو ڪڏهن به نه وڃايو.",
  "home.heroSubtitle2": "ماڻهن ذريعي هلندڙ. اي آءِ ذريعي محفوظ.",
  "home.heroDesc": "هڪ منٽ ۾ گم ٿيل يا مليل سامان جي رپورٽ داخل ڪريو. رازداري مڪمل محفوظ رهي ٿي.",
  "home.reportLost": "گم ٿيل سامان جي رپورٽ ڪريو",
  "home.reportFound": "مليل سامان جي رپورٽ ڪريو",
  "home.findItem": "سامان ڳوليو",
  "home.viewMatches": "اي آءِ ميچ ڏسو",
  "home.startReport": "رپورٽ شروع ڪريو",
  "home.browseFeed": "ڪميونٽي فيڊ ڏسو",
  "home.statsTotal": "ڪل رپورٽون",
  "home.statsLost": "گم ٿيل شيون",
  "home.statsFound": "مليل شيون",
  "home.statsResolved": "واپس ٿيل شيون",
  "home.trustTitle": "لنڪو تي ڀروسو ڇو ڪجي؟",
  "home.trustSubtitle": "زيرو نالج پرائيويسي ۽ تصديق ٿيل سڃاڻپ تي ٻڌل محفوظ نيٽ ورڪ.",
  "home.trustPrivacyTitle": "مڪمل رازداري",
  "home.trustPrivacyDesc": "توهان جو فون نمبر ۽ ذاتي معلومات عوام سامهون ڪڏهن به ظاهر نه ڪئي ويندي.",
  "home.trustProofTitle": "ملڪيت جو پڪو ثبوت",
  "home.trustProofDesc": "ملاقات کان اڳ اي آءِ جا سوال ڪوڙين دعوائن کي روڪين ٿا.",
  "home.trustRecoveryTitle": "محفوظ واپسي نيٽ ورڪ",
  "home.trustRecoveryDesc": "محفوظ چيٽ، ٻطرفي منظوري ۽ رهنمائي ڪيل حوالگيءَ ذريعي واپسي ممڪن بڻايو.",
  "home.timelineShowcaseTitle": "اي آءِ ٽائم لائن سسٽم",
  "home.timelineShowcaseSubtitle": "پنهنجي واٽ کي ياد ڪريو ته جيئن صحيح هنڌ ۽ وقت سامهون اچي.",
  "home.timelineTryPrompt": "هڪ مثال آزمايو:",
  "home.faqTitle": "عام پڇيا ويندڙ سوال",
  "home.faqSubtitle": "ڄاڻو ته لنڪو ڪيئن ڪم ڪري ٿو ۽ توهان جو سامان ڪيئن واپس ملي ٿو.",
  "dashboard.title": "منهنجو ڊيش بورڊ",
  "dashboard.subtitle": "پنهنجي رپورٽن، دعوائن ۽ حفاظتي سيٽنگن جو انتظام ڪريو.",
  "dashboard.tabReports": "منهنجون رپورٽون",
  "dashboard.tabClaims": "منهنجيون دعوائون",
  "dashboard.tabRecovery": "بحالي جا ڪمرا",
  "dashboard.tabSettings": "سيٽنگون",
  "dashboard.noReports": "اڃا تائين ڪا رپورٽ داخل نه ڪئي وئي آهي.",
  "dashboard.noClaims": "اڃا تائين ڪا دعويٰ داخل نه ڪئي وئي آهي.",
  "dashboard.noRecovery": "ڪو به فعال ريڪوري روم ناهي.",
  "dashboard.accountDetails": "کاتي جا تفصيل",
  "dashboard.fullName": "پورو نالو",
  "dashboard.phoneNumber": "فون نمبر",
  "dashboard.city": "شهر",
  "dashboard.languagePreference": "پسنديده ٻولي",
  "dashboard.changeLanguage": "ٻولي تبديل ڪريو",
  "dashboard.saveSettings": "سيٽنگون محفوظ ڪريو",
  "dashboard.settingsSaved": "سيٽنگون ڪاميابيءَ سان محفوظ ٿي ويون.",
  "claim.modalTitle": "ملڪيت جي دعويٰ داخل ڪريو",
  "claim.modalSubtitle": "ثبوت ڏيو ته هي مليل سامان توهان جو آهي.",
  "claim.verifyIdentity": "سڃاڻپ جي تصديق",
  "claim.questionsPrompt": "مهرباني ڪري هيٺين سوالن جا سچا جواب ڏيو:",
  "claim.proofDetails": "خاص ثبوت يا اندروني راز",
  "claim.proofPlaceholder": "ڪا خاص ڇِڪ، اندروني سامان يا سيريل نمبر جيڪو رڳو مالڪ کي خبر هجي...",
  "claim.submitClaim": "دعويٰ جمع ڪريو",
  "claim.statusPending": "تصديق جي انتظار ۾",
  "claim.statusApproved": "دعويٰ منظور ٿي وئي",
  "claim.statusRejected": "دعويٰ رد ڪئي وئي",
  "claim.statusResolved": "ڪاميابيءَ سان حل ٿي ويو",
  "category.Electronics": "اليڪٽرانڪس",
  "category.Documents": "دستاويز",
  "category.Keys": "ڪنجيون",
  "category.Pet": "پالتو جانور",
  "category.Jewelry": "زيور",
  "category.Vehicle": "گاڏي",
  "category.Clothing": "ڪپڙا",
  "category.Other": "ٻيا",
  "urgency.Normal": "عام",
  "urgency.Urgent": "ضروري",
  "urgency.Medical": "طبي / انتهائي اهم"
}
