# -*- coding: utf-8 -*-
"""Authentic Chinese Simplified (ZH), Japanese (JA), and Korean (KO) translations for all 269 UI keys."""

ZH_269 = {
  "app.tagline": "印度智能失物招领平台",
  "app.subtitle": "在严密保护隐私与核实信任的前提下，寻回遗失物品。",
  "nav.home": "首页",
  "nav.report": "发布寻物/招领",
  "nav.feed": "社区动态",
  "nav.matches": "AI 智能匹配",
  "nav.activity": "活动动态",
  "nav.profile": "个人中心",
  "nav.about": "关于我们",
  "nav.privacyTrust": "隐私与安全",
  "nav.language": "语言",
  "nav.saathii": "LINCO 助手",
  "common.back": "返回",
  "common.next": "下一步",
  "common.cancel": "取消",
  "common.save": "保存",
  "common.submit": "提交",
  "common.edit": "编辑",
  "common.delete": "删除",
  "common.close": "关闭",
  "common.loading": "加载中...",
  "common.success": "成功",
  "common.error": "错误",
  "common.search": "搜索",
  "common.filter": "筛选",
  "common.clear": "清空",
  "common.optional": "可选",
  "common.required": "必填",
  "common.viewAll": "查看全部",
  "common.details": "详情",
  "common.status": "状态",
  "lang.heading": "选择您的语言",
  "lang.subheading": "以您最熟悉的语言使用 LINCO。",
  "lang.note": "您可以随时在“设置”中更改界面语言。",
  "lang.continue": "继续使用 LINCO",
  "lang.searchPlaceholder": "搜索语言（如：简体中文、English、Hindi）...",
  "lang.tabAll": "所有语言",
  "lang.tabIndian": "印度官方语言 (22)",
  "lang.tabInternational": "国际语言",
  "lang.supportedBadge": "完全支持",
  "lang.previewBadge": "预览版 / 测试版",
  "voice.button": "语音输入",
  "voice.listening": "正在倾听... 请以您的语言自然说话",
  "voice.processing": "正在处理您的语音...",
  "voice.transcribing": "正在转写为文字...",
  "voice.reviewTitle": "确认语音生成信息",
  "voice.reviewSubtitle": "在应用前请确认识别出的各项细节。",
  "voice.apply": "应用详情",
  "voice.retry": "重新录入",
  "voice.cancel": "取消",
  "voice.notSupported": "您的浏览器暂不支持语音识别功能。",
  "voice.permissionDenied": "麦克风访问权限被拒绝，请在浏览器中开启授权。",
  "notifications.centerTitle": "通知与活动中心",
  "notifications.centerSubtitle": "实时查看匹配、认领申请及归还交接进度。",
  "notifications.readAll": "全部标为已读",
  "notifications.unread": "未读",
  "notifications.emptyTitle": "暂无新通知",
  "notifications.emptySubtitle": "当您的发布有新动态时，我们会立即在此通知您。",
  "notifications.networkFooter": "LINCO 智能通知服务网络",
  "notifications.listingAlert": "发现新发布线索",
  "notifications.matchFound": "发现高度疑似匹配",
  "notifications.claimReceived": "收到失物认领申请",
  "notifications.ownerApproved": "失主已核实确认",
  "notifications.finderVerified": "拾得人已核验通过",
  "notifications.verificationComplete": "双方互认验证完成",
  "notifications.newMessage": "收到加密私信",
  "notifications.trustUpdate": "信任等级已提升",
  "notifications.handoverUpdate": "交接状态更新",
  "notifications.itemReceived": "物品已成功接收",
  "notifications.itemReunited": "失物归还完满结束",
  "notifications.actions.viewMatch": "查看匹配结果",
  "notifications.actions.reviewClaim": "审核认领申请",
  "notifications.actions.viewVerification": "查看核验详情",
  "notifications.actions.openChat": "进入加密聊天",
  "notifications.actions.confirmHandover": "确认物品交接",
  "notifications.actions.viewCase": "查看案件进展",
  "notifications.actions.viewDetails": "查看详细信息",
  "notifications.actions.confirmTrust": "确认互信授权",
  "notifications.matchFoundMsg": "系统为您的发布找到了一个置信度极高的匹配项。",
  "notifications.claimReceivedMsg": "有人针对该物品提交了所有权认领申请。",
  "notifications.claimApprovedMsg": "您的认领申请已被对方核验并确认。",
  "notifications.ownerApprovedMsg": "失主确认该物品极有可能是其遗失物。",
  "notifications.finderVerifiedMsg": "拾得人确认您的回答与所拾物品特征完全相符。",
  "notifications.bothApprovedMsg": "双方均已确认匹配，加密聊天通道已开放。",
  "notifications.newMessageMsg": "您在加密聊天室收到了一条新消息。",
  "notifications.trustUpdateMsg": "互信验证通过！双方 WhatsApp 联系方式已解锁。",
  "notifications.handoverUpdateMsg": "安全线下交接流程已经启动。",
  "notifications.itemReceivedMsg": "已成功确认接收物品。",
  "notifications.itemReunitedMsg": "物品已顺利归还失主！案件正式结案归档。",
  "help.notSure": "不确定该如何填写？",
  "help.askLinco": "向 LINCO 助手咨询",
  "help.listen": "朗读提示",
  "help.stopListen": "停止朗读",
  "help.itemName": "写清物品通用名称（如：黑色皮夹、iPhone 14）。",
  "help.location": "请注明附近的地铁站或标志性地标。",
  "help.time": "选择大致的发生时间及一天中的时段。",
  "help.description": "描述颜色、材质、品牌特征及内部物件。",
  "help.identifying": "提供仅有真正失主知晓的隐秘防伪细节。",
  "help.timeline": "按顺序回顾您今天的行程以缩小搜索范围。",
  "report.badge": "智能发布",
  "report.titleLost": "登记遗失物品",
  "report.titleFound": "登记拾得物品",
  "report.step1.title": "基本信息",
  "report.step1.typeLost": "我遗失了物品",
  "report.step1.typeFound": "我捡到了物品",
  "report.step1.itemName": "物品名称",
  "report.step1.itemNamePlaceholder": "例如：Tommy Hilfiger 黑色真皮钱包、iPhone 15 Pro",
  "report.step1.category": "所属分类",
  "report.step1.urgency": "紧急程度",
  "report.step2.title": "地点位置",
  "report.step2.location": "地点或标志性建筑",
  "report.step2.locationPlaceholder": "例如：中央车站 2号出入口、大学图书馆主楼",
  "report.step2.useGps": "获取当前 GPS 定位",
  "report.step2.pinMap": "在地图上标注点位",
  "report.step3.title": "发生时间",
  "report.step3.date": "日期",
  "report.step3.time": "大致时间",
  "report.step3.quickToday": "今天",
  "report.step3.quickYesterday": "昨天",
  "report.step3.quickMorning": "早晨",
  "report.step3.quickAfternoon": "下午",
  "report.step3.quickEvening": "傍晚",
  "report.step3.quickNight": "深夜",
  "report.step4.title": "外观特征与隐秘记号",
  "report.step4.desc": "外观详细描述",
  "report.step4.descPlaceholder": "请描述颜色、型号、成色及外观特征...",
  "report.step4.aiEnhance": "使用 AI 润色扩充",
  "report.step4.timelineBuilder": "行程推演助手",
  "report.step4.identifyingMarks": "私密防伪特征（不对外公开）",
  "report.step4.identifyingPlaceholder": "例如：右下角轻微划痕、NASA贴纸、内有两把铜钥匙",
  "report.step4.photo": "物品照片",
  "report.step5.title": "联系与隐私",
  "report.step5.contact": "手机号或 WhatsApp 号码",
  "report.step5.contactPlaceholder": "10位有效手机号码",
  "report.step5.contactNotice": "您的真实号码绝不会在公开动态中泄露。",
  "report.step6.title": "谢礼与安全密码",
  "report.step6.reward": "酬谢金额（可选）",
  "report.step6.aiReward": "AI 建议酬劳",
  "report.step6.pin": "4位数字安全 PIN 码",
  "report.step6.pinNotice": "请牢记此 PIN 码，后续修改或结案时需要验证。",
  "feed.title": "社区动态大厅",
  "feed.subtitle": "您周边最新登记的失物与招领信息实时看板。",
  "feed.all": "全部",
  "feed.lost": "遗失信息",
  "feed.found": "招领信息",
  "feed.resolved": "已成功归还",
  "feed.listView": "列表视图",
  "feed.mapView": "地图视图",
  "feed.searchPlaceholder": "按名称、地标或分类搜索...",
  "feed.noResults": "未找到符合当前搜索条件的记录。",
  "feed.claimButton": "这是我的物品",
  "feed.foundButton": "我拾到了此物",
  "feed.viewMatches": "查看匹配",
  "matches.title": "AI 智能匹配中心",
  "matches.subtitle": "基于语义分析自动计算失物与招领的吻合概率。",
  "matches.allMatches": "所有匹配",
  "matches.mutualApprovals": "双方互认",
  "matches.pendingVerification": "待核验",
  "matches.resolved": "已归还",
  "matches.threshold": "匹配阈值",
  "matches.confidence": "置信度",
  "matches.score": "分值",
  "matches.reason": "匹配依据",
  "matches.lostReport": "失物登记",
  "matches.foundReport": "拾得登记",
  "matches.openChat": "发起加密聊天",
  "matches.verifyApprove": "核验并同意",
  "matches.modalTitle": "匹配详细判定",
  "matches.notFoundTitle": "暂无匹配结果",
  "matches.notFoundDesc": "当前筛选条件下暂无高吻合度的物品。",
  "matches.backToActivity": "返回活动动态",
  "chat.title": "加密归还沟通室",
  "chat.trustButton": "确认信任互信",
  "chat.whatsapp": "转至 WhatsApp 沟通",
  "chat.handover": "发起线下安全交接",
  "chat.received": "我已收到遗失物",
  "chat.resolved": "案件完结",
  "chat.placeholder": "发送安全加密消息...",
  "chat.send": "发送",
  "chat.safetyWarning": "安全提示：交接请务必选择人员密集的公共场所，切勿提前转账汇款。",
  "enhance.modalTitle": "AI 智能描述润色",
  "enhance.aiBadge": "AI 智能生成",
  "enhance.original": "原始描述",
  "enhance.enhanced": "优化后描述",
  "enhance.structuredHeading": "结构化提炼特征",
  "enhance.accept": "采纳并应用",
  "enhance.edit": "自行编辑",
  "enhance.tryAgain": "重新生成",
  "enhance.keepOriginal": "保留原稿",
  "enhance.suggestions": "建议改进点",
  "timeline.title": "AI 行程轨迹重构",
  "timeline.subtitle": "回顾您一天的行程节点，精准推算遗失时刻与区域。",
  "timeline.userProvided": "用户填写",
  "timeline.aiInferred": "AI 推理预测",
  "timeline.unknown": "未知",
  "timeline.likelyLocation": "高概率遗失区域",
  "timeline.timeWindow": "推测时间窗口",
  "timeline.reasoning": "AI 分析逻辑",
  "timeline.applyLocation": "采用此定位",
  "timeline.editEvent": "编辑节点",
  "timeline.addEvent": "新增节点",
  "home.heroTag": "发布 • 核验 • 归还",
  "home.heroTitle1": "身份全面保密。",
  "home.heroTitle2": "失物物归原主。",
  "home.heroSubtitle1": "绝不错过属于您的重要物件。",
  "home.heroSubtitle2": "社区互助共建，AI 智能守护安全。",
  "home.heroDesc": "一分钟即可完成失物或拾得物登记。在双方确认物品归属前，您的隐私信息受到严密保护。",
  "home.reportLost": "登记失物",
  "home.reportFound": "登记招领",
  "home.findItem": "搜寻失物",
  "home.viewMatches": "查看 AI 匹配",
  "home.startReport": "立即登记",
  "home.browseFeed": "浏览社区动态",
  "home.statsTotal": "累计案件",
  "home.statsLost": "失物登记数",
  "home.statsFound": "拾得登记数",
  "home.statsResolved": "物归原主数",
  "home.trustTitle": "为什么选择 LINCO",
  "home.trustSubtitle": "依托零知识隐私保护、严密防伪核验机制与可信交接流程。",
  "home.trustPrivacyTitle": "隐私安全无忧",
  "home.trustPrivacyDesc": "您的电话与私人资料绝不会在社区公共动态中展示。",
  "home.trustProofTitle": "严格防伪核验",
  "home.trustProofDesc": "AI 自动生成专属核验问答，在线下碰面前有效拦截虚假冒领。",
  "home.trustRecoveryTitle": "可信归还网络",
  "home.trustRecoveryDesc": "通过端到端加密沟通、双方双向授权及标准化交接指南确保安全。",
  "home.timelineShowcaseTitle": "AI 行程轨迹推演",
  "home.timelineShowcaseSubtitle": "梳理一天途径的站点与路线，智能推演物品遗失的具体时空范围。",
  "home.timelineTryPrompt": "尝试一个示例：",
  "home.faqTitle": "常见问题解答",
  "home.faqSubtitle": "了解 LINCO 的运作机制及如何守护您的财产安全。",
  "dashboard.title": "市民个人看板",
  "dashboard.subtitle": "管理您名下的登记发布、归还沟通室以及安全隐私设置。",
  "dashboard.tabReports": "我的发布",
  "dashboard.tabClaims": "我的认领",
  "dashboard.tabRecovery": "交接沟通室",
  "dashboard.tabSettings": "个人设置",
  "dashboard.noReports": "您目前尚未发布过任何失物或拾得信息。",
  "dashboard.noClaims": "暂无活跃中的认领申请。",
  "dashboard.noRecovery": "暂无进行中的交接沟通室。",
  "dashboard.accountDetails": "账户基本信息",
  "dashboard.fullName": "姓名",
  "dashboard.phoneNumber": "联系电话",
  "dashboard.city": "所在城市",
  "dashboard.languagePreference": "偏好语言",
  "dashboard.changeLanguage": "更换语言",
  "dashboard.saveSettings": "保存设置",
  "dashboard.settingsSaved": "设置已成功保存更新。",
  "claim.modalTitle": "申请认领此物品",
  "claim.modalSubtitle": "回答防伪核验问题，证明您是该物品的真正所有人。",
  "claim.verifyIdentity": "身份与归属权核验",
  "claim.questionsPrompt": "请根据物品实际情况认真回答下列核验问题：",
  "claim.proofDetails": "独有特征或所有权凭证",
  "claim.proofPlaceholder": "描述内部未公开物件、特定划痕或出厂序列号等...",
  "claim.submitClaim": "提交认领申请",
  "claim.statusPending": "审核核验中",
  "claim.statusApproved": "认领申请已核准",
  "claim.statusRejected": "认领申请已驳回",
  "claim.statusResolved": "已结案物归原主",
  "category.Electronics": "数码电子",
  "category.Documents": "证件卡券",
  "category.Keys": "钥匙门禁",
  "category.Pet": "宠物动物",
  "category.Jewelry": "珠宝首饰与名表",
  "category.Vehicle": "交通工具与配件",
  "category.Clothing": "服装包袋",
  "category.Other": "其他杂物",
  "urgency.Normal": "常规",
  "urgency.Urgent": "紧急",
  "urgency.Medical": "医疗/关键生命物品"
}

JA_269 = {
  "app.tagline": "インドAI落とし物・忘れ物マッチング",
  "app.subtitle": "プライバシーと確かな信頼に基づき、大切な紛失物を持ち主のもとへ。",
  "nav.home": "ホーム",
  "nav.report": "投稿する",
  "nav.feed": "コミュニティ掲示板",
  "nav.matches": "AIマッチング",
  "nav.activity": "アクティビティ",
  "nav.profile": "マイページ",
  "nav.about": "サービス紹介",
  "nav.privacyTrust": "プライバシーと信頼",
  "nav.language": "言語",
  "nav.saathii": "LINCO サポート",
  "common.back": "戻る",
  "common.next": "次へ",
  "common.cancel": "キャンセル",
  "common.save": "保存",
  "common.submit": "送信",
  "common.edit": "編集",
  "common.delete": "削除",
  "common.close": "閉じる",
  "common.loading": "読み込み中...",
  "common.success": "完了",
  "common.error": "エラー",
  "common.search": "検索",
  "common.filter": "絞り込み",
  "common.clear": "クリア",
  "common.optional": "任意",
  "common.required": "必須",
  "common.viewAll": "すべて表示",
  "common.details": "詳細",
  "common.status": "ステータス",
  "lang.heading": "言語を選択してください",
  "lang.subheading": "最も使いやすい言語でLINCOをご利用いただけます。",
  "lang.note": "設定画面からいつでも言語を変更できます。",
  "lang.continue": "LINCOを利用する",
  "lang.searchPlaceholder": "言語を検索（例: 日本語、English、Hindi）...",
  "lang.tabAll": "すべての言語",
  "lang.tabIndian": "インド公用語 (22)",
  "lang.tabInternational": "国際言語",
  "lang.supportedBadge": "完全対応",
  "lang.previewBadge": "プレビュー / ベータ",
  "voice.button": "音声入力",
  "voice.listening": "聞き取り中... お使いの言語で自然にお話しください",
  "voice.processing": "音声を解析しています...",
  "voice.transcribing": "テキストに変換中...",
  "voice.reviewTitle": "音声入力内容の確認",
  "voice.reviewSubtitle": "適用する前に認識された詳細内容をご確認ください。",
  "voice.apply": "内容を反映",
  "voice.retry": "やり直す",
  "voice.cancel": "キャンセル",
  "voice.notSupported": "お使いのブラウザは音声認識に対応していません。",
  "voice.permissionDenied": "マイクの使用が許可されていません。設定で許可してください。",
  "notifications.centerTitle": "通知・アクティビティセンター",
  "notifications.centerSubtitle": "マッチング、所有確認、返還手続きの進行状況。",
  "notifications.readAll": "すべて既読にする",
  "notifications.unread": "未読",
  "notifications.emptyTitle": "新しい通知はありません",
  "notifications.emptySubtitle": "投稿に関する最新情報が届き次第、こちらでお知らせします。",
  "notifications.networkFooter": "LINCO スマート通知ネットワーク",
  "notifications.listingAlert": "新規投稿のお知らせ",
  "notifications.matchFound": "一致する可能性の高い品が見つかりました",
  "notifications.claimReceived": "所有権の確認申請を受信しました",
  "notifications.ownerApproved": "持ち主によって確認されました",
  "notifications.finderVerified": "拾得者によって照合されました",
  "notifications.verificationComplete": "双方の相互照合が完了しました",
  "notifications.newMessage": "新しい保護メッセージ",
  "notifications.trustUpdate": "信頼ステータスが更新されました",
  "notifications.handoverUpdate": "受け渡し状況の更新",
  "notifications.itemReceived": "品物を受け取りました",
  "notifications.itemReunited": "無事に返還が完了しました",
  "notifications.actions.viewMatch": "マッチングを確認",
  "notifications.actions.reviewClaim": "申請内容を確認",
  "notifications.actions.viewVerification": "照合結果を確認",
  "notifications.actions.openChat": "チャットを開く",
  "notifications.actions.confirmHandover": "受け渡しを確認",
  "notifications.actions.viewCase": "事案を見る",
  "notifications.actions.viewDetails": "詳細を見る",
  "notifications.actions.confirmTrust": "信頼を承認",
  "notifications.matchFoundMsg": "投稿に対して高い精度で一致する品物が見つかりました。",
  "notifications.claimReceivedMsg": "この品物に対して所有者申請が提出されました。",
  "notifications.claimApprovedMsg": "あなたの所有者申請が相手方によって確認・承認されました。",
  "notifications.ownerApprovedMsg": "持ち主が自身の紛失物である可能性を確認しました。",
  "notifications.finderVerifiedMsg": "拾得者が申請内容と品物の特徴の一致を確認しました。",
  "notifications.bothApprovedMsg": "双方が一致を確認しました。安全なチャットをご利用いただけます。",
  "notifications.newMessageMsg": "保護されたチャットに新着メッセージがあります。",
  "notifications.trustUpdateMsg": "相互信頼が確認されました！WhatsApp連絡先が表示されます。",
  "notifications.handoverUpdateMsg": "安全な受け渡し手続きが開始されました。",
  "notifications.itemReceivedMsg": "品物の受け取り確認が完了しました。",
  "notifications.itemReunitedMsg": "品物が無事に持ち主へ戻りました！この件は正式に完了しました。",
  "help.notSure": "何を書けばよいかお困りですか？",
  "help.askLinco": "LINCOに相談する",
  "help.listen": "音声ガイダンスを聞く",
  "help.stopListen": "停止",
  "help.itemName": "一般的な品名を入力してください（例: 本革財布、iPhone 14）。",
  "help.location": "最寄り駅や目印となる建物を入力してください。",
  "help.time": "おおよその時間帯を選択してください。",
  "help.description": "色、素材、ブランド、中身の特徴を記載してください。",
  "help.identifying": "本当の持ち主だけが知っている特徴を記載してください。",
  "help.timeline": "一日の行動を順に振り返り、範囲を絞り込みましょう。",
  "report.badge": "スマート届出",
  "report.titleLost": "落とし物を届け出る",
  "report.titleFound": "拾得物を届け出る",
  "report.step1.title": "基本情報",
  "report.step1.typeLost": "物をなくした",
  "report.step1.typeFound": "物を拾った",
  "report.step1.itemName": "品名",
  "report.step1.itemNamePlaceholder": "例: トミーヒルフィガー 黒革財布、iPhone 15 Pro",
  "report.step1.category": "カテゴリー",
  "report.step1.urgency": "緊急度",
  "report.step2.title": "場所",
  "report.step2.location": "場所・最寄り施設",
  "report.step2.locationPlaceholder": "例: 中央駅 2番出口、大学図書館カフェ",
  "report.step2.useGps": "現在地GPSを使用",
  "report.step2.pinMap": "地図上にピン留め",
  "report.step3.title": "日時",
  "report.step3.date": "日付",
  "report.step3.time": "おおよその時間",
  "report.step3.quickToday": "今日",
  "report.step3.quickYesterday": "昨日",
  "report.step3.quickMorning": "午前中",
  "report.step3.quickAfternoon": "昼・午後",
  "report.step3.quickEvening": "夕方",
  "report.step3.quickNight": "夜間",
  "report.step4.title": "特徴・目印",
  "report.step4.desc": "詳しい特徴の説明",
  "report.step4.descPlaceholder": "色、型番、状態などを詳しく入力してください...",
  "report.step4.aiEnhance": "AIで文章を最適化",
  "report.step4.timelineBuilder": "行動ルートアシスタント",
  "report.step4.identifyingMarks": "独自の識別特徴（非公開）",
  "report.step4.identifyingPlaceholder": "例: 右下に小さな傷、NASAステッカー、鍵が2本内包",
  "report.step4.photo": "品物の写真",
  "report.step5.title": "連絡先・プライバシー",
  "report.step5.contact": "電話番号 / WhatsApp番号",
  "report.step5.contactPlaceholder": "10桁の携帯電話番号",
  "report.step5.contactNotice": "電話番号が一般掲示板に公開されることはありません。",
  "report.step6.title": "謝礼とPINコード",
  "report.step6.reward": "謝礼金額（任意）",
  "report.step6.aiReward": "AI推奨謝礼額",
  "report.step6.pin": "4桁のセキュリティPIN",
  "report.step6.pinNotice": "後から内容を変更・終了する際にこのPINが必要になります。",
  "feed.title": "コミュニティ掲示板",
  "feed.subtitle": "お近くの地域で届出された落とし物・拾得物の新着情報。",
  "feed.all": "すべて",
  "feed.lost": "落とし物",
  "feed.found": "拾得物",
  "feed.resolved": "返還済み",
  "feed.listView": "リスト表示",
  "feed.mapView": "地図表示",
  "feed.searchPlaceholder": "品名、場所、カテゴリで検索...",
  "feed.noResults": "該当する届出が見つかりませんでした。",
  "feed.claimButton": "私のものです",
  "feed.foundButton": "拾いました",
  "feed.viewMatches": "一致候補を見る",
  "matches.title": "AIマッチングセンター",
  "matches.subtitle": "落とし物と拾得物の情報をAIが自動照合します。",
  "matches.allMatches": "すべての候補",
  "matches.mutualApprovals": "相互承認済み",
  "matches.pendingVerification": "照合待ち",
  "matches.resolved": "返還完了",
  "matches.threshold": "一致基準値",
  "matches.confidence": "信頼度スコア",
  "matches.score": "スコア",
  "matches.reason": "一致の根拠",
  "matches.lostReport": "紛失の届出",
  "matches.foundReport": "拾得の届出",
  "matches.openChat": "保護チャットを開始",
  "matches.verifyApprove": "照合して承認する",
  "matches.modalTitle": "照合結果の詳細",
  "matches.notFoundTitle": "該当する品が見つかりません",
  "matches.notFoundDesc": "現在、選択された条件に合致する品物はありません。",
  "matches.backToActivity": "アクティビティに戻る",
  "chat.title": "安全な返還チャット",
  "chat.trustButton": "信頼を確認する",
  "chat.whatsapp": "WhatsAppで続ける",
  "chat.handover": "安全な受け渡しを開始",
  "chat.received": "品物を受け取りました",
  "chat.resolved": "対応完了",
  "chat.placeholder": "メッセージを入力...",
  "chat.send": "送信",
  "chat.safetyWarning": "安全上の注意: 受け渡しは必ず人通りの多い公共の場所で行ってください。金銭の事前送金は絶対におやめください。",
  "enhance.modalTitle": "AI文章アシスタント",
  "enhance.aiBadge": "AI生成",
  "enhance.original": "元の説明文",
  "enhance.enhanced": "改善された説明文",
  "enhance.structuredHeading": "抽出された特徴項目",
  "enhance.accept": "この内容を適用する",
  "enhance.edit": "編集する",
  "enhance.tryAgain": "再生成する",
  "enhance.keepOriginal": "元の文を保持する",
  "enhance.suggestions": "アドバイス",
  "timeline.title": "AI行動ルート推定",
  "timeline.subtitle": "立ち寄り先を振り返ることで、紛失場所と時間を絞り込みます。",
  "timeline.userProvided": "入力された情報",
  "timeline.aiInferred": "AIによる推測",
  "timeline.unknown": "不明",
  "timeline.likelyLocation": "最も可能性の高いエリア",
  "timeline.timeWindow": "推定時間帯",
  "timeline.reasoning": "AI推論根拠",
  "timeline.applyLocation": "この場所を適用する",
  "timeline.editEvent": "地点を編集",
  "timeline.addEvent": "地点を追加",
  "home.heroTag": "探す • 照合する • 取り戻す",
  "home.heroTitle1": "あなたのプライバシーを守ります。",
  "home.heroTitle2": "大切な持ち物が戻ってきます。",
  "home.heroSubtitle1": "あなたの大切な物を、決して諦めないでください。",
  "home.heroSubtitle2": "地域の輪と、AIの安心セキュリティ。",
  "home.heroDesc": "1分で紛失・拾得の届出が完了。所有権が確認されるまで、個人情報は厳重に保護されます。",
  "home.reportLost": "紛失物を届け出る",
  "home.reportFound": "拾得物を届け出る",
  "home.findItem": "品物を探す",
  "home.viewMatches": "AI照合を見る",
  "home.startReport": "届出を作成する",
  "home.browseFeed": "掲示板を見る",
  "home.statsTotal": "総届出件数",
  "home.statsLost": "紛失物",
  "home.statsFound": "拾得物",
  "home.statsResolved": "返還済み件数",
  "home.trustTitle": "LINCOが選ばれる理由",
  "home.trustSubtitle": "ゼロ知識プライバシー、厳格な持ち主照合、安全な受け渡し手順。",
  "home.trustPrivacyTitle": "個人情報の保護",
  "home.trustPrivacyDesc": "電話番号や個人情報は掲示板に公開されません。",
  "home.trustProofTitle": "確実な持ち主確認",
  "home.trustProofDesc": "AIが生成する照合質問により、面会前の不正な名乗り出を防ぎます。",
  "home.trustRecoveryTitle": "安全な返還ネットワーク",
  "home.trustRecoveryDesc": "暗号化チャット、相互承認、ガイド付き受け渡しで確実にサポート。",
  "home.timelineShowcaseTitle": "AI行動ルート推論",
  "home.timelineShowcaseSubtitle": "一日の足取りを思い出すことで、紛失場所と時間帯を特定します。",
  "home.timelineTryPrompt": "例を試す:",
  "home.faqTitle": "よくある質問",
  "home.faqSubtitle": "LINCOの仕組みと安心の返還プロセスについて。",
  "dashboard.title": "マイダッシュボード",
  "dashboard.subtitle": "届出の管理、受け渡しチャット、セキュリティ設定。",
  "dashboard.tabReports": "マイ投稿",
  "dashboard.tabClaims": "申請一覧",
  "dashboard.tabRecovery": "返還ルーム",
  "dashboard.tabSettings": "設定",
  "dashboard.noReports": "届出はまだありません。",
  "dashboard.noClaims": "現在進行中の申請はありません。",
  "dashboard.noRecovery": "進行中の返還ルームはありません。",
  "dashboard.accountDetails": "アカウント情報",
  "dashboard.fullName": "氏名",
  "dashboard.phoneNumber": "電話番号",
  "dashboard.city": "都市名",
  "dashboard.languagePreference": "使用言語",
  "dashboard.changeLanguage": "言語を変更",
  "dashboard.saveSettings": "設定を保存",
  "dashboard.settingsSaved": "設定が正常に保存されました。",
  "claim.modalTitle": "この品物の所有者申請をする",
  "claim.modalSubtitle": "照合用の質問に答えて、正当な持ち主であることを証明してください。",
  "claim.verifyIdentity": "持ち主の確認",
  "claim.questionsPrompt": "品物に関する以下の質問に正確にお答えください:",
  "claim.proofDetails": "固有の特徴や証明",
  "claim.proofPlaceholder": "表面には見えない内部の特徴、傷、シリアル番号など...",
  "claim.submitClaim": "申請を送信する",
  "claim.statusPending": "照合審査中",
  "claim.statusApproved": "申請が承認されました",
  "claim.statusRejected": "申請が見送られました",
  "claim.statusResolved": "無事に解決しました",
  "category.Electronics": "家電・デジタル機器",
  "category.Documents": "身分証・書類",
  "category.Keys": "鍵",
  "category.Pet": "ペット",
  "category.Jewelry": "貴金属・時計",
  "category.Vehicle": "乗り物・車両",
  "category.Clothing": "衣類・バッグ",
  "category.Other": "その他",
  "urgency.Normal": "通常",
  "urgency.Urgent": "緊急",
  "urgency.Medical": "医療 / 最重要"
}

KO_269 = {
  "app.tagline": "인도 AI 분실물 및 습득물 센터",
  "app.subtitle": "완벽한 개인정보 보호와 검증된 신뢰를 바탕으로 소중한 물건을 되찾으세요.",
  "nav.home": "홈",
  "nav.report": "등록하기",
  "nav.feed": "커뮤니티 피드",
  "nav.matches": "AI 매칭",
  "nav.activity": "활동 내역",
  "nav.profile": "프로필",
  "nav.about": "소개",
  "nav.privacyTrust": "개인정보 및 보안",
  "nav.language": "언어",
  "nav.saathii": "LINCO 도우미",
  "common.back": "뒤로",
  "common.next": "다음",
  "common.cancel": "취소",
  "common.save": "저장",
  "common.submit": "제출",
  "common.edit": "수정",
  "common.delete": "삭제",
  "common.close": "닫기",
  "common.loading": "불러오는 중...",
  "common.success": "성공",
  "common.error": "오류",
  "common.search": "검색",
  "common.filter": "필터",
  "common.clear": "초기화",
  "common.optional": "선택",
  "common.required": "필수",
  "common.viewAll": "전체 보기",
  "common.details": "상세 정보",
  "common.status": "상태",
  "lang.heading": "사용할 언어를 선택하세요",
  "lang.subheading": "가장 편안한 언어로 LINCO를 이용하세요.",
  "lang.note": "설정에서 언제든지 언어를 변경할 수 있습니다.",
  "lang.continue": "LINCO 시작하기",
  "lang.searchPlaceholder": "언어 검색 (예: 한국어, English, Hindi)...",
  "lang.tabAll": "전체 언어",
  "lang.tabIndian": "인도 공용어 (22)",
  "lang.tabInternational": "국제 언어",
  "lang.supportedBadge": "완전 지원",
  "lang.previewBadge": "미리보기 / 베타",
  "voice.button": "음성 입력",
  "voice.listening": "듣고 있습니다... 편안한 언어로 말씀하세요",
  "voice.processing": "음성을 분석하고 있습니다...",
  "voice.transcribing": "텍스트로 변환 중...",
  "voice.reviewTitle": "음성 입력 내용 검토",
  "voice.reviewSubtitle": "적용하기 전에 인식된 내용을 확인하세요.",
  "voice.apply": "내용 적용",
  "voice.retry": "다시 말하기",
  "voice.cancel": "취소",
  "voice.notSupported": "현재 브라우저에서는 음성 인식을 지원하지 않습니다.",
  "voice.permissionDenied": "마이크 접근 권한이 거부되었습니다. 설정에서 허용해 주세요.",
  "notifications.centerTitle": "활동 및 알림 센터",
  "notifications.centerSubtitle": "실시간 매칭 결과, 소유권 확인 신청 및 반환 진행 현황.",
  "notifications.readAll": "모두 읽음으로 표시",
  "notifications.unread": "읽지 않음",
  "notifications.emptyTitle": "새로운 알림이 없습니다",
  "notifications.emptySubtitle": "등록하신 분실물에 새로운 소식이 있으면 즉시 알려드립니다.",
  "notifications.networkFooter": "LINCO 스마트 알림 네트워크",
  "notifications.listingAlert": "새 게시글 알림",
  "notifications.matchFound": "유력한 매칭 발견",
  "notifications.claimReceived": "소유권 확인 신청 접수",
  "notifications.ownerApproved": "분실자 확인 완료",
  "notifications.finderVerified": "습득자 대조 확인 완료",
  "notifications.verificationComplete": "상호 검증 완료",
  "notifications.newMessage": "새 보안 메시지",
  "notifications.trustUpdate": "신뢰 지수 갱신",
  "notifications.handoverUpdate": "인계 상태 변경",
  "notifications.itemReceived": "물품 수령 완료",
  "notifications.itemReunited": "물품 인계 완료",
  "notifications.actions.viewMatch": "매칭 확인",
  "notifications.actions.reviewClaim": "신청 검토",
  "notifications.actions.viewVerification": "검증 보기",
  "notifications.actions.openChat": "채팅방 열기",
  "notifications.actions.confirmHandover": "인계 확인",
  "notifications.actions.viewCase": "사건 보기",
  "notifications.actions.viewDetails": "상세 보기",
  "notifications.actions.confirmTrust": "신뢰 승인",
  "notifications.matchFoundMsg": "등록하신 물품과 일치 확률이 매우 높은 매칭을 찾았습니다.",
  "notifications.claimReceivedMsg": "이 물품에 대해 소유권 확인 신청이 접수되었습니다.",
  "notifications.claimApprovedMsg": "상대방이 소유권 신청을 확인하고 승인했습니다.",
  "notifications.ownerApprovedMsg": "분실자가 본인의 물건일 가능성이 높다고 확인했습니다.",
  "notifications.finderVerifiedMsg": "습득자가 제출된 답변과 실제 물품의 일치를 확인했습니다.",
  "notifications.bothApprovedMsg": "양측 모두 일치를 확인했습니다. 안전 채팅이 열렸습니다.",
  "notifications.newMessageMsg": "보안 채팅방에 새로운 메시지가 도착했습니다.",
  "notifications.trustUpdateMsg": "상호 신뢰가 확인되었습니다! WhatsApp 연락처가 공개되었습니다.",
  "notifications.handoverUpdateMsg": "안전 인계 절차가 시작되었습니다.",
  "notifications.itemReceivedMsg": "물품 수령이 최종 확인되었습니다.",
  "notifications.itemReunitedMsg": "물건이 안전하게 주인의 품으로 돌아갔습니다! 사건이 종결되었습니다.",
  "help.notSure": "작성이 막막하신가요?",
  "help.askLinco": "LINCO에게 물어보기",
  "help.listen": "도움말 듣기",
  "help.stopListen": "정지",
  "help.itemName": "물품의 일반적인 명칭을 입력하세요 (예: 가죽 지갑, 아이폰 14).",
  "help.location": "가까운 역이나 주요 지형지물을 기재하세요.",
  "help.time": "대략적인 시간대와 하루 중 시점을 선택하세요.",
  "help.description": "색상, 브랜드, 재질 및 내부 물품을 설명하세요.",
  "help.identifying": "진짜 주인만 알고 있는 고유한 특징을 기재하세요.",
  "help.timeline": "오늘의 이동 경로를 되짚어보며 범위를 좁혀보세요.",
  "report.badge": "스마트 등록",
  "report.titleLost": "분실물 등록하기",
  "report.titleFound": "습득물 등록하기",
  "report.step1.title": "기본 정보",
  "report.step1.typeLost": "물건을 잃어버렸어요",
  "report.step1.typeFound": "물건을 주웠어요",
  "report.step1.itemName": "물품명",
  "report.step1.itemNamePlaceholder": "예: 타미힐피거 블랙 가죽 지갑, 아이폰 15 프로",
  "report.step1.category": "카테고리",
  "report.step1.urgency": "긴급도",
  "report.step2.title": "위치 정보",
  "report.step2.location": "위치 또는 랜드마크",
  "report.step2.locationPlaceholder": "예: 중앙역 2번 출구, 대학교 중앙도서관",
  "report.step2.useGps": "현재 GPS 위치 사용",
  "report.step2.pinMap": "지도에 위치 표시",
  "report.step3.title": "날짜 및 시간",
  "report.step3.date": "날짜",
  "report.step3.time": "추정 시간",
  "report.step3.quickToday": "오늘",
  "report.step3.quickYesterday": "어제",
  "report.step3.quickMorning": "아침",
  "report.step3.quickAfternoon": "오후",
  "report.step3.quickEvening": "저녁",
  "report.step3.quickNight": "밤",
  "report.step4.title": "상세 특징 및 단서",
  "report.step4.desc": "상세 설명",
  "report.step4.descPlaceholder": "색상, 모델, 외관 상태 등을 자세히 입력하세요...",
  "report.step4.aiEnhance": "AI로 설명 보완하기",
  "report.step4.timelineBuilder": "이동 경로 도우미",
  "report.step4.identifyingMarks": "고유 식별 특징 (비공개)",
  "report.step4.identifyingPlaceholder": "예: 모서리의 작은 흠집, NASA 스티커, 안쪽에 열쇠 2개",
  "report.step4.photo": "물품 사진",
  "report.step5.title": "연락처 및 개인정보",
  "report.step5.contact": "전화번호 / WhatsApp",
  "report.step5.contactPlaceholder": "10자리 휴대폰 번호",
  "report.step5.contactNotice": "전화번호는 공개 피드에 절대 노출되지 않습니다.",
  "report.step6.title": "사례금 및 비밀번호",
  "report.step6.reward": "사례금 (선택 사항)",
  "report.step6.aiReward": "AI 추천 사례금",
  "report.step6.pin": "4자리 보안 PIN 번호",
  "report.step6.pinNotice": "나중에 내용을 수정하거나 종료할 때 이 PIN 번호가 필요합니다.",
  "feed.title": "커뮤니티 피드",
  "feed.subtitle": "주변 지역에서 등록된 분실물 및 습득물 최신 목록입니다.",
  "feed.all": "전체",
  "feed.lost": "분실물",
  "feed.found": "습득물",
  "feed.resolved": "해결됨",
  "feed.listView": "목록형 보기",
  "feed.mapView": "지도형 보기",
  "feed.searchPlaceholder": "물품명, 위치 또는 카테고리로 검색...",
  "feed.noResults": "검색 조건과 일치하는 내역이 없습니다.",
  "feed.claimButton": "제 물건입니다",
  "feed.foundButton": "제가 주웠습니다",
  "feed.viewMatches": "매칭 확인하기",
  "matches.title": "AI 매칭 센터",
  "matches.subtitle": "분실물과 습득물 간의 의미적 일치도를 자동으로 분석합니다.",
  "matches.allMatches": "전체 매칭",
  "matches.mutualApprovals": "상호 승인 완료",
  "matches.pendingVerification": "검증 대기 중",
  "matches.resolved": "완료된 건",
  "matches.threshold": "일치 기준치",
  "matches.confidence": "신뢰도",
  "matches.score": "점수",
  "matches.reason": "매칭 근거",
  "matches.lostReport": "분실 신고",
  "matches.foundReport": "습득 신고",
  "matches.openChat": "보안 채팅 시작",
  "matches.verifyApprove": "확인 및 승인",
  "matches.modalTitle": "매칭 세부 내역",
  "matches.notFoundTitle": "일치하는 결과가 없습니다",
  "matches.notFoundDesc": "현재 선택된 필터에 맞는 매칭 내역이 없습니다.",
  "matches.backToActivity": "활동 내역으로 돌아가기",
  "chat.title": "안전 인계 채팅",
  "chat.trustButton": "신뢰 확인",
  "chat.whatsapp": "WhatsApp으로 대화",
  "chat.handover": "안전 인계 진행",
  "chat.received": "물건을 받았습니다",
  "chat.resolved": "사건 종료",
  "chat.placeholder": "보안 메시지를 입력하세요...",
  "chat.send": "전송",
  "chat.safetyWarning": "안전 수칙: 반드시 사람이 많은 공공장소에서 만나세요. 사전에 금전을 송금하지 마세요.",
  "enhance.modalTitle": "AI 설명 개선 도우미",
  "enhance.aiBadge": "AI 생성",
  "enhance.original": "기존 설명",
  "enhance.enhanced": "개선된 설명",
  "enhance.structuredHeading": "구조화된 특징",
  "enhance.accept": "개선안 적용",
  "enhance.edit": "직접 수정",
  "enhance.tryAgain": "다시 생성",
  "enhance.keepOriginal": "원문 유지",
  "enhance.suggestions": "권장 사항",
  "timeline.title": "AI 이동 경로 재구성",
  "timeline.subtitle": "오늘의 동선을 되짚어 분실 시간과 위치를 정확히 추정합니다.",
  "timeline.userProvided": "사용자 입력 내용",
  "timeline.aiInferred": "AI 추론 분석",
  "timeline.unknown": "알 수 없음",
  "timeline.likelyLocation": "유력 분실 지역",
  "timeline.timeWindow": "추정 시간대",
  "timeline.reasoning": "AI 판단 근거",
  "timeline.applyLocation": "이 위치 적용하기",
  "timeline.editEvent": "경로 수정",
  "timeline.addEvent": "경로 추가",
  "home.heroTag": "등록 • 검증 • 반환",
  "home.heroTitle1": "신원은 완벽히 보호됩니다.",
  "home.heroTitle2": "물건은 반드시 돌아옵니다.",
  "home.heroSubtitle1": "소중한 물건을 결코 포기하지 마세요.",
  "home.heroSubtitle2": "시민들의 온정과 AI 기술로 지켜지는 신뢰 네트워크.",
  "home.heroDesc": "1분이면 분실물 등록이 완료됩니다. 소유권이 서로 확인될 때까지 개인정보는 안전하게 보호됩니다.",
  "home.reportLost": "분실물 등록",
  "home.reportFound": "습득물 등록",
  "home.findItem": "물건 찾기",
  "home.viewMatches": "AI 매칭 결과 보기",
  "home.startReport": "등록 시작하기",
  "home.browseFeed": "커뮤니티 둘러보기",
  "home.statsTotal": "총 접수 건수",
  "home.statsLost": "분실 신고 건수",
  "home.statsFound": "습득 신고 건수",
  "home.statsResolved": "성공적 반환 건수",
  "home.trustTitle": "LINCO가 특별한 이유",
  "home.trustSubtitle": "영지식 개인정보 보호, 확실한 소유권 증명, 안전한 직거래 가이드.",
  "home.trustPrivacyTitle": "안전한 신원 보호",
  "home.trustPrivacyDesc": "전화번호와 개인정보는 전체 공개 피드에 노출되지 않습니다.",
  "home.trustProofTitle": "확실한 소유권 증명",
  "home.trustProofDesc": "AI가 생성한 비공개 확인 질문을 통해 사기 및 거짓 주장을 사전에 차단합니다.",
  "home.trustRecoveryTitle": "안전 반환 네트워크",
  "home.trustRecoveryDesc": "암호화 채팅, 상호 동의, 단계별 가이드를 통해 안전하게 돌려받으세요.",
  "home.timelineShowcaseTitle": "AI 이동 동선 추적",
  "home.timelineShowcaseSubtitle": "하루 동안 방문한 장소들을 떠올려 분실 위치와 시간을 정밀하게 좁혀보세요.",
  "home.timelineTryPrompt": "예시 체험하기:",
  "home.faqTitle": "자주 묻는 질문",
  "home.faqSubtitle": "LINCO의 안전한 운영 방식과 이용 팁을 확인하세요.",
  "dashboard.title": "시민 대시보드",
  "dashboard.subtitle": "등록한 게시물, 반환 채팅방 및 보안 설정을 관리하세요.",
  "dashboard.tabReports": "내 등록 내역",
  "dashboard.tabClaims": "내 소유권 신청",
  "dashboard.tabRecovery": "반환 채팅방",
  "dashboard.tabSettings": "환경 설정",
  "dashboard.noReports": "아직 등록한 내역이 없습니다.",
  "dashboard.noClaims": "진행 중인 신청이 없습니다.",
  "dashboard.noRecovery": "활성화된 반환 채팅방이 없습니다.",
  "dashboard.accountDetails": "계정 정보",
  "dashboard.fullName": "이름",
  "dashboard.phoneNumber": "전화번호",
  "dashboard.city": "도시",
  "dashboard.languagePreference": "선호 언어",
  "dashboard.changeLanguage": "언어 변경",
  "dashboard.saveSettings": "설정 저장",
  "dashboard.settingsSaved": "설정이 성공적으로 저장되었습니다.",
  "claim.modalTitle": "이 물품에 대한 소유권 신청",
  "claim.modalSubtitle": "확인 질문에 답하여 실제 소유자임을 인증하세요.",
  "claim.verifyIdentity": "소유권 확인 검증",
  "claim.questionsPrompt": "물품에 관한 다음 질문에 성실히 답변해 주세요:",
  "claim.proofDetails": "고유 식별 단서 또는 증거",
  "claim.proofPlaceholder": "외부에 드러나지 않는 내부 특징, 특유의 흠집, 일련번호 등을 입력하세요...",
  "claim.submitClaim": "신청서 제출",
  "claim.statusPending": "검증 대기 중",
  "claim.statusApproved": "소유권 승인됨",
  "claim.statusRejected": "신청 반려됨",
  "claim.statusResolved": "반환 완료 종결",
  "category.Electronics": "전자기기",
  "category.Documents": "신분증 및 서류",
  "category.Keys": "열쇠",
  "category.Pet": "반려동물",
  "category.Jewelry": "귀금속 및 시계",
  "category.Vehicle": "차량 및 이동수단",
  "category.Clothing": "의류 및 가방",
  "category.Other": "기타 물품",
  "urgency.Normal": "일반",
  "urgency.Urgent": "긴급",
  "urgency.Medical": "의료 / 생명 직결"
}
