# -*- coding: utf-8 -*-
"""Authentic Spanish, French, Italian, Portuguese translations for all 269 UI keys."""

ES_269 = {
  "app.tagline": "Objetos Perdidos y Encontrados con IA en India",
  "app.subtitle": "Recuperación de objetos perdidos con privacidad y confianza verificada.",
  "nav.home": "Inicio",
  "nav.report": "Publicar Reporte",
  "nav.feed": "Muro Comunitario",
  "nav.matches": "Coincidencias IA",
  "nav.activity": "Actividad",
  "nav.profile": "Perfil",
  "nav.about": "Acerca de",
  "nav.privacyTrust": "Privacidad y Confianza",
  "nav.language": "Idioma",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Volver",
  "common.next": "Siguiente",
  "common.cancel": "Cancelar",
  "common.save": "Guardar",
  "common.submit": "Enviar",
  "common.edit": "Editar",
  "common.delete": "Eliminar",
  "common.close": "Cerrar",
  "common.loading": "Cargando...",
  "common.success": "Éxito",
  "common.error": "Error",
  "common.search": "Buscar",
  "common.filter": "Filtrar",
  "common.clear": "Limpiar",
  "common.optional": "Opcional",
  "common.required": "Obligatorio",
  "common.viewAll": "Ver Todo",
  "common.details": "Detalles",
  "common.status": "Estado",
  "lang.heading": "Elige tu idioma",
  "lang.subheading": "Usa LINCO en el idioma con el que te sientas más cómodo.",
  "lang.note": "Puedes cambiar tu idioma en cualquier momento desde Configuración.",
  "lang.continue": "Continuar con LINCO",
  "lang.searchPlaceholder": "Buscar idiomas (ej. Español, English, Hindi)...",
  "lang.tabAll": "Todos los Idiomas",
  "lang.tabIndian": "Idiomas de la India (22)",
  "lang.tabInternational": "Idiomas Internacionales",
  "lang.supportedBadge": "Totalmente Compatible",
  "lang.previewBadge": "Vista Previa / Beta",
  "voice.button": "Entrada de Voz",
  "voice.listening": "Escuchando... Habla de forma natural en tu idioma",
  "voice.processing": "Procesando tu nota de voz...",
  "voice.transcribing": "Transcribiendo...",
  "voice.reviewTitle": "Revisar Reporte de Voz",
  "voice.reviewSubtitle": "Verifica los detalles reconocidos antes de aplicarlos.",
  "voice.apply": "Aplicar Detalles",
  "voice.retry": "Reintentar",
  "voice.cancel": "Cancelar",
  "voice.notSupported": "El reconocimiento de voz no es compatible con este navegador.",
  "voice.permissionDenied": "Permiso de micrófono denegado. Por favor, habilítalo.",
  "notifications.centerTitle": "Centro de Actividad",
  "notifications.centerSubtitle": "Coincidencias en tiempo real, reclamos y progreso de recuperación.",
  "notifications.readAll": "Marcar todo como leído",
  "notifications.unread": "No leídos",
  "notifications.emptyTitle": "Sin notificaciones aún",
  "notifications.emptySubtitle": "Te notificaremos cuando haya novedades sobre tus reportes.",
  "notifications.networkFooter": "Red de Notificaciones Inteligentes de LINCO",
  "notifications.listingAlert": "Alerta de Nueva Publicación",
  "notifications.matchFound": "Posible Coincidencia Encontrada",
  "notifications.claimReceived": "Reclamo de Propiedad Recibido",
  "notifications.ownerApproved": "Aprobado por el Propietario",
  "notifications.finderVerified": "Verificado por quien Encontró",
  "notifications.verificationComplete": "Verificación Mutua Completa",
  "notifications.newMessage": "Nuevo Mensaje Seguro",
  "notifications.trustUpdate": "Nivel de Confianza Actualizado",
  "notifications.handoverUpdate": "Actualización de Entrega",
  "notifications.itemReceived": "Objeto Recibido",
  "notifications.itemReunited": "Reunión Exitosa Completa",
  "notifications.actions.viewMatch": "Ver Coincidencia",
  "notifications.actions.reviewClaim": "Revisar Reclamo",
  "notifications.actions.viewVerification": "Ver Verificación",
  "notifications.actions.openChat": "Abrir Chat",
  "notifications.actions.confirmHandover": "Confirmar Entrega",
  "notifications.actions.viewCase": "Ver Caso",
  "notifications.actions.viewDetails": "Ver Detalles",
  "notifications.actions.confirmTrust": "Confirmar Confianza",
  "notifications.matchFoundMsg": "Encontramos una coincidencia de alta confianza para tu reporte.",
  "notifications.claimReceivedMsg": "Alguien ha enviado un reclamo de propiedad sobre este objeto.",
  "notifications.claimApprovedMsg": "Tu reclamo ha sido verificado y aprobado por la otra parte.",
  "notifications.ownerApprovedMsg": "El propietario confirmó que este podría ser su objeto.",
  "notifications.finderVerifiedMsg": "Quien lo encontró confirmó que tu reclamo coincide con el objeto recuperado.",
  "notifications.bothApprovedMsg": "Ambas partes confirmaron la coincidencia. El chat seguro ya está disponible.",
  "notifications.newMessageMsg": "Tienes un nuevo mensaje en el chat seguro.",
  "notifications.trustUpdateMsg": "¡Confianza mutua confirmada! Los datos de contacto de WhatsApp están desbloqueados.",
  "notifications.handoverUpdateMsg": "El proceso de entrega segura ha comenzado.",
  "notifications.itemReceivedMsg": "Se ha confirmado la recepción del objeto.",
  "notifications.itemReunitedMsg": "¡Objeto recuperado con éxito! El caso ha concluido oficialmente.",
  "help.notSure": "¿No estás seguro de qué escribir?",
  "help.askLinco": "Preguntar a LINCO",
  "help.listen": "Escuchar Ayuda",
  "help.stopListen": "Detener",
  "help.itemName": "Nombra el objeto con claridad (ej. Cartera de cuero, iPhone 14).",
  "help.location": "Menciona el punto de referencia o estación más cercana.",
  "help.time": "Indica una hora aproximada y el momento del día.",
  "help.description": "Describe colores, materiales, marcas o contenido interior.",
  "help.identifying": "Menciona detalles que solo el verdadero dueño sabría.",
  "help.timeline": "Reconstruye tu recorrido paso a paso para acotar la zona.",
  "report.badge": "Reporte Inteligente",
  "report.titleLost": "Reportar Objeto Perdido",
  "report.titleFound": "Reportar Objeto Encontrado",
  "report.step1.title": "Información Básica",
  "report.step1.typeLost": "He Perdido Algo",
  "report.step1.typeFound": "He Encontrado Algo",
  "report.step1.itemName": "Nombre del Objeto",
  "report.step1.itemNamePlaceholder": "ej. Cartera de cuero negra Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "Categoría",
  "report.step1.urgency": "Nivel de Urgencia",
  "report.step2.title": "Ubicación",
  "report.step2.location": "Ubicación / Punto de Referencia",
  "report.step2.locationPlaceholder": "ej. Estación de metro Rajiv Chowk, Puerta 2",
  "report.step2.useGps": "Usar GPS Actual",
  "report.step2.pinMap": "Fijar en el Mapa",
  "report.step3.title": "Fecha y Hora",
  "report.step3.date": "Fecha",
  "report.step3.time": "Hora Aproximada",
  "report.step3.quickToday": "Hoy",
  "report.step3.quickYesterday": "Ayer",
  "report.step3.quickMorning": "Mañana",
  "report.step3.quickAfternoon": "Tarde",
  "report.step3.quickEvening": "Atardecer",
  "report.step3.quickNight": "Noche",
  "report.step4.title": "Descripción y Marcas",
  "report.step4.desc": "Descripción Detallada",
  "report.step4.descPlaceholder": "Describe colores, modelo, estado general...",
  "report.step4.aiEnhance": "Mejorar con IA",
  "report.step4.timelineBuilder": "Asistente de Cronología",
  "report.step4.identifyingMarks": "Marcas Identificativas (Privadas)",
  "report.step4.identifyingPlaceholder": "ej. Rayón en la esquina inferior, pegatina de NASA, 2 llaves dentro",
  "report.step4.photo": "Foto del Objeto",
  "report.step5.title": "Contacto y Privacidad",
  "report.step5.contact": "Número de Contacto / WhatsApp",
  "report.step5.contactPlaceholder": "Número de teléfono a 10 dígitos",
  "report.step5.contactNotice": "Tu número nunca se comparte públicamente.",
  "report.step6.title": "Recompensa y PIN",
  "report.step6.reward": "Recompensa Ofrecida (Opcional)",
  "report.step6.aiReward": "Recompensa sugerida por IA",
  "report.step6.pin": "PIN de Seguridad de 4 Dígitos",
  "report.step6.pinNotice": "Usa este PIN para editar o cerrar este reporte en el futuro.",
  "feed.title": "Muro de la Comunidad",
  "feed.subtitle": "Reportes recientes de objetos perdidos y encontrados a tu alrededor.",
  "feed.all": "Todos",
  "feed.lost": "Perdidos",
  "feed.found": "Encontrados",
  "feed.resolved": "Resueltos",
  "feed.listView": "Vista de Lista",
  "feed.mapView": "Vista de Mapa",
  "feed.searchPlaceholder": "Buscar por nombre, categoría o zona...",
  "feed.noResults": "No se encontraron reportes con estos criterios.",
  "feed.claimButton": "Reclamar Propiedad",
  "feed.foundButton": "Lo He Encontrado",
  "feed.viewMatches": "Ver Coincidencias",
  "matches.title": "Centro de Coincidencias con IA",
  "matches.subtitle": "Comparación semántica inteligente entre objetos perdidos y encontrados.",
  "matches.allMatches": "Todas las Coincidencias",
  "matches.mutualApprovals": "Aprobaciones Mutuas",
  "matches.pendingVerification": "Verificación Pendiente",
  "matches.resolved": "Completados",
  "matches.threshold": "Umbral de Coincidencia",
  "matches.confidence": "Nivel de Confianza",
  "matches.score": "Puntuación",
  "matches.reason": "Motivo del Emparejamiento",
  "matches.lostReport": "Reporte de Pérdida",
  "matches.foundReport": "Reporte de Hallazgo",
  "matches.openChat": "Iniciar Chat Seguro",
  "matches.verifyApprove": "Verificar y Aprobar",
  "matches.modalTitle": "Detalle de la Coincidencia",
  "matches.notFoundTitle": "No se encontraron coincidencias",
  "matches.notFoundDesc": "Aún no hay coincidencias con los filtros seleccionados.",
  "matches.backToActivity": "Volver a Actividad",
  "chat.title": "Chat de Recuperación Seguro",
  "chat.trustButton": "Confirmar Confianza",
  "chat.whatsapp": "Continuar en WhatsApp",
  "chat.handover": "Iniciar Entrega Segura",
  "chat.received": "He Recibido mi Objeto",
  "chat.resolved": "Caso Resuelto",
  "chat.placeholder": "Escribe un mensaje seguro...",
  "chat.send": "Enviar",
  "chat.safetyWarning": "Consejo de seguridad: Reúnete siempre en lugares públicos concurridos. Nunca envíes dinero por adelantado.",
  "enhance.modalTitle": "Asistente de Redacción con IA",
  "enhance.aiBadge": "Generado por IA",
  "enhance.original": "Texto Original",
  "enhance.enhanced": "Texto Mejorado",
  "enhance.structuredHeading": "Atributos Extraídos",
  "enhance.accept": "Aplicar Mejoras",
  "enhance.edit": "Editar",
  "enhance.tryAgain": "Reintentar",
  "enhance.keepOriginal": "Conservar Original",
  "enhance.suggestions": "Sugerencias",
  "timeline.title": "Reconstructor de Cronología con IA",
  "timeline.subtitle": "Reconstruye tu recorrido para encontrar el momento y lugar exactos.",
  "timeline.userProvided": "Datos del Usuario",
  "timeline.aiInferred": "Deducido por IA",
  "timeline.unknown": "Desconocido",
  "timeline.likelyLocation": "Zona Más Probable",
  "timeline.timeWindow": "Ventana de Tiempo",
  "timeline.reasoning": "Razonamiento de la IA",
  "timeline.applyLocation": "Usar Esta Ubicación",
  "timeline.editEvent": "Editar Punto",
  "timeline.addEvent": "Agregar Punto",
  "home.heroTag": "Buscar • Verificar • Reunir",
  "home.heroTitle1": "Tu identidad se mantiene privada.",
  "home.heroTitle2": "Tus pertenencias no se pierden.",
  "home.heroSubtitle1": "No pierdas nunca lo que es tuyo.",
  "home.heroSubtitle2": "Impulsado por personas. Protegido por IA.",
  "home.heroDesc": "Publica reportes en menos de un minuto. Tu privacidad permanece protegida hasta que la propiedad se verifique mutuamente.",
  "home.reportLost": "Reportar Objeto Perdido",
  "home.reportFound": "Reportar Objeto Encontrado",
  "home.findItem": "Buscar Objetos",
  "home.viewMatches": "Ver Coincidencias IA",
  "home.startReport": "Comenzar Reporte",
  "home.browseFeed": "Explorar Muro Comunitario",
  "home.statsTotal": "Casos Totales",
  "home.statsLost": "Objetos Perdidos",
  "home.statsFound": "Objetos Encontrados",
  "home.statsResolved": "Objetos Recuperados",
  "home.trustTitle": "Por Qué LINCO es Diferente",
  "home.trustSubtitle": "Construido sobre privacidad de conocimiento cero, verificación rigurosa y restitución segura.",
  "home.trustPrivacyTitle": "Identidad Protegida",
  "home.trustPrivacyDesc": "Tus datos personales y números de teléfono nunca se exhiben en el muro público.",
  "home.trustProofTitle": "Verificación de Propiedad",
  "home.trustProofDesc": "Preguntas secretas generadas por IA previenen reclamos fraudulentos antes de cualquier encuentro.",
  "home.trustRecoveryTitle": "Red Comunitaria Segura",
  "home.trustRecoveryDesc": "Recupera pertenencias mediante chats cifrados, aprobaciones mutuas y entregas guiadas.",
  "home.timelineShowcaseTitle": "Reconstructor de Rutas con IA",
  "home.timelineShowcaseSubtitle": "Recuerda las paradas de tu jornada para estimar con precisión cuándo y dónde ocurrió la pérdida.",
  "home.timelineTryPrompt": "Prueba un ejemplo:",
  "home.faqTitle": "Preguntas Frecuentes",
  "home.faqSubtitle": "Todo lo que necesitas saber sobre el funcionamiento de LINCO.",
  "dashboard.title": "Panel del Ciudadano",
  "dashboard.subtitle": "Administra tus reportes activos, salas de recuperación y ajustes de seguridad.",
  "dashboard.tabReports": "Mis Reportes",
  "dashboard.tabClaims": "Mis Reclamos",
  "dashboard.tabRecovery": "Salas de Recuperación",
  "dashboard.tabSettings": "Configuración",
  "dashboard.noReports": "Aún no has publicado ningún reporte.",
  "dashboard.noClaims": "No tienes reclamos activos.",
  "dashboard.noRecovery": "No hay salas de recuperación en curso.",
  "dashboard.accountDetails": "Detalles de la Cuenta",
  "dashboard.fullName": "Nombre Completo",
  "dashboard.phoneNumber": "Número de Teléfono",
  "dashboard.city": "Ciudad",
  "dashboard.languagePreference": "Idioma Preferido",
  "dashboard.changeLanguage": "Cambiar Idioma",
  "dashboard.saveSettings": "Guardar Cambios",
  "dashboard.settingsSaved": "Configuración guardada correctamente.",
  "claim.modalTitle": "Reclamar Propiedad de este Objeto",
  "claim.modalSubtitle": "Demuestra que eres el dueño legítimo respondiendo a las preguntas de control.",
  "claim.verifyIdentity": "Verificación de Identidad",
  "claim.questionsPrompt": "Por favor, responde a las siguientes preguntas sobre el objeto:",
  "claim.proofDetails": "Detalles o Pruebas de Propiedad",
  "claim.proofPlaceholder": "Describe marcas únicas, contenido oculto o números de serie...",
  "claim.submitClaim": "Enviar Reclamo",
  "claim.statusPending": "Revisión Pendiente",
  "claim.statusApproved": "Reclamo Aprobado",
  "claim.statusRejected": "Reclamo Rechazado",
  "claim.statusResolved": "Caso Resuelto",
  "category.Electronics": "Electrónica",
  "category.Documents": "Documentos",
  "category.Keys": "Llaves",
  "category.Pet": "Mascotas",
  "category.Jewelry": "Joyería",
  "category.Vehicle": "Vehículos",
  "category.Clothing": "Ropa y Accesorios",
  "category.Other": "Otros",
  "urgency.Normal": "Normal",
  "urgency.Urgent": "Urgente",
  "urgency.Medical": "Médico / Crítico"
}

FR_269 = {
  "app.tagline": "Objets Trouvés et Perdus avec IA en Inde",
  "app.subtitle": "Retrouvez vos objets perdus en toute confidentialité et confiance vérifiée.",
  "nav.home": "Accueil",
  "nav.report": "Publier un Signalement",
  "nav.feed": "Fil Communautaire",
  "nav.matches": "Correspondances IA",
  "nav.activity": "Activité",
  "nav.profile": "Profil",
  "nav.about": "À Propos",
  "nav.privacyTrust": "Confidentialité et Sécurité",
  "nav.language": "Langue",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Retour",
  "common.next": "Suivant",
  "common.cancel": "Annuler",
  "common.save": "Enregistrer",
  "common.submit": "Soumettre",
  "common.edit": "Modifier",
  "common.delete": "Supprimer",
  "common.close": "Fermer",
  "common.loading": "Chargement...",
  "common.success": "Succès",
  "common.error": "Erreur",
  "common.search": "Rechercher",
  "common.filter": "Filtrer",
  "common.clear": "Effacer",
  "common.optional": "Facultatif",
  "common.required": "Obligatoire",
  "common.viewAll": "Voir Tout",
  "common.details": "Détails",
  "common.status": "Statut",
  "lang.heading": "Choisissez votre langue",
  "lang.subheading": "Utilisez LINCO dans la langue avec laquelle vous êtes le plus à l'aise.",
  "lang.note": "Vous pouvez modifier votre langue à tout moment dans les Paramètres.",
  "lang.continue": "Continuer avec LINCO",
  "lang.searchPlaceholder": "Rechercher des langues (ex. Français, English, Hindi)...",
  "lang.tabAll": "Toutes les Langues",
  "lang.tabIndian": "Langues Indiennes (22)",
  "lang.tabInternational": "Langues Internationales",
  "lang.supportedBadge": "Entièrement Prise en Charge",
  "lang.previewBadge": "Aperçu / Bêta",
  "voice.button": "Saisie Vocale",
  "voice.listening": "Écoute en cours... Parlez naturellement dans votre langue",
  "voice.processing": "Traitement de votre message vocal...",
  "voice.transcribing": "Transcription...",
  "voice.reviewTitle": "Vérifier le Signalement Vocal",
  "voice.reviewSubtitle": "Vérifiez les informations reconnues avant de les appliquer.",
  "voice.apply": "Appliquer les Détails",
  "voice.retry": "Réessayer",
  "voice.cancel": "Annuler",
  "voice.notSupported": "La reconnaissance vocale n'est pas supportée par votre navigateur.",
  "voice.permissionDenied": "Accès au microphone refusé. Veuillez l'autoriser.",
  "notifications.centerTitle": "Centre d'Activité",
  "notifications.centerSubtitle": "Correspondances en temps réel, réclamations et progression des restitutions.",
  "notifications.readAll": "Tout marquer comme lu",
  "notifications.unread": "Non lus",
  "notifications.emptyTitle": "Aucune notification pour le moment",
  "notifications.emptySubtitle": "Nous vous informerons dès qu'une action concerne vos signalements.",
  "notifications.networkFooter": "Réseau Intelligent de Notifications LINCO",
  "notifications.listingAlert": "Alerte de Nouveau Signalement",
  "notifications.matchFound": "Correspondance Potentielle Trouvée",
  "notifications.claimReceived": "Réclamation de Propriété Reçue",
  "notifications.ownerApproved": "Approuvé par le Propriétaire",
  "notifications.finderVerified": "Vérifié par l'Inventeur",
  "notifications.verificationComplete": "Vérification Mutuelle Terminée",
  "notifications.newMessage": "Nouveau Message Sécurisé",
  "notifications.trustUpdate": "Niveau de Confiance Mis à Jour",
  "notifications.handoverUpdate": "Mise à Jour de Restitution",
  "notifications.itemReceived": "Objet Récupéré",
  "notifications.itemReunited": "Restitution Réussie et Terminée",
  "notifications.actions.viewMatch": "Voir la Correspondance",
  "notifications.actions.reviewClaim": "Examiner la Réclamation",
  "notifications.actions.viewVerification": "Voir la Vérification",
  "notifications.actions.openChat": "Ouvrir le Chat",
  "notifications.actions.confirmHandover": "Confirmer la Restitution",
  "notifications.actions.viewCase": "Voir le Dossier",
  "notifications.actions.viewDetails": "Voir les Détails",
  "notifications.actions.confirmTrust": "Confirmer la Confiance",
  "notifications.matchFoundMsg": "Nous avons trouvé une correspondance à forte probabilité pour votre signalement.",
  "notifications.claimReceivedMsg": "Une personne a soumis une réclamation de propriété sur cet objet.",
  "notifications.claimApprovedMsg": "Votre réclamation a été validée et approuvée par l'autre partie.",
  "notifications.ownerApprovedMsg": "Le propriétaire a confirmé qu'il pourrait s'agir de son objet.",
  "notifications.finderVerifiedMsg": "La personne qui l'a trouvé a confirmé que votre réclamation correspond à l'objet.",
  "notifications.bothApprovedMsg": "Les deux parties ont validé la correspondance. Le chat sécurisé est ouvert.",
  "notifications.newMessageMsg": "Vous avez reçu un nouveau message dans le chat sécurisé.",
  "notifications.trustUpdateMsg": "Confiance mutuelle établie ! Les coordonnées WhatsApp sont déverrouillées.",
  "notifications.handoverUpdateMsg": "Le protocole de remise en main propre sécurisée a commencé.",
  "notifications.itemReceivedMsg": "La bonne réception de l'objet a été confirmée.",
  "notifications.itemReunitedMsg": "Objet restitué avec succès ! Le dossier est officiellement clos.",
  "help.notSure": "Besoin d'aide pour rédiger ?",
  "help.askLinco": "Demander à LINCO",
  "help.listen": "Écouter l'Aide",
  "help.stopListen": "Arrêter",
  "help.itemName": "Indiquez un nom précis (ex. Portefeuille en cuir, iPhone 14 Pro).",
  "help.location": "Mentionnez la station ou le repère le plus proche.",
  "help.time": "Indiquez l'heure approximative et le moment de la journée.",
  "help.description": "Décrivez la couleur, les matériaux, la marque et le contenu.",
  "help.identifying": "Mentionnez un détail secret connu uniquement du vrai propriétaire.",
  "help.timeline": "Reconstituez votre trajet étape par étape pour affiner le lieu.",
  "report.badge": "Signalement Intelligent",
  "report.titleLost": "Signaler un Objet Perdu",
  "report.titleFound": "Signaler un Objet Trouvé",
  "report.step1.title": "Informations Essentielles",
  "report.step1.typeLost": "J'ai Perdu un Objet",
  "report.step1.typeFound": "J'ai Trouvé un Objet",
  "report.step1.itemName": "Nom de l'Objet",
  "report.step1.itemNamePlaceholder": "ex. Portefeuille Tommy Hilfiger noir, iPhone 15 Pro",
  "report.step1.category": "Catégorie",
  "report.step1.urgency": "Degré d'Urgence",
  "report.step2.title": "Localisation",
  "report.step2.location": "Lieu / Point de Repère",
  "report.step2.locationPlaceholder": "ex. Gare Centrale, Quai 4, Cafétéria",
  "report.step2.useGps": "Utiliser la Position GPS Actuelle",
  "report.step2.pinMap": "Pointer sur la Carte",
  "report.step3.title": "Date et Heure",
  "report.step3.date": "Date",
  "report.step3.time": "Heure Approximative",
  "report.step3.quickToday": "Aujourd'hui",
  "report.step3.quickYesterday": "Hier",
  "report.step3.quickMorning": "Matin",
  "report.step3.quickAfternoon": "Après-midi",
  "report.step3.quickEvening": "Soirée",
  "report.step3.quickNight": "Nuit",
  "report.step4.title": "Description et Marques",
  "report.step4.desc": "Description Détaillée",
  "report.step4.descPlaceholder": "Précisez les couleurs, le modèle, l'état général...",
  "report.step4.aiEnhance": "Enrichir avec l'IA",
  "report.step4.timelineBuilder": "Assistant Chronologique",
  "report.step4.identifyingMarks": "Signes Distinctifs (Confidentiels)",
  "report.step4.identifyingPlaceholder": "ex. Rayure sur le coin inférieur, autocollant, 2 clés à l'intérieur",
  "report.step4.photo": "Photo de l'Objet",
  "report.step5.title": "Contact et Confidentialité",
  "report.step5.contact": "Numéro de Téléphone / WhatsApp",
  "report.step5.contactPlaceholder": "Numéro à 10 chiffres",
  "report.step5.contactNotice": "Votre numéro ne sera jamais publié sur le fil public.",
  "report.step6.title": "Récompense et Code PIN",
  "report.step6.reward": "Récompense Proposée (Optionnelle)",
  "report.step6.aiReward": "Récompense suggérée par l'IA",
  "report.step6.pin": "Code PIN de Sécurité à 4 Chiffres",
  "report.step6.pinNotice": "Conservez ce PIN pour modifier ou clore votre signalement ultérieurement.",
  "feed.title": "Fil de la Communauté",
  "feed.subtitle": "Derniers signalements d'objets perdus et trouvés près de chez vous.",
  "feed.all": "Tous",
  "feed.lost": "Perdus",
  "feed.found": "Trouvés",
  "feed.resolved": "Résolus",
  "feed.listView": "Vue Liste",
  "feed.mapView": "Vue Carte",
  "feed.searchPlaceholder": "Rechercher par mot-clé, catégorie ou zone...",
  "feed.noResults": "Aucun signalement ne correspond à vos critères.",
  "feed.claimButton": "C'est le Mien",
  "feed.foundButton": "Je l'ai Trouvé",
  "feed.viewMatches": "Voir les Correspondances",
  "matches.title": "Correspondances par IA",
  "matches.subtitle": "Comparaison sémantique automatisée entre objets perdus et trouvés.",
  "matches.allMatches": "Toutes les Correspondances",
  "matches.mutualApprovals": "Approbations Mutuelles",
  "matches.pendingVerification": "En Attente de Vérification",
  "matches.resolved": "Clôturés",
  "matches.threshold": "Seuil de Similitude",
  "matches.confidence": "Indice de Confiance",
  "matches.score": "Score",
  "matches.reason": "Motif de la Correspondance",
  "matches.lostReport": "Signalement Perdu",
  "matches.foundReport": "Signalement Trouvé",
  "matches.openChat": "Ouvrir le Chat Sécurisé",
  "matches.verifyApprove": "Vérifier et Approuver",
  "matches.modalTitle": "Détail de la Correspondance",
  "matches.notFoundTitle": "Aucune correspondance trouvée",
  "matches.notFoundDesc": "Aucun résultat ne correspond actuellement à vos filtres.",
  "matches.backToActivity": "Retour à l'Activité",
  "chat.title": "Chat Sécurisé de Restitution",
  "chat.trustButton": "Valider la Confiance",
  "chat.whatsapp": "Poursuivre sur WhatsApp",
  "chat.handover": "Organiser la Remise",
  "chat.received": "J'ai Récupéré mon Objet",
  "chat.resolved": "Dossier Clôturé",
  "chat.placeholder": "Rédigez un message sécurisé...",
  "chat.send": "Envoyer",
  "chat.safetyWarning": "Conseil de sécurité : Rencontrez-vous toujours dans un lieu public fréquenté. N'envoyez jamais d'argent d'avance.",
  "enhance.modalTitle": "Amélioration du Texte par IA",
  "enhance.aiBadge": "Généré par IA",
  "enhance.original": "Description Initiale",
  "enhance.enhanced": "Description Améliorée",
  "enhance.structuredHeading": "Informations Structurées",
  "enhance.accept": "Appliquer les Modifications",
  "enhance.edit": "Modifier",
  "enhance.tryAgain": "Régénérer",
  "enhance.keepOriginal": "Garder la Version Initiale",
  "enhance.suggestions": "Recommandations",
  "timeline.title": "Reconstitution Chronologique par IA",
  "timeline.subtitle": "Retracez vos étapes pour localiser le moment et l'endroit précis.",
  "timeline.userProvided": "Données Renseignées",
  "timeline.aiInferred": "Déduit par l'IA",
  "timeline.unknown": "Inconnu",
  "timeline.likelyLocation": "Zone Probable",
  "timeline.timeWindow": "Créneau Horaire",
  "timeline.reasoning": "Raisonnement de l'IA",
  "timeline.applyLocation": "Adopter ce Lieu",
  "timeline.editEvent": "Modifier l'Étape",
  "timeline.addEvent": "Ajouter une Étape",
  "home.heroTag": "Signaler • Vérifier • Restituer",
  "home.heroTitle1": "Votre identité reste protégée.",
  "home.heroTitle2": "Vos biens sont retrouvés.",
  "home.heroSubtitle1": "Ne perdez plus jamais ce qui vous appartient.",
  "home.heroSubtitle2": "Propulsé par la communauté. Sécurisé par l'IA.",
  "home.heroDesc": "Publiez un signalement en une minute. Votre anonymat est garanti jusqu'à vérification complète du propriétaire légitime.",
  "home.reportLost": "Déclarer un Objet Perdu",
  "home.reportFound": "Déclarer un Objet Trouvé",
  "home.findItem": "Chercher un Objet",
  "home.viewMatches": "Voir les Correspondances IA",
  "home.startReport": "Commencer un Signalement",
  "home.browseFeed": "Consulter le Fil Public",
  "home.statsTotal": "Signalements Totaux",
  "home.statsLost": "Objets Perdus",
  "home.statsFound": "Objets Trouvés",
  "home.statsResolved": "Objets Restitués",
  "home.trustTitle": "Pourquoi LINCO Fait la Différence",
  "home.trustSubtitle": "Une plateforme axée sur la confidentialité à divulgation nulle, des preuves rigoureuses et une restitution sécurisée.",
  "home.trustPrivacyTitle": "Identité Protégée",
  "home.trustPrivacyDesc": "Vos numéros et coordonnées ne sont jamais exposés sur le fil public.",
  "home.trustProofTitle": "Preuve de Propriété Rigoureuse",
  "home.trustProofDesc": "Des questions générées par IA écartent les faux réclamants avant toute rencontre.",
  "home.trustRecoveryTitle": "Réseau de Restitution Sûr",
  "home.trustRecoveryDesc": "Coordonnez la restitution via messagerie sécurisée, double validation et protocole de remise.",
  "home.timelineShowcaseTitle": "Reconstitution de Trajet par IA",
  "home.timelineShowcaseSubtitle": "Retracez vos déplacements de la journée pour cibler le lieu probable de la perte.",
  "home.timelineTryPrompt": "Essayez un exemple :",
  "home.faqTitle": "Foire Aux Questions",
  "home.faqSubtitle": "Tout ce que vous devez savoir sur le fonctionnement de LINCO.",
  "dashboard.title": "Espace Citoyen",
  "dashboard.subtitle": "Gérez vos signalements actifs, vos salons de restitution et vos paramètres de sécurité.",
  "dashboard.tabReports": "Mes Signalements",
  "dashboard.tabClaims": "Mes Réclamations",
  "dashboard.tabRecovery": "Salons de Restitution",
  "dashboard.tabSettings": "Paramètres",
  "dashboard.noReports": "Vous n'avez publié aucun signalement pour le moment.",
  "dashboard.noClaims": "Aucune réclamation active pour le moment.",
  "dashboard.noRecovery": "Aucun salon de restitution en cours.",
  "dashboard.accountDetails": "Informations du Compte",
  "dashboard.fullName": "Nom Complet",
  "dashboard.phoneNumber": "Numéro de Téléphone",
  "dashboard.city": "Ville",
  "dashboard.languagePreference": "Langue Préférée",
  "dashboard.changeLanguage": "Changer de Langue",
  "dashboard.saveSettings": "Enregistrer les Préférences",
  "dashboard.settingsSaved": "Préférences enregistrées avec succès.",
  "claim.modalTitle": "Réclamer la Propriété de cet Objet",
  "claim.modalSubtitle": "Prouvez que vous êtes le propriétaire légitime en répondant aux questions de sécurité.",
  "claim.verifyIdentity": "Vérification de Propriété",
  "claim.questionsPrompt": "Veuillez répondre avec précision aux questions suivantes :",
  "claim.proofDetails": "Indices Distinctifs ou Preuves d'Achat",
  "claim.proofPlaceholder": "Décrivez des marques d'usure particulières, le contenu intérieur ou des numéros de série...",
  "claim.submitClaim": "Transmettre la Réclamation",
  "claim.statusPending": "Vérification en Cours",
  "claim.statusApproved": "Réclamation Validée",
  "claim.statusRejected": "Réclamation Rejetée",
  "claim.statusResolved": "Dossier Résolu",
  "category.Electronics": "Appareils Électroniques",
  "category.Documents": "Papiers et Documents",
  "category.Keys": "Clés",
  "category.Pet": "Animaux de Compagnie",
  "category.Jewelry": "Bijoux et Montres",
  "category.Vehicle": "Véhicules",
  "category.Clothing": "Vêtements et Bagagerie",
  "category.Other": "Autres Objets",
  "urgency.Normal": "Normale",
  "urgency.Urgent": "Urgente",
  "urgency.Medical": "Médicale / Critique"
}

IT_269 = {
  "app.tagline": "Oggetti Smarriti e Ritrovati con IA in India",
  "app.subtitle": "Recupero di beni smarriti con privacy e fiducia verificata.",
  "nav.home": "Home",
  "nav.report": "Pubblica Segnalazione",
  "nav.feed": "Bacheca Pubblica",
  "nav.matches": "Corrispondenze IA",
  "nav.activity": "Attività",
  "nav.profile": "Profilo",
  "nav.about": "Informazioni",
  "nav.privacyTrust": "Privacy e Sicurezza",
  "nav.language": "Lingua",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Indietro",
  "common.next": "Avanti",
  "common.cancel": "Annulla",
  "common.save": "Salva",
  "common.submit": "Invia",
  "common.edit": "Modifica",
  "common.delete": "Elimina",
  "common.close": "Chiudi",
  "common.loading": "Caricamento in corso...",
  "common.success": "Operazione riuscita",
  "common.error": "Errore",
  "common.search": "Cerca",
  "common.filter": "Filtra",
  "common.clear": "Cancella",
  "common.optional": "Facoltativo",
  "common.required": "Obbligatorio",
  "common.viewAll": "Mostra Tutto",
  "common.details": "Dettagli",
  "common.status": "Stato",
  "lang.heading": "Scegli la tua lingua",
  "lang.subheading": "Utilizza LINCO nella lingua con cui ti trovi più a tuo agio.",
  "lang.note": "Puoi modificare la lingua in qualsiasi momento dalle Impostazioni.",
  "lang.continue": "Continua con LINCO",
  "lang.searchPlaceholder": "Cerca lingue (es. Italiano, English, Hindi)...",
  "lang.tabAll": "Tutte le Lingue",
  "lang.tabIndian": "Lingue Indiane (22)",
  "lang.tabInternational": "Lingue Internazionali",
  "lang.supportedBadge": "Completamente Supportata",
  "lang.previewBadge": "Anteprima / Beta",
  "voice.button": "Input Vocale",
  "voice.listening": "Ascolto in corso... Parla normalmente nella tua lingua",
  "voice.processing": "Elaborazione della nota vocale...",
  "voice.transcribing": "Trascrizione...",
  "voice.reviewTitle": "Rivedi Segnalazione Vocale",
  "voice.reviewSubtitle": "Verifica le informazioni acquisite prima di applicarle.",
  "voice.apply": "Applica Informazioni",
  "voice.retry": "Riprova",
  "voice.cancel": "Annulla",
  "voice.notSupported": "Il riconoscimento vocale non è supportato da questo browser.",
  "voice.permissionDenied": "Permesso microfono negato. Consenti l'accesso nelle impostazioni.",
  "notifications.centerTitle": "Centro Attività",
  "notifications.centerSubtitle": "Corrispondenze in tempo reale, reclami e stato dei recuperi.",
  "notifications.readAll": "Segna tutti come letti",
  "notifications.unread": "Non letti",
  "notifications.emptyTitle": "Nessuna notifica presente",
  "notifications.emptySubtitle": "Riceverai una notifica quando ci saranno sviluppi sulle tue segnalazioni.",
  "notifications.networkFooter": "Rete Notifiche Intelligenti LINCO",
  "notifications.listingAlert": "Nuova Segnalazione Rilevata",
  "notifications.matchFound": "Trovata Corrispondenza Potenziale",
  "notifications.claimReceived": "Ricevuto Reclamo di Proprietà",
  "notifications.ownerApproved": "Confermato dal Proprietario",
  "notifications.finderVerified": "Verificato da chi ha Ritrovato",
  "notifications.verificationComplete": "Verifica Reciproca Conclusa",
  "notifications.newMessage": "Nuovo Messaggio Sicuro",
  "notifications.trustUpdate": "Livello di Fiducia Aggiornato",
  "notifications.handoverUpdate": "Aggiornamento Consegna",
  "notifications.itemReceived": "Oggetto Consegnato",
  "notifications.itemReunited": "Restituzione Completata con Successo",
  "notifications.actions.viewMatch": "Vedi Corrispondenza",
  "notifications.actions.reviewClaim": "Esamina Reclamo",
  "notifications.actions.viewVerification": "Vedi Verifica",
  "notifications.actions.openChat": "Apri Chat",
  "notifications.actions.confirmHandover": "Conferma Consegna",
  "notifications.actions.viewCase": "Visualizza Caso",
  "notifications.actions.viewDetails": "Visualizza Dettagli",
  "notifications.actions.confirmTrust": "Conferma Fiducia",
  "notifications.matchFoundMsg": "Abbiamo trovato una corrispondenza ad alta affidabilità per la tua segnalazione.",
  "notifications.claimReceivedMsg": "È stato inviato un reclamo di proprietà per questo oggetto.",
  "notifications.claimApprovedMsg": "Il tuo reclamo è stato verificato e approvato dalla controparte.",
  "notifications.ownerApprovedMsg": "Il proprietario ha confermato che questo potrebbe essere il suo oggetto.",
  "notifications.finderVerifiedMsg": "Chi ha trovato l'oggetto ha confermato che il tuo reclamo corrisponde all'oggetto recuperato.",
  "notifications.bothApprovedMsg": "Entrambe le parti hanno approvato. La chat protetta è ora attiva.",
  "notifications.newMessageMsg": "Hai un nuovo messaggio nella chat protetta.",
  "notifications.trustUpdateMsg": "Fiducia reciproca confermata! I recapiti WhatsApp sono stati sbloccati.",
  "notifications.handoverUpdateMsg": "La procedura per la consegna sicura è stata avviata.",
  "notifications.itemReceivedMsg": "La ricezione dell'oggetto è stata confermata.",
  "notifications.itemReunitedMsg": "Oggetto restituito con successo! La pratica è ufficialmente chiusa.",
  "help.notSure": "Non sai cosa inserire?",
  "help.askLinco": "Chiedi a LINCO",
  "help.listen": "Ascolta Aiuto",
  "help.stopListen": "Ferma",
  "help.itemName": "Indica il nome comune dell'oggetto (es. Portafoglio in pelle, iPhone 14).",
  "help.location": "Menziona la fermata o il punto di riferimento più vicino.",
  "help.time": "Specifica l'orario approssimativo e la fascia del giorno.",
  "help.description": "Descrivi colori, materiali, marca o contenuto interno.",
  "help.identifying": "Indica un dettaglio segreto noto solo al legittimo proprietario.",
  "help.timeline": "Ricostruisci i tuoi spostamenti per individuare la zona precisa.",
  "report.badge": "Modulo Intelligente",
  "report.titleLost": "Segnala Oggetto Smarrito",
  "report.titleFound": "Segnala Oggetto Trovato",
  "report.step1.title": "Dati Principali",
  "report.step1.typeLost": "Ho Smarrito un Oggetto",
  "report.step1.typeFound": "Ho Trovato un Oggetto",
  "report.step1.itemName": "Nome dell'Oggetto",
  "report.step1.itemNamePlaceholder": "es. Portafoglio in pelle nero Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "Categoria",
  "report.step1.urgency": "Livello di Urgenza",
  "report.step2.title": "Posizione",
  "report.step2.location": "Luogo o Punto di Riferimento",
  "report.step2.locationPlaceholder": "es. Stazione Centrale, Binario 3, Ingresso principale",
  "report.step2.useGps": "Rileva Posizione GPS Attuale",
  "report.step2.pinMap": "Posiziona Punto sulla Mappa",
  "report.step3.title": "Data e Ora",
  "report.step3.date": "Data",
  "report.step3.time": "Ora Approssimativa",
  "report.step3.quickToday": "Oggi",
  "report.step3.quickYesterday": "Ieri",
  "report.step3.quickMorning": "Mattina",
  "report.step3.quickAfternoon": "Pomeriggio",
  "report.step3.quickEvening": "Sera",
  "report.step3.quickNight": "Notte",
  "report.step4.title": "Descrizione e Segni Particolari",
  "report.step4.desc": "Descrizione Dettagliata",
  "report.step4.descPlaceholder": "Descrivi colori, marca, modello e condizioni generali...",
  "report.step4.aiEnhance": "Migliora con IA",
  "report.step4.timelineBuilder": "Assistente Cronologia",
  "report.step4.identifyingMarks": "Segni Particolari (Riservati)",
  "report.step4.identifyingPlaceholder": "es. Graffio sul retro, adesivo NASA, 2 chiavi all'interno",
  "report.step4.photo": "Foto dell'Oggetto",
  "report.step5.title": "Contatti e Riservatezza",
  "report.step5.contact": "Numero di Telefono o WhatsApp",
  "report.step5.contactPlaceholder": "Numero a 10 cifre",
  "report.step5.contactNotice": "Il tuo numero non sarà mai reso visibile pubblicamente.",
  "report.step6.title": "Ricompensa e PIN",
  "report.step6.reward": "Ricompensa Proposta (Facoltativa)",
  "report.step6.aiReward": "Ricompensa suggerita dall'IA",
  "report.step6.pin": "PIN di Sicurezza a 4 Cifre",
  "report.step6.pinNotice": "Conserva questo PIN per modificare o rimuovere la segnalazione in seguito.",
  "feed.title": "Bacheca della Comunità",
  "feed.subtitle": "Segnalazioni recenti di oggetti smarriti e ritrovati nella tua zona.",
  "feed.all": "Tutti",
  "feed.lost": "Smarriti",
  "feed.found": "Trovati",
  "feed.resolved": "Riconsegnati",
  "feed.listView": "Vista Elenco",
  "feed.mapView": "Vista Mappa",
  "feed.searchPlaceholder": "Cerca per oggetto, categoria o località...",
  "feed.noResults": "Nessuna segnalazione corrisponde ai criteri impostati.",
  "feed.claimButton": "È Mio",
  "feed.foundButton": "L'ho Trovato",
  "feed.viewMatches": "Mostra Corrispondenze",
  "matches.title": "Corrispondenze Intelligenti IA",
  "matches.subtitle": "Confronto semantico automatico tra oggetti persi e trovati.",
  "matches.allMatches": "Tutte le Corrispondenze",
  "matches.mutualApprovals": "Approvazioni Reciproche",
  "matches.pendingVerification": "In Attesa di Verifica",
  "matches.resolved": "Risolti",
  "matches.threshold": "Soglia di Rilevamento",
  "matches.confidence": "Livello di Affidabilità",
  "matches.score": "Punteggio",
  "matches.reason": "Motivazione Corrispondenza",
  "matches.lostReport": "Segnalazione Smarrimento",
  "matches.foundReport": "Segnalazione Ritrovamento",
  "matches.openChat": "Apri Chat Protetta",
  "matches.verifyApprove": "Verifica e Approva",
  "matches.modalTitle": "Dettaglio Corrispondenza",
  "matches.notFoundTitle": "Nessuna corrispondenza trovata",
  "matches.notFoundDesc": "Al momento non risultano corrispondenze con i filtri attuali.",
  "matches.backToActivity": "Torna ad Attività",
  "chat.title": "Chat Protetta di Recupero",
  "chat.trustButton": "Conferma Fiducia",
  "chat.whatsapp": "Continua su WhatsApp",
  "chat.handover": "Avvia Consegna Sicura",
  "chat.received": "Ho Ricevuto il Mio Oggetto",
  "chat.resolved": "Caso Concluso",
  "chat.placeholder": "Scrivi un messaggio protetto...",
  "chat.send": "Invia",
  "chat.safetyWarning": "Sicurezza: Incontrati sempre in luoghi pubblici e frequentati. Non inviare mai denaro in anticipo.",
  "enhance.modalTitle": "Miglioramento Testo con IA",
  "enhance.aiBadge": "Generato da IA",
  "enhance.original": "Descrizione Originale",
  "enhance.enhanced": "Descrizione Ottimizzata",
  "enhance.structuredHeading": "Caratteristiche Estratte",
  "enhance.accept": "Applica Modifiche",
  "enhance.edit": "Modifica",
  "enhance.tryAgain": "Rigenera",
  "enhance.keepOriginal": "Mantieni Originale",
  "enhance.suggestions": "Suggerimenti",
  "timeline.title": "Ricostruzione Cronologica con IA",
  "timeline.subtitle": "Ripercorri i tuoi spostamenti per risalire a orario e luogo precisi.",
  "timeline.userProvided": "Dati Inseriti",
  "timeline.aiInferred": "Dedotto dall'IA",
  "timeline.unknown": "Sconosciuto",
  "timeline.likelyLocation": "Zona più Probabile",
  "timeline.timeWindow": "Intervallo Orario",
  "timeline.reasoning": "Logica IA",
  "timeline.applyLocation": "Applica Questa Posizione",
  "timeline.editEvent": "Modifica Tappa",
  "timeline.addEvent": "Aggiungi Tappa",
  "home.heroTag": "Trova • Verifica • Riconsegna",
  "home.heroTitle1": "La tua identità rimane protetta.",
  "home.heroTitle2": "I tuoi oggetti ritornano da te.",
  "home.heroSubtitle1": "Non perdere mai ciò che ti appartiene.",
  "home.heroSubtitle2": "Alimentato dalle persone. Protetto dall'IA.",
  "home.heroDesc": "Segnala oggetti smarriti o trovati in meno di un minuto. La privacy è tutelata fino all'avvenuta verifica della proprietà.",
  "home.reportLost": "Segnala Oggetto Smarrito",
  "home.reportFound": "Segnala Oggetto Trovato",
  "home.findItem": "Cerca Oggetti",
  "home.viewMatches": "Vedi Corrispondenze IA",
  "home.startReport": "Inizia Segnalazione",
  "home.browseFeed": "Esplora Bacheca",
  "home.statsTotal": "Casi Totali",
  "home.statsLost": "Oggetti Smarriti",
  "home.statsFound": "Oggetti Trovati",
  "home.statsResolved": "Oggetti Riconsegnati",
  "home.trustTitle": "Perché LINCO è Diverso",
  "home.trustSubtitle": "Basato su privacy a conoscenza zero, verifiche sicure della proprietà e restituzioni protette.",
  "home.trustPrivacyTitle": "Identità Protetta",
  "home.trustPrivacyDesc": "I tuoi dati di contatto personali non vengono mai esposti sulla bacheca pubblica.",
  "home.trustProofTitle": "Verifica Rigorosa della Proprietà",
  "home.trustProofDesc": "Domande di controllo create dall'IA sventano falsi reclami prima di qualsiasi incontro.",
  "home.trustRecoveryTitle": "Rete di Recupero Protetta",
  "home.trustRecoveryDesc": "Recupera i tuoi beni tramite chat protetta, approvazioni bilaterali e consegna assistita.",
  "home.timelineShowcaseTitle": "Ricostruttore di Tragitto con IA",
  "home.timelineShowcaseSubtitle": "Ricostruisci la tua giornata per risalire con precisione a orario e zona dello smarrimento.",
  "home.timelineTryPrompt": "Prova un esempio:",
  "home.faqTitle": "Domande Frequenti",
  "home.faqSubtitle": "Scopri come funziona LINCO e come ti aiuta a ritrovare i tuoi beni.",
  "dashboard.title": "Pannello Utente",
  "dashboard.subtitle": "Gestisci le tue segnalazioni, le stanze di recupero e le preferenze di sicurezza.",
  "dashboard.tabReports": "Le Mie Segnalazioni",
  "dashboard.tabClaims": "I Miei Reclami",
  "dashboard.tabRecovery": "Stanze di Recupero",
  "dashboard.tabSettings": "Impostazioni",
  "dashboard.noReports": "Non hai ancora pubblicato nessuna segnalazione.",
  "dashboard.noClaims": "Nessun reclamo attivo al momento.",
  "dashboard.noRecovery": "Nessuna stanza di recupero attiva.",
  "dashboard.accountDetails": "Informazioni Account",
  "dashboard.fullName": "Nome Completo",
  "dashboard.phoneNumber": "Numero di Telefono",
  "dashboard.city": "Città",
  "dashboard.languagePreference": "Lingua Preferita",
  "dashboard.changeLanguage": "Cambia Lingua",
  "dashboard.saveSettings": "Salva Impostazioni",
  "dashboard.settingsSaved": "Impostazioni salvate con successo.",
  "claim.modalTitle": "Reclama Proprietà di Questo Oggetto",
  "claim.modalSubtitle": "Dimostra di essere il legittimo proprietario rispondendo alle domande di verifica.",
  "claim.verifyIdentity": "Verifica dell'Identità",
  "claim.questionsPrompt": "Rispondi con attenzione alle seguenti domande:",
  "claim.proofDetails": "Dettagli o Segni Riservati",
  "claim.proofPlaceholder": "Descrivi segni d'usura, dettagli interni o codici seriali...",
  "claim.submitClaim": "Invia Reclamo",
  "claim.statusPending": "Verifica in Corso",
  "claim.statusApproved": "Reclamo Accolto",
  "claim.statusRejected": "Reclamo Rifiutato",
  "claim.statusResolved": "Caso Concluso",
  "category.Electronics": "Elettronica",
  "category.Documents": "Documenti",
  "category.Keys": "Chiavi",
  "category.Pet": "Animali Domestici",
  "category.Jewelry": "Gioielli e Orologi",
  "category.Vehicle": "Veicoli",
  "category.Clothing": "Abbigliamento e Borse",
  "category.Other": "Altri Oggetti",
  "urgency.Normal": "Normale",
  "urgency.Urgent": "Urgente",
  "urgency.Medical": "Sanitario / Critico"
}

PT_269 = {
  "app.tagline": "Achados e Perdidos com IA na Índia",
  "app.subtitle": "Recuperação de itens perdidos com privacidade e confiança verificada.",
  "nav.home": "Início",
  "nav.report": "Publicar Relato",
  "nav.feed": "Mural da Comunidade",
  "nav.matches": "Correspondências IA",
  "nav.activity": "Atividade",
  "nav.profile": "Perfil",
  "nav.about": "Sobre",
  "nav.privacyTrust": "Privacidade e Segurança",
  "nav.language": "Idioma",
  "nav.saathii": "LINCO Saathii",
  "common.back": "Voltar",
  "common.next": "Próximo",
  "common.cancel": "Cancelar",
  "common.save": "Salvar",
  "common.submit": "Enviar",
  "common.edit": "Editar",
  "common.delete": "Excluir",
  "common.close": "Fechar",
  "common.loading": "Carregando...",
  "common.success": "Sucesso",
  "common.error": "Erro",
  "common.search": "Buscar",
  "common.filter": "Filtrar",
  "common.clear": "Limpar",
  "common.optional": "Opcional",
  "common.required": "Obrigatório",
  "common.viewAll": "Ver Tudo",
  "common.details": "Detalhes",
  "common.status": "Status",
  "lang.heading": "Escolha o seu idioma",
  "lang.subheading": "Use o LINCO no idioma com o qual você se sente mais confortável.",
  "lang.note": "Você pode alterar seu idioma a qualquer momento nas Configurações.",
  "lang.continue": "Continuar com o LINCO",
  "lang.searchPlaceholder": "Buscar idiomas (ex.: Português, English, Hindi)...",
  "lang.tabAll": "Todos os Idiomas",
  "lang.tabIndian": "Idiomas Indianos (22)",
  "lang.tabInternational": "Idiomas Internacionais",
  "lang.supportedBadge": "Suporte Completo",
  "lang.previewBadge": "Pré-visualização / Beta",
  "voice.button": "Entrada de Voz",
  "voice.listening": "Ouvindo... Fale naturalmente em seu idioma",
  "voice.processing": "Processando sua nota de voz...",
  "voice.transcribing": "Transcrevendo...",
  "voice.reviewTitle": "Revisar Relato por Voz",
  "voice.reviewSubtitle": "Confira as informações identificadas antes de aplicar.",
  "voice.apply": "Aplicar Detalhes",
  "voice.retry": "Tentar Novamente",
  "voice.cancel": "Cancelar",
  "voice.notSupported": "O reconhecimento de voz não é compatível com este navegador.",
  "voice.permissionDenied": "Permissão de microfone negada. Por favor, habilite o acesso.",
  "notifications.centerTitle": "Central de Atividades",
  "notifications.centerSubtitle": "Correspondências em tempo real, reivindicações e progresso da devolução.",
  "notifications.readAll": "Marcar tudo como lido",
  "notifications.unread": "Não lidas",
  "notifications.emptyTitle": "Nenhuma notificação por enquanto",
  "notifications.emptySubtitle": "Avisaremos você assim que houver atualizações sobre seus itens.",
  "notifications.networkFooter": "Rede de Notificações Inteligentes LINCO",
  "notifications.listingAlert": "Novo Relato Publicado",
  "notifications.matchFound": "Correspondência em Potencial Encontrada",
  "notifications.claimReceived": "Reivindicação de Posse Recebida",
  "notifications.ownerApproved": "Confirmado pelo Dono",
  "notifications.finderVerified": "Verificado por quem Encontrou",
  "notifications.verificationComplete": "Verificação Mútua Concluída",
  "notifications.newMessage": "Nova Mensagem Segura",
  "notifications.trustUpdate": "Nível de Confiança Atualizado",
  "notifications.handoverUpdate": "Atualização sobre a Entrega",
  "notifications.itemReceived": "Item Recebido com Sucesso",
  "notifications.itemReunited": "Devolução Concluída com Sucesso",
  "notifications.actions.viewMatch": "Ver Correspondência",
  "notifications.actions.reviewClaim": "Analisar Reivindicação",
  "notifications.actions.viewVerification": "Ver Verificação",
  "notifications.actions.openChat": "Abrir Chat",
  "notifications.actions.confirmHandover": "Confirmar Entrega",
  "notifications.actions.viewCase": "Visualizar Caso",
  "notifications.actions.viewDetails": "Visualizar Detalhes",
  "notifications.actions.confirmTrust": "Confirmar Confiança",
  "notifications.matchFoundMsg": "Localizamos uma correspondência de alta probabilidade para seu relato.",
  "notifications.claimReceivedMsg": "Alguém enviou uma reivindicação de posse para este item.",
  "notifications.claimApprovedMsg": "Sua reivindicação foi conferida e aprovada pela outra parte.",
  "notifications.ownerApprovedMsg": "O proprietário confirmou que este item pode ser dele.",
  "notifications.finderVerifiedMsg": "Quem encontrou o item confirmou que suas respostas coincidem com o objeto.",
  "notifications.bothApprovedMsg": "Ambas as partes confirmaram a correspondência. O chat seguro já está ativo.",
  "notifications.newMessageMsg": "Você recebeu uma nova mensagem no chat protegido.",
  "notifications.trustUpdateMsg": "Confiança mútua confirmada! Os dados de contato no WhatsApp foram liberados.",
  "notifications.handoverUpdateMsg": "O processo de entrega segura foi iniciado.",
  "notifications.itemReceivedMsg": "A recepção do item foi confirmada com sucesso.",
  "notifications.itemReunitedMsg": "Item devolvido com sucesso! O caso foi oficialmente encerrado.",
  "help.notSure": "Em dúvida sobre o que escrever?",
  "help.askLinco": "Perguntar ao LINCO",
  "help.listen": "Ouvir Instruções",
  "help.stopListen": "Parar",
  "help.itemName": "Nomeie o item com clareza (ex.: Carteira de couro, iPhone 14 Pro).",
  "help.location": "Mencione a estação ou ponto de referência mais próximo.",
  "help.time": "Informe um horário aproximado e o período do dia.",
  "help.description": "Descreva cores, marcas, material e conteúdo interno.",
  "help.identifying": "Mencione um detalhe secreto conhecido apenas pelo verdadeiro dono.",
  "help.timeline": "Reconstrua o trajeto passo a passo para delimitar a área.",
  "report.badge": "Relato Inteligente",
  "report.titleLost": "Relatar Item Perdido",
  "report.titleFound": "Relatar Item Encontrado",
  "report.step1.title": "Informações Básicas",
  "report.step1.typeLost": "Perdi um Objeto",
  "report.step1.typeFound": "Encontrei um Objeto",
  "report.step1.itemName": "Nome do Item",
  "report.step1.itemNamePlaceholder": "ex.: Carteira de couro preta Tommy Hilfiger, iPhone 15 Pro",
  "report.step1.category": "Categoria",
  "report.step1.urgency": "Grau de Urgência",
  "report.step2.title": "Localização",
  "report.step2.location": "Local ou Ponto de Referência",
  "report.step2.locationPlaceholder": "ex.: Estação Central, Plataforma 2, Praça de Alimentação",
  "report.step2.useGps": "Usar Localização GPS Atual",
  "report.step2.pinMap": "Marcar no Mapa",
  "report.step3.title": "Data e Horário",
  "report.step3.date": "Data",
  "report.step3.time": "Horário Estimado",
  "report.step3.quickToday": "Hoje",
  "report.step3.quickYesterday": "Ontem",
  "report.step3.quickMorning": "Manhã",
  "report.step3.quickAfternoon": "Tarde",
  "report.step3.quickEvening": "Fim de Tarde",
  "report.step3.quickNight": "Noite",
  "report.step4.title": "Descrição e Marcas",
  "report.step4.desc": "Descrição Detalhada",
  "report.step4.descPlaceholder": "Informe cores, marca, modelo e detalhes visuais...",
  "report.step4.aiEnhance": "Aprimorar com IA",
  "report.step4.timelineBuilder": "Assistente de Trajeto",
  "report.step4.identifyingMarks": "Marcas Particulares (Privadas)",
  "report.step4.identifyingPlaceholder": "ex.: Pequeno arranhão no canto, adesivo da NASA, 2 chaves dentro",
  "report.step4.photo": "Foto do Item",
  "report.step5.title": "Contato e Privacidade",
  "report.step5.contact": "Telefone ou WhatsApp",
  "report.step5.contactPlaceholder": "Número com DDD ou 10 dígitos",
  "report.step5.contactNotice": "Seu número nunca é exibido publicamente no mural.",
  "report.step6.title": "Recompensa e Senha PIN",
  "report.step6.reward": "Recompensa Oferecida (Opcional)",
  "report.step6.aiReward": "Recompensa sugerida por IA",
  "report.step6.pin": "PIN de Segurança de 4 Dígitos",
  "report.step6.pinNotice": "Guarde este PIN para alterar ou encerrar seu relato no futuro.",
  "feed.title": "Mural da Comunidade",
  "feed.subtitle": "Relatos recentes de itens perdidos e achados na sua região.",
  "feed.all": "Todos",
  "feed.lost": "Perdidos",
  "feed.found": "Achados",
  "feed.resolved": "Resolvidos",
  "feed.listView": "Visualização em Lista",
  "feed.mapView": "Visualização em Mapa",
  "feed.searchPlaceholder": "Buscar por nome, categoria ou bairro...",
  "feed.noResults": "Nenhum relato encontrado com esses critérios.",
  "feed.claimButton": "É Meu",
  "feed.foundButton": "Eu Encontrei",
  "feed.viewMatches": "Ver Correspondências",
  "matches.title": "Correspondências por IA",
  "matches.subtitle": "Cruzamento semântico automatizado entre itens perdidos e achados.",
  "matches.allMatches": "Todas as Correspondências",
  "matches.mutualApprovals": "Aprovações Mútuas",
  "matches.pendingVerification": "Verificação Pendente",
  "matches.resolved": "Encerrados",
  "matches.threshold": "Limite de Correspondência",
  "matches.confidence": "Nível de Confiança",
  "matches.score": "Pontuação",
  "matches.reason": "Motivo da Correspondência",
  "matches.lostReport": "Relato de Perda",
  "matches.foundReport": "Relato de Achado",
  "matches.openChat": "Abrir Chat Seguro",
  "matches.verifyApprove": "Verificar e Aprovar",
  "matches.modalTitle": "Detalhes da Correspondência",
  "matches.notFoundTitle": "Nenhuma correspondência localizada",
  "matches.notFoundDesc": "Ainda não encontramos correspondências para os filtros ativos.",
  "matches.backToActivity": "Voltar para Atividade",
  "chat.title": "Chat Seguro de Recuperação",
  "chat.trustButton": "Confirmar Confiança",
  "chat.whatsapp": "Conversar no WhatsApp",
  "chat.handover": "Agendar Entrega Segura",
  "chat.received": "Recebi Meu Item",
  "chat.resolved": "Caso Solucionado",
  "chat.placeholder": "Escreva uma mensagem segura...",
  "chat.send": "Enviar",
  "chat.safetyWarning": "Dica de segurança: Sempre marque encontros em locais públicos e movimentados. Nunca transfira dinheiro adiantado.",
  "enhance.modalTitle": "Aprimoramento de Texto com IA",
  "enhance.aiBadge": "Gerado por IA",
  "enhance.original": "Descrição Inicial",
  "enhance.enhanced": "Descrição Aprimorada",
  "enhance.structuredHeading": "Atributos Estruturados",
  "enhance.accept": "Aceitar Alterações",
  "enhance.edit": "Editar",
  "enhance.tryAgain": "Gerar Novamente",
  "enhance.keepOriginal": "Manter Versão Original",
  "enhance.suggestions": "Recomendações",
  "timeline.title": "Reconstrução Cronológica com IA",
  "timeline.subtitle": "Refaça seus passos para identificar onde e quando a perda ocorreu.",
  "timeline.userProvided": "Informado pelo Usuário",
  "timeline.aiInferred": "Deduzido por IA",
  "timeline.unknown": "Desconhecido",
  "timeline.likelyLocation": "Local Provável",
  "timeline.timeWindow": "Janela de Horário",
  "timeline.reasoning": "Raciocínio da IA",
  "timeline.applyLocation": "Usar Esta Localização",
  "timeline.editEvent": "Editar Etapa",
  "timeline.addEvent": "Adicionar Etapa",
  "home.heroTag": "Buscar • Verificar • Devolver",
  "home.heroTitle1": "Sua identidade fica protegida.",
  "home.heroTitle2": "Seus pertences voltam para você.",
  "home.heroSubtitle1": "Nunca mais perca o que é seu.",
  "home.heroSubtitle2": "Movido pela comunidade. Protegido por IA.",
  "home.heroDesc": "Cadastre itens perdidos ou achados em um minuto. Sua privacidade é preservada até a validação do verdadeiro proprietário.",
  "home.reportLost": "Relatar Item Perdido",
  "home.reportFound": "Relatar Item Encontrado",
  "home.findItem": "Buscar Itens",
  "home.viewMatches": "Ver Correspondências IA",
  "home.startReport": "Iniciar Relato",
  "home.browseFeed": "Explorar Mural",
  "home.statsTotal": "Total de Relatos",
  "home.statsLost": "Itens Perdidos",
  "home.statsFound": "Itens Encontrados",
  "home.statsResolved": "Itens Recuperados",
  "home.trustTitle": "Por Que o LINCO É Diferente",
  "home.trustSubtitle": "Criado com foco em privacidade de conhecimento zero, verificação justa de posse e entrega segura.",
  "home.trustPrivacyTitle": "Identidade Resguardada",
  "home.trustPrivacyDesc": "Seus dados de contato nunca ficam visíveis no mural aberto da comunidade.",
  "home.trustProofTitle": "Comprovação Segura de Propriedade",
  "home.trustProofDesc": "Perguntas de checagem geradas por IA barram falsos donos antes de qualquer encontro.",
  "home.trustRecoveryTitle": "Rede Segura de Devolução",
  "home.trustRecoveryDesc": "Combine a entrega com chats protegidos, autorizações bilaterais e fluxo assistido.",
  "home.timelineShowcaseTitle": "Reconstrução de Rotas com IA",
  "home.timelineShowcaseSubtitle": "Lembre-se dos seus pontos de parada ao longo do dia para estimar a hora e o local exatos.",
  "home.timelineTryPrompt": "Veja um exemplo:",
  "home.faqTitle": "Perguntas Frequentes",
  "home.faqSubtitle": "Tudo o que você precisa saber sobre o funcionamento do LINCO.",
  "dashboard.title": "Painel do Cidadão",
  "dashboard.subtitle": "Gerencie seus relatos, salas de devolução e configurações de segurança.",
  "dashboard.tabReports": "Meus Relatos",
  "dashboard.tabClaims": "Minhas Reivindicações",
  "dashboard.tabRecovery": "Salas de Recuperação",
  "dashboard.tabSettings": "Configurações",
  "dashboard.noReports": "Você ainda não cadastrou nenhum relato.",
  "dashboard.noClaims": "Nenhuma reivindicação ativa no momento.",
  "dashboard.noRecovery": "Nenhuma sala de recuperação em andamento.",
  "dashboard.accountDetails": "Dados da Conta",
  "dashboard.fullName": "Nome Completo",
  "dashboard.phoneNumber": "Telefone",
  "dashboard.city": "Cidade",
  "dashboard.languagePreference": "Idioma de Preferência",
  "dashboard.changeLanguage": "Alterar Idioma",
  "dashboard.saveSettings": "Salvar Configurações",
  "dashboard.settingsSaved": "Configurações salvas com sucesso.",
  "claim.modalTitle": "Reivindicar Posse Deste Item",
  "claim.modalSubtitle": "Comprove que o item pertence a você respondendo às perguntas de verificação.",
  "claim.verifyIdentity": "Verificação de Identidade",
  "claim.questionsPrompt": "Por favor, responda com atenção às perguntas abaixo:",
  "claim.proofDetails": "Detalhes Particulares ou Provas de Posse",
  "claim.proofPlaceholder": "Descreva detalhes ocultos, marcas de uso ou números de série...",
  "claim.submitClaim": "Enviar Reivindicação",
  "claim.statusPending": "Em Análise",
  "claim.statusApproved": "Reivindicação Aprovada",
  "claim.statusRejected": "Reivindicação Recusada",
  "claim.statusResolved": "Caso Solucionado",
  "category.Electronics": "Eletrônicos",
  "category.Documents": "Documentos e Cartões",
  "category.Keys": "Chaves",
  "category.Pet": "Animais de Estimação",
  "category.Jewelry": "Joias e Relógios",
  "category.Vehicle": "Veículos",
  "category.Clothing": "Roupas e Bolsas",
  "category.Other": "Outros Itens",
  "urgency.Normal": "Normal",
  "urgency.Urgent": "Urgente",
  "urgency.Medical": "Médico / Crítico"
}
