"""
Core Indic Dictionaries: mr (Marathi), gu (Gujarati), bn (Bengali)
"""

import json

with open('/tmp/existing_indic_translations.json') as f:
    EXISTING = json.load(f)

with open('/tmp/canonical_master_en.json') as f:
    MASTER_EN = json.load(f)

# Marathi new keys
MR_NEW = {
    "category.Wallet / Purse": "पाकीट / पर्स",
    "category.Bag / Luggage": "बॅग / सामान",
    "category.ID / Card": "ओळखपत्र / कार्ड",
    "urgency.Contains ID": "ओळखपत्र समाविष्ट आहे",
    "voice.stop": "रेकॉर्डिंग थांबवा",
    "voice.error": "आवाज ओळखण्यात त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    "voice.hint": "वस्तूचा ब्रँड, रंग, ठिकाण आणि तारीख यासारखे तपशील बोला.",
    "report.title": "वस्तूची तक्रार / नोंदणी करा",
    "report.subtitle": "स्मार्ट स्थानिक समन्वयासह हरवलेली किंवा सापडलेली वस्तू नोंदवा.",
    "report.type": "अहवाल प्रकार",
    "report.typeLost": "माझी वस्तू हरवली आहे",
    "report.typeFound": "मला एक वस्तू सापडली आहे",
    "report.stepBasics": "१. मूलभूत तपशील",
    "report.stepLocation": "२. ठिकाण आणि तारीख",
    "report.stepPhotos": "३. फोटो आणि पुरावे",
    "report.stepSecurity": "४. सुरक्षा आणि संपर्क",
    "report.itemTitle": "वस्तूचे नाव",
    "report.itemTitlePlaceholder": "उदा. काळे लेदर टायटन घड्याळ, निळी वाईल्डक्राफ्ट बॅग",
    "report.category": "वर्गवारी",
    "report.selectCategory": "वस्तू वर्गवारी निवडा",
    "report.description": "तपशीलवार वर्णन",
    "report.descriptionPlaceholder": "रंग, मॉडेल, ओरखडे, ओळख चिन्हे, आतील वस्तू इत्यादी सांगा...",
    "report.location": "ठिकाण (जिथे सापडली / हरवली)",
    "report.locationPlaceholder": "उदा. अंधेरी मेट्रो स्टेशन गेट २, मुंबई",
    "report.date": "तारीख आणि अंदाजे वेळ",
    "report.urgency": "प्राधान्य पातळी",
    "report.urgencyNormal": "सामान्य",
    "report.urgencyUrgent": "तातडीचे",
    "report.urgencyMedical": "वैद्यकीय / अत्यंत महत्त्वाचे",
    "report.photos": "फोटो अपलोड करा",
    "report.photosHint": "स्पष्ट फोटोंमुळे एआय जुळणी अचूकता वाढते.",
    "report.reward": "बक्षीस रक्कम (पर्यायी)",
    "report.rewardPlaceholder": "₹ रक्कम रुपयांमध्ये",
    "report.contact": "व्हॉट्सॲप / फोन संपर्क",
    "report.contactPlaceholder": "१० अंकी मोबाईल क्रमांक",
    "report.pin": "४ अंकी सुरक्षा पिन",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "नंतर बदल करण्यासाठी किंवा सोडवलेले चिन्हांकित करण्यासाठी आवश्यक.",
    "report.submit": "समुदायात नोंदणी प्रकाशित करा",
    "report.submitting": "सुरक्षित नोंदवहीत प्रकाशित करत आहे...",
    "report.success": "तुमची नोंदणी यशस्वीरित्या प्रकाशित झाली आहे!",
    "report.viewListing": "यादीमध्ये पहा",
    "report.brand": "ब्रँड / निर्माता",
    "report.brandPlaceholder": "उदा. ॲपल, सॅमसंग, टायटन, वाईल्डक्राफ्ट",
    "report.primaryColor": "मुख्य रंग",
    "report.secondaryColor": "दुय्यम रंग",
    "report.landmark": "जवळची खूण",
    "report.landmarkPlaceholder": "उदा. प्लॅटफॉर्म ३ एस्केलेटरजवळ, कॅफेसमोर",
    "report.secretClue": "गुप्त ओळख खूण (पडताळणीसाठी)",
    "report.secretCluePlaceholder": "उदा. आतील खिशात लाल कीचेन, 'RS' नाव कोरलेले",
    "feed.searchPlaceholder": "वस्तू, टॅग, रंग, ब्रँड, शहर शोधा...",
    "feed.filters": "फिल्टर्स",
    "feed.applyFilters": "फिल्टर्स लागू करा",
    "feed.recentSearches": "अलीकडील शोध",
    "feed.savedSearches": "जतन केलेले शोध",
    "feed.listingRegistry": "नोंदणी सूची",
    "feed.category": "वर्गवारी",
    "feed.allCategories": "सर्व वर्गवाऱ्या",
    "feed.city": "शहर",
    "feed.allCities": "सर्व शहरे",
    "feed.dateRange": "तारीख श्रेणी",
    "feed.proximity": "अंतराचा परीघ",
    "feed.allProximities": "सर्व अंतरे (कोणताही परीघ)",
    "feed.within5km": "५ किमीच्या आत",
    "feed.within15km": "१५ किमीच्या आत",
    "feed.within30km": "३० किमीच्या आत",
    "feed.within50km": "५० किमीच्या आत",
    "feed.sortCatalog": "कॅटलॉग क्रमवारी लावा",
    "feed.colorSwatch": "रंग पॅलेट",
    "feed.allColors": "सर्व रंग",
    "feed.hardwareBrand": "ब्रँड निर्माता",
    "feed.allBrands": "सर्व ब्रँड",
    "feed.resetFilters": "फिल्टर्स रीसेट करा",
    "feed.viewList": "यादी",
    "feed.viewMap": "नकाशा",
    "feed.noMatchesFound": "नोंदवहीत कोणतीही जुळणी सापडली नाही",
    "feed.noMatchesDesc": "या निकषांसह कोणतीही वस्तू आढळली नाही. कृपया शोध शब्द बदला किंवा फिल्टर्स रीसेट करा.",
    "feed.reportItem": "हरवलेली/सापडलेली वस्तू नोंदवा",
    "feed.saveParameters": "शोध निकष जतन करा",
    "feed.deleteSavedSearch": "जतन केलेला शोध हटवा",
    "feed.universalSearchBar": "सार्वत्रिक शोध पट्टी",
    "feed.clearSearch": "शोध साफ करा",
    "feed.toggleFilters": "प्रगत फिल्टर्स चालू/बंद",
    "feed.newestFirst": "नवीनतम आधी",
    "feed.oldestFirst": "जुने आधी",
    "feed.highestReward": "सर्वाधिक बक्षीस",
    "feed.closestDistance": "सर्वात जवळचे अंतर",
    "postcard.unlockConnection": "कनेक्शन अनलॉक करा",
    "postcard.iHaveThisItem": "ही वस्तू माझ्याजवळ आहे",
    "postcard.reclaimed": "परत मिळवून सुपूर्द केली",
    "postcard.claims": "दावे",
    "postcard.image": "प्रतिमा",
    "postcard.qr": "क्यूआर",
    "postcard.aiMatch": "एआय जुळणी",
    "postcard.geminiMatches": "जेमिनीला स्मार्ट जुळणी सापडली!",
    "postcard.contactOwner": "मालकाशी संपर्क साधा",
    "postcard.creatorNotice": "केवळ या नोंदणीचे सत्यापित निर्मातेच जुळणी तपशील पाहू शकतात.",
    "postcard.markResolved": "सोडवलेले चिन्हांकित करा",
    "postcard.deleteListing": "नोंदणी हटवा",
    "postcard.unlockWithPin": "सुरक्षा पिनसह संपर्क अनलॉक करा",
    "postcard.manageClaims": "दावे व्यवस्थापित आणि मंजूर/नाकार करा",
    "postcard.shareTemplate": "शेअर मजकूर कॉपी करा",
    "postcard.downloadCard": "कार्ड प्रतिमा म्हणून डाउनलोड करा",
    "postcard.qrSettings": "इंटरअॅक्टिव्ह क्यूआर आणि प्रिंट सेटिंग्ज",
    "postcard.postedOn": "पोस्ट केले",
    "postcard.reward": "बक्षीस",
    "postcard.secureHandover": "सुरक्षित हस्तांतरण",
    "matches.title": "एआय स्मार्ट जुळणी आणि परस्पर पडताळणी",
    "matches.subtitle": "जेमिनी हरवलेल्या आणि सापडलेल्या नोंदींची तुलना करतो. सुरक्षित चॅटपूर्वी परस्पर पडताळणी आवश्यक आहे.",
    "matches.myMatches": "माझ्या जुळण्या",
    "matches.publicMatches": "सार्वजनिक जुळण्या",
    "matches.threshold": "किमान मर्यादा:",
    "matches.security": "सुरक्षा:",
    "matches.mutualApprovalRequired": "परस्पर मंजुरी आवश्यक",
    "matches.noMatchesFound": "कोणतीही संभाव्य जुळणी सापडली नाही",
    "matches.improveReport": "तुमच्या अहवालात सुधारणा करा",
    "matches.noPhoto": "फोटो नाही",
    "matches.chatLive": "थेट चॅट",
    "matches.chatLocked": "चॅट लॉक आहे",
    "matches.inspectReview": "तपासा आणि पुनरावलोकन करा",
    "matches.openChatLive": "थेट चॅट उघडा",
    "matches.verifyApprove": "पडताळणी करा आणि मंजूर करा",
    "matches.approvalNotice": "चॅट अनलॉक होण्यापूर्वी मालक आणि शोधक दोघांनीही पडताळणी मंजूर करणे आवश्यक आहे.",
    "matches.tabComparison": "तुलना",
    "matches.tabVerification": "पडताळणी",
    "matches.tabTrust": "विश्वास आणि व्हॉट्सॲप",
    "matches.tabHandover": "हस्तांतरण",
    "matches.noImageProvided": "कोणतीही प्रतिमा प्रदान केलेली नाही",
    "matches.itemName": "वस्तूचे नाव",
    "matches.category": "वर्गवारी",
    "matches.reward": "बक्षीस",
    "matches.locationAddress": "ठिकाण आणि पत्ता",
    "matches.detailsDescription": "तपशीलवार वर्णन",
    "matches.finderContact": "शोधकाचा संपर्क",
    "matches.matchStatus": "जुळणी स्थिती:",
    "matches.mutualConfirmed": "परस्पर मंजुरीची पुष्टी झाली. दोन्ही बाजूंनी पडताळणी पूर्ण केली आहे.",
    "matches.mutualProtocol": "परस्पर पडताळणी प्रोटोकॉल",
    "matches.protocolNotice": "फसवणूक रोखण्यासाठी दोन्ही बाजू पडताळणी तपशील सादर करतात. दोन्ही बाजूंनी मंजूर करेपर्यंत चॅट लॉक राहते.",
    "matches.ownerStatus": "मालकाची स्थिती",
    "matches.submittedBy": "द्वारे सादर:",
    "matches.aiScore": "एआय पडताळणी स्कोअर:",
    "matches.ownerNotSubmitted": "वस्तूच्या मालकाने अद्याप पडताळणी उत्तरे सादर केलेली नाहीत.",
    "matches.finderStatus": "शोधकाची स्थिती",
    "matches.finderNotSubmitted": "शोधकाने अद्याप पडताळणी उत्तरे सादर केलेली नाहीत.",
    "matches.actionControls": "कृती नियंत्रणे",
    "matches.selectRole": "तपशील सादर करण्यासाठी किंवा पुनरावलोकन करण्यासाठी तुमची भूमिका निवडा.",
    "matches.iAmOwner": "मी मालक आहे",
    "matches.iAmFinder": "मला ही वस्तू सापडली आहे",
    "matches.yourName": "तुमचे नाव",
    "matches.contactWhatsApp": "व्हॉट्सॲप / संपर्क",
    "matches.forensicQuestions": "फॉरेन्सिक पडताळणी प्रश्न",
    "matches.trustTitle": "परस्पर विश्वास आणि सुरक्षित व्हॉट्सॲप संपर्क",
    "matches.trustNotice": "समुदायाच्या सुरक्षेसाठी, थेट फोन नंबर तेव्हाच दिसतात जेव्हा दोन्ही व्यक्ती \"मी या व्यक्तीवर विश्वास ठेवतो\" वर क्लिक करतात.",
    "matches.ownerTrust": "मालकाचा विश्वास",
    "matches.finderTrust": "शोधकाचा विश्वास",
    "matches.unlocked": "अनलॉक केले",
    "matches.masked": "सुरक्षित आणि लपविलेले",
    "matches.contactAlias": "संपर्क नाव / टोपणनाव",
    "matches.phoneWhatsApp": "फोन / व्हॉट्सॲप",
    "matches.openWhatsApp": "व्हॉट्सॲप चॅट उघडा",
    "matches.directCall": "थेट कॉल",
    "matches.trustInstructions": "व्हॉट्सॲप लिंक आणि फोन नंबर पाहण्यासाठी दोन्ही वापरकर्त्यांनी खालील बटणावर क्लिक करणे आवश्यक आहे.",
    "matches.trustConsent": "विश्वासावर क्लिक करून, तुम्ही सुरक्षित हस्तांतरणासाठी संपर्क माहिती सामायिक करण्यास संमती देता.",
    "matches.reunitedResolved": "वस्तू यशस्वीरित्या परत मिळाली आणि प्रकरण मिटले!",
    "matches.reunitedNotice": "मालक आणि शोधक दोघांनीही सुरक्षित हस्तांतरणाची पुष्टी केली आहे.",
    "matches.handoverProtocol": "सुरक्षित हस्तांतरण प्रोटोकॉल",
    "matches.handoverNotice": "सार्वजनिक ठिकाणी भेटण्याची वेळ ठरवा (उदा. मेट्रो स्टेशन किंवा पोलीस चौकी). दिल्यानंतर दोघांनी पुष्टी करा.",
    "matches.handoverSchedule": "हस्तांतरण वेळ आणि ठिकाण",
    "matches.publicMeetingSpot": "सार्वजनिक भेटण्याचे ठिकाण",
    "matches.scheduledDateTime": "नियोजित तारीख / वेळ",
    "matches.confirmHandover": "हस्तांतरणाची पुष्टी करा आणि प्रकरण पूर्ण करा",
    "matches.confirmHandoverDesc": "भेटण्याच्या ठिकाणी वस्तू मिळाल्यानंतर, परतावा अंतिम करण्यासाठी पुष्टी करा.",
    "matches.iHandedOver": "मी ही वस्तू सुपूर्द केली",
    "matches.iReceived": "मला माझी वस्तू मिळाली",
    "matches.chatUnlocksAfter": "पडताळणीनंतर सुरक्षित चॅट अनलॉक होईल",
    "matches.chatUnlocksDesc": "दाव्याच्या पडताळणीनंतर दोन्ही बाजूंमध्ये सुरक्षित चॅट आपोआप उघडेल.",
    "matches.goToVerification": "पडताळणी टॅबवर जा",
    "matches.secureHandoverChat": "सुरक्षित हस्तांतरण चॅट",
    "matches.connectionVerified": "कनेक्शन पडताळले! सुरक्षित हस्तांतरणासाठी संदेश पाठवा.",
    "matches.dismissMatch": "जुळणी फेटाळा",
    "matches.shareMatch": "शेअर करा",
    "matches.directClaim": "थेट दावा",
    "claim.ownershipIndex": "मालकी हक्क निर्देशांक",
    "claim.safeVerification": "सुरक्षित मालकी पडताळणी",
    "claim.stepsNotice": "आम्ही हस्तांतरण सुरक्षित आणि अस्सल करण्यासाठी खाजगी चरणांचा वापर करतो.",
    "claim.protectedContact": "तुमची संपर्क माहिती पूर्णपणे सुरक्षित आहे. केवळ पडताळणी केलेली व्यक्तीच ती पाहू शकते.",
    "claim.unlockedMutual": "परस्पर पडताळणीनंतरच संपर्क पर्याय अनलॉक होतात. तुमचा फोन कधीही सार्वजनिक केला जात नाही.",
    "claim.aiEvaluationNotice": "फसवणूक रोखण्यासाठी आमचे एआय दाव्यांचे मूल्यांकन करते.",
    "claim.trackingNotice": "अद्वितीय ट्रॅकिंग कोड दोन्ही बाजूंचे रक्षण करतात.",
    "claim.modalDescription": "वस्तू तिच्या खऱ्या मालकाला मिळावी यासाठी, संपर्क सामायिक करण्यापूर्वी आम्ही जुळणी पडताळतो. कृपया खालील प्रश्नांची उत्तरे द्या.",
    "claim.aiPreparingQuestions": "एआय तुमचे पडताळणी प्रश्न तयार करत आहे...",
    "claim.claimantName": "दावेदाराचे नाव",
    "claim.officialNamePlaceholder": "तुमचे अधिकृत नाव",
    "claim.whatsappMobile": "व्हॉट्सॲप मोबाईल",
    "claim.mobilePlaceholder": "९८७६५४३२१०",
    "claim.verifyItemDetails": "वस्तू तपशील पडताळा",
    "claim.detailsPlaceholder": "कृपया तपशीलवार सांगा (खुणा, आतील साहित्य, बिल तपशील इत्यादी)...",
    "claim.verificationRegistered": "पडताळणी नोंदणीकृत",
    "claim.detailsSavedSecurely": "तुमचा तपशील सुरक्षितपणे जतन केला गेला आहे. आमच्या एआयने तपशीलांची जुळणी केली आहे.",
    "claim.verificationId": "पडताळणी आयडी (दावा आयडी)",
    "claim.aiMatchDetails": "एआय जुळणी तपशील",
    "claim.bookmarkLink": "थेट लिंक (नंतर पाहण्यासाठी सेव्ह करा)",
    "claim.doneAwaitSignoff": "पूर्ण आणि मालकाच्या मंजुरीची प्रतीक्षा करा",
    "auth.recoverBelongings": "विश्वासू नागरिक आणि बुद्धिमान पडताळणीद्वारे हरवलेल्या वस्तू सुरक्षितपणे परत मिळवा.",
    "auth.startEmail": "ईमेलने सुरुवात करा",
    "auth.continuePhone": "फोनने पुढे जा",
    "auth.signIn": "साइन इन करा",
    "auth.welcomeBack": "पुन्हा स्वागत आहे",
    "auth.resumeTracking": "ट्रॅकिंग सुरू ठेवण्यासाठी तुमच्या लिंको खात्यात साइन इन करा.",
    "auth.emailOrUsername": "ईमेल किंवा वापरकर्तानाव",
    "auth.password": "पासवर्ड",
    "auth.forgotPassword": "पासवर्ड विसरलात?",
    "auth.createAccount": "खाते तयार करा",
    "auth.joinNetwork": "स्मार्ट स्थानिक संरक्षक नेटवर्कमध्ये सामील व्हा.",
    "auth.fullName": "पूर्ण नाव",
    "auth.username": "वापरकर्तानाव",
    "auth.emailAddress": "ईमेल पत्ता",
    "auth.confirmPassword": "पासवर्डची पुष्टी करा",
    "auth.acceptPolicy": "मी गोपनीयता धोरण स्वीकारतो आणि एन्क्रिप्टेड डेटा सामायिक करण्यास संमती देतो.",
    "auth.resetPassword": "पासवर्ड रीसेट करा",
    "auth.resetNotice": "आम्ही तुमच्या खात्यात पुन्हा प्रवेश मिळवण्यासाठी सुरक्षित लिंक पाठवू.",
    "auth.sendResetLink": "रीसेट लिंक पाठवा",
    "auth.returnSignIn": "साइन इनवर परत जा",
    "auth.setupProfile": "तुमचे प्रोफाइल सेट करा",
    "auth.setupNotice": "तुमचे प्रोफाइल पूर्ण करा जेणेकरून नागरिक तुमच्याशी समन्वय साधू शकतील.",
    "auth.takeSnapshot": "फोटो काढा",
    "auth.choosePhoto": "फोटो निवडा",
    "auth.cityNeighborhood": "शहर / परिसर (आवश्यक)",
    "auth.shortBio": "थोडक्यात माहिती (पर्यायी)",
    "auth.completeSetup": "प्रोफाइल सेटअप पूर्ण करा",
    "dashboard.welcomeTitle": "तुमचे प्रोफाइल सेट करा",
    "dashboard.welcomeDesc": "लिंकोमध्ये स्वागत आहे. स्वतःबद्दल थोडी माहिती द्या जेणेकरून नागरिक तुमच्याशी हस्तांतरणाचा समन्वय साधू शकतील.",
    "dashboard.chooseAvatar": "प्रोफाइल फोटो निवडा",
    "dashboard.fullName": "पूर्ण नाव",
    "dashboard.username": "वापरकर्तानाव",
    "dashboard.bio": "माहिती (पर्यायी)",
    "dashboard.city": "शहर",
    "dashboard.createProfile": "प्रोफाइल तयार करा",
    "dashboard.skipForNow": "आत्ता वगळा",
    "dashboard.changeCover": "कव्हर बदला",
    "dashboard.editProfile": "प्रोफाइल संपादित करा",
    "dashboard.shareProfile": "प्रोफाइल शेअर करा",
    "dashboard.settings": "सेटिंग्ज",
    "dashboard.editDetails": "प्रोफाइल तपशील संपादित करा",
    "dashboard.accountSection": "खाते",
    "dashboard.email": "ईमेल",
    "dashboard.password": "पासवर्ड",
    "dashboard.privacySection": "गोपनीयता",
    "dashboard.blockedUsers": "ब्लॉक केलेले वापरकर्ते",
    "dashboard.downloadData": "माझा डेटा डाउनलोड करा",
    "dashboard.deleteAccount": "खाते हटवा",
    "dashboard.notifSection": "सूचना",
    "dashboard.pushNotifs": "पुश सूचना",
    "dashboard.pushDesc": "त्वरित जुळणी आणि चॅटसाठी अपडेट्स",
    "dashboard.emailReports": "ईमेल अहवाल",
    "dashboard.emailDesc": "हक्क नसलेल्या वस्तूंचा साप्ताहिक सारांश",
    "dashboard.appearanceSection": "स्वरूप",
    "dashboard.theme": "थीम",
    "dashboard.language": "भाषा",
    "dashboard.supportSection": "सपोर्ट",
    "dashboard.help": "मदत",
    "dashboard.contact": "संपर्क",
    "dashboard.about": "बद्दल",
    "dashboard.logout": "लिंकोमधून लॉग आउट करा",
    "dashboard.updateEmail": "ईमेल पत्ता अपडेट करा",
    "dashboard.saveEmail": "ईमेल जतन करा",
    "dashboard.changePassword": "पासवर्ड बदला",
    "dashboard.unblock": "अनब्लॉक करा",
    "dashboard.noBlocked": "कोणतेही ब्लॉक केलेले वापरकर्ते नाहीत.",
    "dashboard.contactSupport": "लिंको सपोर्टशी संपर्क साधा",
    "dashboard.supportDesc": "सामान्य मदत किंवा समन्वय प्रश्नांसाठी आमच्या डेव्हलपर्सशी संपर्क साधा:",
    "dashboard.aboutLinco": "लिंको बद्दल",
    "dashboard.aboutDesc": "लिंको हे जेमिनी एआय वापरून हरवलेल्या वस्तू शोधण्यात मदत करणारे एक सुरक्षित ॲप आहे.",
    "dashboard.appVersion": "अनुप्रयोग आवृत्ती: v1.3.0 स्थिर",
    "dashboard.capturePhoto": "फोटो काढा",
    "dashboard.useCamera": "कॅमेरा वापरा",
    "dashboard.chooseGallery": "गॅलरीतून निवडा (क्लाउडिनरी)",
    "dashboard.confirmDeletion": "हटवण्याची पुष्टी करा",
    "dashboard.deletionWarning": "ही कृती कायमस्वरूपी आहे आणि पूर्ववत केली जाऊ शकत नाही. तुमचा सर्व डेटा हटवला जाईल.",
    "dashboard.typePasswordConfirm": "पुष्टीसाठी तुमचा पासवर्ड टाईप करा",
    "dashboard.typeDeletePrompt": "तुमचे खाते कायमचे हटवण्यासाठी खाली DELETE टाईप करा.",
    "ownerClaims.controlBoard": "दावा नियंत्रण फलक",
    "ownerClaims.enterPin": "सुरक्षा पिन प्रविष्ट करा",
    "ownerClaims.pinDesc": "कनेक्शन अनलॉक करण्यासाठी नोंदणी करताना दिलेला ४ अंकी पिन टाका.",
    "ownerClaims.clear": "साफ करा",
    "ownerClaims.authenticating": "प्रमाणीकरण होत आहे...",
    "ownerClaims.integrityScore": "जेमिनी अखंडता स्कोअर",
    "ownerClaims.reviewNotice": "उत्तरांचे पुनरावलोकन करा. मंजूर केल्याने सुरक्षित रिकव्हरी रूम सक्रिय होईल.",
    "ownerClaims.completeHandover": "हस्तांतरण पूर्ण करा",
    "ownerClaims.postClosed": "ही पोस्ट बंद करण्यात आली आहे. मागील दाव्यांचा इतिहास खाली दिसत आहे.",
    "ownerClaims.closeWindow": "खिडकी बंद करा",
    "ownerClaims.approved": "मंजूर",
    "ownerClaims.resolved": "सोडवले",
    "ownerClaims.youReturned": "तुम्ही परत केले:",
    "ownerClaims.meetingCoords": "सुरक्षित भेटीचे समन्वय लिहा...",
    "pin.title": "सुरक्षा पिन प्रविष्टी",
    "pin.passcode": "४ अंकी पासकोड",
    "pin.verifying": "पडताळणी होत आहे...",
    "pin.clear": "साफ करा",
    "pin.unlock": "संवेदनशील संपर्क अनलॉक करा",
    "pin.promise": "तुमचा पिन तुमची वैयक्तिक माहिती सार्वजनिक प्रवेशापासून सुरक्षित ठेवतो.",
    "communityFound.title": "ही वस्तू माझ्याजवळ आहे",
    "communityFound.protocol": "शून्य-विश्वास प्रोटोकॉल",
    "communityFound.verifyFinding": "सापडल्याची पडताळणी करा",
    "communityFound.withoutLeaking": "खाजगी डेटा लीक न करता",
    "communityFound.lostReported": "हरवलेल्या वस्तूची नोंदणी",
    "communityFound.whereFound": "तुम्हाला ही कुठे सापडली?",
    "communityFound.insideContents": "आतील साहित्य / विशिष्ट वस्तू (पर्यायी)",
    "communityFound.secretDetails": "अद्वितीय वैशिष्ट्ये / गुप्त तपशील",
    "communityFound.createPin": "तुमचा सुरक्षा पिन तयार करा",
    "communityFound.reward": "बक्षीस",
    "communityFound.registeredNotice": "नोंदणी झाली आहे. मालकाला तुमच्या उत्तरांचे पुनरावलोकन करण्यासाठी कळवले गेले आहे.",
    "claimTracker.title": "रिकव्हरी स्थिती टाइमलाइन",
    "claimTracker.protocols": "सुरक्षित रिकव्हरी प्रोटोकॉल",
    "claimTracker.publicSpaces": "मेट्रो स्टेशन किंवा कॅफेसारख्या सार्वजनिक आणि चांगल्या प्रकाशाच्या ठिकाणी भेटा.",
    "claimTracker.verifyCarefully": "बक्षीस देण्यापूर्वी वस्तू काळजीपूर्वक तपासा.",
    "claimTracker.documentDetails": "भेटीचे तपशील नोंदवण्यासाठी आमच्या सुरक्षित चॅटचा वापर करा.",
    "claimTracker.lookupAnother": "दुसरा शोधा",
    "claimTracker.unsuccessful": "दावा मूल्यांकन अयशस्वी",
    "claimTracker.trustCheck": "परस्पर विश्वास तपासणी",
    "claimTracker.awaitingApproval": "शोधकाच्या मंजुरीची प्रतीक्षा आहे",
    "claimTracker.recoveryRoom": "सुरक्षित रिकव्हरी रूम",
    "claimTracker.enterRoom": "रिकव्हरी रूममध्ये प्रवेश करा",
    "claimTracker.discussion": "समन्वित हस्तांतरण चर्चा",
    "recovery.transmissionSecured": "डेटा सुरक्षित",
    "recovery.reportIndexed": "नोंदणी यशस्वीरित्या अनुक्रमित केली",
    "recovery.dossierActive": "तुमची पडताळणी फाइल आता सक्रिय आहे. जेमिनी सक्रिय निर्देशांकांचे विश्लेषण करत आहे.",
    "recovery.engineTitle": "एआय रिकव्हरी संभाव्यता इंजिन",
    "recovery.retrievalLikelihood": "परत मिळण्याची शक्यता:",
    "recovery.analyzedFactors": "विश्लेषण केलेले रिकव्हरी घटक",
    "recovery.semanticNotice": "आमचे मॉडेल जुळणीसाठी ब्रँड, रंग आणि ओळखचिन्हे काढते.",
    "recovery.uniqueIdentifier": "एक अद्वितीय ओळखचिन्ह पूर्ण पडताळलेली जुळणी सक्षम करते.",
    "recovery.setReward": "बक्षीस निश्चित करा",
    "reward.fairRange": "अंदाजे योग्य मर्यादा",
    "reward.suggestReward": "बक्षीस सुचवा",
    "reward.customReward": "सानुकूल बक्षीस रक्कम",
    "privacy.complianceProtocols": "अनुपालन, गोपनीयता आणि विश्वास प्रोटोकॉल",
    "privacy.title": "विश्वास आणि अनुपालन केंद्र",
    "privacy.subtitle": "आम्ही वापरकर्ता सुरक्षा आणि पारदर्शकतेच्या सर्वोच्च मानकांचे पालन करतो.",
    "privacy.exitSection": "विभागातून बाहेर पडा",
    "privacy.privacyPolicy": "गोपनीयता धोरण",
    "privacy.lastUpdated": "अंतिम अपडेट: ७ जुलै, २०२६. डेटा कमीत कमी गोळा करणे हा आमचा पाया आहे.",
    "privacy.dataAcquisition": "आम्ही केवळ हरवलेल्या वस्तू शोधण्यासाठी आवश्यक असलेला डेटा गोळा करतो:",
    "privacy.spatiotemporalTags": "स्थानिक-कालिक टॅग्ज:",
    "privacy.coldStorage": "स्वयंचलित कोल्ड स्टोरेजपूर्वी कमाल मर्यादा.",
    "privacy.cookiePreferences": "कुकी प्राधान्ये आणि संमती धोरणे व्यवस्थापित करा.",
    "privacy.purgeBrowser": "या ब्राउझरमधील कुकीज आणि कॅश केलेला डेटा त्वरित हटवा.",
    "privacy.hereToHelp": "आम्ही मदतीसाठी येथे आहोत.",
    "privacy.connectFounder": "अभिप्राय किंवा मदतीसाठी आमच्या नेटवर्क प्रोफाइलवर संपर्क साधा.",
    "cookie.title": "गोपनीयता सार्वभौमत्व",
    "cookie.message": "आम्ही केवळ हरवलेल्या वस्तू परत मिळवण्यासाठी आवश्यक असलेली माहिती गोळा करतो.",
    "cookie.trackingNotice": "मालकी सिद्ध होईपर्यंत तुमची ओळख खाजगी राहते. कोणतेही ट्रॅकिंग नाही.",
    "cookie.acceptAll": "सर्व स्वीकारा",
    "cookie.learnMore": "अधिक जाणून घ्या",
    "about.tagline": "समुदायांना जोडणे, वस्तू परत मिळवणे",
    "about.mission": "लिंको नैतिक एआय आणि सामुदायिक विश्वासाचा वापर करून हरवलेल्या वस्तू त्यांच्या मालकांपर्यंत पोहोचवण्यासाठी समर्पित आहे.",
    "notifications.title": "सूचना",
    "notifications.empty": "कोणतीही नवीन सूचना नाही",
    "notifications.markAllRead": "सर्व वाचलेले चिन्हांकित करा",
    "notifications.clearAll": "सर्व साफ करा",
    "notifications.matchFoundTitle": "संभाव्य जुळणी सापडली",
    "notifications.matchFoundMsg": "आमच्या एआय मॅचिंग इंजिनद्वारे संभाव्य जुळणी शोधली गेली आहे.",
    "notifications.claimReceivedTitle": "नवीन दावा सादर केला",
    "notifications.claimReceivedMsg": "एका नागरिकाने तुमच्या नोंदणीसाठी पडताळणी उत्तरे सादर केली आहेत.",
    "notifications.claimApprovedTitle": "दावा मंजूर",
    "notifications.claimApprovedMsg": "तुमचा दावा वस्तूच्या मालकाद्वारे सत्यापित आणि मंजूर करण्यात आला आहे.",
    "notifications.chatMessageTitle": "रिकव्हरी रूममध्ये नवीन संदेश",
    "notifications.chatMessageMsg": "तुम्हाला तुमच्या रिकव्हरी समन्वयाबाबत एक नवीन संदेश मिळाला आहे.",
    "notifications.handoverDoneTitle": "हस्तांतरणाची पुष्टी झाली",
    "notifications.handoverDoneMsg": "वस्तू परत मिळाल्याची पुष्टी झाली असून प्रकरण आता मिटले आहे.",
    "enhance.button": "एआय वर्णन सुधारा",
    "enhance.loading": "जेमिनी एआय तुमचे वर्णन व्यवस्थित करत आहे...",
    "enhance.apply": "सुधारित वर्णन वापरा",
    "enhance.discard": "मूळ वर्णन ठेवा",
    "enhance.rewardTitle": "एआय योग्य बक्षीस सूचना",
    "enhance.rewardCalculated": "सुचवलेले बक्षीस: ₹",
    "enhance.rewardReason": "वस्तू वर्गवारी, ब्रँड मूल्य आणि समुदाय मानकांवर आधारित.",
    "timeline.reconstruct": "टाइमलाइन पुनर्बांधणी करा",
    "timeline.loading": "प्रवास मार्ग आणि चेकपॉईंटचे विश्लेषण होत आहे...",
    "timeline.spotLikelihood": "संभाव्य हरवण्याचे ठिकाण:",
    "timeline.window": "संभाव्य वेळ विंडो:",
    "timeline.analysis": "पूर्ण प्रवास विश्लेषण:",
    "timeline.confidence": "मार्ग विश्वासार्हता:",
    "timeline.addPoint": "मार्ग चेकपॉईंट जोडा",
    "timeline.pointName": "चेकपॉईंट नाव / स्टेशन",
    "chat.assistant": "एआय सहाय्यक",
    "chat.subtitle": "तुमचा संवाद साथी",
    "chat.description": "हरवलेली किंवा सापडलेली वस्तू ६० सेकंदात नोंदवा. बोला किंवा तुमच्या भाषेत टाइप करा.",
    "chat.startAssistant": "एआय अहवाल सहाय्यक सुरू करा",
    "chat.location": "ठिकाण:",
    "chat.securityPin": "सुरक्षा पिन:",
    "chat.skipPhoto": "फोटो वगळा",
    "chat.item": "वस्तू:",
    "chat.errorLoading": "चॅटबॉट सहाय्यक लोड करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    "chat.welcomeMessage": "लिंकोसाथीमध्ये तुमचे स्वागत आहे! मी तुमचा साथी आहे. मला सांगा काय हरवले किंवा सापडले आहे.",
    "chat.networkError": "क्षमस्व, नेटवर्क समस्या आली. कृपया पुन्हा प्रयत्न करा!",
    "chat.understoodError": "मला नीट समजले नाही. आपण अधिक तपशील देऊ शकता का?",
    "feed.lostOnly": "हरवलेल्या वस्तू",
    "feed.foundOnly": "सापडलेल्या वस्तू",
    "feed.filterByCategory": "वर्गवारी",
    "feed.filterByCity": "शहर",
    "feed.filterByUrgency": "प्राधान्य",
    "feed.empty": "सक्रिय शोध निकषांशी कोणतीही वस्तू जुळत नाही.",
    "feed.emptyAction": "नवीन वस्तूची नोंदणी करा",
    "matches.contactFinder": "शोधकाशी संपर्क साधा",
    "matches.contactOwner": "मालकाशी संपर्क साधा",
    "matches.verifyOwnership": "मालकी हक्क पडताळा",
    "claim.title": "मालकी हक्क दावा सादर करा",
    "claim.subtitle": "सार्वजनिक संपर्क लीक न करता एआय सुरक्षेसह मालकी हक्क पडताळा.",
    "claim.questionsTitle": "पडताळणी प्रश्न",
    "claim.questionsSubtitle": "खरे मालक असल्याचे दाखवण्यासाठी प्रश्नांची उत्तरे द्या:",
    "claim.answerPlaceholder": "या प्रश्नाचे तुमचे उत्तर...",
    "claim.submit": "पुनरावलोकनासाठी दावा सादर करा",
    "claim.submitting": "पडताळणी तपशील सादर करत आहे...",
    "claim.success": "दावा सादर झाला! मालक तुमच्या उत्तरांचे पुनरावलोकन करेल.",
    "dashboard.myReports": "माझे अहवाल",
    "dashboard.myClaims": "माझे दावे",
    "dashboard.savedPosts": "जतन केलेल्या पोस्ट",
    "help.title": "नेहमी विचारले जाणारे प्रश्न",
    "help.q1": "लिंको माझ्या गोपनीयतेचे रक्षण कसे करते?",
    "help.a1": "लिंको तुमची संपर्क माहिती कधीही सार्वजनिक करत नाही. केवळ परस्पर पडताळणीनंतरच ती उघड होते.",
    "help.q2": "मी हरवलेल्या वस्तूची नोंदणी केल्यावर काय होते?",
    "help.a2": "आमचे एआय तुमच्या अहवालाची तुलना सर्व शहरांमधील सापडलेल्या वस्तूंशी करते.",
    "help.q3": "मालकी हक्क पडताळणी कशी कार्य करते?",
    "help.a3": "दावेदारांना एआयने तयार केलेल्या गुप्त प्रश्नांची उत्तरे द्यावी लागतात जी फक्त खऱ्या मालकाला माहित असतात.",
    "help.q4": "लिंको वापरण्यासाठी मोफत आहे का?",
    "help.a4": "होय, लिंको पूर्णपणे मोफत आणि समुदाय-चालित आहे.",
    "home.heroTitle": "एआय आणि पडताळलेल्या विश्वासाने हरवलेल्या वस्तू परत मिळवा",
    "home.heroSubtitle": "भारताचे समुदाय-चालित लॉस्ट अँड फाऊंड व्यासपीठ. सुरक्षित, खाजगी आणि जेमिनी एआय द्वारा समर्थित.",
    "home.statsRecovered": "परत मिळालेल्या वस्तू",
    "home.statsActive": "सक्रिय नागरिक देखरेख",
    "home.statsCities": "समाविष्ट शहरे",
    "home.howItWorks": "लिंको कसे कार्य करते",
    "home.step1Title": "१. सेकंदात नोंदणी करा",
    "home.step1Desc": "३९ भाषांमध्ये आवाज, मजकूर किंवा फोटोद्वारे वस्तू नोंदवा.",
    "home.step2Title": "२. स्मार्ट एआय जुळणी",
    "home.step2Desc": "जेमिनी व्हिज्युअल वैशिष्ट्ये आणि वर्णनांची तुलना करते.",
    "home.step3Title": "३. पडताळलेले हस्तांतरण",
    "home.step3Desc": "गुप्त प्रश्नांद्वारे दावे पडताळा आणि सुरक्षितपणे वस्तू परत मिळवा.",
}

# Gujarati new keys
GU_NEW = {
    "category.Wallet / Purse": "પાકીટ / પર્સ",
    "category.Bag / Luggage": "બેગ / સામાન",
    "category.ID / Card": "ઓળખપત્ર / કાર્ડ",
    "urgency.Contains ID": "ઓળખપત્ર શામેલ છે",
    "voice.stop": "રેકોર્ડિંગ બંધ કરો",
    "voice.error": "અવાજ ઓળખવામાં ભૂલ આવી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    "voice.hint": "વસ્તુની બ્રાન્ડ, રંગ, સ્થળ અને તારીખ જેવી વિગતો બોલો.",
    "report.title": "વસ્તુની જાણ કરો / નોંધણી કરો",
    "report.subtitle": "સ્માર્ટ સ્થાનિક સંકલન સાથે ખોવાયેલી કે મળેલી વસ્તુ નોંધો.",
    "report.type": "અહેવાલ પ્રકાર",
    "report.typeLost": "મારી વસ્તુ ખોવાઈ ગઈ છે",
    "report.typeFound": "મને એક વસ્તુ મળી છે",
    "report.stepBasics": "૧. મૂળભૂત વિગતો",
    "report.stepLocation": "૨. સ્થળ અને તારીખ",
    "report.stepPhotos": "૩. ફોટા અને પુરાવા",
    "report.stepSecurity": "૪. સુરક્ષા અને સંપર્ક",
    "report.itemTitle": "વસ્તુનું નામ",
    "report.itemTitlePlaceholder": "દા.ત. કાળી લેધર ટાઇટન ઘડિયાળ, વાદળી વાઇલ્ડક્રાફ્ટ બેગ",
    "report.category": "શ્રેણી",
    "report.selectCategory": "વસ્તુ શ્રેણી પસંદ કરો",
    "report.description": "વિગતવાર વર્ણન",
    "report.descriptionPlaceholder": "રંગ, મોડેલ, નિશાનો, ઓળખ ચિહ્નો, અંદરની વસ્તુઓ વગેરે જણાવો...",
    "report.location": "સ્થળ (જ્યાં મળી / ખોવાઈ)",
    "report.locationPlaceholder": "દા.ત. અંધેરી મેટ્રો સ્ટેશન ગેટ ૨, મુંબઈ",
    "report.date": "તારીખ અને અંદાજિત સમય",
    "report.urgency": "પ્રાથમિકતા સ્તર",
    "report.urgencyNormal": "સામાન્ય",
    "report.urgencyUrgent": "તાકીદનું",
    "report.urgencyMedical": "તબીબી / અત્યંત મહત્વપૂર્ણ",
    "report.photos": "ફોટા અપલોડ કરો",
    "report.photosHint": "સ્પષ્ટ ફોટા એઆઈ મેળ ખાવાની ચોકસાઈમાં ઘણો સુધારો કરે છે.",
    "report.reward": "ઇનામ રકમ (વૈકલ્પિક)",
    "report.rewardPlaceholder": "₹ રકમ રૂપિયામાં",
    "report.contact": "વોટ્સએપ / ફોન સંપર્ક",
    "report.contactPlaceholder": "૧૦ અંકનો મોબાઈલ નંબર",
    "report.pin": "૪ અંકનો સુરક્ષા પિન",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "પાછળથી ફેરફાર કરવા અથવા ઉકેલાયેલ ચિહ્નિત કરવા માટે જરૂરી.",
    "report.submit": "સમુદાયમાં નોંધણી પ્રકાશિત કરો",
    "report.submitting": "સુરક્ષિત રજિસ્ટ્રીમાં પ્રકાશિત થઈ રહ્યું છે...",
    "report.success": "તમારી નોંધણી સફળતાપૂર્વક પ્રકાશિત થઈ ગઈ છે!",
    "report.viewListing": "યાદીમાં જુઓ",
    "report.brand": "બ્રાન્ડ / ઉત્પાદક",
    "report.brandPlaceholder": "દા.ત. એપલ, સેમસંગ, ટાઇટન, વાઇલ્ડક્રાફ્ટ",
    "report.primaryColor": "મુખ્ય રંગ",
    "report.secondaryColor": "ગૌણ રંગ",
    "report.landmark": "નજીકનું લેન્ડમાર્ક",
    "report.landmarkPlaceholder": "દા.ત. પ્લેટફોર્મ ૩ એસ્કેલેટર પાસે, કેફે સામે",
    "report.secretClue": "ગુપ્ત ઓળખ ચિહ્ન (ચકાસણી માટે)",
    "report.secretCluePlaceholder": "દા.ત. અંદરના ખિસ્સામાં લાલ કીચેન, કોતરેલું નામ 'RS'",
    "feed.searchPlaceholder": "વસ્તુઓ, ટેગ્સ, રંગો, બ્રાન્ડ્સ, શહેરો શોધો...",
    "feed.filters": "ફિલ્ટર્સ",
    "feed.applyFilters": "ફિલ્ટર્સ લાગુ કરો",
    "feed.recentSearches": "તાજેતરની શોધો",
    "feed.savedSearches": "સાચવેલી શોધો",
    "feed.listingRegistry": "નોંધણી સૂચિ",
    "feed.category": "શ્રેણી",
    "feed.allCategories": "બધી શ્રેણીઓ",
    "feed.city": "શહેર",
    "feed.allCities": "બધા શહેરો",
    "feed.dateRange": "તારીખ મર્યાદા",
    "feed.proximity": "અંતર ત્રિજ્યા",
    "feed.allProximities": "બધા અંતરો (કોઈપણ ત્રિજ્યા)",
    "feed.within5km": "૫ કિમીની અંદર",
    "feed.within15km": "૧૫ કિમીની અંદર",
    "feed.within30km": "૩૦ કિમીની અંદર",
    "feed.within50km": "૫૦ કિમીની અંદર",
    "feed.sortCatalog": "કેટલોગ ક્રમબદ્ધ કરો",
    "feed.colorSwatch": "રંગ પેલેટ",
    "feed.allColors": "બધા રંગો",
    "feed.hardwareBrand": "બ્રાન્ડ ઉત્પાદક",
    "feed.allBrands": "બધી બ્રાન્ડ્સ",
    "feed.resetFilters": "ફિલ્ટર્સ રીસેટ કરો",
    "feed.viewList": "યાદી",
    "feed.viewMap": "નકશો",
    "feed.noMatchesFound": "રજિસ્ટ્રીમાં કોઈ મેળ મળ્યો નથી",
    "feed.noMatchesDesc": "આ ફિલ્ટર્સ સાથે કોઈ વસ્તુ મળી નથી. કૃપા કરીને શોધ શબ્દો બદલો અથવા ફિલ્ટર્સ રીસેટ કરો.",
    "feed.reportItem": "ખોવાયેલી/મળેલી વસ્તુ નોંધો",
    "feed.saveParameters": "શોધ પરિમાણો સાચવો",
    "feed.deleteSavedSearch": "સાચવેલી શોધ કાઢી નાખો",
    "feed.universalSearchBar": "સાર્વત્રિક શોધ પટ્ટી",
    "feed.clearSearch": "શોધ સાફ કરો",
    "feed.toggleFilters": "અદ્યતન ફિલ્ટર્સ ચાલુ/બંધ",
    "feed.newestFirst": "સૌથી નવી પહેલાં",
    "feed.oldestFirst": "સૌથી જૂની પહેલાં",
    "feed.highestReward": "સૌથી વધુ ઇનામ",
    "feed.closestDistance": "સૌથી નજીકનું અંતર",
    "postcard.unlockConnection": "કનેક્શન અનલૉક કરો",
    "postcard.iHaveThisItem": "આ વસ્તુ મારી પાસે છે",
    "postcard.reclaimed": "પરત મેળવી અને સોંપવામાં આવી",
    "postcard.claims": "દાવાઓ",
    "postcard.image": "છબી",
    "postcard.qr": "ક્યૂઆર",
    "postcard.aiMatch": "એઆઈ મેળ",
    "postcard.geminiMatches": "જેમિનીએ સ્માર્ટ મેળ શોધ્યો!",
    "postcard.contactOwner": "માલિકનો સંપર્ક કરો",
    "postcard.creatorNotice": "માત્ર આ લિસ્ટિંગના ચકાસાયેલ નિર્માતા જ મેળ વિગતો જોઈ શકે છે.",
    "postcard.markResolved": "ઉકેલાયેલ ચિહ્નિત કરો",
    "postcard.deleteListing": "લિસ્ટિંગ કાઢી નાખો",
    "postcard.unlockWithPin": "સુરક્ષા પિન વડે કનેક્શન અનલૉક કરો",
    "postcard.manageClaims": "દાવાઓનું સંચાલન અને મંજૂરી/અસ્વીકાર કરો",
    "postcard.shareTemplate": "શેર લખાણ કૉપિ કરો",
    "postcard.downloadCard": "કાર્ડ ઇમેજ તરીકે ડાઉનલોડ કરો",
    "postcard.qrSettings": "ઇન્ટરેક્ટિવ ક્યૂઆર અને પ્રિન્ટ સેટિંગ્સ",
    "postcard.postedOn": "પોસ્ટ કર્યું",
    "postcard.reward": "ઇનામ",
    "postcard.secureHandover": "સુરક્ષિત સોંપણી",
    "matches.title": "એઆઈ સ્માર્ટ મેળ અને પરસ્પર ચકાસણી",
    "matches.subtitle": "જેમિની ખોવાયેલી અને મળેલી યાદીઓની સરખામણી કરે છે. સુરક્ષિત ચેટ પહેલાં પરસ્પર ચકાસણી જરૂરી છે.",
    "matches.myMatches": "મારા મેળ",
    "matches.publicMatches": "જાહેર મેળ",
    "matches.threshold": "ન્યૂનતમ મર્યાદા:",
    "matches.security": "સુરક્ષા:",
    "matches.mutualApprovalRequired": "પરસ્પર મંજૂરી જરૂરી",
    "matches.noMatchesFound": "કોઈ સંભવિત મેળ મળ્યો નથી",
    "matches.improveReport": "તમારા અહેવાલમાં સુધારો કરો",
    "matches.noPhoto": "કોઈ ફોટો નથી",
    "matches.chatLive": "લાઇવ ચેટ",
    "matches.chatLocked": "ચેટ લૉક છે",
    "matches.inspectReview": "તપાસો અને સમીક્ષા કરો",
    "matches.openChatLive": "લાઇવ ચેટ ખોલો",
    "matches.verifyApprove": "ચકાસો અને મંજૂર કરો",
    "matches.approvalNotice": "ચેટ અનલૉક થાય તે પહેલાં માલિક અને શોધક બંનેએ ચકાસણી મંજૂર કરવી આવશ્યક છે.",
    "matches.tabComparison": "સરખામણી",
    "matches.tabVerification": "ચકાસણી",
    "matches.tabTrust": "વિશ્વાસ અને વોટ્સએપ",
    "matches.tabHandover": "સોંપણી",
    "matches.noImageProvided": "કોઈ છબી આપવામાં આવી નથી",
    "matches.itemName": "વસ્તુનું નામ",
    "matches.category": "શ્રેણી",
    "matches.reward": "ઇનામ",
    "matches.locationAddress": "સ્થળ અને સરનામું",
    "matches.detailsDescription": "વિગતવાર વર્ણન",
    "matches.finderContact": "શોધકનો સંપર્ક",
    "matches.matchStatus": "મેળ સ્થિતિ:",
    "matches.mutualConfirmed": "પરસ્પર મંજૂરીની પુષ્ટિ થઈ. બંને પક્ષોએ ચકાસણી પૂર્ણ કરી છે.",
    "matches.mutualProtocol": "પરસ્પર ચકાસણી પ્રોટોકોલ",
    "matches.protocolNotice": "છેતરપિંડી રોકવા બંને પક્ષો ચકાસણી વિગતો સબમિટ કરે છે. બંને પક્ષો મંજૂર ન કરે ત્યાં સુધી ચેટ લૉક રહે છે.",
    "matches.ownerStatus": "માલિકની સ્થિતિ",
    "matches.submittedBy": "દ્વારા સબમિટ કરેલ:",
    "matches.aiScore": "એઆઈ ચકાસણી સ્કોર:",
    "matches.ownerNotSubmitted": "વસ્તુના માલિકે હજુ સુધી જવાબો સબમિટ કર્યા નથી.",
    "matches.finderStatus": "શોધકની સ્થિતિ",
    "matches.finderNotSubmitted": "શોધકે હજુ સુધી જવાબો સબમિટ કર્યા નથી.",
    "matches.actionControls": "ક્રિયા નિયંત્રણો",
    "matches.selectRole": "વિગતો સબમિટ કરવા અથવા સમીક્ષા કરવા માટે તમારી ભૂમિકા પસંદ કરો.",
    "matches.iAmOwner": "હું માલિક છું",
    "matches.iAmFinder": "મને આ વસ્તુ મળી છે",
    "matches.yourName": "તમારું નામ",
    "matches.contactWhatsApp": "વોટ્સએપ / સંપર્ક",
    "matches.forensicQuestions": "ફોરેન્સિક ચકાસણી પ્રશ્નો",
    "matches.trustTitle": "પરસ્પર વિશ્વાસ અને સુરક્ષિત વોટ્સએપ સંપર્ક",
    "matches.trustNotice": "સમુદાયની સુરક્ષા માટે, સીધા ફોન નંબર ત્યારે જ દેખાય છે જ્યારે બંને પક્ષો \"હું આ વ્યક્તિ પર વિશ્વાસ કરું છું\" પર ક્લિક કરે.",
    "matches.ownerTrust": "માલિકનો વિશ્વાસ",
    "matches.finderTrust": "શોધકનો વિશ્વાસ",
    "matches.unlocked": "અનલૉક કરેલ",
    "matches.masked": "સુરક્ષિત અને છુપાયેલ",
    "matches.contactAlias": "સંપર્ક નામ / ઉપનામ",
    "matches.phoneWhatsApp": "ફોન / વોટ્સએપ",
    "matches.openWhatsApp": "વોટ્સએપ ચેટ ખોલો",
    "matches.directCall": "સીધો કૉલ",
    "matches.trustInstructions": "વોટ્સએપ લિંક અને ફોન નંબર જોવા માટે બંને વપરાશકર્તાઓએ નીચે આપેલા બટન પર ક્લિક કરવું આવશ્યક છે.",
    "matches.trustConsent": "વિશ્વાસ પર ક્લિક કરીને, તમે સુરક્ષિત સોંપણી માટે સંપર્ક વિગતો શેર કરવા માટે સંમતિ આપો છો.",
    "matches.reunitedResolved": "વસ્તુ સફળતાપૂર્વક પરત મળી અને કેસ ઉકેલાયો!",
    "matches.reunitedNotice": "માલિક અને શોધક બંનેએ સુરક્ષિત સોંપણીની પુષ્ટિ કરી છે.",
    "matches.handoverProtocol": "સુરક્ષિત સોંપણી પ્રોટોકોલ",
    "matches.handoverNotice": "જાહેર સ્થળે મળવાનો સમય નક્કી કરો (દા.ત. મેટ્રો સ્ટેશન અથવા પોલીસ ચોકી). આપ્યા પછી બંને પુષ્ટિ કરો.",
    "matches.handoverSchedule": "સોંપણી સમય અને સ્થળ",
    "matches.publicMeetingSpot": "જાહેર મળવાનું સ્થળ",
    "matches.scheduledDateTime": "નિયુક્ત તારીખ / સમય",
    "matches.confirmHandover": "સોંપણીની પુષ્ટિ કરો અને કેસ પૂર્ણ કરો",
    "matches.confirmHandoverDesc": "મળવાના સ્થળે વસ્તુ મળ્યા પછી, પરત પ્રક્રિયાને અંતિમ સ્વરૂપ આપવા પુષ્ટિ કરો.",
    "matches.iHandedOver": "મેં આ વસ્તુ સોંપી દીધી",
    "matches.iReceived": "મને મારી વસ્તુ મળી ગઈ",
    "matches.chatUnlocksAfter": "ચકાસણી પછી સુરક્ષિત ચેટ અનલૉક થશે",
    "matches.chatUnlocksDesc": "દાવાની ચકાસણી પછી બંને પક્ષો વચ્ચે સુરક્ષિત ચેટ આપમેળે ખૂલશે.",
    "matches.goToVerification": "ચકાસણી ટેબ પર જાઓ",
    "matches.secureHandoverChat": "સુરક્ષિત સોંપણી ચેટ",
    "matches.connectionVerified": "કનેક્શન ચકાસાયેલ! સુરક્ષિત સોંપણી માટે સંદેશ મોકલો.",
    "matches.dismissMatch": "મેળ નકારી કાઢો",
    "matches.shareMatch": "શેર કરો",
    "matches.directClaim": "સીધો દાવો",
    "claim.ownershipIndex": "માલિકી અધિકાર અનુક્રમણિકા",
    "claim.safeVerification": "સુરક્ષિત માલિકી ચકાસણી",
    "claim.stepsNotice": "અમે સોંપણી સુરક્ષિત અને અસલી બનાવવા ખાનગી પગલાંનો ઉપયોગ કરીએ છીએ.",
    "claim.protectedContact": "તમારી સંપર્ક વિગતો સંપૂર્ણપણે સુરક્ષિત છે. માત્ર ચકાસાયેલ વ્યક્તિ જ તેને જોઈ શકે છે.",
    "claim.unlockedMutual": "પરસ્પર ચકાસણી પછી જ સંપર્ક વિકલ્પો ખુલે છે. તમારો ફોન ક્યારેય જાહેર કરવામાં આવતો નથી.",
    "claim.aiEvaluationNotice": "છેતરપિંડી રોકવા માટે અમારું એઆઈ દાવાઓનું મૂલ્યાંકન કરે છે.",
    "claim.trackingNotice": "અનન્ય ટ્રેકિંગ કોડ બંને પક્ષોનું રક્ષણ કરે છે.",
    "claim.modalDescription": "વસ્તુ તેના સાચા માલિકને મળે તે માટે, અમે સંપર્ક શેર કરતાં પહેલાં મેળ ચકાસીએ છીએ. કૃપા કરીને નીચેના પ્રશ્નોના જવાબ આપો.",
    "claim.aiPreparingQuestions": "એઆઈ તમારા ચકાસણી પ્રશ્નો તૈયાર કરી રહ્યું છે...",
    "claim.claimantName": "દાવેદારનું નામ",
    "claim.officialNamePlaceholder": "તમારું સત્તાવાર નામ",
    "claim.whatsappMobile": "વોટ્સએપ મોબાઈલ",
    "claim.mobilePlaceholder": "૯૮૭૬૫૪૩૨૧૦",
    "claim.verifyItemDetails": "વસ્તુ વિગતો ચકાસો",
    "claim.detailsPlaceholder": "કૃપા કરીને વિગતવાર જણાવો (નિશાનો, અંદરની સામગ્રી, બિલ વિગતો વગેરે)...",
    "claim.verificationRegistered": "ચકાસણી નોંધાયેલ",
    "claim.detailsSavedSecurely": "તમારી વિગતો સુરક્ષિત રીતે સાચવી લેવામાં આવી છે. અમારા એઆઈએ વિગતો મેળવી છે.",
    "claim.verificationId": "ચકાસણી આઈડી (દાવો આઈડી)",
    "claim.aiMatchDetails": "એઆઈ મેળ વિગતો",
    "claim.bookmarkLink": "સીધી લિંક (પછીથી જોવા માટે સાચવો)",
    "claim.doneAwaitSignoff": "પૂર્ણ અને માલિકની મંજૂરીની રાહ જુઓ",
    "auth.recoverBelongings": "વિશ્વાસુ નાગરિકો અને બુદ્ધિશાળી ચકાસણી દ્વારા ખોવાયેલી વસ્તુઓ સુરક્ષિત રીતે પરત મેળવો.",
    "auth.startEmail": "ઈમેલથી શરૂ કરો",
    "auth.continuePhone": "ફોનથી આગળ વધો",
    "auth.signIn": "સાઇન ઇન કરો",
    "auth.welcomeBack": "ફરી સ્વાગત છે",
    "auth.resumeTracking": "ટ્રેકિંગ ચાલુ રાખવા માટે તમારા લિન્કો ખાતામાં સાઇન ઇન કરો.",
    "auth.emailOrUsername": "ઈમેલ અથવા વપરાશકર્તાનામ",
    "auth.password": "પાસવર્ડ",
    "auth.forgotPassword": "પાસવર્ડ ભૂલી ગયા?",
    "auth.createAccount": "ખાતું બનાવો",
    "auth.joinNetwork": "સ્માર્ટ સ્થાનિક વાલી નેટવર્કમાં જોડાઓ.",
    "auth.fullName": "પૂરું નામ",
    "auth.username": "વપરાશકર્તાનામ",
    "auth.emailAddress": "ઈમેલ સરનામું",
    "auth.confirmPassword": "પાસવર્ડની પુષ્ટિ કરો",
    "auth.acceptPolicy": "હું ગોપનીયતા નીતિ સ્વીકારું છું અને એન્ક્રિપ્ટેડ ડેટા શેરિંગ માટે સંમતિ આપું છું.",
    "auth.resetPassword": "પાસવર્ડ રીસેટ કરો",
    "auth.resetNotice": "તમારા ખાતામાં ફરી પ્રવેશ મેળવવા માટે અમે સુરક્ષિત લિંક મોકલીશું.",
    "auth.sendResetLink": "રીસેટ લિંક મોકલો",
    "auth.returnSignIn": "સાઇન ઇન પર પાછા જાઓ",
    "auth.setupProfile": "તમારી પ્રોફાઇલ સેટ કરો",
    "auth.setupNotice": "તમારી પ્રોફાઇલ પૂર્ણ કરો જેથી નાગરિકો તમારી સાથે સંકલન કરી શકે.",
    "auth.takeSnapshot": "ફોટો લો",
    "auth.choosePhoto": "ફોટો પસંદ કરો",
    "auth.cityNeighborhood": "શહેર / વિસ્તાર (જરૂરી)",
    "auth.shortBio": "ટૂંકમાં પરિચય (વૈકલ્પિક)",
    "auth.completeSetup": "પ્રોફાઇલ સેટઅપ પૂર્ણ કરો",
    "dashboard.welcomeTitle": "તમારી પ્રોફાઇલ સેટ કરો",
    "dashboard.welcomeDesc": "લિન્કોમાં સ્વાગત છે. તમારા વિશે થોડી માહિતી આપો જેથી નાગરિકો તમારી સાથે સોંપણીનું સંકલન કરી શકે.",
    "dashboard.chooseAvatar": "પ્રોફાઇલ ફોટો પસંદ કરો",
    "dashboard.fullName": "પૂરું નામ",
    "dashboard.username": "વપરાશકર્તાનામ",
    "dashboard.bio": "પરિચય (વૈકલ્પિક)",
    "dashboard.city": "શહેર",
    "dashboard.createProfile": "પ્રોફાઇલ બનાવો",
    "dashboard.skipForNow": "હમણાં માટે છોડો",
    "dashboard.changeCover": "કવર બદલો",
    "dashboard.editProfile": "પ્રોફાઇલ સંપાદિત કરો",
    "dashboard.shareProfile": "પ્રોફાઇલ શેર કરો",
    "dashboard.settings": "સેટિંગ્સ",
    "dashboard.editDetails": "પ્રોફાઇલ વિગતો સંપાદિત કરો",
    "dashboard.accountSection": "ખાતું",
    "dashboard.email": "ઈમેલ",
    "dashboard.password": "પાસવર્ડ",
    "dashboard.privacySection": "ગોપનીયતા",
    "dashboard.blockedUsers": "બ્લૉક કરેલા વપરાશકર્તાઓ",
    "dashboard.downloadData": "મારો ડેટા ડાઉનલોડ કરો",
    "dashboard.deleteAccount": "ખાતું કાઢી નાખો",
    "dashboard.notifSection": "સૂચનાઓ",
    "dashboard.pushNotifs": "પુશ સૂચનાઓ",
    "dashboard.pushDesc": "તાત્કાલિક મેળ અને ચેટ માટે અપડેટ્સ",
    "dashboard.emailReports": "ઈમેલ અહેવાલો",
    "dashboard.emailDesc": "અધિકાર વગરની વસ્તુઓનો સાપ્તાહિક સારાંશ",
    "dashboard.appearanceSection": "દેખાવ",
    "dashboard.theme": "થીમ",
    "dashboard.language": "ભાષા",
    "dashboard.supportSection": "સહાય",
    "dashboard.help": "મદદ",
    "dashboard.contact": "સંપર્ક",
    "dashboard.about": "વિશે",
    "dashboard.logout": "લિન્કોમાંથી લૉગ આઉટ કરો",
    "dashboard.updateEmail": "ઈમેલ સરનામું અપડેટ કરો",
    "dashboard.saveEmail": "ઈમેલ સાચવો",
    "dashboard.changePassword": "પાસવર્ડ બદલો",
    "dashboard.unblock": "અનબ્લૉક કરો",
    "dashboard.noBlocked": "કોઈ બ્લૉક કરેલા વપરાશકર્તાઓ નથી.",
    "dashboard.contactSupport": "લિન્કો સહાયનો સંપર્ક કરો",
    "dashboard.supportDesc": "સામાન્ય સહાય અથવા સંકલન પ્રશ્નો માટે અમારા ડેવલપર્સનો સંપર્ક કરો:",
    "dashboard.aboutLinco": "લિન્કો વિશે",
    "dashboard.aboutDesc": "લિન્કો એ જેમિની એઆઈનો ઉપયોગ કરીને ખોવાયેલી વસ્તુઓ શોધવામાં મદદ કરતી એક સુરક્ષિત એપ્લિકેશન છે.",
    "dashboard.appVersion": "એપ્લિકેશન સંસ્કરણ: v1.3.0 સ્થિર",
    "dashboard.capturePhoto": "ફોટો લો",
    "dashboard.useCamera": "કેમેરા વાપરો",
    "dashboard.chooseGallery": "ગેલેરીમાંથી પસંદ કરો (ક્લાઉડિનરી)",
    "dashboard.confirmDeletion": "કાઢી નાખવાની પુષ્ટિ કરો",
    "dashboard.deletionWarning": "આ ક્રિયા કાયમી છે અને તેને પૂર્વવત્ કરી શકાતી નથી. તમારો બધો ડેટા કાઢી નાખવામાં આવશે.",
    "dashboard.typePasswordConfirm": "પુષ્ટિ માટે તમારો પાસવર્ડ લખો",
    "dashboard.typeDeletePrompt": "તમારું ખાતું કાયમ માટે કાઢી નાખવા નીચે DELETE લખો.",
    "ownerClaims.controlBoard": "દાવો નિયંત્રણ બોર્ડ",
    "ownerClaims.enterPin": "સુરક્ષા પિન દાખલ કરો",
    "ownerClaims.pinDesc": "કનેક્શન અનલૉક કરવા માટે નોંધણી વખતે આપેલ ૪ અંકનો પિન દાખલ કરો.",
    "ownerClaims.clear": "સાફ કરો",
    "ownerClaims.authenticating": "પ્રમાણીકરણ થઈ રહ્યું છે...",
    "ownerClaims.integrityScore": "જેમિની અખંડિતતા સ્કોર",
    "ownerClaims.reviewNotice": "જવાબોની સમીક્ષા કરો. મંજૂર કરવાથી સુરક્ષિત પુનઃપ્રાપ્તિ રૂમ સક્રિય થશે.",
    "ownerClaims.completeHandover": "સોંપણી પૂર્ણ કરો",
    "ownerClaims.postClosed": "આ પોસ્ટ બંધ કરવામાં આવી છે. અગાઉના દાવાઓનો ઇતિહાસ નીચે દેખાય છે.",
    "ownerClaims.closeWindow": "વિંડો બંધ કરો",
    "ownerClaims.approved": "મંજૂર",
    "ownerClaims.resolved": "ઉકેલાયેલ",
    "ownerClaims.youReturned": "તમે પરત કર્યું:",
    "ownerClaims.meetingCoords": "સુરક્ષિત મુલાકાતના કોઓર્ડિનેટ્સ લખો...",
    "pin.title": "સુરક્ષા પિન પ્રવિષ્ટિ",
    "pin.passcode": "૪ અંકનો પાસકોડ",
    "pin.verifying": "ચકાસણી થઈ રહી છે...",
    "pin.clear": "સાફ કરો",
    "pin.unlock": "સંવેદનશીલ સંપર્ક અનલૉક કરો",
    "pin.promise": "તમારો પિન તમારી અંગત માહિતીને જાહેર ઍક્સેસથી સુરક્ષિત રાખે છે.",
    "communityFound.title": "આ વસ્તુ મારી પાસે છે",
    "communityFound.protocol": "શૂન્ય-વિશ્વાસ પ્રોટોકોલ",
    "communityFound.verifyFinding": "મળ્યાની ચકાસણી કરો",
    "communityFound.withoutLeaking": "ખાનગી ડેટા લીક કર્યા વગર",
    "communityFound.lostReported": "ખોવાયેલી વસ્તુની નોંધણી",
    "communityFound.whereFound": "તમને આ ક્યાં મળી?",
    "communityFound.insideContents": "અંદરની સામગ્રી / ચોક્કસ વસ્તુઓ (વૈકલ્પિક)",
    "communityFound.secretDetails": "અનન્ય લક્ષણો / ગુપ્ત વિગતો",
    "communityFound.createPin": "તમારો સુરક્ષા પિન બનાવો",
    "communityFound.reward": "ઇનામ",
    "communityFound.registeredNotice": "નોંધણી થઈ ગઈ છે. માલિકને તમારા જવાબોની સમીક્ષા કરવા માટે સૂચિત કરવામાં આવ્યા છે.",
    "claimTracker.title": "રિકવરી સ્થિતિ સમયરેખા",
    "claimTracker.protocols": "સુરક્ષિત રિકવરી પ્રોટોકોલ",
    "claimTracker.publicSpaces": "મેટ્રો સ્ટેશન અથવા કેફે જેવી જાહેર અને સારી પ્રકાશવાળી જગ્યાએ મળો.",
    "claimTracker.verifyCarefully": "ઇનામ આપતા પહેલાં વસ્તુની કાળજીપૂર્વક તપાસ કરો.",
    "claimTracker.documentDetails": "મીટિંગની વિગતો નોંધવા માટે અમારી સુરક્ષિત ચેટનો ઉપયોગ કરો.",
    "claimTracker.lookupAnother": "બીજું શોધો",
    "claimTracker.unsuccessful": "દાવો મૂલ્યાંકન અસફળ",
    "claimTracker.trustCheck": "પરસ્પર વિશ્વાસ તપાસ",
    "claimTracker.awaitingApproval": "શોધકની મંજૂરીની રાહ જોઈ રહ્યા છીએ",
    "claimTracker.recoveryRoom": "સુરક્ષિત રિકવરી રૂમ",
    "claimTracker.enterRoom": "રિકવરી રૂમમાં પ્રવેશ કરો",
    "claimTracker.discussion": "સંકલિત સોંપણી ચર્ચા",
    "recovery.transmissionSecured": "ડેટા સુરક્ષિત",
    "recovery.reportIndexed": "અહેવાલ સફળતાપૂર્વક અનુક્રમિત થયો",
    "recovery.dossierActive": "તમારી ચકાસણી ફાઇલ હવે સક્રિય છે. જેમિની સક્રિય અનુક્રમણિકાઓનું વિશ્લેષણ કરી રહ્યું છે.",
    "recovery.engineTitle": "એઆઈ રિકવરી સંભાવના એન્જિન",
    "recovery.retrievalLikelihood": "પરત મળવાની શક્યતા:",
    "recovery.analyzedFactors": "વિશ્લેષણ કરેલ રિકવરી પરિબળો",
    "recovery.semanticNotice": "અમારું મૉડલ મેળ ખાવા માટે બ્રાન્ડ, રંગ અને ઓળખકર્તાઓને બહાર કાઢે છે.",
    "recovery.uniqueIdentifier": "અનન્ય ઓળખકર્તા સંપૂર્ણ ચકાસાયેલ મેળને સક્ષમ કરે છે.",
    "recovery.setReward": "ઇનામ નક્કી કરો",
    "reward.fairRange": "અંદાજિત યોગ્ય મર્યાદા",
    "reward.suggestReward": "ઇનામ સૂચવો",
    "reward.customReward": "કસ્ટમ ઇનામ રકમ",
    "privacy.complianceProtocols": "અનુપાલન, ગોપનીયતા અને વિશ્વાસ પ્રોટોકોલ",
    "privacy.title": "વિશ્વાસ અને અનુપાલન કેન્દ્ર",
    "privacy.subtitle": "અમે વપરાશકર્તા સુરક્ષા અને પારદર્શિતાના ઉચ્ચતમ ધોરણોનું પાલન કરીએ છીએ.",
    "privacy.exitSection": "વિભાગમાંથી બહાર નીકળો",
    "privacy.privacyPolicy": "ગોપનીયતા નીતિ",
    "privacy.lastUpdated": "છેલ્લું અપડેટ: ૭ જુલાઈ, ૨૦૨૬. ડેટા ન્યૂનતમકરણ અમારો પાયો છે.",
    "privacy.dataAcquisition": "અમે ફક્ત ખોવાયેલી વસ્તુઓ શોધવા માટે જરૂરી ડેટા એકત્રિત કરીએ છીએ:",
    "privacy.spatiotemporalTags": "અવકાશી-સાંપ્રત ટૅગ્સ:",
    "privacy.coldStorage": "સ્વચાલિત કોલ્ડ સ્ટોરેજ પહેલાં મહત્તમ મર્યાદા.",
    "privacy.cookiePreferences": "કૂકી પસંદગીઓ અને સંમતિ નીતિઓનું સંચાલન કરો.",
    "privacy.purgeBrowser": "આ બ્રાઉઝરમાંથી કૂકીઝ અને કેશ કરેલ ડેટા તરત જ કાઢી નાખો.",
    "privacy.hereToHelp": "અમે મદદ માટે અહીં છીએ.",
    "privacy.connectFounder": "પ્રતિસાદ અથવા મદદ માટે અમારા નેટવર્ક પ્રોફાઇલ પર સંપર્ક કરો.",
    "cookie.title": "ગોપનીયતા સાર્વભૌમત્વ",
    "cookie.message": "અમે માત્ર ખોવાયેલી વસ્તુઓ પાછી મેળવવા માટે જરૂરી માહિતી એકત્રિત કરીએ છીએ.",
    "cookie.trackingNotice": "માલિકી સાબિત ન થાય ત્યાં સુધી તમારી ઓળખ ખાનગી રહે છે. કોઈ ટ્રેકિંગ નથી.",
    "cookie.acceptAll": "બધું સ્વીકારો",
    "cookie.learnMore": "વધુ જાણો",
    "about.tagline": "સમુદાયોને જોડવું, વસ્તુઓ પરત મેળવવી",
    "about.mission": "લિન્કો નૈતિક એઆઈ અને સામુદાયિક વિશ્વાસનો ઉપયોગ કરીને ખોવાયેલી વસ્તુઓ તેમના સાચા માલિકો સુધી પહોંચાડવા માટે સમર્પિત છે.",
    "notifications.title": "સૂચનાઓ",
    "notifications.empty": "કોઈ નવી સૂચના નથી",
    "notifications.markAllRead": "બધી વંચાયેલ તરીકે ચિહ્નિત કરો",
    "notifications.clearAll": "બધી સાફ કરો",
    "notifications.matchFoundTitle": "સંભવિત મેળ મળ્યો",
    "notifications.matchFoundMsg": "અમારા એઆઈ મેચિંગ એન્જિન દ્વારા એક સંભવિત મેળ શોધાયો છે.",
    "notifications.claimReceivedTitle": "નવો દાવો સબમિટ કર્યો",
    "notifications.claimReceivedMsg": "એક નાગરિકે તમારી લિસ્ટિંગ માટે ચકાસણી જવાબો સબમિટ કર્યા છે.",
    "notifications.claimApprovedTitle": "દાવો મંજૂર",
    "notifications.claimApprovedMsg": "તમારો દાવો વસ્તુના માલિક દ્વારા ચકાસાયેલ અને મંજૂર કરવામાં આવ્યો છે.",
    "notifications.chatMessageTitle": "રિકવરી રૂમમાં નવો સંદેશ",
    "notifications.chatMessageMsg": "તમને તમારા પુનઃપ્રાપ્તિ સંકલન અંગે નવો સંદેશ મળ્યો છે.",
    "notifications.handoverDoneTitle": "સોંપણીની પુષ્ટિ થઈ",
    "notifications.handoverDoneMsg": "વસ્તુ પરત મળવાની પુષ્ટિ થઈ ગઈ છે અને કેસ હવે ઉકેલાઈ ગયો છે.",
    "enhance.button": "એઆઈ વર્ણન સુધારો",
    "enhance.loading": "જેમિની એઆઈ તમારું વર્ણન વ્યવસ્થિત કરી રહ્યું છે...",
    "enhance.apply": "સુધારેલ વર્ણન વાપરો",
    "enhance.discard": "મૂળ વર્ણન રાખો",
    "enhance.rewardTitle": "એઆઈ વાજબી ઇનામ સૂચન",
    "enhance.rewardCalculated": "સૂચવેલ ઇનામ: ₹",
    "enhance.rewardReason": "વસ્તુ શ્રેણી, બ્રાન્ડ મૂલ્ય અને સમુદાયના ધોરણો પર આધારિત.",
    "timeline.reconstruct": "સમયરેખા પુનઃનિર્માણ કરો",
    "timeline.loading": "મુસાફરી માર્ગ અને ચેકપોઇન્ટનું વિશ્લેષણ થઈ રહ્યું છે...",
    "timeline.spotLikelihood": "સંભવિત ખોવાઈ જવાનું સ્થળ:",
    "timeline.window": "સંભવિત સમય વિંડો:",
    "timeline.analysis": "સંપૂર્ણ મુસાફરી વિશ્લેષણ:",
    "timeline.confidence": "માર્ગ વિશ્વસનીયતા:",
    "timeline.addPoint": "માર્ગ ચેકપોઇન્ટ ઉમેરો",
    "timeline.pointName": "ચેકપોઇન્ટ નામ / સ્ટેશન",
    "chat.assistant": "એઆઈ સહાયક",
    "chat.subtitle": "તમારો વાતચીત સાથી",
    "chat.description": "ખોવાયેલી કે મળેલી વસ્તુ ૬૦ સેકન્ડમાં નોંધો. બોલો અથવા તમારી ભાષામાં ટાઇપ કરો.",
    "chat.startAssistant": "એઆઈ રિપોર્ટ સહાયક શરૂ કરો",
    "chat.location": "સ્થળ:",
    "chat.securityPin": "સુરક્ષા પિન:",
    "chat.skipPhoto": "ફોટો છોડો",
    "chat.item": "વસ્તુ:",
    "chat.errorLoading": "ચેટબોટ સહાયક લોડ કરવામાં ભૂલ આવી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    "chat.welcomeMessage": "લિન્કોસાથીમાં સ્વાગત છે! હું તમારો સાથી છું. મને કહો શું ખોવાયું કે મળ્યું છે.",
    "chat.networkError": "માફ કરશો, નેટવર્ક સમસ્યા આવી. કૃપા કરીને ફરી પ્રયાસ કરો!",
    "chat.understoodError": "મને બરાબર સમજાયું નથી. શું તમે વધુ વિગત આપી શકો છો?",
    "feed.lostOnly": "ખોવાયેલી વસ્તુઓ",
    "feed.foundOnly": "મળેલી વસ્તુઓ",
    "feed.filterByCategory": "શ્રેણી",
    "feed.filterByCity": "શહેર",
    "feed.filterByUrgency": "પ્રાથમિકતા",
    "feed.empty": "સક્રિય શોધ માપદંડો સાથે કોઈ વસ્તુ મેળ ખાતી નથી.",
    "feed.emptyAction": "નવી વસ્તુ નોંધો",
    "matches.contactFinder": "શોધકનો સંપર્ક કરો",
    "matches.contactOwner": "માલિકનો સંપર્ક કરો",
    "matches.verifyOwnership": "માલિકી ચકાસો",
    "claim.title": "માલિકી દાવો સબમિટ કરો",
    "claim.subtitle": "જાહેર સંપર્ક લીક કર્યા વિના એઆઈ સુરક્ષા સાથે માલિકી ચકાસો.",
    "claim.questionsTitle": "ચકાસણી પ્રશ્નો",
    "claim.questionsSubtitle": "અસલી માલિકી દર્શાવવા માટે પ્રશ્નોના જવાબ આપો:",
    "claim.answerPlaceholder": "આ પ્રશ્નનો તમારો જવાબ...",
    "claim.submit": "સમીક્ષા માટે દાવો સબમિટ કરો",
    "claim.submitting": "ચકાસણી વિગતો સબમિટ થઈ રહી છે...",
    "claim.success": "દાવો સબમિટ થયો! માલિક તમારા જવાબોની સમીક્ષા કરશે.",
    "dashboard.myReports": "મારા અહેવાલો",
    "dashboard.myClaims": "મારા દાવાઓ",
    "dashboard.savedPosts": "સાચવેલી પોસ્ટ્સ",
    "help.title": "વારંવાર પૂછાતા પ્રશ્નો",
    "help.q1": "લિન્કો મારી ગોપનીયતાનું રક્ષણ કેવી રીતે કરે છે?",
    "help.a1": "લિન્કો તમારી સંપર્ક માહિતી ક્યારેય જાહેર કરતું નથી. માત્ર પરસ્પર ચકાસણી પછી જ તે ખુલે છે.",
    "help.q2": "જ્યારે હું ખોવાયેલી વસ્તુ નોંધું છું ત્યારે શું થાય છે?",
    "help.a2": "અમારું એઆઈ તમારા અહેવાલની સરખામણી બધા શહેરોમાં મળેલી વસ્તુઓ સાથે કરે છે.",
    "help.q3": "માલિકી ચકાસણી કેવી રીતે કાર્ય કરે છે?",
    "help.a3": "દાવેદારોએ એઆઈ દ્વારા તૈયાર કરાયેલા ગુપ્ત પ્રશ્નોના જવાબો આપવાના હોય છે જે ફક્ત સાચા માલિક જ જાણે છે.",
    "help.q4": "શું લિન્કો વાપરવા માટે મફત છે?",
    "help.a4": "હા, લિન્કો સંપૂર્ણપણે મફત અને સમુદાય-સંચાલિત છે.",
    "home.heroTitle": "એઆઈ અને ચકાસાયેલ વિશ્વાસ સાથે ખોવાયેલી વસ્તુઓ પરત મેળવો",
    "home.heroSubtitle": "ભારતનું સમુદાય-સંચાલિત લૉસ્ટ એન્ડ ફાઉન્ડ પ્લેટફોર્મ. સુરક્ષિત, ખાનગી અને જેમિની એઆઈ દ્વારા સંચાલિત.",
    "home.statsRecovered": "પરત મળેલી વસ્તુઓ",
    "home.statsActive": "સક્રિય નાગરિક દેખરેખ",
    "home.statsCities": "આવરી લીધેલા શહેરો",
    "home.howItWorks": "લિન્કો કેવી રીતે કાર્ય કરે છે",
    "home.step1Title": "૧. સેકન્ડોમાં નોંધણી કરો",
    "home.step1Desc": "૩૯ ભાષાઓમાં અવાજ, લખાણ અથવા ફોટો દ્વારા વસ્તુ નોંધો.",
    "home.step2Title": "૨. સ્માર્ટ એઆઈ મેળ",
    "home.step2Desc": "જેમિની દ્રશ્ય લક્ષણો અને વર્ણનોની સરખામણી કરે છે.",
    "home.step3Title": "૩. ચકાસાયેલ સોંપણી",
    "home.step3Desc": "ગુપ્ત પ્રશ્નો દ્વારા દાવા ચકાસો અને સુરક્ષિત રીતે વસ્તુ પરત મેળવો.",
}

# Bengali new keys
BN_NEW = {
    "category.Wallet / Purse": "মানিব্যাগ / পার্স",
    "category.Bag / Luggage": "ব্যাগ / লাগেজ",
    "category.ID / Card": "পরিচয়পত্র / কার্ড",
    "urgency.Contains ID": "পরিচয়পত্র রয়েছে",
    "voice.stop": "রেকর্ডিং থামান",
    "voice.error": "কণ্ঠস্বর সনাক্তকরণে ত্রুটি হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "voice.hint": "জিনিসের ব্র্যান্ড, রঙ, স্থান এবং তারিখের মতো বিবরণ বলুন।",
    "report.title": "জিনিস রিপোর্ট করুন",
    "report.subtitle": "স্মার্ট স্থানীয় সমন্বয়ের মাধ্যমে হারানো বা পাওয়া জিনিস নথিভুক্ত করুন।",
    "report.type": "রিপোর্টের ধরন",
    "report.typeLost": "আমার জিনিস হারিয়ে গেছে",
    "report.typeFound": "আমি একটি জিনিস পেয়েছি",
    "report.stepBasics": "১. প্রাথমিক বিবরণ",
    "report.stepLocation": "২. স্থান ও তারিখ",
    "report.stepPhotos": "৩. ছবি ও সূত্র",
    "report.stepSecurity": "৪. নিরাপত্তা ও যোগাযোগ",
    "report.itemTitle": "জিনিসের নাম",
    "report.itemTitlePlaceholder": "উদাঃ কালো লেদার টাইটান ঘড়ি, নীল ওয়াইল্ডক্রাফ্ট ব্যাগ",
    "report.category": "বিভাগ",
    "report.selectCategory": "জিনিসের বিভাগ নির্বাচন করুন",
    "report.description": "বিস্তারিত বিবরণ",
    "report.descriptionPlaceholder": "রঙ, মডেল, দাগ, সনাক্তকরণ চিহ্ন, ভেতরের জিনিস ইত্যাদি বলুন...",
    "report.location": "স্থান (যেখানে পাওয়া গেছে / হারিয়েছে)",
    "report.locationPlaceholder": "উদাঃ শিয়ালদহ স্টেশন গেট ৩, কলকাতা",
    "report.date": "তারিখ ও আনুমানিক সময়",
    "report.urgency": "জরুরি স্তর",
    "report.urgencyNormal": "সাধারণ",
    "report.urgencyUrgent": "জরুরি",
    "report.urgencyMedical": "চিকিৎসা সংক্রান্ত / অত্যন্ত গুরুত্বপূর্ণ",
    "report.photos": "ছবি আপলোড করুন",
    "report.photosHint": "স্পষ্ট ছবি এআই মিলকরণে অনেক সাহায্য করে।",
    "report.reward": "পুরস্কারের পরিমাণ (ঐচ্ছিক)",
    "report.rewardPlaceholder": "₹ টাকা হিসেবে পরিমাণ",
    "report.contact": "হোয়াটসঅ্যাপ / ফোন যোগাযোগ",
    "report.contactPlaceholder": "১০ সংখ্যার মোবাইল নম্বর",
    "report.pin": "৪ সংখ্যার নিরাপত্তা পিন",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "পরে এডিট করতে বা সমাধান চিহ্নিত করতে প্রয়োজন।",
    "report.submit": "কমিউনিটিতে রিপোর্ট প্রকাশ করুন",
    "report.submitting": "সুরক্ষিত রেজিস্ট্রিতে প্রকাশ করা হচ্ছে...",
    "report.success": "আপনার রিপোর্ট সফলভাবে প্রকাশিত হয়েছে!",
    "report.viewListing": "তালিকায় দেখুন",
    "report.brand": "ব্র্যান্ড / প্রস্তুতকারক",
    "report.brandPlaceholder": "উদাঃ অ্যাপল, স্যামসাং, টাইটান, ওয়াইল্ডক্রাফ্ট",
    "report.primaryColor": "প্রধান রঙ",
    "report.secondaryColor": "সহকারী রঙ",
    "report.landmark": "নিকটবর্তী ল্যান্ডমার্ক",
    "report.landmarkPlaceholder": "উদাঃ প্ল্যাটফর্ম ৪ এস্কেলেটরের কাছে",
    "report.secretClue": "গোপন সনাক্তকরণ সূত্র (যাচাইয়ের জন্য)",
    "report.secretCluePlaceholder": "উদাঃ ভেতরের পকেটে লাল কিচেন, খোদাই করা নাম 'RS'",
    "feed.searchPlaceholder": "জিনিস, ট্যাগ, রঙ, ব্র্যান্ড, শহর খুঁজুন...",
    "feed.filters": "ফিল্টার",
    "feed.applyFilters": "ফিল্টার প্রয়োগ করুন",
    "feed.recentSearches": "সাম্প্রতিক অনুসন্ধান",
    "feed.savedSearches": "সংরক্ষিত অনুসন্ধান",
    "feed.listingRegistry": "তালিকা রেজিস্ট্রি",
    "feed.category": "বিভাগ",
    "feed.allCategories": "সকল বিভাগ",
    "feed.city": "শহর",
    "feed.allCities": "সকল শহর",
    "feed.dateRange": "তারিখের সীমা",
    "feed.proximity": "দূরত্বের পরিধি",
    "feed.allProximities": "সকল দূরত্ব (যেকোনো পরিধি)",
    "feed.within5km": "৫ কিমির মধ্যে",
    "feed.within15km": "১৫ কিমির মধ্যে",
    "feed.within30km": "৩০ কিমির মধ্যে",
    "feed.within50km": "৫০ কিমির মধ্যে",
    "feed.sortCatalog": "ক্যাটালগ সাজান",
    "feed.colorSwatch": "রঙের প্যালেট",
    "feed.allColors": "সকল রঙ",
    "feed.hardwareBrand": "ব্র্যান্ড প্রস্তুতকারক",
    "feed.allBrands": "সকল ব্র্যান্ড",
    "feed.resetFilters": "ফিল্টার রিসেট করুন",
    "feed.viewList": "তালিকা",
    "feed.viewMap": "মানচিত্র",
    "feed.noMatchesFound": "রেজিস্ট্রিতে কোনো মিল পাওয়া যায়নি",
    "feed.noMatchesDesc": "এই ফিল্টারগুলির সাথে কোনো জিনিস পাওয়া যায়নি। অনুসন্ধান পরিবর্তন করুন বা ফিল্টার রিসেট করুন।",
    "feed.reportItem": "হারানো/পাওয়া জিনিস রিপোর্ট করুন",
    "feed.saveParameters": "অনুসন্ধান মানদণ্ড সংরক্ষণ করুন",
    "feed.deleteSavedSearch": "সংরক্ষিত অনুসন্ধান মুছুন",
    "feed.universalSearchBar": "সার্বজনীন অনুসন্ধান বার",
    "feed.clearSearch": "অনুসন্ধান সাফ করুন",
    "feed.toggleFilters": "উন্নত ফিল্টার চালু/বন্ধ",
    "feed.newestFirst": "নতুনতম আগে",
    "feed.oldestFirst": "পুরোনো আগে",
    "feed.highestReward": "সর্বোচ্চ পুরস্কার",
    "feed.closestDistance": "নিকটতম দূরত্ব",
    "postcard.unlockConnection": "সংযোগ আনলক করুন",
    "postcard.iHaveThisItem": "এই জিনিসটি আমার কাছে আছে",
    "postcard.reclaimed": "পুনরুদ্ধার এবং হস্তান্তর করা হয়েছে",
    "postcard.claims": "দাবিসমূহ",
    "postcard.image": "ছবি",
    "postcard.qr": "কিউআর",
    "postcard.aiMatch": "এআই মিল",
    "postcard.geminiMatches": "জেমিনি স্মার্ট মিল খুঁজে পেয়েছে!",
    "postcard.contactOwner": "মালিকের সাথে যোগাযোগ করুন",
    "postcard.creatorNotice": "শুধুমাত্র এই তালিকার যাচাইকৃত নির্মাতা মিলের বিবরণ দেখতে পারেন।",
    "postcard.markResolved": "সমাধান হয়েছে চিহ্নিত করুন",
    "postcard.deleteListing": "তালিকা মুছুন",
    "postcard.unlockWithPin": "নিরাপত্তা পিন দিয়ে যোগাযোগ আনলক করুন",
    "postcard.manageClaims": "দাবি পরিচালনা ও অনুমোদন/প্রত্যাখ্যান করুন",
    "postcard.shareTemplate": "শেয়ার টেক্সট কপি করুন",
    "postcard.downloadCard": "কার্ড ছবি হিসেবে ডাউনলোড করুন",
    "postcard.qrSettings": "ইন্টারেক্টিভ কিউআর ও প্রিন্ট সেটিংস",
    "postcard.postedOn": "পোস্ট করা হয়েছে",
    "postcard.reward": "পুরস্কার",
    "postcard.secureHandover": "সুরক্ষিত হস্তান্তর",
    "matches.title": "এআই স্মার্ট মিল ও পারস্পরিক যাচাইকরণ",
    "matches.subtitle": "জেমিনি হারানো এবং পাওয়া তালিকার তুলনা করে। চ্যাটের আগে পারস্পরিক যাচাইকরণ বাধ্যতামূলক।",
    "matches.myMatches": "আমার মিলসমূহ",
    "matches.publicMatches": "পাবলিক মিলসমূহ",
    "matches.threshold": "ন্যূনতম সীমা:",
    "matches.security": "নিরাপত্তা:",
    "matches.mutualApprovalRequired": "পারস্পরিক অনুমোদন প্রয়োজন",
    "matches.noMatchesFound": "কোনো সম্ভাব্য মিল পাওয়া যায়নি",
    "matches.improveReport": "আপনার রিপোর্টে উন্নতি করুন",
    "matches.noPhoto": "কোনো ছবি নেই",
    "matches.chatLive": "লাইভ চ্যাট",
    "matches.chatLocked": "চ্যাট লক করা আছে",
    "matches.inspectReview": "পরিদর্শন ও পর্যালোচনা",
    "matches.openChatLive": "লাইভ চ্যাট খুলুন",
    "matches.verifyApprove": "যাচাই ও অনুমোদন করুন",
    "matches.approvalNotice": "চ্যাট আনলক হওয়ার আগে মালিক এবং প্রাপক উভয়কেই যাচাইকরণ অনুমোদন করতে হবে।",
    "matches.tabComparison": "তুলনা",
    "matches.tabVerification": "যাচাইকরণ",
    "matches.tabTrust": "বিশ্বাস ও হোয়াটসঅ্যাপ",
    "matches.tabHandover": "হস্তান্তর",
    "matches.noImageProvided": "কোনো ছবি প্রদান করা হয়নি",
    "matches.itemName": "জিনিসের নাম",
    "matches.category": "বিভাগ",
    "matches.reward": "পুরস্কার",
    "matches.locationAddress": "স্থান ও ঠিকানা",
    "matches.detailsDescription": "বিস্তারিত বিবরণ",
    "matches.finderContact": "সন্ধানকারীর যোগাযোগ",
    "matches.matchStatus": "মিলের অবস্থা:",
    "matches.mutualConfirmed": "পারস্পরিক অনুমোদন নিশ্চিত হয়েছে। উভয় পক্ষ যাচাই সম্পন্ন করেছে।",
    "matches.mutualProtocol": "পারস্পরিক যাচাইকরণ প্রোটোকল",
    "matches.protocolNotice": "প্রতারণা রোধ করতে উভয় পক্ষ যাচাইয়ের উত্তর জমা দেয়। উভয় পক্ষ অনুমোদন না করা পর্যন্ত চ্যাট লক থাকে।",
    "matches.ownerStatus": "মালিকের অবস্থা",
    "matches.submittedBy": "জমা দিয়েছেন:",
    "matches.aiScore": "এআই যাচাইকরণ স্কোর:",
    "matches.ownerNotSubmitted": "জিনিসের মালিক এখনও উত্তরের বিবরণ জমা দেননি।",
    "matches.finderStatus": "সন্ধানকারীর অবস্থা",
    "matches.finderNotSubmitted": "সন্ধানকারী এখনও উত্তরের বিবরণ জমা দেননি।",
    "matches.actionControls": "অ্যাকশন নিয়ন্ত্রণ",
    "matches.selectRole": "বিবরণ জমা দিতে বা পর্যালোচনা করতে আপনার ভূমিকা নির্বাচন করুন।",
    "matches.iAmOwner": "আমি মালিক",
    "matches.iAmFinder": "আমি এই জিনিসটি পেয়েছি",
    "matches.yourName": "আপনার নাম",
    "matches.contactWhatsApp": "হোয়াটসঅ্যাপ / যোগাযোগ",
    "matches.forensicQuestions": "ফরেনসিক যাচাইকরণ প্রশ্নাবলী",
    "matches.trustTitle": "পারস্পরিক বিশ্বাস ও সুরক্ষিত হোয়াটসঅ্যাপ যোগাযোগ",
    "matches.trustNotice": "কমিউনিটির সুরক্ষার জন্য, সরাসরি ফোন নম্বর কেবল তখনই দৃশ্যমান হয় যখন উভয় পক্ষ \"আমি এই ব্যক্তিকে বিশ্বাস করি\"-তে ক্লিক করে।",
    "matches.ownerTrust": "মালিকের বিশ্বাস",
    "matches.finderTrust": "সন্ধানকারীর বিশ্বাস",
    "matches.unlocked": "আনলক করা হয়েছে",
    "matches.masked": "সুরক্ষিত ও গোপন",
    "matches.contactAlias": "যোগাযোগের নাম / ডাকনাম",
    "matches.phoneWhatsApp": "ফোন / হোয়াটসঅ্যাপ",
    "matches.openWhatsApp": "হোয়াটসঅ্যাপ চ্যাট খুলুন",
    "matches.directCall": "সরাসরি কল",
    "matches.trustInstructions": "হোয়াটসঅ্যাপ লিংক এবং ফোন নম্বর দেখতে উভয় ব্যবহারকারীকে নীচের বোতামে ক্লিক করতে হবে।",
    "matches.trustConsent": "বিশ্বাসে ক্লিক করে, আপনি নিরাপদ হস্তান্তরের জন্য যোগাযোগের বিবরণ ভাগ করতে সম্মত হন।",
    "matches.reunitedResolved": "জিনিস সফলভাবে ফেরত পাওয়া গেছে এবং সমাধান হয়েছে!",
    "matches.reunitedNotice": "মালিক এবং সন্ধানকারী উভয়ই নিরাপদ হস্তান্তর নিশ্চিত করেছেন।",
    "matches.handoverProtocol": "নিরাপদ হস্তান্তর প্রোটোকল",
    "matches.handoverNotice": "জনবহুল স্থানে দেখা করার সময় নির্ধারণ করুন (যেমন মেট্রো স্টেশন বা পুলিশ বুথ)। হস্তান্তরের পর উভয়ই নিশ্চিত করুন।",
    "matches.handoverSchedule": "হস্তান্তরের সময় ও স্থান",
    "matches.publicMeetingSpot": "পাবলিক সাক্ষাতের স্থান",
    "matches.scheduledDateTime": "নির্ধারিত তারিখ / সময়",
    "matches.confirmHandover": "হস্তান্তর নিশ্চিত করুন ও কেস শেষ করুন",
    "matches.confirmHandoverDesc": "সাক্ষাতের স্থানে জিনিস পাওয়ার পর, হস্তান্তর চূড়ান্ত করতে নিশ্চিত করুন।",
    "matches.iHandedOver": "আমি এই জিনিসটি হস্তান্তর করেছি",
    "matches.iReceived": "আমি আমার জিনিস পেয়েছি",
    "matches.chatUnlocksAfter": "যাচাইয়ের পর নিরাপদ চ্যাট আনলক হবে",
    "matches.chatUnlocksDesc": "দাবি যাচাইয়ের পর উভয় পক্ষের মধ্যে এন্ড-টু-এন্ড সুরক্ষিত চ্যাট স্বয়ংক্রিয়ভাবে খুলবে।",
    "matches.goToVerification": "যাচাইকরণ ট্যাবে যান",
    "matches.secureHandoverChat": "সুরক্ষিত হস্তান্তর চ্যাট",
    "matches.connectionVerified": "সংযোগ যাচাইকৃত! নিরাপদ হস্তান্তরের জন্য বার্তা পাঠান।",
    "matches.dismissMatch": "মিল বাতিল করুন",
    "matches.shareMatch": "শেয়ার করুন",
    "matches.directClaim": "সরাসরি দাবি",
    "claim.ownershipIndex": "মালিকানা বিশ্বস্ততা সূচক",
    "claim.safeVerification": "নিরাপদ মালিকানা যাচাইকরণ",
    "claim.stepsNotice": "আমরা হস্তান্তর নিরাপদ এবং খাঁটি করতে ব্যক্তিগত পদক্ষেপ ব্যবহার করি।",
    "claim.protectedContact": "আপনার যোগাযোগের বিবরণ সম্পূর্ণ সুরক্ষিত। কেবল যাচাইকৃত ব্যক্তি এটি দেখতে পারেন।",
    "claim.unlockedMutual": "পারস্পরিক যাচাইয়ের পরেই যোগাযোগের বিকল্পগুলি আনলক হয়। আপনার ফোন কখনও প্রকাশ করা হয় না।",
    "claim.aiEvaluationNotice": "প্রতারণা রোধ করতে আমাদের এআই দাবি মূল্যায়ন করে।",
    "claim.trackingNotice": "অনন্য ট্র্যাকিং কোড উভয় পক্ষকে রক্ষা করে।",
    "claim.modalDescription": "জিনিসটি তার আসল মালিকের কাছে পৌঁছানোর জন্য, আমরা যোগাযোগ ভাগ করার আগে মিল যাচাই করি। দয়া করে নীচের প্রশ্নের উত্তর দিন।",
    "claim.aiPreparingQuestions": "এআই আপনার যাচাইকরণ প্রশ্ন প্রস্তুত করছে...",
    "claim.claimantName": "দাবীদারের নাম",
    "claim.officialNamePlaceholder": "আপনার আনুষ্ঠানিক নাম",
    "claim.whatsappMobile": "হোয়াটসঅ্যাপ মোবাইল",
    "claim.mobilePlaceholder": "৯৮৭৬৫৪৩২১০",
    "claim.verifyItemDetails": "জিনিসের বিবরণ যাচাই করুন",
    "claim.detailsPlaceholder": "দয়া করে বিস্তারিত বলুন (চিহ্ন, ভেতরের জিনিস, বিলের বিবরণ ইত্যাদি)...",
    "claim.verificationRegistered": "যাচাইকরণ নিবন্ধিত",
    "claim.detailsSavedSecurely": "আপনার বিবরণ নিরাপদে সংরক্ষণ করা হয়েছে। আমাদের এআই বিবরণ মিলিয়েছে।",
    "claim.verificationId": "যাচাইকরণ আইডি (দাবি আইডি)",
    "claim.aiMatchDetails": "এআই মিলের বিবরণ",
    "claim.bookmarkLink": "সরাসরি লিংক (পরে দেখার জন্য বুকমার্ক করুন)",
    "claim.doneAwaitSignoff": "সম্পন্ন এবং মালিকের অনুমোদনের অপেক্ষা করুন",
    "auth.recoverBelongings": "বিশ্বস্ত নাগরিক এবং বুদ্ধিমান যাচাইয়ের মাধ্যমে হারানো জিনিস নিরাপদে ফিরে পান।",
    "auth.startEmail": "ইমেল দিয়ে শুরু করুন",
    "auth.continuePhone": "ফোন দিয়ে এগিয়ে যান",
    "auth.signIn": "সাইন ইন করুন",
    "auth.welcomeBack": "স্বাগতম",
    "auth.resumeTracking": "ট্র্যাকিং চালিয়ে যেতে আপনার লিঙ্কো অ্যাকাউন্টে সাইন ইন করুন।",
    "auth.emailOrUsername": "ইমেল বা ব্যবহারকারীর নাম",
    "auth.password": "পাসওয়ার্ড",
    "auth.forgotPassword": "পাসওয়ার্ড ভুলে গেছেন?",
    "auth.createAccount": "অ্যাকাউন্ট তৈরি করুন",
    "auth.joinNetwork": "স্মার্ট স্থানীয় অভিভাবক নেটওয়ার্কে যোগ দিন।",
    "auth.fullName": "সম্পূর্ণ নাম",
    "auth.username": "ব্যবহারকারীর নাম",
    "auth.emailAddress": "ইমেল ঠিকানা",
    "auth.confirmPassword": "পাসওয়ার্ড নিশ্চিত করুন",
    "auth.acceptPolicy": "আমি গোপনীয়তা নীতি গ্রহণ করছি এবং এনক্রিপ্ট করা ডেটা শেয়ারিংয়ে সম্মতি দিচ্ছি।",
    "auth.resetPassword": "পাসওয়ার্ড রিসেট করুন",
    "auth.resetNotice": "আপনার অ্যাকাউন্টে পুনরায় প্রবেশের জন্য আমরা একটি সুরক্ষিত লিংক পাঠাব।",
    "auth.sendResetLink": "রিসেট লিংক পাঠান",
    "auth.returnSignIn": "সাইন ইন-এ ফিরে যান",
    "auth.setupProfile": "আপনার প্রোফাইল সেট আপ করুন",
    "auth.setupNotice": "আপনার প্রোফাইল সম্পূর্ণ করুন যাতে নাগরিকরা আপনার সাথে সমন্বয় করতে পারেন।",
    "auth.takeSnapshot": "ছবি তুলুন",
    "auth.choosePhoto": "ছবি নির্বাচন করুন",
    "auth.cityNeighborhood": "শহর / এলাকা (প্রয়োজনীয়)",
    "auth.shortBio": "সংক্ষিপ্ত বিবরণ (ঐচ্ছিক)",
    "auth.completeSetup": "প্রোফাইল সেটআপ সম্পন্ন করুন",
    "dashboard.welcomeTitle": "আপনার প্রোফাইল সেট আপ করুন",
    "dashboard.welcomeDesc": "লিঙ্কোতে স্বাগতম। নিজের সম্পর্কে কিছু বলুন যাতে নাগরিকরা আপনার সাথে সমন্বয় করতে পারেন।",
    "dashboard.chooseAvatar": "প্রোফাইল ছবি নির্বাচন করুন",
    "dashboard.fullName": "সম্পূর্ণ নাম",
    "dashboard.username": "ব্যবহারকারীর নাম",
    "dashboard.bio": "বিবরণ (ঐচ্ছিক)",
    "dashboard.city": "শহর",
    "dashboard.createProfile": "প্রোফাইল তৈরি করুন",
    "dashboard.skipForNow": "আপাতত এড়িয়ে যান",
    "dashboard.changeCover": "কভার পরিবর্তন করুন",
    "dashboard.editProfile": "প্রোফাইল সম্পাদনা করুন",
    "dashboard.shareProfile": "প্রোফাইল শেয়ার করুন",
    "dashboard.settings": "সেটিংস",
    "dashboard.editDetails": "প্রোফাইলের বিবরণ সম্পাদনা করুন",
    "dashboard.accountSection": "অ্যাকাউন্ট",
    "dashboard.email": "ইমেল",
    "dashboard.password": "পাসওয়ার্ড",
    "dashboard.privacySection": "গোপনীয়তা",
    "dashboard.blockedUsers": "অবরুদ্ধ ব্যবহারকারী",
    "dashboard.downloadData": "আমার ডেটা ডাউনলোড করুন",
    "dashboard.deleteAccount": "অ্যাকাউন্ট মুছুন",
    "dashboard.notifSection": "বিজ্ঞপ্তি",
    "dashboard.pushNotifs": "পুশ বিজ্ঞপ্তি",
    "dashboard.pushDesc": "তাত্ক্ষণিক মিল এবং চ্যাটের আপডেট",
    "dashboard.emailReports": "ইমেল রিপোর্ট",
    "dashboard.emailDesc": "দাবাহীন জিনিসের সাপ্তাহিক সারাংশ",
    "dashboard.appearanceSection": "চেহারা",
    "dashboard.theme": "থিম",
    "dashboard.language": "ভাষা",
    "dashboard.supportSection": "সহায়তা",
    "dashboard.help": "সাহায্য",
    "dashboard.contact": "যোগাযোগ",
    "dashboard.about": "সম্পর্কে",
    "dashboard.logout": "লিঙ্কো থেকে লগ আউট করুন",
    "dashboard.updateEmail": "ইমেল ঠিকানা আপডেট করুন",
    "dashboard.saveEmail": "ইমেল সংরক্ষণ করুন",
    "dashboard.changePassword": "পাসওয়ার্ড পরিবর্তন করুন",
    "dashboard.unblock": "আনব্লক করুন",
    "dashboard.noBlocked": "কোনো অবরুদ্ধ ব্যবহারকারী নেই।",
    "dashboard.contactSupport": "লিঙ্কো সহায়তার সাথে যোগাযোগ করুন",
    "dashboard.supportDesc": "সাধারণ সহায়তা বা সমন্বয় প্রশ্নের জন্য আমাদের ডেভেলপারদের সাথে যোগাযোগ করুন:",
    "dashboard.aboutLinco": "লিঙ্কো সম্পর্কে",
    "dashboard.aboutDesc": "লিঙ্কো হলো একটি ব্যক্তিগত লস্ট অ্যান্ড ফাউন্ড অ্যাপ যা জেমিনি এআই ব্যবহার করে হারানো জিনিস খুঁজে পেতে সাহায্য করে।",
    "dashboard.appVersion": "অ্যাপ্লিকেশন সংস্করণ: v1.3.0 স্থিতিশীল",
    "dashboard.capturePhoto": "ছবি তুলুন",
    "dashboard.useCamera": "ক্যামেরা ব্যবহার করুন",
    "dashboard.chooseGallery": "গ্যালারি থেকে নির্বাচন করুন (ক্লাউডিনারি)",
    "dashboard.confirmDeletion": "মুছে ফেলার নিশ্চিতকরণ",
    "dashboard.deletionWarning": "এই পদক্ষেপটি চূড়ান্ত এবং ফিরিয়ে আনা যাবে না। আপনার সমস্ত ডেটা মুছে যাবে।",
    "dashboard.typePasswordConfirm": "নিশ্চিত করতে আপনার পাসওয়ার্ড টাইপ করুন",
    "dashboard.typeDeletePrompt": "আপনার অ্যাকাউন্ট স্থায়ীভাবে মুছতে নীচে DELETE টাইপ করুন।",
    "ownerClaims.controlBoard": "দাবি নিয়ন্ত্রণ বোর্ড",
    "ownerClaims.enterPin": "নিরাপত্তা পিন লিখুন",
    "ownerClaims.pinDesc": "সংযোগ আনলক করতে রিপোর্ট তৈরির সময় দেওয়া ৪ সংখ্যার পিনটি লিখুন।",
    "ownerClaims.clear": "সাফ করুন",
    "ownerClaims.authenticating": "প্রমাণীকরণ করা হচ্ছে...",
    "ownerClaims.integrityScore": "জেমিনি সততা স্কোর",
    "ownerClaims.reviewNotice": "উত্তরের পর্যালোচনা করুন। অনুমোদন করলে সুরক্ষিত রিকভারি রুম সক্রিয় হবে।",
    "ownerClaims.completeHandover": "হস্তান্তর সম্পন্ন করুন",
    "ownerClaims.postClosed": "এই পোস্টটি বন্ধ করা হয়েছে। পূর্ববর্তী দাবির ইতিহাস নীচে দৃশ্যমান।",
    "ownerClaims.closeWindow": "উইন্ডো বন্ধ করুন",
    "ownerClaims.approved": "অনুমোদিত",
    "ownerClaims.resolved": "সমাধান হয়েছে",
    "ownerClaims.youReturned": "আপনি ফেরত দিয়েছেন:",
    "ownerClaims.meetingCoords": "নিরাপদ সাক্ষাতের বিবরণ লিখুন...",
    "pin.title": "নিরাপত্তা পিন এন্ট্রি",
    "pin.passcode": "৪ সংখ্যার পাসকোড",
    "pin.verifying": "যাচাই করা হচ্ছে...",
    "pin.clear": "সাফ করুন",
    "pin.unlock": "সংবেদনশীল যোগাযোগ আনলক করুন",
    "pin.promise": "আপনার পিন আপনার ব্যক্তিগত তথ্যকে প্রকাশ্য অ্যাক্সেস থেকে সুরক্ষিত রাখে।",
    "communityFound.title": "এই জিনিসটি আমার কাছে আছে",
    "communityFound.protocol": "জিরো-ট্রাস্ট প্রোটোকল",
    "communityFound.verifyFinding": "প্রাপ্তি যাচাই করুন",
    "communityFound.withoutLeaking": "ব্যক্তিগত ডেটা ফাঁস না করে",
    "communityFound.lostReported": "হারানো জিনিসের রিপোর্ট",
    "communityFound.whereFound": "আপনি এটি কোথায় পেয়েছেন?",
    "communityFound.insideContents": "ভেতরের জিনিস / নির্দিষ্ট উপাদান (ঐচ্ছিক)",
    "communityFound.secretDetails": "অনন্য বৈশিষ্ট্য / গোপন বিবরণ",
    "communityFound.createPin": "আপনার নিরাপত্তা পিন তৈরি করুন",
    "communityFound.reward": "পুরস্কার",
    "communityFound.registeredNotice": "নথিভুক্ত হয়েছে। মালিককে আপনার উত্তর পর্যালোচনার জন্য জানানো হয়েছে।",
    "claimTracker.title": "পুনরুদ্ধারের স্থিতি টাইমলাইন",
    "claimTracker.protocols": "নিরাপদ পুনরুদ্ধার প্রোটোকল",
    "claimTracker.publicSpaces": "মেট্রো স্টেশন বা ক্যাফের মতো আলোকিত পাবলিক স্থানে দেখা করুন।",
    "claimTracker.verifyCarefully": "পুরস্কার দেওয়ার আগে জিনিসটি সাবধানে পরীক্ষা করুন।",
    "claimTracker.documentDetails": "সাক্ষাতের বিবরণ রেকর্ড করতে আমাদের নিরাপদ চ্যাট ব্যবহার করুন।",
    "claimTracker.lookupAnother": "অন্যটি সন্ধান করুন",
    "claimTracker.unsuccessful": "দাবি মূল্যায়ন ব্যর্থ হয়েছে",
    "claimTracker.trustCheck": "পারস্পরিক বিশ্বাস পরীক্ষা",
    "claimTracker.awaitingApproval": "সন্ধানকারীর অনুমোদনের অপেক্ষায়",
    "claimTracker.recoveryRoom": "সুরক্ষিত রিকভারি রুম",
    "claimTracker.enterRoom": "রিকভারি রুমে প্রবেশ করুন",
    "claimTracker.discussion": "সমন্বিত হস্তান্তর আলোচনা",
    "recovery.transmissionSecured": "ডেটা সুরক্ষিত",
    "recovery.reportIndexed": "রিপোর্ট সফলভাবে সূচীবদ্ধ হয়েছে",
    "recovery.dossierActive": "আপনার যাচাইকরণ ফাইল এখন সক্রিয়। জেমিনি সক্রিয় সূচকগুলি বিশ্লেষণ করছে।",
    "recovery.engineTitle": "এআই পুনরুদ্ধার সম্ভাব্যতা ইঞ্জিন",
    "recovery.retrievalLikelihood": "পুনরুদ্ধারের সম্ভাবনা:",
    "recovery.analyzedFactors": "বিশ্লেষিত পুনরুদ্ধারের কারণসমূহ",
    "recovery.semanticNotice": "আমাদের মডেল মিলকরণের জন্য ব্র্যান্ড, রঙ এবং সনাক্তকারী বের করে।",
    "recovery.uniqueIdentifier": "একটি অনন্য সনাক্তকারী সম্পূর্ণ যাচাইকৃত মিল সক্ষম করে।",
    "recovery.setReward": "পুরস্কার নির্ধারণ করুন",
    "reward.fairRange": "আনুমানিক ন্যায্য সীমা",
    "reward.suggestReward": "পুরস্কার প্রস্তাব করুন",
    "reward.customReward": "কাস্টম পুরস্কারের পরিমাণ",
    "privacy.complianceProtocols": "সম্মতি, গোপনীয়তা ও বিশ্বাস প্রোটোকল",
    "privacy.title": "বিশ্বাস ও সম্মতি কেন্দ্র",
    "privacy.subtitle": "আমরা ব্যবহারকারীর নিরাপত্তা ও স্বচ্ছতার সর্বোচ্চ মান বজায় রাখি।",
    "privacy.exitSection": "বিভাগ থেকে প্রস্থান করুন",
    "privacy.privacyPolicy": "গোপনীয়তা নীতি",
    "privacy.lastUpdated": "সর্বশেষ আপডেট: ৭ জুলাই, ২০২৬। ডেটা হ্রাসকরণ আমাদের মূল ভিত্তি।",
    "privacy.dataAcquisition": "আমরা কেবল হারানো জিনিস খুঁজে পেতে প্রয়োজনীয় ডেটা সংগ্রহ করি:",
    "privacy.spatiotemporalTags": "স্থানিক-কালিক ট্যাগ:",
    "privacy.coldStorage": "স্বয়ংক্রিয় কোল্ড স্টোরেজের আগের সর্বোচ্চ সীমা।",
    "privacy.cookiePreferences": "কুকি পছন্দ এবং সম্মতি নীতি পরিচালনা করুন।",
    "privacy.purgeBrowser": "এই ব্রাউজার থেকে কুকিজ এবং ক্যাশ করা ডেটা অবিলম্বে মুছুন।",
    "privacy.hereToHelp": "আমরা সাহায্য করতে এখানে আছি।",
    "privacy.connectFounder": "মতামত বা সহায়তার জন্য আমাদের নেটওয়ার্ক প্রোফাইলে যোগাযোগ করুন।",
    "cookie.title": "গোপনীয়তার সার্বভৌমত্ব",
    "cookie.message": "আমরা কেবল হারানো জিনিস পুনরুদ্ধার করতে প্রয়োজনীয় তথ্য সংগ্রহ করি।",
    "cookie.trackingNotice": "মালিকানা যাচাই না হওয়া পর্যন্ত আপনার পরিচয় ব্যক্তিগত থাকে। কোনো ট্র্যাকিং নেই।",
    "cookie.acceptAll": "সব গ্রহণ করুন",
    "cookie.learnMore": "আরও জানুন",
    "about.tagline": "কমিউনিটি যুক্ত করা, জিনিস ফিরিয়ে দেওয়া",
    "about.mission": "লিঙ্কো নৈতিক এআই এবং কমিউনিটি বিশ্বাসের মাধ্যমে হারানো জিনিস তাদের আসল মালিকদের কাছে পৌঁছে দিতে নিবেদিত।",
    "notifications.title": "বিজ্ঞপ্তি",
    "notifications.empty": "কোনো নতুন বিজ্ঞপ্তি নেই",
    "notifications.markAllRead": "সব পঠিত হিসেবে চিহ্নিত করুন",
    "notifications.clearAll": "সব সাফ করুন",
    "notifications.matchFoundTitle": "সম্ভাব্য মিল পাওয়া গেছে",
    "notifications.matchFoundMsg": "আমাদের এআই ম্যাচিং ইঞ্জিন দ্বারা একটি সম্ভাব্য মিল পাওয়া গেছে।",
    "notifications.claimReceivedTitle": "নতুন দাবি জমা দেওয়া হয়েছে",
    "notifications.claimReceivedMsg": "একজন নাগরিক আপনার তালিকার জন্য যাচাইয়ের উত্তর জমা দিয়েছেন।",
    "notifications.claimApprovedTitle": "দাবি অনুমোদিত",
    "notifications.claimApprovedMsg": "আপনার দাবি জিনিসের মালিক দ্বারা যাচাই ও অনুমোদিত হয়েছে।",
    "notifications.chatMessageTitle": "রিকভারি রুমে নতুন বার্তা",
    "notifications.chatMessageMsg": "আপনার পুনরুদ্ধার সমন্বয় সংক্রান্ত একটি নতুন বার্তা পেয়েছেন।",
    "notifications.handoverDoneTitle": "হস্তান্তর নিশ্চিত হয়েছে",
    "notifications.handoverDoneMsg": "জিনিস ফেরত পাওয়ার বিষয়টি নিশ্চিত হয়েছে এবং কেসটি এখন সমাধান হয়েছে।",
    "enhance.button": "এআই বিবরণ উন্নত করুন",
    "enhance.loading": "জেমিনি এআই আপনার বিবরণ সাজিয়ে তুলছে...",
    "enhance.apply": "পরিমার্জিত বিবরণ ব্যবহার করুন",
    "enhance.discard": "আসল বিবরণ রাখুন",
    "enhance.rewardTitle": "এআই ন্যায্য পুরস্কারের পরামর্শ",
    "enhance.rewardCalculated": "প্রস্তাবিত পুরস্কার: ₹",
    "enhance.rewardReason": "জিনিসের বিভাগ, ব্র্যান্ড মূল্য এবং কমিউনিটি মানের ওপর ভিত্তি করে।",
    "timeline.reconstruct": "টাইমলাইন পুনর্নির্মাণ করুন",
    "timeline.loading": "ভ্রমণের পথ এবং চেকপয়েন্ট বিশ্লেষণ করা হচ্ছে...",
    "timeline.spotLikelihood": "সম্ভাব্য হারানোর স্থান:",
    "timeline.window": "সম্ভাব্য সময়ের পরিধি:",
    "timeline.analysis": "সম্পূর্ণ ভ্রমণের বিশ্লেষণ:",
    "timeline.confidence": "পথের নির্ভরযোগ্যতা:",
    "timeline.addPoint": "পথের চেকপয়েন্ট যোগ করুন",
    "timeline.pointName": "চেকপয়েন্টের নাম / স্টেশন",
    "chat.assistant": "এআই সহকারী",
    "chat.subtitle": "আপনার কথোপকথনের সঙ্গী",
    "chat.description": "৬০ সেকেন্ডে হারানো বা পাওয়া জিনিসের রিপোর্ট করুন। বলুন বা আপনার ভাষায় টাইপ করুন।",
    "chat.startAssistant": "এআই রিপোর্ট সহকারী শুরু করুন",
    "chat.location": "স্থান:",
    "chat.securityPin": "নিরাপত্তা পিন:",
    "chat.skipPhoto": "ছবি এড়িয়ে যান",
    "chat.item": "জিনিস:",
    "chat.errorLoading": "চ্যাটবট সহকারী লোড করার সময় ত্রুটি হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "chat.welcomeMessage": "লিঙ্কোসাথীতে স্বাগতম! আমি আপনার সঙ্গী। বলুন কি হারিয়েছে বা পাওয়া গেছে।",
    "chat.networkError": "দুঃখিত, নেটওয়ার্ক সমস্যা হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন!",
    "chat.understoodError": "আমি ঠিক বুঝতে পারিনি। আপনি কি আরও কিছু বিবরণ দিতে পারেন?",
    "feed.lostOnly": "হারানো জিনিস",
    "feed.foundOnly": "পাওয়া জিনিস",
    "feed.filterByCategory": "বিভাগ",
    "feed.filterByCity": "শহর",
    "feed.filterByUrgency": "জরুরি স্তর",
    "feed.empty": "সক্রিয় অনুসন্ধান মানদণ্ডের সাথে কোনো জিনিস মিলছে না।",
    "feed.emptyAction": "নতুন জিনিস রিপোর্ট করুন",
    "matches.contactFinder": "সন্ধানকারীর সাথে যোগাযোগ করুন",
    "matches.contactOwner": "মালিকের সাথে যোগাযোগ করুন",
    "matches.verifyOwnership": "মালিকানা যাচাই করুন",
    "claim.title": "মালিকানার দাবি জমা দিন",
    "claim.subtitle": "পাবলিক যোগাযোগ প্রকাশ না করে এআই সুরক্ষার সাথে মালিকানা যাচাই করুন।",
    "claim.questionsTitle": "যাচাইকরণ প্রশ্নাবলী",
    "claim.questionsSubtitle": "আসল মালিকানা প্রমাণ করতে নির্দিষ্ট প্রশ্নের উত্তর দিন:",
    "claim.answerPlaceholder": "এই প্রশ্নের আপনার উত্তর...",
    "claim.submit": "পর্যালোচনার জন্য দাবি জমা দিন",
    "claim.submitting": "যাচাইকরণের বিবরণ জমা দেওয়া হচ্ছে...",
    "claim.success": "দাবি জমা দেওয়া হয়েছে! মালিক আপনার উত্তর পর্যালোচনা করবেন।",
    "dashboard.myReports": "আমার রিপোর্টসমূহ",
    "dashboard.myClaims": "আমার দাবিসমূহ",
    "dashboard.savedPosts": "সংরক্ষিত পোস্টসমূহ",
    "help.title": "প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী",
    "help.q1": "লিঙ্কো কীভাবে আমার গোপনীয়তা রক্ষা করে?",
    "help.a1": "লিঙ্কো আপনার যোগাযোগের তথ্য কখনও প্রকাশ্য করে না। কেবল পারস্পরিক যাচাইয়ের পরেই তা প্রকাশ পায়।",
    "help.q2": "আমি যখন কোনো হারানো জিনিস রিপোর্ট করি তখন কি ঘটে?",
    "help.a2": "আমাদের এআই আপনার রিপোর্টকে বিভিন্ন শহরে পাওয়া জিনিসের সাথে তুলনা করে।",
    "help.q3": "মালিকানা যাচাইকরণ কীভাবে কাজ করে?",
    "help.a3": "দাবীদারদের এআই-প্রস্তুত গোপন প্রশ্নের উত্তর দিতে হয় যা কেবল আসল মালিক জানেন।",
    "help.q4": "লিঙ্কো কি ব্যবহারের জন্য বিনামূল্যে?",
    "help.a4": "হ্যাঁ, লিঙ্কো সম্পূর্ণ বিনামূল্যে এবং কমিউনিটি-চালিত।",
    "home.heroTitle": "এআই এবং যাচাইকৃত বিশ্বাসের সাথে হারানো জিনিস ফিরে পান",
    "home.heroSubtitle": "ভারতের কমিউনিটি-চালিত লস্ট অ্যান্ড ফাউন্ড প্ল্যাটফর্ম। নিরাপদ, ব্যক্তিগত এবং জেমিনি এআই দ্বারা পরিচালিত।",
    "home.statsRecovered": "পুনরুদ্ধার করা জিনিস",
    "home.statsActive": "সক্রিয় নাগরিক নজরদারি",
    "home.statsCities": "আওতাভুক্ত শহর",
    "home.howItWorks": "লিঙ্কো কীভাবে কাজ করে",
    "home.step1Title": "১. সেকেন্ডের মধ্যে রিপোর্ট করুন",
    "home.step1Desc": "৩৯টি ভাষায় কণ্ঠস্বর, টেক্সট বা ছবির মাধ্যমে জিনিস নথিভুক্ত করুন।",
    "home.step2Title": "২. স্মার্ট এআই মিল",
    "home.step2Desc": "জেমিনি ভিজ্যুয়াল বৈশিষ্ট্য এবং বিবরণ তুলনা করে।",
    "home.step3Title": "৩. যাচাইকৃত হস্তান্তর",
    "home.step3Desc": "গোপন প্রশ্নের মাধ্যমে দাবি যাচাই করুন এবং নিরাপদে জিনিস ফিরে পান।",
}

print("Loaded MR_NEW, GU_NEW, BN_NEW.")
