UR_NEW = {
    "category.Wallet / Purse": "بٹوہ / پرس",
    "category.Bag / Luggage": "بیگ / سامان",
    "category.ID / Card": "شناختی کارڈ / کارڈ",
    "urgency.Contains ID": "شناختی کارڈ موجود ہے",
    "voice.stop": "ریکارڈنگ بند کریں",
    "voice.error": "آواز کی شناخت میں خرابی۔ براہ کرم دوبارہ کوشش کریں۔",
    "voice.hint": "سامان کا برانڈ، رنگ، مقام اور تاریخ بتائیں۔",
    "report.title": "سامان کی رپورٹ کریں",
    "report.subtitle": "گمشدہ یا ملنے والا سامان محفوظ طریقے سے درج کریں۔",
    "report.type": "رپورٹ کی قسم",
    "report.typeLost": "میرا سامان گم ہو گیا ہے",
    "report.typeFound": "مجھے کوئی سامان ملا ہے",
    "report.stepBasics": "1. بنیادی تفصیلات",
    "report.stepLocation": "2. مقام اور تاریخ",
    "report.stepPhotos": "3. تصاویر اور نشانیاں",
    "report.stepSecurity": "4. سیکیورٹی اور رابطہ",
    "report.itemTitle": "سامان کا نام",
    "report.itemTitlePlaceholder": "جیسے کالا چمڑے کا ٹائٹن گھڑی، نیلا وائلڈ کرافٹ بیگ",
    "report.category": "زمرہ",
    "report.selectCategory": "سامان کا زمرہ منتخب کریں",
    "report.description": "تفصیلی وضاحت",
    "report.descriptionPlaceholder": "رنگ، ماڈل، مخصوص نشانات، اندر موجود اشیاء وغیرہ درج کریں...",
    "report.location": "مقام (گمشدگی یا ملنے کی جگہ)",
    "report.locationPlaceholder": "جیسے ریلوے اسٹیشن گیٹ 1، دہلی",
    "report.date": "تاریخ اور تخمینی وقت",
    "report.urgency": "ضرورت کی سطح",
    "report.urgencyNormal": "معمول",
    "report.urgencyUrgent": "ضروری",
    "report.urgencyMedical": "طبی / انتہائی اہم",
    "report.photos": "تصاویر اپ لوڈ کریں",
    "report.photosHint": "واضح تصاویر AI میچ کو زیادہ درست بناتی ہیں۔",
    "report.reward": "انعام کی رقم (اختیاری)",
    "report.rewardPlaceholder": "₹ روپے میں رقم",
    "report.contact": "واٹس ایپ / فون رابطہ",
    "report.contactPlaceholder": "10 ہندسوں کا موبائل نمبر",
    "report.pin": "4 ہندسوں کا سیکیورٹی پن",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "بعد میں ترمیم یا حل شدہ نشان زد کرنے کے لیے ضروری ہے۔",
    "report.submit": "رپورٹ جمع کروائیں",
    "report.submitting": "محفوظ رجسٹری میں شائع کیا جا رہا ہے...",
    "report.success": "آپ کی رپورٹ کامیابی سے شائع ہو گئی!",
    "report.viewListing": "فہرست میں دیکھیں",
    "report.brand": "برانڈ / بنانے والا",
    "report.brandPlaceholder": "جیسے ایپل، سام سنگ، ٹائٹن",
    "report.primaryColor": "بنیادی رنگ",
    "report.secondaryColor": "ثانوی رنگ",
    "report.landmark": "قریبی مشہور جگہ",
    "report.landmarkPlaceholder": "جیسے پلیٹ فارم 2 کے قریب، کیفے کے سامنے",
    "report.secretClue": "خفیہ شناختی نشانی (تصدیق کے لیے)",
    "report.secretCluePlaceholder": "جیسے اندرونی جیب میں سرخ چابی کا چھلا، 'RS' لکھا ہوا",
    "feed.searchPlaceholder": "سامان، ٹیگز، رنگ، شہر تلاش کریں...",
    "feed.filters": "فلٹرز",
    "feed.applyFilters": "فلٹرز لاگو کریں",
    "feed.recentSearches": "حالیہ تلاشیں",
    "feed.savedSearches": "محفوظ تلاشیں",
    "feed.listingRegistry": "فہرست رجسٹری",
    "feed.category": "زمرہ",
    "feed.allCategories": "تمام زمرہ جات",
    "feed.city": "شہر",
    "feed.allCities": "تمام شہر",
    "feed.dateRange": "تاریخ کی حد",
    "feed.proximity": "فاصلے کی حد",
    "feed.allProximities": "تمام فاصلے",
    "feed.within5km": "5 کلومیٹر کے اندر",
    "feed.within15km": "15 کلومیٹر کے اندر",
    "feed.within30km": "30 کلومیٹر کے اندر",
    "feed.within50km": "50 کلومیٹر کے اندر",
    "feed.sortCatalog": "ترتیب دیں",
    "feed.colorSwatch": "رنگوں کا انتخاب",
    "feed.allColors": "تمام رنگ",
    "feed.hardwareBrand": "برانڈ",
    "feed.allBrands": "تمام برانڈز",
    "feed.resetFilters": "فلٹرز ری سیٹ کریں",
    "feed.viewList": "فہرست",
    "feed.viewMap": "نقشہ",
    "feed.noMatchesFound": "کوئی مماثلت نہیں ملی",
    "feed.noMatchesDesc": "ان فلٹرز کے مطابق کوئی سامان نہیں ملا۔",
    "feed.reportItem": "گمشدہ/ملا ہوا سامان درج کریں",
    "feed.saveParameters": "تلاش کے پیرامیٹرز محفوظ کریں",
    "feed.deleteSavedSearch": "محفوظ تلاش حذف کریں",
    "feed.universalSearchBar": "سرچ بار",
    "feed.clearSearch": "تلاش صاف کریں",
    "feed.toggleFilters": "جدید فلٹرز",
    "feed.newestFirst": "تازہ ترین پہلے",
    "feed.oldestFirst": "پرانا پہلے",
    "feed.highestReward": "سب سے زیادہ انعام",
    "feed.closestDistance": "سب سے قریب",
    "postcard.unlockConnection": "رابطہ انلاک کریں",
    "postcard.iHaveThisItem": "یہ سامان میرے پاس ہے",
    "postcard.reclaimed": "حاصل شدہ اور واپس کر دیا گیا",
    "postcard.claims": "دعوے",
    "postcard.image": "تصویر",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI میچ",
    "postcard.geminiMatches": "جیمنی کو مناسب میچ ملے ہیں!",
    "postcard.contactOwner": "مالک سے رابطہ کریں",
    "postcard.creatorNotice": "صرف تصدیق شدہ خالق ہی مماثلت کی تفصیلات دیکھ سکتے ہیں۔",
    "postcard.markResolved": "حل شدہ نشان زد کریں",
    "postcard.deleteListing": "فہرست حذف کریں",
    "postcard.unlockWithPin": "سیکیورٹی پن سے انلاک کریں",
    "postcard.manageClaims": "دعووں کا انتظام کریں",
    "postcard.shareTemplate": "شیئر کرنے والا متن کاپی کریں",
    "postcard.downloadCard": "کارڈ کی تصویر ڈاؤن لوڈ کریں",
    "postcard.qrSettings": "QR سیٹنگز",
    "postcard.postedOn": "پوسٹ کی گئی تاریخ",
    "postcard.reward": "انعام",
    "postcard.secureHandover": "محفوظ سپردگی",
    "matches.title": "AI اسمارٹ میچ اور باہمی تصدیق",
    "matches.subtitle": "جیمنی گمشدہ اور ملے ہوئے سامان کا موازنہ کرتا ہے۔ گفتگو سے قبل تصدیق لازمی ہے۔",
    "matches.myMatches": "میرے میچز",
    "matches.publicMatches": "عوامی میچز",
    "matches.threshold": "کم از کم حد:",
    "matches.security": "سیکیورٹی:",
    "matches.mutualApprovalRequired": "دونوں فریقین کی منظوری درکار ہے",
    "matches.noMatchesFound": "کوئی ممکنہ مماثلت نہیں ملی",
    "matches.improveReport": "اپنی رپورٹ کو بہتر بنائیں",
    "matches.noPhoto": "کوئی تصویر نہیں",
    "matches.chatLive": "لائیو چیٹ",
    "matches.chatLocked": "چیٹ لاک ہے",
    "matches.inspectReview": "معائنہ اور جائزہ لیں",
    "matches.openChatLive": "لائیو چیٹ کھولیں",
    "matches.verifyApprove": "تصدیق کریں اور منظور کریں",
    "matches.approvalNotice": "چیٹ کھلنے سے پہلے مالک اور تلاش کنندہ دونوں کو تصدیق منظور کرنی ہوگی۔",
    "matches.tabComparison": "موازنہ",
    "matches.tabVerification": "تصدیق",
    "matches.tabTrust": "اعتماد اور واٹس ایپ",
    "matches.tabHandover": "سپردگی",
    "matches.noImageProvided": "کوئی تصویر فراہم نہیں کی گئی",
    "matches.itemName": "سامان کا نام",
    "matches.category": "زمرہ",
    "matches.reward": "انعام",
    "matches.locationAddress": "مقام اور پتہ",
    "matches.detailsDescription": "تفصیلی معلومات",
    "matches.finderContact": "تلاش کنندہ کا رابطہ",
    "matches.matchStatus": "میچ کی حیثیت:",
    "matches.mutualConfirmed": "باہمی منظوری کی تصدیق ہو گئی۔ دونوں فریقوں نے تصدیق مکمل کر لی ہے۔",
    "matches.mutualProtocol": "باہمی تصدیق کا پروٹوکول",
    "matches.protocolNotice": "دھوکہ دہی روکنے کے لیے دونوں فریق تصدیقی تفصیلات جمع کراتے ہیں۔ منظوری تک چیٹ لاک رہے گی۔",
    "matches.ownerStatus": "مالک کی حیثیت",
    "matches.submittedBy": "جمع کرانے والا:",
    "matches.aiScore": "AI تصدیقی اسکور:",
    "matches.ownerNotSubmitted": "مالک نے ابھی تک جوابات جمع نہیں کروائے۔",
    "matches.finderStatus": "تلاش کنندہ کی حیثیت",
    "matches.finderNotSubmitted": "تلاش کنندہ نے ابھی تک جوابات جمع نہیں کروائے۔",
    "matches.actionControls": "کارروائی کے کنٹرولز",
    "matches.selectRole": "تفصیلات جمع کرانے کے لیے اپنا کردار منتخب کریں۔",
    "matches.iAmOwner": "میں مالک ہوں",
    "matches.iAmFinder": "مجھے یہ سامان ملا ہے",
    "matches.yourName": "آپ کا نام",
    "matches.contactWhatsApp": "واٹس ایپ / رابطہ",
    "matches.forensicQuestions": "فرانزک تصدیقی سوالات",
    "matches.trustTitle": "باہمی اعتماد اور محفوظ واٹس ایپ رابطہ",
    "matches.trustNotice": "حفاظت کے پیش نظر، دونوں صارفین کے \"میں اس شخص پر بھروسہ کرتا ہوں\" پر کلک کرنے کے بعد ہی فون نمبر ظاہر ہوں گے۔",
    "matches.ownerTrust": "مالک کا اعتماد",
    "matches.finderTrust": "تلاش کنندہ کا اعتماد",
    "matches.unlocked": "انلاک کر دیا گیا",
    "matches.masked": "پوشیدہ",
    "matches.contactAlias": "رابطے کا نام",
    "matches.phoneWhatsApp": "فون / واٹس ایپ",
    "matches.openWhatsApp": "واٹس ایپ چیٹ کھولیں",
    "matches.directCall": "براہ راست کال",
    "matches.trustInstructions": "واٹس ایپ لنک اور فون نمبر دیکھنے کے لیے نیچے دیے گئے بٹن پر کلک کریں۔",
    "matches.trustConsent": "بھروسہ پر کلک کر کے، آپ محفوظ سپردگی کے لیے رابطے کی تفصیلات شیئر کرنے پر رضامند ہوتے ہیں۔",
    "matches.reunitedResolved": "سامان کامیابی سے سپرد کر دیا گیا اور معاملہ حل ہو گیا!",
    "matches.reunitedNotice": "مالک اور تلاش کنندہ دونوں نے محفوظ واپسی کی تصدیق کی ہے۔",
    "matches.handoverProtocol": "محفوظ سپردگی کا طریقہ کار",
    "matches.handoverNotice": "کسی عوامی مقام پر ملنے کا منصوبہ بنائیں (جیسے میٹرو اسٹیشن یا تھانہ)۔ سپردگی کے بعد دونوں تصدیق کریں۔",
    "matches.handoverSchedule": "سپردگی کا وقت اور مقام",
    "matches.publicMeetingSpot": "عوامی ملاقات کی جگہ",
    "matches.scheduledDateTime": "مقررہ تاریخ / وقت",
    "matches.confirmHandover": "سپردگی کی تصدیق کریں اور مکمل کریں",
    "matches.confirmHandoverDesc": "سامان وصول کرنے کے بعد عمل مکمل کرنے کی تصدیق کریں۔",
    "matches.iHandedOver": "میں نے سامان حوالے کر دیا ہے",
    "matches.iReceived": "مجھے میرا سامان مل گیا ہے",
    "matches.chatUnlocksAfter": "تصدیق کے بعد محفوظ چیٹ کھلے گی",
    "matches.chatUnlocksDesc": "دعوے کی تصدیق ہونے کے بعد فریقین کے درمیان محفوظ چیٹ خود بخود کھل جائے گی۔",
    "matches.goToVerification": "تصدیق کے ٹیب پر جائیں",
    "matches.secureHandoverChat": "محفوظ سپردگی چیٹ",
    "matches.connectionVerified": "رابطے کی تصدیق ہو گئی! محفوظ واپسی کے لیے پیغام بھیجیں۔",
    "matches.dismissMatch": "میچ مسترد کریں",
    "matches.shareMatch": "شیئر کریں",
    "matches.directClaim": "براہ راست دعویٰ",
    "claim.ownershipIndex": "ملکیت کا اعتماد اشاریہ",
    "claim.safeVerification": "محفوظ ملکیتی تصدیق",
    "claim.stepsNotice": "سپردگی کو محفوظ اور مستند بنانے کے لیے ہم نجی اقدامات استعمال کرتے ہیں۔",
    "claim.protectedContact": "آپ کے رابطے کی تفصیلات مکمل محفوظ ہیں۔ صرف تصدیق شدہ شخص ہی دیکھ سکتا ہے۔",
    "claim.unlockedMutual": "باہمی تصدیق کے بعد ہی رابطے کے اختیارات کھلیں گے۔ آپ کا نمبر عام نہیں کیا جائے گا۔",
    "claim.aiEvaluationNotice": "دھوکہ دہی روکنے کے لیے ہمارا AI دعووں کا جائزہ لیتا ہے۔",
    "claim.trackingNotice": "منفرد ٹریکنگ کوڈز دونوں فریقوں کی حفاظت کرتے ہیں۔",
    "claim.modalDescription": "سامان اصل مالک تک پہنچنے کو یقینی بنانے کے لیے ہم رابطہ شیئر کرنے سے پہلے جانچ کرتے ہیں۔",
    "claim.aiPreparingQuestions": "AI آپ کے تصدیقی سوالات تیار کر رہا ہے...",
    "claim.claimantName": "دعویدار کا نام",
    "claim.officialNamePlaceholder": "آپ کا سرکاری نام",
    "claim.whatsappMobile": "واٹس ایپ موبائل",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "سامان کی تفصیلات کی تصدیق کریں",
    "claim.detailsPlaceholder": "براہ کرم تفصیل سے بتائیں (نشانات، اندر کی اشیاء، رسید وغیرہ)...",
    "claim.verificationRegistered": "تصدیق درج ہو گئی",
    "claim.detailsSavedSecurely": "آپ کی تفصیلات محفوظ کر لی گئیں۔ AI نے تفصیلات کا موازنہ کیا ہے۔",
    "claim.verificationId": "تصدیقی ID (دعوے کی ID)",
    "claim.aiMatchDetails": "AI میچ کی تفصیلات",
    "claim.bookmarkLink": "براہ راست لنک (بعد میں دیکھنے کے لیے محفوظ رکھیں)",
    "claim.doneAwaitSignoff": "مکمل & مالک کی منظوری کا انتظار کریں",
    "auth.recoverBelongings": "قابل اعتماد شہریوں اور ذہین تصدیق کے ذریعے گمشدہ سامان محفوظ طریقے سے واپس پائیں۔",
    "auth.startEmail": "ای میل سے شروع کریں",
    "auth.continuePhone": "فون کے ساتھ جاری رکھیں",
    "auth.signIn": "سائن ان کریں",
    "auth.welcomeBack": "خوش آمدید",
    "auth.resumeTracking": "ٹریکنگ جاری رکھنے کے لیے اپنے اکاؤنٹ میں سائن ان کریں۔",
    "auth.emailOrUsername": "ای میل یا صارف کا نام",
    "auth.password": "پاس ورڈ",
    "auth.forgotPassword": "پاس ورڈ بھول گئے؟",
    "auth.createAccount": "اکاؤنٹ بنائیں",
    "auth.joinNetwork": "محافظ نیٹ ورک میں شامل ہوں۔",
    "auth.fullName": "پورا نام",
    "auth.username": "صارف کا نام",
    "auth.emailAddress": "ای میل پتہ",
    "auth.confirmPassword": "پاس ورڈ کی تصدیق کریں",
    "auth.acceptPolicy": "میں رازداری کی پالیسی قبول کرتا ہوں اور انکرپٹڈ ڈیٹا شیئرنگ سے متفق ہوں۔",
    "auth.resetPassword": "پاس ورڈ ری سیٹ کریں",
    "auth.resetNotice": "اکاؤنٹ تک رسائی کے لیے ہم ایک محفوظ لنک بھیجیں گے۔",
    "auth.sendResetLink": "ری سیٹ لنک بھیجیں",
    "auth.returnSignIn": "سائن ان پر واپس جائیں",
    "auth.setupProfile": "اپنا پروفائل سیٹ کریں",
    "auth.setupNotice": "دوسروں کے ساتھ ہم آہنگی کے لیے اپنا پروفائل مکمل کریں۔",
    "auth.takeSnapshot": "تصویر لیں",
    "auth.choosePhoto": "تصویر منتخب کریں",
    "auth.cityNeighborhood": "شہر / علاقہ (لازمی)",
    "auth.shortBio": "مختصر تعارف (اختیاری)",
    "auth.completeSetup": "سیٹ اپ مکمل کریں",
    "dashboard.welcomeTitle": "اپنا پروفائل سیٹ کریں",
    "dashboard.welcomeDesc": "LINCO میں خوش آمدید۔ محفوظ سپردگی کے لیے اپنے بارے میں مختصر بتائیں۔",
    "dashboard.chooseAvatar": "اوتار منتخب کریں",
    "dashboard.fullName": "پورا نام",
    "dashboard.username": "صارف کا نام",
    "dashboard.bio": "تعارف (اختیاری)",
    "dashboard.city": "شہر",
    "dashboard.createProfile": "پروفائل بنائیں",
    "dashboard.skipForNow": "فی الحال چھوڑ دیں",
    "dashboard.changeCover": "کور تبدیل کریں",
    "dashboard.editProfile": "پروفائل میں ترمیم کریں",
    "dashboard.shareProfile": "پروفائل شیئر کریں",
    "dashboard.settings": "سیٹنگز",
    "dashboard.editDetails": "تفصیلات میں ترمیم کریں",
    "dashboard.accountSection": "اکاؤنٹ",
    "dashboard.email": "ای میل",
    "dashboard.password": "پاس ورڈ",
    "dashboard.privacySection": "رازداری",
    "dashboard.blockedUsers": "بلاک شدہ صارفین",
    "dashboard.downloadData": "میرا ڈیٹا ڈاؤن لوڈ کریں",
    "dashboard.deleteAccount": "اکاؤنٹ حذف کریں",
    "dashboard.notifSection": "اطلاعات",
    "dashboard.pushNotifs": "پش اطلاعات",
    "dashboard.pushDesc": "فوری مماثلت اور چیٹ کی اطلاعات",
    "dashboard.emailReports": "ای میل رپورٹس",
    "dashboard.emailDesc": "لاوارث اشیاء کا ہفتہ وار خلاصہ",
    "dashboard.appearanceSection": "ظاہری شکل",
    "dashboard.theme": "تھیم",
    "dashboard.language": "زبان",
    "dashboard.supportSection": "سپورٹ",
    "dashboard.help": "مدد",
    "dashboard.contact": "رابطہ",
    "dashboard.about": "کے بارے میں",
    "dashboard.logout": "لاگ آؤٹ",
    "dashboard.updateEmail": "ای میل اپ ڈیٹ کریں",
    "dashboard.saveEmail": "ای میل محفوظ کریں",
    "dashboard.changePassword": "پاس ورڈ تبدیل کریں",
    "dashboard.unblock": "ان بلاک کریں",
    "dashboard.noBlocked": "کوئی بلاک شدہ صارف نہیں۔",
    "dashboard.contactSupport": "سپورٹ سے رابطہ کریں",
    "dashboard.supportDesc": "مدد یا سوالات کے لیے ہماری ٹیم سے رابطہ کریں:",
    "dashboard.aboutLinco": "LINCO کے بارے میں",
    "dashboard.aboutDesc": "LINCO ایک محفوظ ایپ ہے جو گمشدہ اشیاء کی تلاش میں جیمنی AI استعمال کرتی ہے۔",
    "dashboard.appVersion": "ایپ ورژن: v1.3.0",
    "dashboard.capturePhoto": "تصویر لیں",
    "dashboard.useCamera": "کیمرہ استعمال کریں",
    "dashboard.chooseGallery": "گیلری سے منتخب کریں",
    "dashboard.confirmDeletion": "حذف کرنے کی تصدیق کریں",
    "dashboard.deletionWarning": "یہ عمل مستقل ہے۔ آپ کا تمام ڈیٹا حذف کر دیا جائے گا۔",
    "dashboard.typePasswordConfirm": "تصدیق کے لیے پاس ورڈ درج کریں",
    "dashboard.typeDeletePrompt": "اکاؤنٹ مستقل طور پر حذف کرنے کے لیے نیچے DELETE ٹائپ کریں۔",
    "ownerClaims.controlBoard": "کلیم کنٹرول بورڈ",
    "ownerClaims.enterPin": "سیکیورٹی پن درج کریں",
    "ownerClaims.pinDesc": "رجسٹریشن کے دوران دیا گیا 4 ہندسوں کا پن درج کریں۔",
    "ownerClaims.clear": "صاف کریں",
    "ownerClaims.authenticating": "تصدیق کی جا رہی ہے...",
    "ownerClaims.integrityScore": "جیمنی اسکور",
    "ownerClaims.reviewNotice": "جوابات کا جائزہ لیں۔ منظوری دینے سے محفوظ ریکوری روم فعال ہو جائے گا۔",
    "ownerClaims.completeHandover": "سپردگی مکمل کریں",
    "ownerClaims.postClosed": "یہ پوسٹ بند کر دی گئی ہے۔",
    "ownerClaims.closeWindow": "ونڈو بند کریں",
    "ownerClaims.approved": "منظور شدہ",
    "ownerClaims.resolved": "حل شدہ",
    "ownerClaims.youReturned": "آپ نے واپس کیا:",
    "ownerClaims.meetingCoords": "محفوظ ملاقات کی تفصیلات درج کریں...",
    "pin.title": "سیکیورٹی پن درج کریں",
    "pin.passcode": "4 ہندسوں کا پاس کوڈ",
    "pin.verifying": "تصدیق ہو رہی ہے...",
    "pin.clear": "صاف کریں",
    "pin.unlock": "انلاک کریں",
    "pin.promise": "آپ کا پن آپ کی ذاتی معلومات کو محفوظ رکھتا ہے۔",
    "communityFound.title": "یہ سامان میرے پاس ہے",
    "communityFound.protocol": "زیرو ٹرسٹ پروٹوکول",
    "communityFound.verifyFinding": "ملنے کی تصدیق کریں",
    "communityFound.withoutLeaking": "ذاتی معلومات ظاہر کیے بغیر",
    "communityFound.lostReported": "گمشدہ سامان کی رپورٹ",
    "communityFound.whereFound": "آپ کو یہ کہاں سے ملا؟",
    "communityFound.insideContents": "اندرونی اشیاء (اختیاری)",
    "communityFound.secretDetails": "خصوصی نشانیاں / خفیہ تفصیلات",
    "communityFound.createPin": "اپنا سیکیورٹی پن بنائیں",
    "communityFound.reward": "انعام",
    "communityFound.registeredNotice": "درج کر دیا گیا۔ مالک کو آپ کے جوابات سے آگاہ کر دیا گیا ہے۔",
    "claimTracker.title": "اسٹیٹس ٹائم لائن",
    "claimTracker.protocols": "محفوظ ریکوری پروٹوکول",
    "claimTracker.publicSpaces": "میٹرو اسٹیشن یا کیفے جیسی روشن عوامی جگہوں پر ملیں۔",
    "claimTracker.verifyCarefully": "انعام دینے سے پہلے سامان کی اچھی طرح جانچ کریں۔",
    "claimTracker.documentDetails": "ملاقات کی تفصیلات درج کرنے کے لیے ہماری محفوظ چیٹ استعمال کریں۔",
    "claimTracker.lookupAnother": "کوئی اور تلاش کریں",
    "claimTracker.unsuccessful": "دعوے کی تشخیص ناکام رہی",
    "claimTracker.trustCheck": "باہمی اعتماد کی جانچ",
    "claimTracker.awaitingApproval": "تلاش کنندہ کی منظوری کا انتظار",
    "claimTracker.recoveryRoom": "محفوظ ریکوری روم",
    "claimTracker.enterRoom": "روم میں داخل ہوں",
    "claimTracker.discussion": "سپردگی کی بات چیت",
    "recovery.transmissionSecured": "ڈیٹا محفوظ ہے",
    "recovery.reportIndexed": "رپورٹ فہرست میں شامل",
    "recovery.dossierActive": "فائل فعال ہے۔ جیمنی شواہد کا تجزیہ کر رہا ہے۔",
    "recovery.engineTitle": "AI ریکوری امکانی انجن",
    "recovery.retrievalLikelihood": "ملنے کا امکان:",
    "recovery.analyzedFactors": "تجزیہ کردہ عوامل",
    "recovery.semanticNotice": "ہمارا ماڈل برانڈ، رنگ اور نشانات کا تجزیہ کرتا ہے۔",
    "recovery.uniqueIdentifier": "منفرد شناخت مکمل تصدیق کو ممکن بناتی ہے۔",
    "recovery.setReward": "انعام مقرر کریں",
    "reward.fairRange": "مناسب حد",
    "reward.suggestReward": "انعام تجویز کریں",
    "reward.customReward": "دوسری رقم",
    "privacy.complianceProtocols": "رازداری کے پروٹوکول",
    "privacy.title": "اعتماد اور حفاظت کا مرکز",
    "privacy.subtitle": "ہم صارف کی حفاظت کے اعلیٰ ترین معیارات پر عمل کرتے ہیں۔",
    "privacy.exitSection": "باہر نکلیں",
    "privacy.privacyPolicy": "رازداری کی پالیسی",
    "privacy.lastUpdated": "آخری اپ ڈیٹ: 7 جولائی، 2026۔",
    "privacy.dataAcquisition": "ہم صرف ضروری ڈیٹا اکٹھا کرتے ہیں:",
    "privacy.spatiotemporalTags": "مقام و وقت کے ٹیگز:",
    "privacy.coldStorage": "اسٹوریج سے پہلے زیادہ سے زیادہ حد۔",
    "privacy.cookiePreferences": "کوکی کی ترجیحات کا انتظام کریں۔",
    "privacy.purgeBrowser": "ڈیٹا فوری طور پر صاف کریں۔",
    "privacy.hereToHelp": "ہم مدد کے لیے حاضر ہیں۔",
    "privacy.connectFounder": "سپورٹ کے لیے ہم سے رابطہ کریں۔",
    "cookie.title": "رازداری کا تحفظ",
    "cookie.message": "ہم صرف سامان تلاش کرنے کے لیے درکار معلومات اکٹھی کرتے ہیں۔",
    "cookie.trackingNotice": "ملکیت ثابت ہونے تک معلومات نجی رہتی ہیں۔",
    "cookie.acceptAll": "سب قبول کریں",
    "cookie.learnMore": "مزید جانیں",
    "about.tagline": "برادریوں کو جوڑنا، سامان واپس لانا",
    "about.mission": "LINCO اخلاقی AI اور سماجی اعتماد کے ذریعے گمشدہ اشیاء مالکان تک پہنچانے کے لیے پرعزم ہے۔",
    "notifications.title": "اطلاعات",
    "notifications.empty": "کوئی نئی اطلاع نہیں",
    "notifications.markAllRead": "سبھی پڑھی ہوئی نشان زد کریں",
    "notifications.clearAll": "سب صاف کریں",
    "notifications.matchFoundTitle": "ممکنہ میچ ملا",
    "notifications.matchFoundMsg": "ہمارے AI نے ایک ممکنہ مماثلت کی نشاندہی کی ہے۔",
    "notifications.claimReceivedTitle": "نیا دعویٰ موصول ہوا",
    "notifications.claimReceivedMsg": "ایک صارف نے آپ کی فہرست کے لیے تصدیقی جوابات جمع کرائے ہیں۔",
    "notifications.claimApprovedTitle": "دعویٰ منظور ہو گیا",
    "notifications.claimApprovedMsg": "آپ کا دعویٰ مالک کی طرف سے تصدیق اور منظور ہو گیا ہے۔",
    "notifications.chatMessageTitle": "ریکوری روم میں نیا پیغام",
    "notifications.chatMessageMsg": "آپ کی سپردگی سے متعلق ایک نیا پیغام آیا ہے۔",
    "notifications.handoverDoneTitle": "سپردگی کی تصدیق ہو گئی",
    "notifications.handoverDoneMsg": "سامان واپس ملنے کی تصدیق ہو گئی ہے اور معاملہ حل ہو گیا ہے۔",
    "enhance.button": "AI تفصیل بہتر بنائیں",
    "enhance.loading": "جیمنی AI تفصیل تیار کر رہا ہے...",
    "enhance.apply": "بہتر تفصیل استعمال کریں",
    "enhance.discard": "اصل تفصیل رکھیں",
    "enhance.rewardTitle": "AI انعام کی تجویز",
    "enhance.rewardCalculated": "تجویز کردہ انعام: ₹",
    "enhance.rewardReason": "سامان کے زمرے اور برانڈ کی قیمت پر مبنی۔",
    "timeline.reconstruct": "ٹائم لائن دوبارہ بنائیں",
    "timeline.loading": "راستوں اور چیک پوائنٹس کا تجزیہ کیا جا رہا ہے...",
    "timeline.spotLikelihood": "گمشدگی کا ممکنہ مقام:",
    "timeline.window": "ممکنہ وقت:",
    "timeline.analysis": "سفر کا تجزیہ:",
    "timeline.confidence": "اعتماد کی شرح:",
    "timeline.addPoint": "چیک پوائنٹ شامل کریں",
    "timeline.pointName": "چیک پوائنٹ کا نام / اسٹیشن",
    "chat.assistant": "AI معاون",
    "chat.subtitle": "آپ کا ساتھی",
    "chat.description": "60 سیکنڈ میں گمشدہ یا ملے ہوئے سامان کی رپورٹ کریں۔ بولیں یا لکھیں۔",
    "chat.startAssistant": "AI رپورٹ اسسٹنٹ شروع کریں",
    "chat.location": "مقام:",
    "chat.securityPin": "سیکیورٹی پن:",
    "chat.skipPhoto": "تصویر چھوڑیں",
    "chat.item": "سامان:",
    "chat.errorLoading": "معاون لوڈ کرنے میں خرابی۔ دوبارہ کوشش کریں۔",
    "chat.welcomeMessage": "LINCO Saathii میں خوش آمدید! بتائیں کیا گم ہوا ہے یا ملا ہے؟",
    "chat.networkError": "نیٹ ورک کا مسئلہ۔ براہ کرم دوبارہ کوشش کریں!",
    "chat.understoodError": "واضح طور پر سمجھ نہیں آیا۔ کیا آپ مزید تفصیلات دے سکتے ہیں؟",
    "feed.lostOnly": "گمشدہ سامان",
    "feed.foundOnly": "ملا ہوا سامان",
    "feed.filterByCategory": "زمرہ",
    "feed.filterByCity": "شہر",
    "feed.filterByUrgency": "اہمیت",
    "feed.empty": "کوئی سامان نہیں ملا۔",
    "feed.emptyAction": "نیا سامان درج کریں",
    "matches.contactFinder": "تلاش کنندہ سے رابطہ کریں",
    "matches.contactOwner": "مالک سے رابطہ کریں",
    "matches.verifyOwnership": "ملکیت کی تصدیق کریں",
    "claim.title": "ملکیت کا دعویٰ جمع کروائیں",
    "claim.subtitle": "رابطہ ظاہر کیے بغیر AI تحفظ کے ساتھ ملکیتی تصدیق کریں۔",
    "claim.questionsTitle": "تصدیقی سوالات",
    "claim.questionsSubtitle": "اصل ملکیت ثابت کرنے کے لیے سوالات کے جوابات دیں:",
    "claim.answerPlaceholder": "آپ کا جواب...",
    "claim.submit": "جمع کروائیں",
    "claim.submitting": "تصدیقی تفصیلات جمع کی جا رہی ہیں...",
    "claim.success": "دعویٰ جمع ہو گیا! مالک آپ کے جوابات کا جائزہ لے گا۔",
    "dashboard.myReports": "میری رپورٹس",
    "dashboard.myClaims": "میرے دعوے",
    "dashboard.savedPosts": "محفوظ پوسٹس",
    "help.title": "اکثر پوچھے گئے سوالات",
    "help.q1": "LINCO میری رازداری کا تحفظ کیسے کرتا ہے؟",
    "help.a1": "فون نمبر عام نہیں کیا جاتا۔ باہمی منظوری کے بعد ہی رابطہ کھلتا ہے۔",
    "help.q2": "رپورٹ کرنے پر کیا ہوتا ہے؟",
    "help.a2": "ہمارا AI آپ کی رپورٹ کا موازنہ ملی ہوئی اشیاء سے کرتا ہے۔",
    "help.q3": "ملکیتی تصدیق کیسے کام کرتی ہے؟",
    "help.a3": "صرف اصل مالک کو معلوم خفیہ سوالات کے جوابات دینے ہوتے ہیں۔",
    "help.q4": "کیا یہ مفت ہے؟",
    "help.a4": "جی ہاں، LINCO مکمل طور پر مفت اور سماجی ہے۔",
    "home.heroTitle": "گمشدہ اشیاء محفوظ طریقے سے واپس حاصل کریں",
    "home.heroSubtitle": "محفوظ اور AI پر مبنی سماجی پلیٹ فارم۔",
    "home.statsRecovered": "واپس شدہ سامان",
    "home.statsActive": "فعال شہری",
    "home.statsCities": "شہر",
    "home.howItWorks": "یہ کیسے کام کرتا ہے",
    "home.step1Title": "1. تفصیلات درج کریں",
    "home.step1Desc": "آواز یا تحریر کے ذریعے درج کریں۔",
    "home.step2Title": "2. AI میچنگ",
    "home.step2Desc": "تفصیلات اور تصاویر کا باہمی موازنہ کیا جاتا ہے۔",
    "home.step3Title": "3. محفوظ واپسی",
    "home.step3Desc": "تصدیق کر کے محفوظ طریقے سے سامان واپس حاصل کریں۔",
}

print(f"Loaded UR_NEW ({len(UR_NEW)} keys).")
