import json

# Odia dictionary for all 439 missing keys
OR_NEW = {
    "category.Wallet / Purse": "ୱାଲେଟ୍ / ପର୍ସ",
    "category.Bag / Luggage": "ବ୍ୟାଗ୍ / ଲଗେଜ୍",
    "category.ID / Card": "ପରିଚୟ ପତ୍ର / କାର୍ଡ",
    "urgency.Contains ID": "ପରିଚୟ ପତ୍ର ଉପଲବ୍ଧ",
    "voice.stop": "ରେକର୍ଡିଂ ବନ୍ଦ କରନ୍ତୁ",
    "voice.error": "ଭଏସ୍ ସନ୍ଧାନରେ ତ୍ରୁଟି। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
    "voice.hint": "ବ୍ରାଣ୍ଡ, ରଙ୍ଗ, ସ୍ଥାନ ଏବଂ ତାରିଖ କୁହନ୍ତୁ।",
    "report.title": "ଜିନିଷ ରିପୋର୍ଟ କରନ୍ତୁ",
    "report.subtitle": "ହଜିଯାଇଥିବା କିମ୍ବା ମିଳିଥିବା ସାମଗ୍ରୀ ସୁରକ୍ଷିତ ଭାବରେ ଦର୍ଜ କରନ୍ତୁ।",
    "report.type": "ରିପୋର୍ଟ ପ୍ରକାର",
    "report.typeLost": "ମୋର ଜିନିଷ ହଜିଯାଇଛି",
    "report.typeFound": "ମୋତେ କିଛି ଜିନିଷ ମିଳିଛି",
    "report.stepBasics": "1. ପ୍ରାଥମିକ ବିବରଣୀ",
    "report.stepLocation": "2. ସ୍ଥାନ ଏବଂ ତାରିଖ",
    "report.stepPhotos": "3. ଫଟୋ ଏବଂ ସୂଚକ",
    "report.stepSecurity": "4. ସୁରକ୍ଷା ଏବଂ ଯୋଗାଯୋଗ",
    "report.itemTitle": "ଜିନିଷର ନାମ",
    "report.itemTitlePlaceholder": "ଯେପରିକି କଳା ଚମଡା ଟାଇଟାନ୍ ଘଣ୍ଟା, ନୀଳ ୱାଇଲ୍ଡକ୍ରାଫ୍ଟ ବ୍ୟାଗ୍",
    "report.category": "ବର୍ଗ",
    "report.selectCategory": "ସାମଗ୍ରୀର ବର୍ଗ ବାଛନ୍ତୁ",
    "report.description": "ବିସ୍ତୃତ ବିବରଣୀ",
    "report.descriptionPlaceholder": "ରଙ୍ଗ, ମଡେଲ, ଚିହ୍ନ, ଭିତର ସାମଗ୍ରୀ ଇତ୍ୟାଦି ଲେଖନ୍ତୁ...",
    "report.location": "ସ୍ଥାନ (ହଜିଥିବା ବା ମିଳିଥିବା ସ୍ଥାନ)",
    "report.locationPlaceholder": "ଯେପରିକି ଭୁବନେଶ୍ୱର ରେଳ ଷ୍ଟେସନ ଗେଟ୍ 1",
    "report.date": "ତାରିଖ ଏବଂ ଆନୁମାନିକ ସମୟ",
    "report.urgency": "ଜରୁରୀ ସ୍ତର",
    "report.urgencyNormal": "ସାଧାରଣ",
    "report.urgencyUrgent": "ଜରୁରୀ",
    "report.urgencyMedical": "ଡାକ୍ତରୀ / ଅତ୍ୟନ୍ତ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ",
    "report.photos": "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
    "report.photosHint": "ସ୍ପଷ୍ଟ ଫଟୋ AI ମେଳକକୁ ଅଧିକ ସଠିକ୍ କରେ।",
    "report.reward": "ପୁରସ୍କାର ରାଶି (ଇଚ୍ଛାଧୀନ)",
    "report.rewardPlaceholder": "₹ ଟଙ୍କା ରେ ରାଶି",
    "report.contact": "ହ୍ୱାଟ୍ସଆପ୍ / ଫୋନ୍ ନମ୍ବର",
    "report.contactPlaceholder": "10 ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର",
    "report.pin": "4 ଅଙ୍କ ବିଶିଷ୍ଟ ସୁରକ୍ଷା ପିନ୍",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "ପରବର୍ତ୍ତୀ ସମୟରେ ପରିବର୍ତ୍ତନ କିମ୍ବା ସମାପ୍ତ କରିବା ପାଇଁ ଆବଶ୍ୟକ।",
    "report.submit": "ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ",
    "report.submitting": "ସୁରକ୍ଷିତ ରେଜିଷ୍ଟ୍ରିରେ ପ୍ରକାଶ କରାଯାଉଛି...",
    "report.success": "ଆପଣଙ୍କ ରିପୋର୍ଟ ସଫଳତାର ସହ ପ୍ରକାଶିତ ହେଲା!",
    "report.viewListing": "ତାଲିକାରେ ଦେଖନ୍ତୁ",
    "report.brand": "ବ୍ରାଣ୍ଡ / ନିର୍ମାତା",
    "report.brandPlaceholder": "ଯେପରିକି ଆପଲ୍, ସାମସଙ୍ଗ, ଟାଇଟାନ୍",
    "report.primaryColor": "ମୁଖ୍ୟ ରଙ୍ଗ",
    "report.secondaryColor": "ଦ୍ୱିତୀୟ ରଙ୍ଗ",
    "report.landmark": "ନିକଟସ୍ଥ ପ୍ରସିଦ୍ଧ ସ୍ଥାନ",
    "report.landmarkPlaceholder": "ଯେପରିକି ପ୍ଲାଟଫର୍ମ 2 ନିକଟରେ, କାଫେ ସାମ୍ନାରେ",
    "report.secretClue": "ଗୁପ୍ତ ଚିହ୍ନ (ପ୍ରମାଣୀକରଣ ପାଇଁ)",
    "report.secretCluePlaceholder": "ଯେପରିକି ଭିତର ପକେଟରେ ନାଲି କି-ଚେନ୍, 'RS' ନାମ ଲେଖାଅଛି",
    "feed.searchPlaceholder": "ସାମଗ୍ରୀ, ଟ୍ୟାଗ୍, ରଙ୍ଗ, ସହର ଖୋଜନ୍ତୁ...",
    "feed.filters": "ଫିଲ୍ଟର୍",
    "feed.applyFilters": "ଫିଲ୍ଟର୍ ଲାଗୁ କରନ୍ତୁ",
    "feed.recentSearches": "ସାମ୍ପ୍ରତିକ ସନ୍ଧାନ",
    "feed.savedSearches": "ସଂରକ୍ଷିତ ସନ୍ଧାନ",
    "feed.listingRegistry": "ତାଲିକା ରେଜିଷ୍ଟ୍ରି",
    "feed.category": "ବର୍ଗ",
    "feed.allCategories": "ସମସ୍ତ ବର୍ଗ",
    "feed.city": "ସହର",
    "feed.allCities": "ସମସ୍ତ ସହର",
    "feed.dateRange": "ତାରିଖ ସୀମା",
    "feed.proximity": "ଦୂରତା ସୀମା",
    "feed.allProximities": "ସମସ୍ତ ଦୂରତା",
    "feed.within5km": "5 କିଲୋମିଟର ମଧ୍ୟରେ",
    "feed.within15km": "15 କିଲୋମିଟର ମଧ୍ୟରେ",
    "feed.within30km": "30 କିଲୋମିଟର ମଧ୍ୟରେ",
    "feed.within50km": "50 କିଲୋମିଟର ମଧ୍ୟରେ",
    "feed.sortCatalog": "କ୍ରମ ସଜାନ୍ତୁ",
    "feed.colorSwatch": "ରଙ୍ଗ ପ୍ୟାଲେଟ୍",
    "feed.allColors": "ସମସ୍ତ ରଙ୍ଗ",
    "feed.hardwareBrand": "ବ୍ରାଣ୍ଡ",
    "feed.allBrands": "ସମସ୍ତ ବ୍ରାଣ୍ଡ",
    "feed.resetFilters": "ଫିଲ୍ଟର୍ ରିସେଟ୍ କରନ୍ତୁ",
    "feed.viewList": "ତାଲିକା",
    "feed.viewMap": "ମାନଚିତ୍ର",
    "feed.noMatchesFound": "କୌଣସି ମେଳ ମିଳିଲା ନାହିଁ",
    "feed.noMatchesDesc": "ଏହି ଫିଲ୍ଟର୍ ସହିତ କୌଣସି ସାମଗ୍ରୀ ମେଳ ଖାଉନାହିଁ।",
    "feed.reportItem": "ହଜିଥିବା/ମିଳିଥିବା ଜିନିଷ ଦର୍ଜ କରନ୍ତୁ",
    "feed.saveParameters": "ସନ୍ଧାନ ପାରାମିଟର ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "feed.deleteSavedSearch": "ସଂରକ୍ଷିତ ସନ୍ଧାନ ହଟାନ୍ତୁ",
    "feed.universalSearchBar": "ସନ୍ଧାନ ବାର୍",
    "feed.clearSearch": "ସନ୍ଧାନ ସଫା କରନ୍ତୁ",
    "feed.toggleFilters": "ଉନ୍ନତ ଫିଲ୍ଟର୍",
    "feed.newestFirst": "ନୂତନ ପ୍ରଥମେ",
    "feed.oldestFirst": "ପୁରୁଣା ପ୍ରଥମେ",
    "feed.highestReward": "ସର୍ବାଧିକ ପୁରସ୍କାର",
    "feed.closestDistance": "ସବୁଠାରୁ ନିକଟତର",
    "postcard.unlockConnection": "ଯୋଗାଯୋଗ ଅନଲକ୍ କରନ୍ତୁ",
    "postcard.iHaveThisItem": "ଏହି ଜିନିଷ ମୋ ପାଖରେ ଅଛି",
    "postcard.reclaimed": "ପ୍ରାପ୍ତ ଏବଂ ହସ୍ତାନ୍ତର ହୋଇଛି",
    "postcard.claims": "ଦାବି",
    "postcard.image": "ଛବି",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI ମେଳ",
    "postcard.geminiMatches": "ଜେମିନି ଉପଯୁକ୍ତ ମେଳ ପାଇଛି!",
    "postcard.contactOwner": "ମାଲିକଙ୍କ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    "postcard.creatorNotice": "କେବଳ ପ୍ରମାଣିତ ସୃଷ୍ଟିକର୍ତ୍ତା ମେଳ ଦେଖିପାରିବେ।",
    "postcard.markResolved": "ସମାପ୍ତ ଚିହ୍ନିତ କରନ୍ତୁ",
    "postcard.deleteListing": "ତାଲିକା ବିଲୋପ କରନ୍ତୁ",
    "postcard.unlockWithPin": "ସୁରକ୍ଷା ପିନ୍ ସହିତ ଅନଲକ୍ କରନ୍ତୁ",
    "postcard.manageClaims": "ଦାବି ପରିଚାଳନା କରନ୍ତୁ",
    "postcard.shareTemplate": "ଅଂଶୀଦାର ଟେକ୍ସଟ୍ କପି କରନ୍ତୁ",
    "postcard.downloadCard": "କାର୍ଡ ଫଟୋ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    "postcard.qrSettings": "QR ସେଟିଂସ",
    "postcard.postedOn": "ପୋଷ୍ଟ କରାଯାଇଛି",
    "postcard.reward": "ପୁରସ୍କାର",
    "postcard.secureHandover": "ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର",
    "matches.title": "AI ସ୍ମାର୍ଟ ମେଳ ଏବଂ ପାରସ୍ପରିକ ଯାଞ୍ଚ",
    "matches.subtitle": "ଜେମିନି ହଜିଥିବା ଏବଂ ମିଳିଥିବା ତାଲିକା ତୁଳନା କରେ। ଚାଟ୍ ପୂର୍ବରୁ ଯାଞ୍ଚ ବାଧ୍ୟତାମୂଳକ।",
    "matches.myMatches": "ମୋର ମେଳ",
    "matches.publicMatches": "ସାର୍ବଜନୀନ ମେଳ",
    "matches.threshold": "ସର୍ବନିମ୍ନ ସୀମା:",
    "matches.security": "ସୁରକ୍ଷା:",
    "matches.mutualApprovalRequired": "ଉଭୟ ପକ୍ଷର ଅନୁମୋଦନ ଆବଶ୍ୟକ",
    "matches.noMatchesFound": "କୌଣସି ସମ୍ଭାବ୍ୟ ମେଳ ମିଳିଲା ନାହିଁ",
    "matches.improveReport": "ଆପଣଙ୍କ ରିପୋର୍ଟ ସୁଧାରନ୍ତୁ",
    "matches.noPhoto": "କୌଣସି ଫଟୋ ନାହିଁ",
    "matches.chatLive": "ଲାଇଭ୍ ଚାଟ୍",
    "matches.chatLocked": "ଚାଟ୍ ଲକ୍ ଅଛି",
    "matches.inspectReview": "ପରୀକ୍ଷା ଏବଂ ସମୀକ୍ଷା କରନ୍ତୁ",
    "matches.openChatLive": "ଲାଇଭ୍ ଚାଟ୍ ଖୋଲନ୍ତୁ",
    "matches.verifyApprove": "ଯାଞ୍ଚ ଏବଂ ଅନୁମୋଦନ କରନ୍ତୁ",
    "matches.approvalNotice": "ଚାଟ୍ ଖୋଲିବା ପୂର୍ବରୁ ମାଲିକ ଏବଂ ପାଇଥିବା ବ୍ୟକ୍ତି ଉଭୟ ଯାଞ୍ଚ ଅନୁମୋଦନ କରିବା ଆବଶ୍ୟକ।",
    "matches.tabComparison": "ତୁଳନା",
    "matches.tabVerification": "ଯାଞ୍ଚ",
    "matches.tabTrust": "ବିଶ୍ୱାସ ଏବଂ ହ୍ୱାଟ୍ସଆପ୍",
    "matches.tabHandover": "ହସ୍ତାନ୍ତର",
    "matches.noImageProvided": "କୌଣସି ଛବି ଦିଆଯାଇ ନାହିଁ",
    "matches.itemName": "ସାମଗ୍ରୀର ନାମ",
    "matches.category": "ବର୍ଗ",
    "matches.reward": "ପୁରସ୍କାର",
    "matches.locationAddress": "ସ୍ଥାନ ଏବଂ ଠିକଣା",
    "matches.detailsDescription": "ବିସ୍ତୃତ ବିବରଣୀ",
    "matches.finderContact": "ପାଇଥିବା ବ୍ୟକ୍ତିଙ୍କ ଯୋଗାଯୋଗ",
    "matches.matchStatus": "ମେଳ ସ୍ଥିତି:",
    "matches.mutualConfirmed": "ପାରସ୍ପରିକ ଅନୁମୋଦନ ନିଶ୍ଚିତ ହୋଇଛି। ଉଭୟ ପକ୍ଷ ଯାଞ୍ଚ ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି।",
    "matches.mutualProtocol": "ପାରସ୍ପରିକ ଯାଞ୍ଚ ପ୍ରୋଟୋକଲ୍",
    "matches.protocolNotice": "ପ୍ରତାରଣା ରୋକିବା ପାଇଁ ଉଭୟ ପକ୍ଷ ଯାଞ୍ଚ ବିବରଣୀ ଦାଖଲ କରନ୍ତି। ଅନୁମୋଦନ ପର୍ଯ୍ୟନ୍ତ ଚାଟ୍ ଲକ୍ ରହିବ।",
    "matches.ownerStatus": "ମାଲିକଙ୍କ ସ୍ଥିତି",
    "matches.submittedBy": "ଦାଖଲକାରୀ:",
    "matches.aiScore": "AI ଯାଞ୍ଚ ସ୍କୋର:",
    "matches.ownerNotSubmitted": "ମାଲିକ ଏପର୍ଯ୍ୟନ୍ତ ଉତ୍ତର ଦାଖଲ କରିନାହାଁନ୍ତି।",
    "matches.finderStatus": "ପାଇଥିବା ବ୍ୟକ୍ତିଙ୍କ ସ୍ଥିତି",
    "matches.finderNotSubmitted": "ପାଇଥିବା ବ୍ୟକ୍ତି ଏପର୍ଯ୍ୟନ୍ତ ଉତ୍ତର ଦାଖଲ କରିନାହାଁନ୍ତି।",
    "matches.actionControls": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ନିୟନ୍ତ୍ରଣ",
    "matches.selectRole": "ବିବରଣୀ ଦାଖଲ ପାଇଁ ନିଜ ଭୂମିକା ବାଛନ୍ତୁ।",
    "matches.iAmOwner": "ମୁଁ ମାଲିକ ଅଟେ",
    "matches.iAmFinder": "ମୋତେ ଏହି ଜିନିଷ ମିଳିଛି",
    "matches.yourName": "ଆପଣଙ୍କ ନାମ",
    "matches.contactWhatsApp": "ହ୍ୱାଟ୍ସଆପ୍ / ଯୋଗାଯୋଗ",
    "matches.forensicQuestions": "ଫୋରେନସିକ୍ ଯାଞ୍ଚ ପ୍ରଶ୍ନ",
    "matches.trustTitle": "ପାରସ୍ପରିକ ବିଶ୍ୱାସ ଏବଂ ସୁରକ୍ଷିତ ହ୍ୱାଟ୍ସଆପ୍ ଯୋଗାଯୋଗ",
    "matches.trustNotice": "ସୁରକ୍ଷା ପାଇଁ, ଉଭୟ ବ୍ୟବହାରକାରୀ \"ମୁଁ ଏହି ବ୍ୟକ୍ତିଙ୍କୁ ବିଶ୍ୱାସ କରେ\" କ୍ଲିକ୍ କରିବା ପରେ ହିଁ ଫୋନ୍ ନମ୍ବର ଦେଖାଯିବ।",
    "matches.ownerTrust": "ମାଲିକଙ୍କ ବିଶ୍ୱାସ",
    "matches.finderTrust": "ପାଇଥିବା ବ୍ୟକ୍ତିଙ୍କ ବିଶ୍ୱାସ",
    "matches.unlocked": "ଅନଲକ୍ ହୋଇଛି",
    "matches.masked": "ଲୁକ୍କାୟିତ",
    "matches.contactAlias": "ଯୋଗାଯୋଗ ନାମ",
    "matches.phoneWhatsApp": "ଫୋନ୍ / ହ୍ୱାଟ୍ସଆପ୍",
    "matches.openWhatsApp": "ହ୍ୱାଟ୍ସଆପ୍ ଚାଟ୍ ଖୋଲନ୍ତୁ",
    "matches.directCall": "ସିଧାସଳଖ କଲ୍",
    "matches.trustInstructions": "ହ୍ୱାଟ୍ସଆପ୍ ଲିଙ୍କ୍ ଏବଂ ଫୋନ୍ ନମ୍ବର ଦେଖିବା ପାଇଁ ତଳ ବଟନ୍ କ୍ଲିକ୍ କରନ୍ତୁ।",
    "matches.trustConsent": "ବିଶ୍ୱାସ କ୍ଲିକ୍ କରି, ଆପଣ ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ପାଇଁ ଯୋଗାଯୋଗ ବିବରଣୀ ଅଂଶୀଦାର କରିବାକୁ ରାଜି ହେଉଛନ୍ତି।",
    "matches.reunitedResolved": "ଜିନିଷ ସଫଳତାର ସହିତ ହସ୍ତାନ୍ତର ହେଲା ଏବଂ ସମସ୍ୟା ସମାଧାନ ହେଲା!",
    "matches.reunitedNotice": "ମାଲିକ ଏବଂ ପାଇଥିବା ବ୍ୟକ୍ତି ଉଭୟ ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ନିଶ୍ଚିତ କରିଛନ୍ତି।",
    "matches.handoverProtocol": "ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ପ୍ରୋଟୋକଲ୍",
    "matches.handoverNotice": "କୌଣସି ଜନସାଧାରଣ ସ୍ଥାନରେ ଭେଟିବାକୁ ଯୋଜନା କରନ୍ତୁ (ଯେପରିକି ମେଟ୍ରୋ ଷ୍ଟେସନ ବା ଥାନା)। ହସ୍ତାନ୍ତର ପରେ ଉଭୟ ନିଶ୍ଚିତ କରନ୍ତୁ।",
    "matches.handoverSchedule": "ହସ୍ତାନ୍ତର ସମୟ ଏବଂ ସ୍ଥାନ",
    "matches.publicMeetingSpot": "ସାର୍ବଜନୀନ ଭେଟିବା ସ୍ଥାନ",
    "matches.scheduledDateTime": "ନିର୍ଦ୍ଧାରିତ ତାରିଖ / ସମୟ",
    "matches.confirmHandover": "ହସ୍ତାନ୍ତର ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ କାର୍ଯ୍ୟ ସମାପ୍ତ କରନ୍ତୁ",
    "matches.confirmHandoverDesc": "ଜିନିଷ ପାଇବା ପରେ, ପ୍ରକ୍ରିୟା ସମାପ୍ତ କରିବାକୁ ନିଶ୍ଚିତ କରନ୍ତୁ।",
    "matches.iHandedOver": "ମୁଁ ଏହି ଜିନିଷ ହସ୍ତାନ୍ତର କରିଛି",
    "matches.iReceived": "ମୋତେ ମୋର ଜିନିଷ ମିଳିଛି",
    "matches.chatUnlocksAfter": "ଯାଞ୍ଚ ପରେ ସୁରକ୍ଷିତ ଚାଟ୍ ଖୋଲିବ",
    "matches.chatUnlocksDesc": "ଦାବି ଯାଞ୍ଚ ହେବା ପରେ ଉଭୟ ପକ୍ଷ ମଧ୍ୟରେ ସୁରକ୍ଷିତ ଚାଟ୍ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ଖୋଲିବ।",
    "matches.goToVerification": "ଯାଞ୍ଚ ଟ୍ୟାବ୍ କୁ ଯାଆନ୍ତୁ",
    "matches.secureHandoverChat": "ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ଚାଟ୍",
    "matches.connectionVerified": "ସଂଯୋଗ ଯାଞ୍ଚ ହୋଇଛି! ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ପାଇଁ ବାର୍ତ୍ତା ପଠାନ୍ତୁ।",
    "matches.dismissMatch": "ମେଳ ଖାରଜ କରନ୍ତୁ",
    "matches.shareMatch": "ଅଂଶୀଦାର କରନ୍ତୁ",
    "matches.directClaim": "ସିଧାସଳଖ ଦାବି",
    "claim.ownershipIndex": "ମାଲିକାନା ବିଶ୍ୱସନୀୟତା ସୂଚକାଙ୍କ",
    "claim.safeVerification": "ସୁରକ୍ଷିତ ମାଲିକାନା ଯାଞ୍ଚ",
    "claim.stepsNotice": "ହସ୍ତାନ୍ତରକୁ ସୁରକ୍ଷିତ ଏବଂ ପ୍ରାମାଣିକ କରିବା ପାଇଁ ଆମେ ବ୍ୟକ୍ତିଗତ ପଦକ୍ଷେପ ବ୍ୟବହାର କରୁ।",
    "claim.protectedContact": "ଆପଣଙ୍କ ଯୋଗାଯୋଗ ବିବରଣୀ ସମ୍ପୂର୍ଣ୍ଣ ସୁରକ୍ଷିତ। କେବଳ ଯାଞ୍ଚ ହୋଇଥିବା ବ୍ୟକ୍ତି ହିଁ ଦେଖିପାରିବେ।",
    "claim.unlockedMutual": "ପାରସ୍ପରିକ ଯାଞ୍ଚ ପରେ ହିଁ ଯୋଗାଯୋଗ ବିକଳ୍ପ ଖୋଲିବ। ଆପଣଙ୍କ ନମ୍ବର ସାର୍ବଜନୀନ ହେବ ନାହିଁ।",
    "claim.aiEvaluationNotice": "ପ୍ରତାରଣା ରୋକିବା ପାଇଁ ଆମର AI ଦାବିର ମୂଲ୍ୟାଙ୍କନ କରେ।",
    "claim.trackingNotice": "ସ୍ୱତନ୍ତ୍ର ଟ୍ରାକିଂ କୋଡ୍ ଉଭୟ ପକ୍ଷଙ୍କୁ ସୁରକ୍ଷା ଦିଏ।",
    "claim.modalDescription": "ଜିନିଷ ପ୍ରକୃତ ମାଲିକଙ୍କ ପାଖରେ ପହଞ୍ଚିବା ନିଶ୍ଚିତ କରିବା ପାଇଁ, ଯୋଗାଯୋଗ ଅଂଶୀଦାର ପୂର୍ବରୁ ଆମେ ଯାଞ୍ଚ କରୁ।",
    "claim.aiPreparingQuestions": "AI ଆପଣଙ୍କ ଯାଞ୍ଚ ପ୍ରଶ୍ନ ପ୍ରସ୍ତୁତ କରୁଛି...",
    "claim.claimantName": "ଦାବିଦାରଙ୍କ ନାମ",
    "claim.officialNamePlaceholder": "ଆପଣଙ୍କ ସରକାରୀ ନାମ",
    "claim.whatsappMobile": "ହ୍ୱାଟ୍ସଆପ୍ ମୋବାଇଲ୍",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "ଜିନିଷର ବିବରଣୀ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "claim.detailsPlaceholder": "ଦୟାକରି ବିସ୍ତାରରେ ଉଲ୍ଲେଖ କରନ୍ତୁ (ଚିହ୍ନ, ଭିତର ସାମଗ୍ରୀ, ବିଲ୍ ଇତ୍ୟାଦି)...",
    "claim.verificationRegistered": "ଯାଞ୍ଚ ପଞ୍ଜୀକୃତ ହୋଇଛି",
    "claim.detailsSavedSecurely": "ଆପଣଙ୍କ ବିବରଣୀ ସୁରକ୍ଷିତ ଭାବେ ସଂରକ୍ଷିତ ହେଲା। AI ବିବରଣୀ ତୁଳନା କରିଛି।",
    "claim.verificationId": "ଯାଞ୍ଚ ID (ଦାବି ID)",
    "claim.aiMatchDetails": "AI ମେଳ ବିବରଣୀ",
    "claim.bookmarkLink": "ସିଧାସଳଖ ଲିଙ୍କ୍ (ପରେ ଦେଖିବା ପାଇଁ ସଂରକ୍ଷଣ କରନ୍ତୁ)",
    "claim.doneAwaitSignoff": "ସମ୍ପୂର୍ଣ୍ଣ & ମାଲିକଙ୍କ ଅନୁମୋଦନକୁ ଅପେକ୍ଷା କରନ୍ତୁ",
    "auth.recoverBelongings": "ବିଶ୍ୱାସଯୋଗ୍ୟ ନାଗରିକ ଏବଂ ବୁଦ୍ଧିମାନ ଯାଞ୍ଚ ମାଧ୍ୟମରେ ହଜିଥିବା ଜିନିଷ ସୁରକ୍ଷିତ ଫେରିପାଆନ୍ତୁ।",
    "auth.startEmail": "ଇମେଲ୍ ସହିତ ଆରମ୍ଭ କରନ୍ତୁ",
    "auth.continuePhone": "ଫୋନ୍ ସହିତ ଜାରି ରଖନ୍ତୁ",
    "auth.signIn": "ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
    "auth.welcomeBack": "ପୁନର୍ବାର ସ୍ୱାଗତ",
    "auth.resumeTracking": "ଟ୍ରାକିଂ ଜାରି ରଖିବା ପାଇଁ ଆପଣଙ୍କ ଖାତାରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।",
    "auth.emailOrUsername": "ଇମେଲ୍ କିମ୍ବା ୟୁଜରନେମ୍",
    "auth.password": "ପାସୱାର୍ଡ",
    "auth.forgotPassword": "ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?",
    "auth.createAccount": "ଖାତା ତିଆରି କରନ୍ତୁ",
    "auth.joinNetwork": "ରକ୍ଷକ ନେଟୱାର୍କରେ ଯୋଗ ଦିଅନ୍ତୁ।",
    "auth.fullName": "ପୂରା ନାମ",
    "auth.username": "ୟୁଜରନେମ୍",
    "auth.emailAddress": "ଇମେଲ୍ ଠିକଣା",
    "auth.confirmPassword": "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "auth.acceptPolicy": "ମୁଁ ଗୋପନୀୟତା ନୀତି ଗ୍ରହଣ କରୁଛି ଏବଂ ଏନକ୍ରିପ୍ଟ ହୋଇଥିବା ତଥ୍ୟ ଅଂଶୀଦାର କରିବାକୁ ରାଜି।",
    "auth.resetPassword": "ପାସୱାର୍ଡ ରିସେଟ୍ କରନ୍ତୁ",
    "auth.resetNotice": "ଖାତା ପ୍ରବେଶ ପାଇଁ ଆମେ ଏକ ସୁରକ୍ଷିତ ଲିଙ୍କ୍ ପଠାଇବୁ।",
    "auth.sendResetLink": "ରିସେଟ୍ ଲିଙ୍କ୍ ପଠାନ୍ତୁ",
    "auth.returnSignIn": "ସାଇନ୍ ଇନ୍ କୁ ଫେରନ୍ତୁ",
    "auth.setupProfile": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସେଟ୍ କରନ୍ତୁ",
    "auth.setupNotice": "ଅନ୍ୟମାନଙ୍କ ସହ ସମନ୍ୱୟ ରକ୍ଷା କରିବା ପାଇଁ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ପୂରଣ କରନ୍ତୁ।",
    "auth.takeSnapshot": "ଫଟୋ ନିଅନ୍ତୁ",
    "auth.choosePhoto": "ଫଟୋ ବାଛନ୍ତୁ",
    "auth.cityNeighborhood": "ସହର / ଅଞ୍ଚଳ (ବାଧ୍ୟତାମୂଳକ)",
    "auth.shortBio": "ସଂକ୍ଷିପ୍ତ ପରିଚୟ (ଇଚ୍ଛାଧୀନ)",
    "auth.completeSetup": "ସେଟଅପ୍ ସମାପ୍ତ କରନ୍ତୁ",
    "dashboard.welcomeTitle": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସେଟ୍ କରନ୍ତୁ",
    "dashboard.welcomeDesc": "LINCO ରେ ସ୍ୱାଗତ। ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର ପାଇଁ ନିଜ ବିଷୟରେ ସଂକ୍ଷେପରେ କୁହନ୍ତୁ।",
    "dashboard.chooseAvatar": "ଅବତାର ବାଛନ୍ତୁ",
    "dashboard.fullName": "ପୂରା ନାମ",
    "dashboard.username": "ୟୁଜରନେମ୍",
    "dashboard.bio": "ପରିଚୟ (ଇଚ୍ଛାଧୀନ)",
    "dashboard.city": "ସହର",
    "dashboard.createProfile": "ପ୍ରୋଫାଇଲ୍ ସୃଷ୍ଟି କରନ୍ତୁ",
    "dashboard.skipForNow": "ବର୍ତ୍ତମାନ ପାଇଁ ଛାଡନ୍ତୁ",
    "dashboard.changeCover": "କଭର ବଦଳାନ୍ତୁ",
    "dashboard.editProfile": "ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନ କରନ୍ତୁ",
    "dashboard.shareProfile": "ପ୍ରୋଫାଇଲ୍ ଅଂଶୀଦାର କରନ୍ତୁ",
    "dashboard.settings": "ସେଟିଂସ",
    "dashboard.editDetails": "ବିବରଣୀ ସମ୍ପାଦନ କରନ୍ତୁ",
    "dashboard.accountSection": "ଖାତା",
    "dashboard.email": "ଇମେଲ୍",
    "dashboard.password": "ପାସୱାର୍ଡ",
    "dashboard.privacySection": "ଗୋପନୀୟତା",
    "dashboard.blockedUsers": "ଅବରୋଧିତ ବ୍ୟବହାରକାରୀ",
    "dashboard.downloadData": "ମୋର ତଥ୍ୟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    "dashboard.deleteAccount": "ଖାତା ବିଲୋପ କରନ୍ତୁ",
    "dashboard.notifSection": "ବିଜ୍ଞପ୍ତି",
    "dashboard.pushNotifs": "ପୁଶ୍ ବିଜ୍ଞପ୍ତି",
    "dashboard.pushDesc": "ତୁରନ୍ତ ମେଳ ଏବଂ ଚାଟ୍ ପାଇଁ ବିଜ୍ଞପ୍ତି",
    "dashboard.emailReports": "ଇମେଲ୍ ରିପୋର୍ଟ",
    "dashboard.emailDesc": "ଅପ୍ରାପ୍ତ ସାମଗ୍ରୀର ସାପ୍ତାହିକ ସାରାଂଶ",
    "dashboard.appearanceSection": "ଦୃଶ୍ୟ",
    "dashboard.theme": "ଥିମ୍",
    "dashboard.language": "ଭାଷା",
    "dashboard.supportSection": "ସହାୟତା",
    "dashboard.help": "ସାହାଯ୍ୟ",
    "dashboard.contact": "ଯୋଗାଯୋଗ",
    "dashboard.about": "ବିବରଣୀ",
    "dashboard.logout": "ଲଗ୍ ଆଉଟ୍",
    "dashboard.updateEmail": "ଇମେଲ୍ ଅଦ୍ୟତନ କରନ୍ତୁ",
    "dashboard.saveEmail": "ଇମେଲ୍ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "dashboard.changePassword": "ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    "dashboard.unblock": "ଅନବ୍ଲକ୍ କରନ୍ତୁ",
    "dashboard.noBlocked": "କୌଣସି ଅବରୋଧିତ ବ୍ୟବହାରକାରୀ ନାହାଁନ୍ତି।",
    "dashboard.contactSupport": "ସହାୟତା ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    "dashboard.supportDesc": "ସହାୟତା ବା ପ୍ରଶ୍ନ ପାଇଁ ଆମ ଟିମ୍ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ:",
    "dashboard.aboutLinco": "LINCO ବିଷୟରେ",
    "dashboard.aboutDesc": "LINCO ଏକ ସୁରକ୍ଷିତ ଆପ୍ ଯାହା ଜେମିନି AI ବ୍ୟବହାର କରି ହଜିଥିବା ଜିନିଷ ଖୋଜିବାରେ ସାହାଯ୍ୟ କରେ।",
    "dashboard.appVersion": "ଆପ୍ ସଂସ୍କରଣ: v1.3.0",
    "dashboard.capturePhoto": "ଫଟୋ ଉଠାନ୍ତୁ",
    "dashboard.useCamera": "କ୍ୟାମେରା ବ୍ୟବହାର କରନ୍ତୁ",
    "dashboard.chooseGallery": "ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ",
    "dashboard.confirmDeletion": "ବିଲୋପ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "dashboard.deletionWarning": "ଏହି କାର୍ଯ୍ୟ ସ୍ଥାୟୀ। ଆପଣଙ୍କ ସମସ୍ତ ତଥ୍ୟ ବିଲୋପ ହୋଇଯିବ।",
    "dashboard.typePasswordConfirm": "ନିଶ୍ଚିତ କରିବାକୁ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ",
    "dashboard.typeDeletePrompt": "ଖାତା ସ୍ଥାୟୀ ଭାବେ ବିଲୋପ କରିବାକୁ ତଳେ DELETE ଲେଖନ୍ତୁ।",
    "ownerClaims.controlBoard": "ଦାବି ନିୟନ୍ତ୍ରଣ ବୋର୍ଡ",
    "ownerClaims.enterPin": "ସୁରକ୍ଷା ପିନ୍ ଦିଅନ୍ତୁ",
    "ownerClaims.pinDesc": "ପଞ୍ଜୀକରଣ ସମୟରେ ଦିଆଯାଇଥିବା 4 ଅଙ୍କର ପିନ୍ ଦିଅନ୍ତୁ।",
    "ownerClaims.clear": "ସଫା କରନ୍ତୁ",
    "ownerClaims.authenticating": "ପ୍ରମାଣୀକରଣ କରାଯାଉଛି...",
    "ownerClaims.integrityScore": "ଜେମିନି ସ୍କୋର",
    "ownerClaims.reviewNotice": "ଉତ୍ତର ସମୀକ୍ଷା କରନ୍ତୁ। ଅନୁମୋଦନ ଦ୍ୱାରା ସୁରକ୍ଷିତ ପୁନରୁଦ୍ଧାର କକ୍ଷ ସକ୍ରିୟ ହେବ।",
    "ownerClaims.completeHandover": "ହସ୍ତାନ୍ତର ସମାପ୍ତ କରନ୍ତୁ",
    "ownerClaims.postClosed": "ଏହି ପୋଷ୍ଟ ବନ୍ଦ ହୋଇଯାଇଛି।",
    "ownerClaims.closeWindow": "ୱିଣ୍ଡୋ ବନ୍ଦ କରନ୍ତୁ",
    "ownerClaims.approved": "ଅନୁମୋଦିତ",
    "ownerClaims.resolved": "ସମାଧିତ",
    "ownerClaims.youReturned": "ଆପଣ ଫେରସ୍ତ କରିଛନ୍ତି:",
    "ownerClaims.meetingCoords": "ସୁରକ୍ଷିତ ସାକ୍ଷାତ ବିବରଣୀ ପ୍ରବେଶ କରନ୍ତୁ...",
    "pin.title": "ସୁରକ୍ଷା ପିନ୍ ପ୍ରବେଶ କରନ୍ତୁ",
    "pin.passcode": "4 ଅଙ୍କର ପାସକୋଡ୍",
    "pin.verifying": "ଯାଞ୍ଚ କରାଯାଉଛି...",
    "pin.clear": "ସଫା କରନ୍ତୁ",
    "pin.unlock": "ଅନଲକ୍ କରନ୍ତୁ",
    "pin.promise": "ଆପଣଙ୍କ ପିନ୍ ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ ସୂଚନାକୁ ସୁରକ୍ଷିତ ରଖେ।",
    "communityFound.title": "ଏହି ଜିନିଷ ମୋ ପାଖରେ ଅଛି",
    "communityFound.protocol": "ଜିରୋ-ଟ୍ରଷ୍ଟ ପ୍ରୋଟୋକଲ୍",
    "communityFound.verifyFinding": "ପ୍ରାପ୍ତି ଯାଞ୍ଚ କରନ୍ତୁ",
    "communityFound.withoutLeaking": "ବ୍ୟକ୍ତିଗତ ସୂଚନା ଲିକ୍ ନକରି",
    "communityFound.lostReported": "ହଜିଥିବା ସାମଗ୍ରୀର ରିପୋର୍ଟ",
    "communityFound.whereFound": "ଆପଣ ଏହା କେଉଁଠାରୁ ପାଇଲେ?",
    "communityFound.insideContents": "ଭିତର ସାମଗ୍ରୀ (ଇଚ୍ଛାଧୀନ)",
    "communityFound.secretDetails": "ସ୍ୱତନ୍ତ୍ର ବିଶେଷତା / ଗୁପ୍ତ ବିବରଣୀ",
    "communityFound.createPin": "ନିଜର ସୁରକ୍ଷା ପିନ୍ ତିଆରି କରନ୍ତୁ",
    "communityFound.reward": "ପୁରସ୍କାର",
    "communityFound.registeredNotice": "ପଞ୍ଜୀକୃତ ହେଲା। ମାଲିକଙ୍କୁ ଆପଣଙ୍କ ଉତ୍ତର ବିଷୟରେ ଜଣାଇ ଦିଆଯାଇଛି।",
    "claimTracker.title": "ସ୍ଥିତି ଟାଇମଲାଇନ୍",
    "claimTracker.protocols": "ସୁରକ୍ଷିତ ପୁନରୁଦ୍ଧାର ପ୍ରୋଟୋକଲ୍",
    "claimTracker.publicSpaces": "ମେଟ୍ରୋ ଷ୍ଟେସନ କିମ୍ବା କାଫେ ପରି ଆଲୋକିତ ସାର୍ବଜନୀନ ସ୍ଥାନରେ ଭେଟନ୍ତୁ।",
    "claimTracker.verifyCarefully": "ପୁରସ୍କାର ଦେବା ପୂର୍ବରୁ ସାମଗ୍ରୀ ଭଲଭାବେ ଯାଞ୍ଚ କରନ୍ତୁ।",
    "claimTracker.documentDetails": "ସାକ୍ଷାତ ବିବରଣୀ ରେକର୍ଡ କରିବାକୁ ଆମ ସୁରକ୍ଷିତ ଚାଟ୍ ବ୍ୟବହାର କରନ୍ତୁ।",
    "claimTracker.lookupAnother": "ଅନ୍ୟ ଏକ ଖୋଜନ୍ତୁ",
    "claimTracker.unsuccessful": "ଦାବି ମୂଲ୍ୟାଙ୍କନ ଅସଫଳ ହେଲା",
    "claimTracker.trustCheck": "ପାରସ୍ପରିକ ବିଶ୍ୱାସ ଯାଞ୍ଚ",
    "claimTracker.awaitingApproval": "ପାଇଥିବା ବ୍ୟକ୍ତିଙ୍କ ଅନୁମୋଦନକୁ ଅପେକ୍ଷା",
    "claimTracker.recoveryRoom": "ସୁରକ୍ଷିତ ପୁନରୁଦ୍ଧାର କକ୍ଷ",
    "claimTracker.enterRoom": "କକ୍ଷରେ ପ୍ରବେଶ କରନ୍ତୁ",
    "claimTracker.discussion": "ହସ୍ତାନ୍ତର ଆଲୋଚନା",
    "recovery.transmissionSecured": "ତଥ୍ୟ ସୁରକ୍ଷିତ ଅଛି",
    "recovery.reportIndexed": "ରିପୋର୍ଟ ସୂଚୀବଦ୍ଧ ହୋଇଛି",
    "recovery.dossierActive": "ଫାଇଲ୍ ସକ୍ରିୟ। ଜେମିନି ସୂଚକ ବିଶ୍ଳେଷଣ କରୁଛି।",
    "recovery.engineTitle": "AI ପୁନରୁଦ୍ଧାର ସମ୍ଭାବନା ଇଞ୍ଜିନ୍",
    "recovery.retrievalLikelihood": "ମିଳିବାର ସମ୍ଭାବନା:",
    "recovery.analyzedFactors": "ବିଶ୍ଳେଷଣ କରାଯାଇଥିବା କାରକ",
    "recovery.semanticNotice": "ଆମ ମଡେଲ୍ ବ୍ରାଣ୍ଡ, ରଙ୍ଗ ଏବଂ ଚିହ୍ନ ବିଶ୍ଳେଷଣ କରେ।",
    "recovery.uniqueIdentifier": "ସ୍ୱତନ୍ତ୍ର ପରିଚାୟକ ସମ୍ପୂର୍ଣ୍ଣ ଯାଞ୍ଚକୁ ସକ୍ଷମ କରେ।",
    "recovery.setReward": "ପୁରସ୍କାର ସ୍ଥିର କରନ୍ତୁ",
    "reward.fairRange": "ଯୁକ୍ତିଯୁକ୍ତ ପରିସର",
    "reward.suggestReward": "ପୁରସ୍କାର ପରାମର୍ଶ ଦିଅନ୍ତୁ",
    "reward.customReward": "ଅନ୍ୟ ରାଶି",
    "privacy.complianceProtocols": "ଗୋପନୀୟତା ପ୍ରୋଟୋକଲ୍",
    "privacy.title": "ବିଶ୍ୱାସ ଏବଂ ସୁରକ୍ଷା କେନ୍ଦ୍ର",
    "privacy.subtitle": "ଆମେ ବ୍ୟବହାରକାରୀ ସୁରକ୍ଷାର ସର୍ବୋଚ୍ଚ ମାନଦଣ୍ଡ ପାଳନ କରୁ।",
    "privacy.exitSection": "ବାହାରକୁ ଯାଆନ୍ତୁ",
    "privacy.privacyPolicy": "ଗୋପନୀୟତା ନୀତି",
    "privacy.lastUpdated": "ଶେଷ ଅଦ୍ୟତନ: 7 ଜୁଲାଇ, 2026।",
    "privacy.dataAcquisition": "ଆମେ କେବଳ ଆବଶ୍ୟକୀୟ ତଥ୍ୟ ସଂଗ୍ରହ କରୁ:",
    "privacy.spatiotemporalTags": "ସ୍ଥାନ-ସମୟ ଟ୍ୟାଗ୍:",
    "privacy.coldStorage": "ଭଣ୍ଡାରଣ ପୂର୍ବରୁ ସର୍ବାଧିକ ସୀମା।",
    "privacy.cookiePreferences": "କୁକି ପସନ୍ଦ ପରିଚାଳନା କରନ୍ତୁ।",
    "privacy.purgeBrowser": "ତଥ୍ୟ ତୁରନ୍ତ ସଫା କରନ୍ତୁ।",
    "privacy.hereToHelp": "ଆମେ ସାହାଯ୍ୟ କରିବାକୁ ଏଠାରେ ଅଛୁ।",
    "privacy.connectFounder": "ସହାୟତା ପାଇଁ ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।",
    "cookie.title": "ଗୋପନୀୟତା ସୁରକ୍ଷା",
    "cookie.message": "ଆମେ କେବଳ ସାମଗ୍ରୀ ଖୋଜିବା ପାଇଁ ଆବଶ୍ୟକୀୟ ସୂଚନା ସଂଗ୍ରହ କରୁ।",
    "cookie.trackingNotice": "ମାଲିକାନା ପ୍ରମାଣିତ ହେବା ପର୍ଯ୍ୟନ୍ତ ସୂଚନା ବ୍ୟକ୍ତିଗତ ରହିବ।",
    "cookie.acceptAll": "ସମସ୍ତ ଗ୍ରହଣ କରନ୍ତୁ",
    "cookie.learnMore": "ଅଧିକ ଜାଣନ୍ତୁ",
    "about.tagline": "ସମ୍ପ୍ରଦାୟକୁ ଯୋଡିବା, ଜିନିଷ ଫେରାଇ ଆଣିବା",
    "about.mission": "LINCO ନୈତିକ AI ଏବଂ ସାମାଜିକ ବିଶ୍ୱାସ ମାଧ୍ୟମରେ ହଜିଥିବା ସାମଗ୍ରୀକୁ ମାଲିକଙ୍କ ନିକଟରେ ପହଞ୍ଚାଇବାକୁ ପ୍ରତିଶ୍ରୁତିବଦ୍ଧ।",
    "notifications.title": "ବିଜ୍ଞପ୍ତି",
    "notifications.empty": "କୌଣସି ନୂତନ ବିଜ୍ଞପ୍ତି ନାହିଁ",
    "notifications.markAllRead": "ସମସ୍ତ ପଢାଯାଇଛି ଚିହ୍ନିତ କରନ୍ତୁ",
    "notifications.clearAll": "ସମସ୍ତ ସଫା କରନ୍ତୁ",
    "notifications.matchFoundTitle": "ସମ୍ଭାବ୍ୟ ମେଳ ମିଳିଲା",
    "notifications.matchFoundMsg": "ଆମ AI ଦ୍ୱାରା ଏକ ସମ୍ଭାବ୍ୟ ମେଳ ଚିହ୍ନଟ ହୋଇଛି।",
    "notifications.claimReceivedTitle": "ନୂତନ ଦାବି ପ୍ରାପ୍ତ ହେଲା",
    "notifications.claimReceivedMsg": "ଜଣେ ବ୍ୟବହାରକାରୀ ଆପଣଙ୍କ ତାଲିକା ପାଇଁ ଯାଞ୍ଚ ଉତ୍ତର ଦାଖଲ କରିଛନ୍ତି।",
    "notifications.claimApprovedTitle": "ଦାବି ଅନୁମୋଦିତ ହେଲା",
    "notifications.claimApprovedMsg": "ଆପଣଙ୍କ ଦାବି ମାଲିକଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ ଏବଂ ଅନୁମୋଦିତ ହୋଇଛି।",
    "notifications.chatMessageTitle": "ପୁନରୁଦ୍ଧାର କକ୍ଷରେ ନୂଆ ବାର୍ତ୍ତା",
    "notifications.chatMessageMsg": "ଆପଣଙ୍କ ହସ୍ତାନ୍ତର ବିଷୟରେ ଏକ ନୂତନ ବାର୍ତ୍ତା ଆସିଛି।",
    "notifications.handoverDoneTitle": "ହସ୍ତାନ୍ତର ନିଶ୍ଚିତ ହେଲା",
    "notifications.handoverDoneMsg": "ଜିନିଷ ଫେରିପାଇବା ନିଶ୍ଚିତ ହୋଇଛି ଏବଂ ମାମଲା ସମାଧାନ ହୋଇଛି।",
    "enhance.button": "AI ବିବରଣୀ ସୁଧାରନ୍ତୁ",
    "enhance.loading": "ଜେମିନି AI ବିବରଣୀ ପ୍ରସ୍ତୁତ କରୁଛି...",
    "enhance.apply": "ସୁଧାରିତ ବିବରଣୀ ବ୍ୟବହାର କରନ୍ତୁ",
    "enhance.discard": "ମୂଳ ବିବରଣୀ ରଖନ୍ତୁ",
    "enhance.rewardTitle": "AI ପୁରସ୍କାର ପରାମର୍ଶ",
    "enhance.rewardCalculated": "ପରାମର୍ଶିତ ପୁରସ୍କାର: ₹",
    "enhance.rewardReason": "ଜିନିଷର ବର୍ଗ ଏବଂ ବ୍ରାଣ୍ଡ ମୂଲ୍ୟ ଉପରେ ଆଧାରିତ।",
    "timeline.reconstruct": "ଟାଇମଲାଇନ୍ ପୁନର୍ଗଠନ କରନ୍ତୁ",
    "timeline.loading": "ମାର୍ଗ ଏବଂ ଚେକପଏଣ୍ଟ ବିଶ୍ଳେଷଣ କରାଯାଉଛି...",
    "timeline.spotLikelihood": "ହଜିବାର ସମ୍ଭାବ୍ୟ ସ୍ଥାନ:",
    "timeline.window": "ସମ୍ଭାବ୍ୟ ସମୟ:",
    "timeline.analysis": "ଯାତ୍ରା ବିଶ୍ଳେଷଣ:",
    "timeline.confidence": "ବିଶ୍ୱାସନୀୟତା:",
    "timeline.addPoint": "ଚେକପଏଣ୍ଟ ଯୋଡନ୍ତୁ",
    "timeline.pointName": "ଚେକପଏଣ୍ଟ ନାମ / ଷ୍ଟେସନ",
    "chat.assistant": "AI ସହାୟକ",
    "chat.subtitle": "ଆପଣଙ୍କ ସାଥୀ",
    "chat.description": "60 ସେକେଣ୍ଡରେ ହଜିଥିବା ବା ମିଳିଥିବା ସାମଗ୍ରୀ ରିପୋର୍ଟ କରନ୍ତୁ। କୁହନ୍ତୁ ବା ଟାଇପ୍ କରନ୍ତୁ।",
    "chat.startAssistant": "AI ରିପୋର୍ଟ ସହାୟକ ଆରମ୍ଭ କରନ୍ତୁ",
    "chat.location": "ସ୍ଥାନ:",
    "chat.securityPin": "ସୁରକ୍ଷା ପିନ୍:",
    "chat.skipPhoto": "ଫଟୋ ଛାଡନ୍ତୁ",
    "chat.item": "ସାମଗ୍ରୀ:",
    "chat.errorLoading": "ସହାୟକ ଲୋଡ୍ କରିବାରେ ତ୍ରୁଟି। ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
    "chat.welcomeMessage": "LINCO Saathii କୁ ସ୍ୱାଗତ! କୁହନ୍ତୁ କଣ ହଜିଛି କିମ୍ବା ମିଳିଛି?",
    "chat.networkError": "ନେଟୱାର୍କ ସମସ୍ୟା। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ!",
    "chat.understoodError": "ସ୍ପଷ୍ଟ ବୁଝିପାରିଲୁ ନାହିଁ। ଆପଣ ଅଧିକ ବିବରଣୀ ଦେଇପାରିବେ କି?",
    "feed.lostOnly": "ହଜିଯାଇଥିବା ସାମଗ୍ରୀ",
    "feed.foundOnly": "ମିଳିଥିବା ସାମଗ୍ରୀ",
    "feed.filterByCategory": "ବର୍ଗ",
    "feed.filterByCity": "ସହର",
    "feed.filterByUrgency": "ଜରୁରୀ",
    "feed.empty": "କୌଣସି ସାମଗ୍ରୀ ମିଳିଲା ନାହିଁ।",
    "feed.emptyAction": "ନୂତନ ସାମଗ୍ରୀ ଦର୍ଜ କରନ୍ତୁ",
    "matches.contactFinder": "ପାଇଥିବା ବ୍ୟକ୍ତିଙ୍କ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    "matches.contactOwner": "ମାଲିକଙ୍କ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    "matches.verifyOwnership": "ମାଲିକାନା ଯାଞ୍ଚ କରନ୍ତୁ",
    "claim.title": "ମାଲିକାନା ଦାବି ଦାଖଲ କରନ୍ତୁ",
    "claim.subtitle": "ଯୋଗାଯୋଗ ଲିକ୍ ନକରି AI ସୁରକ୍ଷା ସହିତ ମାଲିକାନା ଯାଞ୍ଚ କରନ୍ତୁ।",
    "claim.questionsTitle": "ଯାଞ୍ଚ ପ୍ରଶ୍ନ",
    "claim.questionsSubtitle": "ପ୍ରକୃତ ମାଲିକାନା ପ୍ରମାଣ କରିବା ପାଇଁ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତୁ:",
    "claim.answerPlaceholder": "ଆପଣଙ୍କ ଉତ୍ତର...",
    "claim.submit": "ଦାଖଲ କରନ୍ତୁ",
    "claim.submitting": "ଯାଞ୍ଚ ବିବରଣୀ ଦାଖଲ କରାଯାଉଛି...",
    "claim.success": "ଦାବି ଦାଖଲ ହେଲା! ମାଲିକ ଆପଣଙ୍କ ଉତ୍ତର ସମୀକ୍ଷା କରିବେ।",
    "dashboard.myReports": "ମୋର ରିପୋର୍ଟ",
    "dashboard.myClaims": "ମୋର ଦାବି",
    "dashboard.savedPosts": "ସଂରକ୍ଷିତ ପୋଷ୍ଟ",
    "help.title": "ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ",
    "help.q1": "LINCO ମୋର ଗୋପନୀୟତା କିପରି ସୁରକ୍ଷା କରେ?",
    "help.a1": "ଫୋନ୍ ନମ୍ବର ସାର୍ବଜନୀନ ହୁଏ ନାହିଁ। ପାରସ୍ପରିକ ଅନୁମୋଦନ ପରେ ହିଁ ଯୋଗାଯୋଗ ଖୋଲେ।",
    "help.q2": "ରିପୋର୍ଟ କଲେ କଣ ହୁଏ?",
    "help.a2": "ଆମ AI ଆପଣଙ୍କ ରିପୋର୍ଟକୁ ମିଳିଥିବା ସାମଗ୍ରୀ ସହିତ ତୁଳନା କରେ।",
    "help.q3": "ମାଲିକାନା ଯାଞ୍ଚ କିପରି କାମ କରେ?",
    "help.a3": "କେବଳ ପ୍ରକୃତ ମାଲିକ ଜାଣିଥିବା ଗୁପ୍ତ ପ୍ରଶ୍ନର ଉତ୍ତର ଦେବାକୁ ପଡିଥାଏ।",
    "help.q4": "ଏହା ମାଗଣା କି?",
    "help.a4": "ହଁ, LINCO ସମ୍ପୂର୍ଣ୍ଣ ମାଗଣା ଏବଂ ସାମାଜିକ ଅଟେ।",
    "home.heroTitle": "ହଜିଥିବା ଜିନିଷକୁ ସୁରକ୍ଷିତ ଭାବେ ଫେରିପାଆନ୍ତୁ",
    "home.heroSubtitle": "ସୁରକ୍ଷିତ ଏବଂ AI ସମର୍ଥିତ ସାମାଜିକ ପ୍ଲାଟଫର୍ମ।",
    "home.statsRecovered": "ପୁନରୁଦ୍ଧାର ହୋଇଥିବା ସାମଗ୍ରୀ",
    "home.statsActive": "ସକ୍ରିୟ ନାଗରିକ",
    "home.statsCities": "ସହର",
    "home.howItWorks": "ଏହା କିପରି କାମ କରେ",
    "home.step1Title": "1. ବିବରଣୀ ଦର୍ଜ କରନ୍ତୁ",
    "home.step1Desc": "ଭଏସ୍ ବା ଲେଖା ମାଧ୍ୟମରେ ଦର୍ଜ କରନ୍ତୁ।",
    "home.step2Title": "2. AI ମେଳ",
    "home.step2Desc": "ବିବରଣୀ ଏବଂ ଫଟୋ ପାରସ୍ପରିକ ମେଳ କରାଯାଏ।",
    "home.step3Title": "3. ସୁରକ୍ଷିତ ହସ୍ତାନ୍ତର",
    "home.step3Desc": "ଯାଞ୍ଚ କରି ସୁରକ୍ଷିତ ଭାବେ ସାମଗ୍ରୀ ଫେରିପାଆନ୍ତୁ।",
}

print(f"Loaded OR_NEW ({len(OR_NEW)} keys).")
