AS_NEW = {
    "category.Wallet / Purse": "মানিবেগ / পাৰ্চ",
    "category.Bag / Luggage": "বেগ / লাগেজ",
    "category.ID / Card": "পৰিচয় পত্ৰ / কাৰ্ড",
    "urgency.Contains ID": "পৰিচয় পত্ৰ অন্তৰ্ভুক্ত আছে",
    "voice.stop": "ৰেকৰ্ডিং বন্ধ কৰক",
    "voice.error": "ভইচ চিনাক্তকৰণত সমস্যা হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
    "voice.hint": "বস্তুৰ ব্ৰেণ্ড, ৰং, স্থান আৰু তাৰিখৰ বিষয়ে কওক।",
    "report.title": "বস্তুৰ ৰিপৰ্ট কৰক",
    "report.subtitle": "হেৰোৱা বা পোৱা বস্তু সুৰক্ষিতভাৱে পঞ্জীয়ন কৰক।",
    "report.type": "ৰিপৰ্টৰ প্ৰকাৰ",
    "report.typeLost": "মোৰ বস্তু হেৰাইছে",
    "report.typeFound": "মই এটা বস্তু পাইছোঁ",
    "report.stepBasics": "1. প্ৰাথমিক তথ্য",
    "report.stepLocation": "2. স্থান আৰু তাৰিখ",
    "report.stepPhotos": "3. ফটো আৰু সূত্ৰ",
    "report.stepSecurity": "4. সুৰক্ষা আৰু যোগাযোগ",
    "report.itemTitle": "বস্তুৰ নাম",
    "report.itemTitlePlaceholder": "যেনে ক'লা চামৰাৰ টাইটান ঘড়ী, নীলা ৱাইল্ডক্ৰাফ্ট বেগ",
    "report.category": "শ্ৰেণী",
    "report.selectCategory": "বস্তুৰ শ্ৰেণী বাছনি কৰক",
    "report.description": "বিতং বিৱৰণ",
    "report.descriptionPlaceholder": "ৰং, মডেল, বিশেষ দাগ, ভিতৰৰ সামগ্ৰী ইত্যাদি...",
    "report.location": "স্থান (হেৰোৱা বা পোৱা স্থান)",
    "report.locationPlaceholder": "যেনে গুৱাহাটী ৰেলৱে ষ্টেচন ১ নং গেট",
    "report.date": "তাৰিখ আৰু আনুমানিক সময়",
    "report.urgency": "জৰুৰীকালীন মাত্ৰা",
    "report.urgencyNormal": "সাধাৰণ",
    "report.urgencyUrgent": "জৰুৰী",
    "report.urgencyMedical": "চিকিৎসা / অতি প্ৰয়োজনীয়",
    "report.photos": "ফটো আপলোড কৰক",
    "report.photosHint": "স্পষ্ট ফটোৱে AI মিল নিৰ্ভুল কৰে।",
    "report.reward": "পুৰস্কাৰৰ পৰিমাণ (ঐচ্ছিক)",
    "report.rewardPlaceholder": "₹ টকাত পৰিমাণ",
    "report.contact": "হোৱাটছএপ / ফোন নম্বৰ",
    "report.contactPlaceholder": "১০ টা সংখ্যাৰ মোবাইল নম্বৰ",
    "report.pin": "৪ টা সংখ্যাৰ সুৰক্ষা পিন",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "পাছত সম্পাদনা বা সমাধান কৰিবলৈ প্ৰয়োজন।",
    "report.submit": "ৰিপৰ্ট জমা দিয়ক",
    "report.submitting": "সুৰক্ষিত ৰেজিষ্ট্ৰীত প্ৰকাশ কৰা হৈছে...",
    "report.success": "আপোনাৰ ৰিপৰ্ট সফলতাৰে প্ৰকাশ কৰা হ'ল!",
    "report.viewListing": "তালিকাত চাওক",
    "report.brand": "ব্ৰেণ্ড / নিৰ্মাতা",
    "report.brandPlaceholder": "যেনে এপল, ছেমচাং, টাইটান",
    "report.primaryColor": "প্ৰাথমিক ৰং",
    "report.secondaryColor": "দ্বিতীয় ৰং",
    "report.landmark": "ওচৰৰ চিনাকী স্থান",
    "report.landmarkPlaceholder": "যেনে প্লেটফৰ্ম ২ ৰ ওচৰত, কেফেৰ সন্মুখত",
    "report.secretClue": "গোপন চিনাক্তকৰণ সূত্ৰ (পৰীক্ষাৰ বাবে)",
    "report.secretCluePlaceholder": "যেনে ভিতৰৰ পকেটত ৰঙা কি-চেইন, 'RS' লিখা আছে",
    "feed.searchPlaceholder": "বস্তু, টেগ, ৰং, চহৰ সন্ধান কৰক...",
    "feed.filters": "ফিল্টাৰ",
    "feed.applyFilters": "ফিল্টাৰ প্ৰয়োগ কৰক",
    "feed.recentSearches": "শেহতীয়া সন্ধান",
    "feed.savedSearches": "সংৰক্ষিত সন্ধান",
    "feed.listingRegistry": "তালিকা পঞ্জীয়ন",
    "feed.category": "শ্ৰেণী",
    "feed.allCategories": "সকলো শ্ৰেণী",
    "feed.city": "চহৰ",
    "feed.allCities": "সকলো চহৰ",
    "feed.dateRange": "তাৰিখৰ পৰিসীমা",
    "feed.proximity": "দূৰত্বৰ পৰিসীমা",
    "feed.allProximities": "সকলো দূৰত্ব",
    "feed.within5km": "৫ কিঃমিঃ ভিতৰত",
    "feed.within15km": "১৫ কিঃমিঃ ভিতৰত",
    "feed.within30km": "৩০ কিঃমিঃ ভিতৰত",
    "feed.within50km": "৫০ কিঃমিঃ ভিতৰত",
    "feed.sortCatalog": "ক্ৰম সজাওক",
    "feed.colorSwatch": "ৰঙৰ তালিকা",
    "feed.allColors": "সকলো ৰং",
    "feed.hardwareBrand": "ব্ৰেণ্ড",
    "feed.allBrands": "সকলো ব্ৰেণ্ড",
    "feed.resetFilters": "ফিল্টাৰ ৰিচেট কৰক",
    "feed.viewList": "তালিকা",
    "feed.viewMap": "মেপ",
    "feed.noMatchesFound": "কোনো মিল পোৱা নগ'ল",
    "feed.noMatchesDesc": "এই ফিল্টাৰৰ সৈতে কোনো বস্তু মিল খোৱা নাই।",
    "feed.reportItem": "হেৰোৱা/পোৱা বস্তু পঞ্জীয়ন কৰক",
    "feed.saveParameters": "সন্ধান পেৰামিটাৰ সংৰক্ষণ কৰক",
    "feed.deleteSavedSearch": "সংৰক্ষিত সন্ধান মচক",
    "feed.universalSearchBar": "সন্ধান বাৰ",
    "feed.clearSearch": "সন্ধান পৰিষ্কাৰ কৰক",
    "feed.toggleFilters": "উন্নত ফিল্টাৰ",
    "feed.newestFirst": "নতুন প্ৰথমে",
    "feed.oldestFirst": "পুৰণি প্ৰথমে",
    "feed.highestReward": "সৰ্বাধিক পুৰস্কাৰ",
    "feed.closestDistance": "আটাইতকৈ ওচৰত",
    "postcard.unlockConnection": "যোগাযোগ আনলক কৰক",
    "postcard.iHaveThisItem": "এই বস্তুটো মোৰ ওচৰত আছে",
    "postcard.reclaimed": "উদ্ধাৰ আৰু হস্তান্তৰ সম্পন্ন",
    "postcard.claims": "দাবী",
    "postcard.image": "ছবি",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI মিল",
    "postcard.geminiMatches": "জেমেমিনিয়ে সঠিক মিল পাইছে!",
    "postcard.contactOwner": "গৰাকীৰ সৈতে যোগাযোগ কৰক",
    "postcard.creatorNotice": "কেৱল প্ৰমাণিত পঞ্জীয়কে মিল চাব পাৰিব।",
    "postcard.markResolved": "সমাধান হিচাপে চিহ্নিত কৰক",
    "postcard.deleteListing": "তালিকা মচি পেলাওক",
    "postcard.unlockWithPin": "সুৰক্ষা পিন দি আনলক কৰক",
    "postcard.manageClaims": "দাবী পৰিচালনা কৰক",
    "postcard.shareTemplate": "শ্বেয়াৰ টেক্সট কপি কৰক",
    "postcard.downloadCard": "কাৰ্ড ছবি ডাউনল'ড কৰক",
    "postcard.qrSettings": "QR ছেটিংছ",
    "postcard.postedOn": "পোষ্ট কৰা হৈছে",
    "postcard.reward": "পুৰস্কাৰ",
    "postcard.secureHandover": "সুৰক্ষিত হস্তান্তৰ",
    "matches.title": "AI স্মাৰ্ট মিল আৰু পাৰস্পৰিক সত্যপন",
    "matches.subtitle": "জেমেমিনিয়ে হেৰোৱা আৰু পোৱা বস্তুৰ তুলনা কৰে। কথা-বতৰাৰ পূৰ্বে সত্যপন বাধ্যতামূলক।",
    "matches.myMatches": "মোৰ মিলসমূহ",
    "matches.publicMatches": "ৰাজহুৱা মিলসমূহ",
    "matches.threshold": "ন্যূনতম সীমা:",
    "matches.security": "সুৰক্ষা:",
    "matches.mutualApprovalRequired": "উভয় পক্ষৰ অনুমোদন প্ৰয়োজন",
    "matches.noMatchesFound": "কোনো সম্ভাব্য মিল পোৱা নগ'ল",
    "matches.improveReport": "ৰিপৰ্ট উন্নত কৰক",
    "matches.noPhoto": "কোনো ফটো নাই",
    "matches.chatLive": "লাইভ চ্যাট",
    "matches.chatLocked": "চ্যাট লক কৰা আছে",
    "matches.inspectReview": "পৰীক্ষা আৰু পুনৰীক্ষণ কৰক",
    "matches.openChatLive": "লাইভ চ্যাট খোলক",
    "matches.verifyApprove": "সত্যপন আৰু অনুমোদন কৰক",
    "matches.approvalNotice": "চ্যাট খোলাৰ পূৰ্বে গৰাকী আৰু প্ৰাপক উভয়ে সত্যপন অনুমোদন কৰিব লাগিব।",
    "matches.tabComparison": "তুলনা",
    "matches.tabVerification": "সত্যপন",
    "matches.tabTrust": "বিশ্বাস আৰু হোৱাটছএপ",
    "matches.tabHandover": "হস্তান্তৰ",
    "matches.noImageProvided": "কোনো ছবি প্ৰদান কৰা হোৱা নাই",
    "matches.itemName": "বস্তুৰ নাম",
    "matches.category": "শ্ৰেণী",
    "matches.reward": "পুৰস্কাৰ",
    "matches.locationAddress": "স্থান আৰু ঠিকনা",
    "matches.detailsDescription": "বিতং বিৱৰণ",
    "matches.finderContact": "প্ৰাপকৰ যোগাযোগ",
    "matches.matchStatus": "মিলৰ স্থিতি:",
    "matches.mutualConfirmed": "পাৰস্পৰিক অনুমোদন নিশ্চিত হ'ল। উভয় পক্ষই সত্যপন সম্পূৰ্ণ কৰিছে।",
    "matches.mutualProtocol": "পাৰস্পৰিক সত্যপন প্ৰটোকল",
    "matches.protocolNotice": "প্ৰতাৰণা ৰোধ কৰিবলৈ উভয় পক্ষই সত্যপন তথ্য জমা দিয়ে। অনুমোদন নোহোৱালৈ চ্যাট লক থাকিব।",
    "matches.ownerStatus": "গৰাকীৰ স্থিতি",
    "matches.submittedBy": "জমা দিওঁতা:",
    "matches.aiScore": "AI সত্যপন স্ক'ৰ:",
    "matches.ownerNotSubmitted": "গৰাকীয়ে এতিয়াও উত্তৰ জমা দিয়া নাই।",
    "matches.finderStatus": "প্ৰাপকৰ স্থিতি",
    "matches.finderNotSubmitted": "প্ৰাপকে এতিয়াও উত্তৰ জমা দিয়া নাই।",
    "matches.actionControls": "কাৰ্য্যকলাপ নিয়ন্ত্ৰণ",
    "matches.selectRole": "তথ্য জমা দিবলৈ আপোনাৰ ভূমিকা বাছক।",
    "matches.iAmOwner": "মই গৰাকী হওঁ",
    "matches.iAmFinder": "মই বস্তুটো পাইছোঁ",
    "matches.yourName": "আপোনাৰ নাম",
    "matches.contactWhatsApp": "হোৱাটছএপ / ফোন",
    "matches.forensicQuestions": "বিশেষ সত্যপন প্ৰশ্নসমূহ",
    "matches.trustTitle": "পাৰস্পৰিক বিশ্বাস আৰু সুৰক্ষিত হোৱাটছএপ যোগাযোগ",
    "matches.trustNotice": "সুৰক্ষাৰ বাবে, উভয় ব্যৱহাৰকাৰীয়ে \"মই এই ব্যক্তিক বিশ্বাস কৰোঁ\" ক্লিক কৰাৰ পাছতহে ফোন নম্বৰ দেখা যাব।",
    "matches.ownerTrust": "গৰাকীৰ বিশ্বাস",
    "matches.finderTrust": "প্ৰাপকৰ বিশ্বাস",
    "matches.unlocked": "আনলক কৰা হ'ল",
    "matches.masked": "লুকুওৱা হৈছে",
    "matches.contactAlias": "যোগাযোগৰ নাম",
    "matches.phoneWhatsApp": "ফোন / হোৱাটছএপ",
    "matches.openWhatsApp": "হোৱাটছএপ চ্যাট খোলক",
    "matches.directCall": "পোনপটীয়া কল",
    "matches.trustInstructions": "হোৱাটছএপ লিংক আৰু ফোন নম্বৰ চাবলৈ তলৰ বুটামত ক্লিক কৰক।",
    "matches.trustConsent": "বিশ্বাস ক্লিক কৰি, আপুনি হস্তান্তৰৰ বাবে যোগাযোগ তথ্য বিনিময় কৰিবলৈ সন্মত হৈছে।",
    "matches.reunitedResolved": "বস্তু সফলতাৰে হস্তান্তৰ হ'ল আৰু বিষয়টো সমাধান হ'ল!",
    "matches.reunitedNotice": "গৰাকী আৰু প্ৰাপক উভয়ে সুৰক্ষিত হস্তান্তৰ নিশ্চিত কৰিছে।",
    "matches.handoverProtocol": "সুৰক্ষিত হস্তান্তৰ প্ৰটোকল",
    "matches.handoverNotice": "কোনো ৰাজহুৱা স্থানত লগ পোৱাৰ পৰিকল্পনা কৰক (যেনে ৰেলৱে ষ্টেচন বা থানা)। হস্তান্তৰৰ পাছত দুয়ো নিশ্চিত কৰক।",
    "matches.handoverSchedule": "হস্তান্তৰৰ সময় আৰু স্থান",
    "matches.publicMeetingSpot": "ৰাজহুৱা মিলন স্থান",
    "matches.scheduledDateTime": "নিৰ্ধাৰিত তাৰিখ / সময়",
    "matches.confirmHandover": "হস্তান্তৰ নিশ্চিত কৰক আৰু সমাপ্ত কৰক",
    "matches.confirmHandoverDesc": "বস্তু পোৱাৰ পাছত প্ৰক্ৰিয়া সমাপ্ত কৰিবলৈ নিশ্চিত কৰক।",
    "matches.iHandedOver": "মই বস্তুটো গতাই দিছোঁ",
    "matches.iReceived": "মই মোৰ বস্তুটো পাইছোঁ",
    "matches.chatUnlocksAfter": "সত্যপনৰ পাছত সুৰক্ষিত চ্যাট খোল খাব",
    "matches.chatUnlocksDesc": "দাবী সত্যপন হোৱাৰ পাছত উভয় পক্ষৰ মাজত সুৰক্ষিত চ্যাট স্বয়ংক্ৰিয়ভাৱে খোল খাব।",
    "matches.goToVerification": "সত্যপন টেবিলৈ যাওক",
    "matches.secureHandoverChat": "সুৰক্ষিত হস্তান্তৰ চ্যাট",
    "matches.connectionVerified": "সংযোগ সত্যপন হ'ল! সুৰক্ষিত হস্তান্তৰৰ বাবে বাৰ্তা প্ৰেৰণ কৰক।",
    "matches.dismissMatch": "মিল বাতিল কৰক",
    "matches.shareMatch": "শ্বেয়াৰ কৰক",
    "matches.directClaim": "পোনপটীয়া দাবী",
    "claim.ownershipIndex": "মালিকানা বিশ্বাসযোগ্যতা সূচক",
    "claim.safeVerification": "সুৰক্ষিত মালিকানা সত্যপন",
    "claim.stepsNotice": "হস্তান্তৰ সুৰক্ষিত আৰু প্ৰামাণিক কৰিবলৈ আমি গোপনীয় পদক্ষেপ ব্যৱহাৰ কৰোঁ।",
    "claim.protectedContact": "আপোনাৰ যোগাযোগ তথ্য সম্পূৰ্ণ সুৰক্ষিত। কেৱল সত্যপন কৰা ব্যক্তিয়েহে চাব পাৰিব।",
    "claim.unlockedMutual": "পাৰস্পৰিক সত্যপনৰ পাছতহে যোগাযোগ মুকলি হ'ব। আপোনাৰ নম্বৰ ৰাজহুৱা কৰা নহয়।",
    "claim.aiEvaluationNotice": "প্ৰতাৰণা ৰোধ কৰিবলৈ আমাৰ AI য়ে দাবী মূল্যায়ন কৰে।",
    "claim.trackingNotice": "অনন্য ট্ৰেকিং কোডে উভয় পক্ষক সুৰক্ষা দিয়ে।",
    "claim.modalDescription": "বস্তু প্ৰকৃত গৰাকীৰ ওচৰলৈ যোৱাটো নিশ্চিত কৰিবলৈ আমি যোগাযোগ শ্বেয়াৰ কৰাৰ পূৰ্বে পৰীক্ষা কৰোঁ।",
    "claim.aiPreparingQuestions": "AI য়ে আপোনাৰ সত্যপন প্ৰশ্ন প্ৰস্তুত কৰি আছে...",
    "claim.claimantName": "দাবীদায়ীৰ নাম",
    "claim.officialNamePlaceholder": "আপোনাৰ চৰকাৰী নাম",
    "claim.whatsappMobile": "হোৱাটছএপ মোবাইল",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "বস্তুৰ বিৱৰণ নিশ্চিত কৰক",
    "claim.detailsPlaceholder": "অনুগ্ৰহ কৰি বিতংকৈ কওক (দাগ, ভিতৰৰ সামগ্ৰী, বিল ইত্যাদি)...",
    "claim.verificationRegistered": "সত্যপন পঞ্জীয়ন হ'ল",
    "claim.detailsSavedSecurely": "আপোনাৰ তথ্য সুৰক্ষিতভাৱে সংৰক্ষণ কৰা হ'ল। AI য়ে তথ্য তুলনা কৰিছে।",
    "claim.verificationId": "সত্যপন ID (দাবী ID)",
    "claim.aiMatchDetails": "AI মিল বিৱৰণ",
    "claim.bookmarkLink": "পোনপটীয়া লিংক (পাছত চাবলৈ সংৰক্ষণ কৰক)",
    "claim.doneAwaitSignoff": "সম্পূৰ্ণ & গৰাকীৰ অনুমোদনলৈ অপেক্ষা কৰক",
    "auth.recoverBelongings": "বিশ্বস্ত নাগৰিক আৰু বুদ্ধিমত্তাৰে হেৰোৱা বস্তু সুৰক্ষিতভাৱে ঘূৰাই পাওক।",
    "auth.startEmail": "ইমেইলৰ সৈতে আৰম্ভ কৰক",
    "auth.continuePhone": "ফোনৰ সৈতে আগবাঢ়ক",
    "auth.signIn": "ছাইন ইন কৰক",
    "auth.welcomeBack": "পুনৰ স্বাগতম",
    "auth.resumeTracking": "ট্ৰেকিং অব্যাহত ৰাখিবলৈ আপোনাৰ একাউণ্টত ছাইন ইন কৰক।",
    "auth.emailOrUsername": "ইমেইল বা ব্যৱহাৰকাৰী নাম",
    "auth.password": "পাছৱৰ্ড",
    "auth.forgotPassword": "পাছৱৰ্ড পাহৰিলে নেকি?",
    "auth.createAccount": "একাউণ্ট খোলক",
    "auth.joinNetwork": "ৰক্ষক নেটৱৰ্কত যোগদান কৰক।",
    "auth.fullName": "সম্পূৰ্ণ নাম",
    "auth.username": "ব্যৱহাৰকাৰী নাম",
    "auth.emailAddress": "ইমেইল ঠিকনা",
    "auth.confirmPassword": "পাছৱৰ্ড নিশ্চিত কৰক",
    "auth.acceptPolicy": "মই গোপনীয়তা নীতি গ্ৰহণ কৰিলোঁ আৰু তথ্য বিনিময়ত সন্মত।",
    "auth.resetPassword": "পাছৱৰ্ড ৰিচেট কৰক",
    "auth.resetNotice": "একাউণ্ট প্ৰৱেশৰ বাবে আমি এটা সুৰক্ষিত লিংক প্ৰেৰণ কৰিম।",
    "auth.sendResetLink": "ৰিচেট লিংক পঠাওক",
    "auth.returnSignIn": "ছাইন ইনলৈ উভতি যাওক",
    "auth.setupProfile": "আপোনাৰ প্ৰ'ফাইল ছেট কৰক",
    "auth.setupNotice": "আনৰ সৈতে সমন্বয় ৰাখিবলৈ প্ৰ'ফাইল সম্পূৰ্ণ কৰক।",
    "auth.takeSnapshot": "ফটো তোলক",
    "auth.choosePhoto": "ফটো বাছক",
    "auth.cityNeighborhood": "চহৰ / অঞ্চল (বাধ্যতামূলক)",
    "auth.shortBio": "চমু পৰিচয় (ঐচ্ছিক)",
    "auth.completeSetup": "ছেটআপ সম্পূৰ্ণ কৰক",
    "dashboard.welcomeTitle": "আপোনাৰ প্ৰ'ফাইল ছেট কৰক",
    "dashboard.welcomeDesc": "LINCO লৈ স্বাগতম। সুৰক্ষিত হস্তান্তৰৰ বাবে আপোনাৰ বিষয়ে চমুকৈ কওক।",
    "dashboard.chooseAvatar": "অৱতাৰ বাছক",
    "dashboard.fullName": "সম্পূৰ্ণ নাম",
    "dashboard.username": "ব্যৱহাৰকাৰী নাম",
    "dashboard.bio": "পৰিচয় (ঐচ্ছিক)",
    "dashboard.city": "চহৰ",
    "dashboard.createProfile": "প্ৰ'ফাইল সৃষ্টি কৰক",
    "dashboard.skipForNow": "বৰ্তমান এৰাই চলক",
    "dashboard.changeCover": "কভাৰ সলনি কৰক",
    "dashboard.editProfile": "প্ৰ'ফাইল সম্পাদনা কৰক",
    "dashboard.shareProfile": "প্ৰ'ফাইল শ্বেয়াৰ কৰক",
    "dashboard.settings": "ছেটিংছ",
    "dashboard.editDetails": "বিৱৰণ সম্পাদনা কৰক",
    "dashboard.accountSection": "একাউণ্ট",
    "dashboard.email": "ইমেইল",
    "dashboard.password": "পাছৱৰ্ড",
    "dashboard.privacySection": "গোপনীয়তা",
    "dashboard.blockedUsers": "অৱৰোধ কৰা ব্যৱহাৰকাৰী",
    "dashboard.downloadData": "মোৰ তথ্য ডাউনল'ড কৰক",
    "dashboard.deleteAccount": "একাউণ্ট মচক",
    "dashboard.notifSection": "অধিসূচনা",
    "dashboard.pushNotifs": "পুশ অধিসূচনা",
    "dashboard.pushDesc": "তৎক্ষণাৎ মিল আৰু চ্যাটৰ বাবে অধিসূচনা",
    "dashboard.emailReports": "ইমেইল ৰিপৰ্ট",
    "dashboard.emailDesc": "অন দাবীযুক্ত বস্তুৰ সাপ্তাহিক সাৰাংশ",
    "dashboard.appearanceSection": "চেহেৰা",
    "dashboard.theme": "থিম",
    "dashboard.language": "ভাষা",
    "dashboard.supportSection": "সহায়তা",
    "dashboard.help": "সহায়",
    "dashboard.contact": "যোগাযোগ",
    "dashboard.about": "বিৱৰণ",
    "dashboard.logout": "লগ আউট",
    "dashboard.updateEmail": "ইমেইল আপডেট কৰক",
    "dashboard.saveEmail": "ইমেইল সংৰক্ষণ কৰক",
    "dashboard.changePassword": "পাছৱৰ্ড সলনি কৰক",
    "dashboard.unblock": "আনব্লক কৰক",
    "dashboard.noBlocked": "কোনো অৱৰোধ কৰা ব্যৱহাৰকাৰী নাই।",
    "dashboard.contactSupport": "সহায়তাৰ সৈতে যোগাযোগ কৰক",
    "dashboard.supportDesc": "সহায় বা প্ৰশ্নৰ বাবে আমাৰ দলৰ সৈতে যোগাযোগ কৰক:",
    "dashboard.aboutLinco": "LINCO ৰ বিষয়ে",
    "dashboard.aboutDesc": "LINCO এটা সুৰক্ষিত এপ যিয়ে জেমেমিনি AI ব্যৱহাৰ কৰি হেৰোৱা বস্তু বিচৰাত সহায় কৰে।",
    "dashboard.appVersion": "এপ সংস্কৰণ: v1.3.0",
    "dashboard.capturePhoto": "ফটো তোলক",
    "dashboard.useCamera": "কেমেৰা ব্যৱহাৰ কৰক",
    "dashboard.chooseGallery": "গেলেৰীৰ পৰা বাছক",
    "dashboard.confirmDeletion": "মচা নিশ্চিত কৰক",
    "dashboard.deletionWarning": "এই কাৰ্য স্থায়ী। আপোনাৰ সকলো তথ্য মচি পেলোৱা হ'ব।",
    "dashboard.typePasswordConfirm": "নিশ্চিত কৰিবলৈ পাছৱৰ্ড দিয়ক",
    "dashboard.typeDeletePrompt": "একাউণ্ট স্থায়ীভাৱে মচিবলৈ তলত DELETE লিখক।",
    "ownerClaims.controlBoard": "দাবী নিয়ন্ত্ৰণ ব'ৰ্ড",
    "ownerClaims.enterPin": "সুৰক্ষা পিন দিয়ক",
    "ownerClaims.pinDesc": "পঞ্জীয়নৰ সময়ত দিয়া ৪ টা সংখ্যাৰ পিন দিয়ক।",
    "ownerClaims.clear": "পৰিষ্কাৰ কৰক",
    "ownerClaims.authenticating": "প্ৰমাণীকৰণ কৰা হৈছে...",
    "ownerClaims.integrityScore": "জেমেমিনি স্ক'ৰ",
    "ownerClaims.reviewNotice": "উত্তৰ পৰীক্ষা কৰক। অনুমোদন দিলে সুৰক্ষিত উদ্ধাৰ কক্ষ সক্ৰিয় হ'ব।",
    "ownerClaims.completeHandover": "হস্তান্তৰ সম্পূৰ্ণ কৰক",
    "ownerClaims.postClosed": "এই পোষ্টটো বন্ধ কৰা হৈছে।",
    "ownerClaims.closeWindow": "উইণ্ডো বন্ধ কৰক",
    "ownerClaims.approved": "অনুমোদিত",
    "ownerClaims.resolved": "সমাধান হ'ল",
    "ownerClaims.youReturned": "আপুনি ঘূৰাই দিলে:",
    "ownerClaims.meetingCoords": "সুৰক্ষিত মিলন তথ্য দিয়ক...",
    "pin.title": "সুৰক্ষা পিন দিয়ক",
    "pin.passcode": "৪ টা সংখ্যাৰ পাছকোড",
    "pin.verifying": "পৰীক্ষা কৰা হৈছে...",
    "pin.clear": "পৰিষ্কাৰ কৰক",
    "pin.unlock": "আনলক কৰক",
    "pin.promise": "আপোনাৰ পিনে আপোনাৰ ব্যক্তিগত তথ্য সুৰক্ষিত ৰাখে।",
    "communityFound.title": "এই বস্তুটো মোৰ ওচৰত আছে",
    "communityFound.protocol": "জিৰো-ট্ৰাষ্ট প্ৰটোকল",
    "communityFound.verifyFinding": "প্ৰাপ্তি নিশ্চিত কৰক",
    "communityFound.withoutLeaking": "ব্যক্তিগত তথ্য ফাদিল নকৰাকৈ",
    "communityFound.lostReported": "হেৰোৱা বস্তুৰ ৰিপৰ্ট",
    "communityFound.whereFound": "আপুনি এইটো ক'ত পালে?",
    "communityFound.insideContents": "ভিতৰৰ বস্তু (ঐচ্ছিক)",
    "communityFound.secretDetails": "বিশেষ বৈশিষ্ট্য / গোপন তথ্য",
    "communityFound.createPin": "আপোনাৰ সুৰক্ষা পিন সৃষ্টি কৰক",
    "communityFound.reward": "পুৰস্কাৰ",
    "communityFound.registeredNotice": "পঞ্জীয়ন হ'ল। গৰাকীক আপোনাৰ উত্তৰ জনোৱা হৈছে।",
    "claimTracker.title": "স্থিতি সময়ৰেখা",
    "claimTracker.protocols": "সুৰক্ষিত উদ্ধাৰ প্ৰটোকল",
    "claimTracker.publicSpaces": "ষ্টেচন বা কেফেৰ দৰে আলোকিত ৰাজহুৱা স্থানত লগ পাওক।",
    "claimTracker.verifyCarefully": "পুৰস্কাৰ দিয়াৰ পূৰ্বে বস্তু সাৱধানে পৰীক্ষা কৰক।",
    "claimTracker.documentDetails": "মিলন তথ্য ৰেকৰ্ড কৰিবলৈ আমাৰ সুৰক্ষিত চ্যাট ব্যৱহাৰ কৰক।",
    "claimTracker.lookupAnother": "অন্য এটা সন্ধান কৰক",
    "claimTracker.unsuccessful": "দাবী মূল্যায়ন ব্যৰ্থ হ'ল",
    "claimTracker.trustCheck": "পাৰস্পৰিক বিশ্বাস পৰীক্ষা",
    "claimTracker.awaitingApproval": "প্ৰাপকৰ অনুমোদনলৈ অপেক্ষা",
    "claimTracker.recoveryRoom": "সুৰক্ষিত উদ্ধাৰ কক্ষ",
    "claimTracker.enterRoom": "কক্ষত প্ৰৱেশ কৰক",
    "claimTracker.discussion": "হস্তান্তৰ আলোচনা",
    "recovery.transmissionSecured": "তথ্য সুৰক্ষিত",
    "recovery.reportIndexed": "ৰিপৰ্ট তালিকাভুক্ত কৰা হৈছে",
    "recovery.dossierActive": "নথিপত্ৰ সক্ৰিয়। জেমেমিনিয়ে বিশ্লেষণ কৰিছে।",
    "recovery.engineTitle": "AI উদ্ধাৰ সম্ভাৱনা ইঞ্জিন",
    "recovery.retrievalLikelihood": "পোৱাৰ সম্ভাৱনা:",
    "recovery.analyzedFactors": "বিশ্লেষিত কাৰকসমূহ",
    "recovery.semanticNotice": "আমাৰ মডেলে ব্ৰেণ্ড, ৰং আৰু দাগ বিশ্লেষণ কৰে।",
    "recovery.uniqueIdentifier": "অনন্য চিনাক্তকাৰীয়ে সম্পূৰ্ণ সত্যপন সম্ভৱ কৰে।",
    "recovery.setReward": "পুৰস্কাৰ নিৰ্ধাৰণ কৰক",
    "reward.fairRange": "উপযুক্ত সীমা",
    "reward.suggestReward": "পুৰস্কাৰ পৰামৰ্শ দিয়ক",
    "reward.customReward": "অন্য পৰিমাণ",
    "privacy.complianceProtocols": "গোপনীয়তা প্ৰটোকল",
    "privacy.title": "বিশ্বাস আৰু সুৰক্ষা কেন্দ্ৰ",
    "privacy.subtitle": "আমি ব্যৱহাৰকাৰীৰ সুৰক্ষাৰ উচ্চতম মান অনুসৰণ কৰোঁ।",
    "privacy.exitSection": "প্ৰস্থান কৰক",
    "privacy.privacyPolicy": "গোপনীয়তা নীতি",
    "privacy.lastUpdated": "শেহতীয়া আপডেট: ৭ জুলাই, ২০২৬।",
    "privacy.dataAcquisition": "আমি কেৱল প্ৰয়োজনীয় তথ্য সংগ্ৰহ কৰোঁ:",
    "privacy.spatiotemporalTags": "স্থান-সময় টেগ:",
    "privacy.coldStorage": "সংৰক্ষণৰ পূৰ্বে সৰ্বোচ্চ সীমা।",
    "privacy.cookiePreferences": "কুকি পছন্দ পৰিচালনা কৰক।",
    "privacy.purgeBrowser": "তথ্য তৎক্ষণাৎ মচক।",
    "privacy.hereToHelp": "আমি সহায়ৰ বাবে সাজু।",
    "privacy.connectFounder": "সহায়তাৰ বাবে আমাৰ সৈতে যোগাযোগ কৰক।",
    "cookie.title": "গোপনীয়তা সুৰক্ষা",
    "cookie.message": "আমি কেৱল বস্তু বিচৰাৰ বাবে প্ৰয়োজনীয় তথ্য সংগ্ৰহ কৰোঁ।",
    "cookie.trackingNotice": "মালিকানা প্ৰমাণ নোহোৱালৈকে তথ্য ব্যক্তিগত থাকে।",
    "cookie.acceptAll": "সকলো গ্ৰহণ কৰক",
    "cookie.learnMore": "অধিক জানক",
    "about.tagline": "সমাজক সংযোগ কৰা, হেৰোৱা বস্তু ঘূৰাই অনা",
    "about.mission": "LINCO নৈতিক AI আৰু সামাজিক বিশ্বাসেৰে হেৰোৱা বস্তু গৰাকীক গতাই দিবলৈ সংকল্পবদ্ধ।",
    "notifications.title": "অধিসূচনা",
    "notifications.empty": "কোনো নতুন অধিসূচনা নাই",
    "notifications.markAllRead": "সকলো পঢ়া হ'ল বুলি চিহ্নিত কৰক",
    "notifications.clearAll": "সকলো পৰিষ্কাৰ কৰক",
    "notifications.matchFoundTitle": "সম্ভাব্য মিল পোৱা গৈছে",
    "notifications.matchFoundMsg": "আমাৰ AI য়ে এটা সম্ভাব্য মিল চিনাক্ত কৰিছে।",
    "notifications.claimReceivedTitle": "নতুন দাবী পোৱা গৈছে",
    "notifications.claimReceivedMsg": "এজন ব্যৱহাৰকাৰীয়ে আপোনাৰ তালিকাৰ বাবে সত্যপন উত্তৰ দিছে।",
    "notifications.claimApprovedTitle": "দাবী অনুমোদিত হ'ল",
    "notifications.claimApprovedMsg": "আপোনাৰ দাবী গৰাকীয়ে সত্যপন আৰু অনুমোদন কৰিছে।",
    "notifications.chatMessageTitle": "উদ্ধাৰ কক্ষত নতুন বাৰ্তা",
    "notifications.chatMessageMsg": "আপোনাৰ হস্তান্তৰ সন্দৰ্ভত এটা নতুন বাৰ্তা আহিছে।",
    "notifications.handoverDoneTitle": "হস্তান্তৰ নিশ্চিত হ'ল",
    "notifications.handoverDoneMsg": "বস্তু ঘূৰাই পোৱা নিশ্চিত হ'ল আৰু বিষয়টো সমাধান হ'ল।",
    "enhance.button": "AI বিৱৰণ উন্নত কৰক",
    "enhance.loading": "জেমেমিনি AI য়ে বিৱৰণ প্ৰস্তুত কৰি আছে...",
    "enhance.apply": "উন্নত বিৱৰণ ব্যৱহাৰ কৰক",
    "enhance.discard": "মূল বিৱৰণ ৰাখক",
    "enhance.rewardTitle": "AI পুৰস্কাৰ পৰামৰ্শ",
    "enhance.rewardCalculated": "পৰামৰ্শিত পুৰস্কাৰ: ₹",
    "enhance.rewardReason": "বস্তুৰ শ্ৰেণী আৰু ব্ৰেণ্ড মূল্যৰ ওপৰত ভিত্তি কৰি।",
    "timeline.reconstruct": "সময়ৰেখা পুনৰ নিৰ্মাণ কৰক",
    "timeline.loading": "পথ আৰু চেকপইণ্ট বিশ্লেষণ কৰা হৈছে...",
    "timeline.spotLikelihood": "হেৰোৱাৰ সম্ভাব্য স্থান:",
    "timeline.window": "সম্ভাব্য সময়:",
    "timeline.analysis": "যাত্ৰা বিশ্লেষণ:",
    "timeline.confidence": "বিশ্বাসযোগ্যতা:",
    "timeline.addPoint": "চেকপইণ্ট যোগ কৰক",
    "timeline.pointName": "চেকপইণ্টৰ নাম / ষ্টেচন",
    "chat.assistant": "AI সহায়ক",
    "chat.subtitle": "আপোনাৰ সাথী",
    "chat.description": "৬০ ছেকেণ্ডত হেৰোৱা বা পোৱা বস্তুৰ ৰিপৰ্ট কৰক। কওক বা লিখক।",
    "chat.startAssistant": "AI ৰিপৰ্ট সহায়ক আৰম্ভ কৰক",
    "chat.location": "স্থান:",
    "chat.securityPin": "সুৰক্ষা পিন:",
    "chat.skipPhoto": "ফটো এৰাই চলক",
    "chat.item": "বস্তু:",
    "chat.errorLoading": "সহায়ক লোড কৰাত সমস্যা। পুনৰ চেষ্টা কৰক।",
    "chat.welcomeMessage": "LINCO Saathii লৈ স্বাগতম! কওক কি হেৰাইছে বা পাইছে?",
    "chat.networkError": "নেটৱৰ্ক সমস্যা। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক!",
    "chat.understoodError": "স্পষ্ট বুজিব নোৱাৰিলোঁ। অধিক বিৱৰণ দিব পাৰিবনে?",
    "feed.lostOnly": "হেৰোৱা বস্তু",
    "feed.foundOnly": "পোৱা বস্তু",
    "feed.filterByCategory": "শ্ৰেণী",
    "feed.filterByCity": "চহৰ",
    "feed.filterByUrgency": "জৰুৰী",
    "feed.empty": "কোনো বস্তু পোৱা নগ'ল।",
    "feed.emptyAction": "নতুন বস্তু পঞ্জীয়ন কৰক",
    "matches.contactFinder": "প্ৰাপকৰ সৈতে যোগাযোগ কৰক",
    "matches.contactOwner": "গৰাকীৰ সৈতে যোগাযোগ কৰক",
    "matches.verifyOwnership": "মালিকানা সত্যপন কৰক",
    "claim.title": "মালিকানা দাবী জমা দিয়ক",
    "claim.subtitle": "যোগাযোগ ফাদিল নকৰাকৈ AI সুৰক্ষাৰে মালিকানা সত্যপন কৰক।",
    "claim.questionsTitle": "সত্যপন প্ৰশ্নসমূহ",
    "claim.questionsSubtitle": "প্ৰকৃত মালিকানা প্ৰমাণ কৰিবলৈ প্ৰশ্নৰ উত্তৰ দিয়ক:",
    "claim.answerPlaceholder": "আপোনাৰ উত্তৰ...",
    "claim.submit": "জমা দিয়ক",
    "claim.submitting": "সত্যপন তথ্য জমা দিয়া হৈছে...",
    "claim.success": "দাবী জমা হ'ল! গৰাকীয়ে আপোনাৰ উত্তৰ পৰীক্ষা কৰিব।",
    "dashboard.myReports": "মোৰ ৰিপৰ্টসমূহ",
    "dashboard.myClaims": "মোৰ দাবীসমূহ",
    "dashboard.savedPosts": "সংৰক্ষিত পোষ্টসমূহ",
    "help.title": "সঘনাই সোধা প্ৰশ্নসমূহ",
    "help.q1": "LINCO এ মোৰ গোপনীয়তা কেনেকৈ ৰক্ষা কৰে?",
    "help.a1": "ফোন নম্বৰ ৰাজহুৱা কৰা নহয়। পাৰস্পৰিক অনুমোদনৰ পাছতহে যোগাযোগ মুকলি হয়।",
    "help.q2": "ৰিপৰ্ট কৰিলে কি হয়?",
    "help.a2": "আমাৰ AI য়ে আপোনাৰ ৰিপৰ্ট পোৱা বস্তুৰ সৈতে তুলনা কৰে।",
    "help.q3": "মালিকানা সত্যপন কেনেকৈ কাম কৰে?",
    "help.a3": "কেৱল প্ৰকৃত গৰাকীয়ে জনা গোপন প্ৰশ্নৰ উত্তৰ দিব লাগে।",
    "help.q4": "এইটো বিনামূলীয়ানে?",
    "help.a4": "হয়, LINCO সম্পূৰ্ণ বিনামূলীয়া আৰু সামাজিক।",
    "home.heroTitle": "হেৰোৱা বস্তু সুৰক্ষিতভাৱে ঘূৰাই পাওক",
    "home.heroSubtitle": "সুৰক্ষিত আৰু AI সমৰ্থিত সামাজিক মঞ্চ।",
    "home.statsRecovered": "উদ্ধাৰ হোৱা বস্তু",
    "home.statsActive": "সক্ৰিয় নাগৰিক",
    "home.statsCities": "চহৰ",
    "home.howItWorks": "এইটো কেনেদৰে কাম কৰে",
    "home.step1Title": "1. তথ্য পঞ্জীয়ন কৰক",
    "home.step1Desc": "ভইচ বা লেখাৰে পঞ্জীয়ন কৰক।",
    "home.step2Title": "2. AI মিল",
    "home.step2Desc": "তথ্য আৰু ফটো পৰস্পৰ মিলোৱা হয়।",
    "home.step3Title": "3. সুৰক্ষিত হস্তান্তৰ",
    "home.step3Desc": "সত্যপন কৰি সুৰক্ষিতভাৱে বস্তু ঘূৰাই লওক।",
}

print(f"Loaded AS_NEW ({len(AS_NEW)} keys).")
