"""
Master English Canonical Keys for LINCO (39 languages).
"""

MASTER_EN: dict[str, str] = {
    # App & Navigation
    "app.tagline": "AI Lost & Found India",
    "app.subtitle": "Reuniting lost belongings across Indian communities with privacy, precision, and verified trust.",
    "nav.home": "Home",
    "nav.report": "Report Item",
    "nav.feed": "Community Feed",
    "nav.matches": "AI Matches",
    "nav.activity": "Activity",
    "nav.profile": "Profile & Settings",
    "nav.about": "About LINCO",
    "nav.privacyTrust": "Privacy & Security",
    "nav.language": "Language",
    "nav.saathii": "AI Assistant Saathii",

    # Common
    "common.back": "Back",
    "common.next": "Next Step",
    "common.cancel": "Cancel",
    "common.save": "Save Changes",
    "common.submit": "Submit Report",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.success": "Success",
    "common.error": "Error",
    "common.search": "Search items, landmarks, brands...",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.optional": "Optional",
    "common.required": "Required",
    "common.viewAll": "View All",
    "common.details": "Details",
    "common.status": "Status",

    # Language selection
    "lang.heading": "Choose Your Language",
    "lang.subheading": "Use LINCO in the language you're most comfortable with.",
    "lang.note": "You can change your language anytime from Settings.",
    "lang.continue": "Continue with LINCO",
    "lang.searchPlaceholder": "Search languages (e.g. Hindi, ગુજરાતી, मराठी, தமிழ்)...",
    "lang.tabAll": "All Languages",
    "lang.tabIndian": "Indian Languages (22)",
    "lang.tabInternational": "International Languages",
    "lang.supportedBadge": "Fully Supported",
    "lang.previewBadge": "Preview / Beta",

    # Voice Quick Fill
    "voice.button": "Voice Input",
    "voice.listening": "Listening... Speak naturally in your language",
    "voice.processing": "Processing your voice note...",
    "voice.transcribing": "Transcribing speech...",
    "voice.reviewTitle": "Voice Transcription Review",
    "voice.reviewSubtitle": "Review and edit before populating report fields:",
    "voice.apply": "Apply to Report",
    "voice.retry": "Try Again",
    "voice.stop": "Stop Recording",
    "voice.error": "Voice recognition encountered an error. Please try again.",
    "voice.hint": "Speak details like item brand, color, location, and date.",

    # Report Wizard
    "report.title": "Report an Item",
    "report.subtitle": "Register a lost or found item with smart spatial correlation.",
    "report.type": "Report Type",
    "report.typeLost": "I Lost an Item",
    "report.typeFound": "I Found an Item",
    "report.stepBasics": "1. Basic Details",
    "report.stepLocation": "2. Location & Date",
    "report.stepPhotos": "3. Photos & Clues",
    "report.stepSecurity": "4. Security & Contact",
    "report.itemTitle": "Item Name",
    "report.itemTitlePlaceholder": "e.g. Black Leather Casio Watch, Blue Samsonite Backpack",
    "report.category": "Category",
    "report.selectCategory": "Select item category",
    "report.description": "Detailed Description",
    "report.descriptionPlaceholder": "Describe color, model, scratches, distinctive marks, contents inside...",
    "report.location": "Location Found / Lost",
    "report.locationPlaceholder": "e.g. Andheri Metro Station Gate 2, Mumbai or Sector 18 Noida",
    "report.date": "Date & Approximate Time",
    "report.urgency": "Urgency Level",
    "report.urgencyNormal": "Normal",
    "report.urgencyUrgent": "Urgent",
    "report.urgencyMedical": "Medical / Critical",
    "report.photos": "Upload Photos",
    "report.photosHint": "Clear photos significantly improve AI visual matching accuracy.",
    "report.reward": "Reward Offered (Optional)",
    "report.rewardPlaceholder": "₹ Amount in INR",
    "report.contact": "WhatsApp / Phone Contact",
    "report.contactPlaceholder": "10-digit mobile number",
    "report.pin": "4-Digit Security PIN",
    "report.pinPlaceholder": "••••",
    "report.pinHint": "Required to edit, claim, or mark this listing resolved later.",
    "report.submit": "Publish Listing to Community",
    "report.submitting": "Publishing report to secure registry...",
    "report.success": "Your item report has been published successfully!",
    "report.viewListing": "View Listing in Feed",
    "report.brand": "Brand / Manufacturer",
    "report.brandPlaceholder": "e.g. Apple, Samsung, Titan, Wildcraft",
    "report.primaryColor": "Primary Color",
    "report.secondaryColor": "Secondary Color",
    "report.landmark": "Nearby Landmark",
    "report.landmarkPlaceholder": "e.g. Near platform 3 escalator, opposite Coffee Day",
    "report.secretClue": "Secret Characteristic (Verification Clue)",
    "report.secretCluePlaceholder": "e.g. Small red keychain inside pocket, engraved initials 'RS'",

    # AI Enhancement & Smart Tools
    "enhance.button": "AI Polish Description",
    "enhance.loading": "Gemini AI is structuring your description...",
    "enhance.modalTitle": "AI Enhanced Description",
    "enhance.original": "Original Text:",
    "enhance.enhanced": "AI Refined Text:",
    "enhance.apply": "Use Refined Description",
    "enhance.discard": "Keep Original",
    "enhance.rewardTitle": "AI Fair Reward Suggestion",
    "enhance.rewardCalculated": "Suggested Reward: ₹",
    "enhance.rewardReason": "Based on item category, brand value, and community recovery standards.",

    # Timeline Reconstructor
    "timeline.title": "AI Spatiotemporal Timeline",
    "timeline.subtitle": "Reconstructing item trajectory across reported waypoints.",
    "timeline.reconstruct": "Reconstruct Timeline",
    "timeline.loading": "Analyzing travel trajectory and reported checkpoints...",
    "timeline.spotLikelihood": "Likely Loss Location:",
    "timeline.window": "Likely Time Window:",
    "timeline.reasoning": "Spatial Correlation Reasoning:",
    "timeline.analysis": "Full Journey Analysis:",
    "timeline.confidence": "Trajectory Confidence:",
    "timeline.addPoint": "Add Trajectory Checkpoint",
    "timeline.pointName": "Checkpoint Name / Station",

    # LincoSaathii Chat
    "chat.title": "LINCO Saathii",
    "chat.assistant": "AI Assistant",
    "chat.subtitle": "Your Conversational Companion",
    "chat.description": "Report your lost or found item in under 60 seconds. Speak or type in your language. Our AI automatically extracts fields, reverse-geocodes locations, and formats your entry.",
    "chat.startAssistant": "Start AI Report Assistant",
    "chat.location": "Location:",
    "chat.securityPin": "Security PIN:",
    "chat.skipPhoto": "Skip Photo",
    "chat.item": "Item:",
    "chat.errorLoading": "Something went wrong while loading the chatbot assistant. Please refresh the page or try again.",
    "chat.placeholder": "Type lost/found item details...",
    "chat.welcomeMessage": "Welcome to LincoSaathii! I am your lost and found companion. Tell me what was lost or found, and we'll record it together.",
    "chat.networkError": "Sorry, there was a temporary network issue. Please try again!",
    "chat.understoodError": "I could not understand properly. Could you please rephrase or give more details?",

    # Community Feed & Search
    "feed.title": "Community Registry Feed",
    "feed.subtitle": "Browse verified active lost and found reports across communities.",
    "feed.searchPlaceholder": "Search matching items, tags, colors, brand names, cities...",
    "feed.all": "All Items",
    "feed.lostOnly": "Lost Items",
    "feed.foundOnly": "Found Items",
    "feed.filterByCategory": "Category",
    "feed.filterByCity": "City",
    "feed.filterByUrgency": "Urgency",
    "feed.empty": "No items match your active search criteria.",
    "feed.emptyAction": "Report a New Item",
    "feed.filters": "Filters",
    "feed.applyFilters": "Apply As Filters",
    "feed.recentSearches": "Recent Searches",
    "feed.savedSearches": "Saved Search Configurations",
    "feed.listingRegistry": "Listing Registry",
    "feed.category": "Category",
    "feed.allCategories": "All Categories",
    "feed.city": "Geographical City",
    "feed.allCities": "All Cities",
    "feed.dateRange": "Date Range",
    "feed.proximity": "Proximity Boundary",
    "feed.allProximities": "All Proximities (Any Distance)",
    "feed.within5km": "Within 5 Kilometers",
    "feed.within15km": "Within 15 Kilometers",
    "feed.within30km": "Within 30 Kilometers",
    "feed.within50km": "Within 50 Kilometers",
    "feed.sortCatalog": "Sort Catalog",
    "feed.colorSwatch": "Color Chromatic Swatch",
    "feed.allColors": "All Colors",
    "feed.hardwareBrand": "Hardware Brand Manufacturer",
    "feed.allBrands": "All Brands",
    "feed.resetFilters": "Reset Filter Suite",
    "feed.viewList": "List",
    "feed.viewMap": "Map",
    "feed.noMatchesFound": "No match found in indexing tables",
    "feed.noMatchesDesc": "We scanned our secure databases but didn't find any lost or found items fitting these exact filters. Try broadening your keywords or resetting selected swatches.",
    "feed.reportItem": "Report Lost/Found Item",
    "feed.saveParameters": "Save Search Parameters",
    "feed.deleteSavedSearch": "Delete Saved Search",
    "feed.universalSearchBar": "Universal Search Bar",
    "feed.clearSearch": "Clear Search Input",
    "feed.toggleFilters": "Toggle Advanced Filters",
    "feed.newestFirst": "Newest First",
    "feed.oldestFirst": "Oldest First",
    "feed.highestReward": "Highest Reward",
    "feed.closestDistance": "Closest Distance",

    # PostCard & Actions
    "postcard.unlockConnection": "Unlock Connection",
    "postcard.iHaveThisItem": "I Have This Item",
    "postcard.reclaimed": "Reclaimed & Handed Over",
    "postcard.claims": "Claims",
    "postcard.image": "Image",
    "postcard.qr": "QR",
    "postcard.aiMatch": "AI MATCH",
    "postcard.geminiMatches": "Gemini detected smart matches!",
    "postcard.contactOwner": "Contact Owner",
    "postcard.creatorNotice": "Only the verified creator of this listing can decrypt similarity breakdowns and contact matching owners.",
    "postcard.markResolved": "Mark as Resolved",
    "postcard.deleteListing": "Delete Listing",
    "postcard.unlockWithPin": "Unlock connection with Security PIN",
    "postcard.manageClaims": "Manage Claims & Approve/Reject",
    "postcard.shareTemplate": "Share/Copy Template Text",
    "postcard.downloadCard": "Download Post as Image Card",
    "postcard.qrSettings": "Interactive QR Code & Print Settings",
    "postcard.postedOn": "Posted on",
    "postcard.reward": "Reward",
    "postcard.secureHandover": "Secure Handover",

    # AI Matches & Handover
    "matches.title": "AI Smart Matches & Mutual Verification",
    "matches.subtitle": "Gemini continuously compares Lost and Found listings. Connections follow strict mutual verification before Secure Chat coordinates item handover.",
    "matches.score": "Similarity Score",
    "matches.reason": "Match Explanation",
    "matches.contactFinder": "Contact Finder",
    "matches.contactOwner": "Contact Owner",
    "matches.verifyOwnership": "Verify Ownership",
    "matches.myMatches": "My Matches",
    "matches.publicMatches": "Public Matches",
    "matches.threshold": "Threshold:",
    "matches.security": "Security:",
    "matches.mutualApprovalRequired": "Mutual Approval Required",
    "matches.noMatchesFound": "No Potential Matches Found",
    "matches.improveReport": "Improve Your Report",
    "matches.noPhoto": "No Photo",
    "matches.chatLive": "Chat Live",
    "matches.chatLocked": "Chat Locked",
    "matches.inspectReview": "Inspect & Review",
    "matches.openChatLive": "Open Chat (Live)",
    "matches.verifyApprove": "Verify & Approve",
    "matches.approvalNotice": "Both Owner and Finder must approve verification before Chat unlocks.",
    "matches.tabComparison": "Comparison",
    "matches.tabVerification": "Verification",
    "matches.tabTrust": "Trust & WhatsApp",
    "matches.tabHandover": "Handover",
    "matches.noImageProvided": "No Image Provided",
    "matches.itemName": "Item Name",
    "matches.category": "Category",
    "matches.reward": "Reward",
    "matches.locationAddress": "Location & Address",
    "matches.detailsDescription": "Details Description",
    "matches.finderContact": "Finder Contact",
    "matches.matchStatus": "Match Status:",
    "matches.mutualConfirmed": "Mutual approval confirmed. Both parties have verified.",
    "matches.mutualProtocol": "Mutual Verification Protocol",
    "matches.protocolNotice": "To maintain zero-trust security and prevent fraudulent handovers, both the Owner and Finder submit verification details. Chat stays strictly locked until both parties approve each other's answers.",
    "matches.ownerStatus": "Owner Status",
    "matches.submittedBy": "Submitted By:",
    "matches.aiScore": "AI Verification Score:",
    "matches.ownerNotSubmitted": "The item owner has not submitted verification answers yet.",
    "matches.finderStatus": "Finder Status",
    "matches.finderNotSubmitted": "The item finder has not submitted verification answers yet.",
    "matches.actionControls": "Participant Action Controls",
    "matches.selectRole": "Select your role to submit details or review and verify this connection.",
    "matches.iAmOwner": "I am the Owner",
    "matches.iAmFinder": "I am the Finder",
    "matches.yourName": "Your Name",
    "matches.contactWhatsApp": "WhatsApp / Contact",
    "matches.forensicQuestions": "Forensic Verification Questions",
    "matches.trustTitle": "Mutual Trust & Protected WhatsApp Contact",
    "matches.trustNotice": "To ensure safety and privacy across the community, direct WhatsApp and contact numbers are revealed as soon as BOTH parties click \"I Trust This Person\".",
    "matches.ownerTrust": "Owner Trust",
    "matches.finderTrust": "Finder Trust",
    "matches.unlocked": "Unlocked",
    "matches.masked": "Masked & Protected",
    "matches.contactAlias": "Contact Name / Alias",
    "matches.phoneWhatsApp": "Phone / WhatsApp",
    "matches.openWhatsApp": "Open WhatsApp Chat",
    "matches.directCall": "Direct Call",
    "matches.trustInstructions": "Both users must click \"I Trust This Person\" below to reveal active WhatsApp link and phone number.",
    "matches.trustConsent": "By clicking trust, you authorize exchanging direct WhatsApp contact for safe item handover.",
    "matches.reunitedResolved": "Item Successfully Reunited & Resolved!",
    "matches.reunitedNotice": "Both owner and finder have confirmed the safe handover. Case resolved!",
    "matches.handoverProtocol": "Safe Handover Protocol",
    "matches.handoverNotice": "Coordinate a public meetup location (e.g. Metro Station, Police Helpdesk, or campus security). Once physically handed over, both parties confirm below to resolve the case.",
    "matches.handoverSchedule": "Handover Location & Schedule",
    "matches.publicMeetingSpot": "Public Meeting Spot",
    "matches.scheduledDateTime": "Scheduled Date / Time",
    "matches.confirmHandover": "Confirm Handover & Resolve Case",
    "matches.confirmHandoverDesc": "Once physically handed over at the meetup spot, confirm to finalize the return.",
    "matches.iHandedOver": "I handed over this item",
    "matches.iReceived": "I received my item",
    "matches.chatUnlocksAfter": "Secure Chat Unlocks After Verification",
    "matches.chatUnlocksDesc": "Once the claim is verified, end-to-end Secure Chat automatically opens between both parties.",
    "matches.goToVerification": "Go to Verification Tab",
    "matches.secureHandoverChat": "End-to-End Secure Handover Chat",
    "matches.connectionVerified": "Connection verified! Send a message to coordinate safe handover.",
    "matches.dismissMatch": "Dismiss Match",
    "matches.shareMatch": "Share",
    "matches.directClaim": "Direct Claim",

    # Claim Modal & Verification
    "claim.title": "Submit an Ownership Claim",
    "claim.subtitle": "Verify item ownership with AI protection and zero public contact leakage.",
    "claim.questionsTitle": "Verification Questions",
    "claim.questionsSubtitle": "Answer specific questions to demonstrate authentic ownership:",
    "claim.answerPlaceholder": "Your answer to this question...",
    "claim.submit": "Submit Claim for Review",
    "claim.submitting": "Submitting verification details...",
    "claim.success": "Claim submitted! The owner will review your verification answers.",
    "claim.statusPending": "Verification Pending",
    "claim.statusApproved": "Claim Approved",
    "claim.statusRejected": "Claim Declined",
    "claim.ownershipIndex": "Ownership Integrity Index",
    "claim.safeVerification": "Safe Ownership Verification",
    "claim.stepsNotice": "We use secure, private steps to ensure handovers are completely safe, authentic, and trouble-free.",
    "claim.protectedContact": "Your contact details are fully protected. Only verified matched parties can unlock them.",
    "claim.unlockedMutual": "Contact options are only unlocked once mutual ownership is verified. Your phone is never shown publicly.",
    "claim.aiEvaluationNotice": "Our AI evaluates claims to confirm genuine details and protect against fraudulent claims.",
    "claim.trackingNotice": "Unique verification tracking codes protect both parties and let you coordinate a safe, easy meeting.",
    "claim.modalDescription": "To ensure items are returned to their rightful owners, we verify matches before sharing contact details. Please answer the simple verification questions below.",
    "claim.aiPreparingQuestions": "AI is helping prepare your verification questions...",
    "claim.claimantName": "Claimant Name",
    "claim.officialNamePlaceholder": "Your official name",
    "claim.whatsappMobile": "WhatsApp Mobile",
    "claim.mobilePlaceholder": "9876543210",
    "claim.verifyItemDetails": "Verify Item Details",
    "claim.detailsPlaceholder": "Please explain in detail (mention markings, inner contents, purchase details if applicable)...",
    "claim.verificationRegistered": "Verification Registered",
    "claim.detailsSavedSecurely": "Your details have been saved securely. Our AI helper has matched your description.",
    "claim.verificationId": "Verification ID (Claim ID)",
    "claim.aiMatchDetails": "AI Match Details",
    "claim.bookmarkLink": "Direct check-in link (bookmark this to return later)",
    "claim.doneAwaitSignoff": "Done & Await Owner Sign-off",

    # Auth Flow
    "auth.recoverBelongings": "Recover lost belongings safely through trusted citizens and intelligent verification.",
    "auth.startEmail": "Get Started with Email",
    "auth.continuePhone": "Continue with Phone",
    "auth.signIn": "Sign In",
    "auth.welcomeBack": "Welcome Back",
    "auth.resumeTracking": "Sign in to your LINCO account to resume tracking.",
    "auth.emailOrUsername": "Email or Username",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.createAccount": "Create Account",
    "auth.joinNetwork": "Join the smart local guardian network.",
    "auth.fullName": "Full Name",
    "auth.username": "Username",
    "auth.emailAddress": "Email Address",
    "auth.confirmPassword": "Confirm Password",
    "auth.acceptPolicy": "I accept the Privacy Policy and consent to encrypted data sharing.",
    "auth.resetPassword": "Reset Password",
    "auth.resetNotice": "We'll transmit a secure recovery connection link to retrieve control of your profile.",
    "auth.sendResetLink": "Send Reset Link",
    "auth.returnSignIn": "Return to Sign In",
    "auth.setupProfile": "Set Up Your Profile",
    "auth.setupNotice": "Complete your profile so citizens can coordinate handovers with you.",
    "auth.takeSnapshot": "Take Snapshot",
    "auth.choosePhoto": "Choose Photo",
    "auth.cityNeighborhood": "City / Neighborhood (Required)",
    "auth.shortBio": "Short Bio (Optional)",
    "auth.completeSetup": "Complete Profile Setup",

    # User Dashboard & Profile
    "dashboard.title": "Profile & Activity Dashboard",
    "dashboard.subtitle": "Manage your reported items, active claims, and security settings.",
    "dashboard.myReports": "My Reports",
    "dashboard.myClaims": "My Claims",
    "dashboard.savedPosts": "Saved Posts",
    "dashboard.welcomeTitle": "Set up your profile",
    "dashboard.welcomeDesc": "Welcome to LINCO. Tell us a bit about yourself so citizens can coordinate lost and found handovers with you. You can skip this and proceed instantly.",
    "dashboard.chooseAvatar": "Choose Profile Picture",
    "dashboard.fullName": "Full Name",
    "dashboard.username": "Username",
    "dashboard.bio": "Bio (Optional)",
    "dashboard.city": "City",
    "dashboard.createProfile": "Create Profile",
    "dashboard.skipForNow": "Skip for Now",
    "dashboard.changeCover": "Change Cover",
    "dashboard.editProfile": "Edit Profile",
    "dashboard.shareProfile": "Share Profile",
    "dashboard.settings": "Settings",
    "dashboard.editDetails": "Edit Profile Details",
    "dashboard.accountSection": "ACCOUNT",
    "dashboard.email": "Email",
    "dashboard.password": "Password",
    "dashboard.privacySection": "PRIVACY",
    "dashboard.blockedUsers": "Blocked Users",
    "dashboard.downloadData": "Download My Data",
    "dashboard.deleteAccount": "Delete Account",
    "dashboard.notifSection": "NOTIFICATIONS",
    "dashboard.pushNotifs": "Push Notifications",
    "dashboard.pushDesc": "Updates for immediate matches & chats",
    "dashboard.emailReports": "Email Reports",
    "dashboard.emailDesc": "Weekly digests of unclaimed items",
    "dashboard.appearanceSection": "APPEARANCE",
    "dashboard.theme": "Theme",
    "dashboard.language": "Language",
    "dashboard.supportSection": "SUPPORT",
    "dashboard.help": "Help",
    "dashboard.contact": "Contact",
    "dashboard.about": "About",
    "dashboard.logout": "Logout from LINCO",
    "dashboard.updateEmail": "Update Email Address",
    "dashboard.saveEmail": "Save Email",
    "dashboard.changePassword": "Change Password",
    "dashboard.unblock": "Unblock",
    "dashboard.noBlocked": "No blocked users.",
    "dashboard.contactSupport": "Contact LINCO Support",
    "dashboard.supportDesc": "For general support, data access requests or neighborhood coordination queries, contact our lead developers at:",
    "dashboard.aboutLinco": "About LINCO",
    "dashboard.aboutDesc": "LINCO is a private lost and found handover application that helps you find and recover misplaced objects using smart Gemini AI semantic matches.",
    "dashboard.appVersion": "Application Version: v1.3.0 Stable",
    "dashboard.capturePhoto": "Capture Photo",
    "dashboard.useCamera": "Use Camera Stream",
    "dashboard.chooseGallery": "Choose From Gallery (Cloudinary)",
    "dashboard.confirmDeletion": "Confirm Deletion",
    "dashboard.deletionWarning": "This action is final and cannot be undone. All your lost/found registrations, handovers, and credentials will be purged.",
    "dashboard.typePasswordConfirm": "Type your password to confirm",
    "dashboard.typeDeletePrompt": "Type DELETE below to permanently destroy your LINCO profile and credentials.",

    # Owner Claims Dashboard
    "ownerClaims.controlBoard": "Claims Control Board",
    "ownerClaims.enterPin": "Enter security pin",
    "ownerClaims.pinDesc": "Specify the 4-digit security PIN specified when publishing this report to decrypt connection keys.",
    "ownerClaims.clear": "Clear",
    "ownerClaims.authenticating": "Authenticating...",
    "ownerClaims.integrityScore": "Gemini Integrity Score",
    "ownerClaims.reviewNotice": "Review answers. Approving activates the Secure Recovery Room.",
    "ownerClaims.completeHandover": "Complete Handover",
    "ownerClaims.postClosed": "This post is closed and is no longer accepting new claims. Existing claim history remains visible below.",
    "ownerClaims.closeWindow": "Close Window",
    "ownerClaims.approved": "Approved",
    "ownerClaims.resolved": "Resolved",
    "ownerClaims.youReturned": "You returned:",
    "ownerClaims.meetingCoords": "Type secure meeting coordinates...",

    # PIN Modal
    "pin.title": "Security PIN Entry",
    "pin.passcode": "4-Digit Passcode",
    "pin.verifying": "Verifying...",
    "pin.clear": "Clear",
    "pin.unlock": "Unlock Sensitive Post Contact",
    "pin.promise": "Your PIN protects your personal contact from public web crawlers and unsolicited calls.",

    # Community Found Modal
    "communityFound.title": "I Have This Item",
    "communityFound.protocol": "Zero-Trust Protocol",
    "communityFound.verifyFinding": "Verify finding",
    "communityFound.withoutLeaking": "without leaking private data",
    "communityFound.lostReported": "Lost Item Reported",
    "communityFound.whereFound": "Where did you find it?",
    "communityFound.insideContents": "Inside Contents / Specific Items (Optional)",
    "communityFound.secretDetails": "Unique Characteristics / Secret Details",
    "communityFound.createPin": "Create Your Security PIN",
    "communityFound.reward": "Reward",
    "communityFound.registeredNotice": "has been registered. The owner has been notified to review your answers.",

    # Claim Tracker
    "claimTracker.title": "Recovery Status Timeline",
    "claimTracker.protocols": "Safe Recovery Protocols",
    "claimTracker.publicSpaces": "Meet in public, highly visible, well-lit spaces like a metro station or cafe.",
    "claimTracker.verifyCarefully": "Verify the item carefully in hand before releasing rewards or completing.",
    "claimTracker.documentDetails": "Use our Secure Chat to document and agree on meeting details.",
    "claimTracker.lookupAnother": "Lookup another",
    "claimTracker.unsuccessful": "Claim Evaluation Unsuccessful",
    "claimTracker.trustCheck": "Mutual Trust Check",
    "claimTracker.awaitingApproval": "Awaiting Finder Approval",
    "claimTracker.recoveryRoom": "Secure Recovery Room",
    "claimTracker.enterRoom": "Enter Recovery Room",
    "claimTracker.discussion": "End-to-end coordinated handover discussion",

    # Recovery Intelligence Card
    "recovery.transmissionSecured": "TRANSMISSION SECURED",
    "recovery.reportIndexed": "Report Indexed Successfully",
    "recovery.dossierActive": "Your verification dossier is now active. Gemini comparative scanners are analyzing active spatial indexes.",
    "recovery.engineTitle": "AI Recovery Probability Engine",
    "recovery.retrievalLikelihood": "Likelihood of Retrieval:",
    "recovery.analyzedFactors": "Analyzed Recovery Factors",
    "recovery.semanticNotice": "Our semantic generator extracts brand, colors, and identifiers to build an optimized match model.",
    "recovery.uniqueIdentifier": "A unique identifier enables absolute verified matching and legally binding claim security.",
    "recovery.setReward": "Set Reward",

    # Reward Section
    "reward.fairRange": "Estimated Fair Range",
    "reward.suggestReward": "Suggest Reward",
    "reward.customReward": "Custom Reward Amount",

    # Privacy & Trust Center
    "privacy.complianceProtocols": "COMPLIANCE, PRIVACY & TRUST PROTOCOLS",
    "privacy.title": "Trust & Compliance Center",
    "privacy.subtitle": "We hold ourselves to the highest standards of user safety, extreme privacy isolation, and radical transparency.",
    "privacy.exitSection": "Exit Section",
    "privacy.privacyPolicy": "Privacy Policy",
    "privacy.lastUpdated": "Last Updated: July 7, 2026. Built with extreme data minimization as our baseline.",
    "privacy.dataAcquisition": "We strictly limit data acquisition to parameters necessary to locate and match your lost belongings:",
    "privacy.spatiotemporalTags": "Coarse Spatiotemporal Tags:",
    "privacy.coldStorage": "maximum before automatic cold storage archiving.",
    "privacy.cookiePreferences": "Manage real-time cookie preferences, consent policies, and data processing toggles.",
    "privacy.purgeBrowser": "Instantly purge active cookies, locally cached coordinates, matching indices, and file previews from this local browser instance.",
    "privacy.hereToHelp": "We're here to help.",
    "privacy.connectFounder": "Connect directly with our founder on our official professional network profile for escalation, feedback, or partnerships.",

    # Cookie Consent
    "cookie.title": "Privacy Sovereignty",
    "cookie.message": "We only collect information required to help recover lost items.",
    "cookie.trackingNotice": "Your identity remains private until ownership is verified. No tracking, no profiling, absolute spatiotemporal isolation.",
    "cookie.acceptAll": "Accept All",
    "cookie.learnMore": "Learn More",

    # About
    "about.tagline": "Connecting Communities, Reuniting Belongings",
    "about.mission": "LINCO is dedicated to leveraging ethical AI and community trust to restore lost items to their rightful owners with complete privacy protection.",

    # Notifications
    "notifications.title": "Notifications",
    "notifications.empty": "No new notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.clearAll": "Clear all",
    "notifications.matchFoundTitle": "Possible Match Detected",
    "notifications.matchFoundMsg": "A potential match was discovered by our AI matching engine.",
    "notifications.claimReceivedTitle": "New Claim Submitted",
    "notifications.claimReceivedMsg": "A citizen has submitted verification answers for your listing.",
    "notifications.claimApprovedTitle": "Claim Approved",
    "notifications.claimApprovedMsg": "Your claim has been verified and approved by the item owner.",
    "notifications.chatMessageTitle": "New Message in Recovery Room",
    "notifications.chatMessageMsg": "You have received a new message regarding your recovery coordination.",
    "notifications.handoverDoneTitle": "Handover Confirmed",
    "notifications.handoverDoneMsg": "The item return was confirmed and the case is now resolved.",

    # Help & FAQ
    "help.title": "Frequently Asked Questions",
    "help.q1": "How does LINCO protect my privacy?",
    "help.a1": "LINCO never shares your contact details publicly. Contact is only unlocked after mutual verification.",
    "help.q2": "What happens when I report a lost item?",
    "help.a2": "Our AI compares your report with found items across cities, landmarks, and spatial checkpoints.",
    "help.q3": "How does ownership verification work?",
    "help.a3": "Claimants must answer specific questions prepared by AI to verify details only the true owner knows.",
    "help.q4": "Is LINCO free to use?",
    "help.a4": "Yes, LINCO is completely free and community-driven.",

    # Home Landing Sections
    "home.heroTitle": "Reuniting Lost Belongings with AI & Verified Trust",
    "home.heroSubtitle": "India's community-driven lost and found platform. Safe, private, and powered by Gemini AI.",
    "home.reportLost": "Report Lost Item",
    "home.reportFound": "Report Found Item",
    "home.browseFeed": "Browse Community Feed",
    "home.statsRecovered": "Belongings Reunited",
    "home.statsActive": "Active Community Watch",
    "home.statsCities": "Cities Covered",
    "home.howItWorks": "How LINCO Works",
    "home.step1Title": "1. Report in Seconds",
    "home.step1Desc": "Use voice, text, or photos to log a lost or found item across 39 languages.",
    "home.step2Title": "2. Smart AI Matching",
    "home.step2Desc": "Gemini compares visual attributes, spatio-temporal waypoints, and descriptions.",
    "home.step3Title": "3. Verified Handover",
    "home.step3Desc": "Verify claims through secret questions and coordinate safe returns.",

    # Categories
    "category.Electronics": "Electronics",
    "category.Documents": "Documents",
    "category.Wallet / Purse": "Wallet / Purse",
    "category.Keys": "Keys",
    "category.Pet": "Pet",
    "category.Bag / Luggage": "Bag / Luggage",
    "category.Jewelry": "Jewelry",
    "category.ID / Card": "ID / Card",
    "category.Vehicle": "Vehicle",
    "category.Clothing": "Clothing",
    "category.Other": "Other",

    # Urgencies
    "urgency.Normal": "Normal",
    "urgency.Urgent": "Urgent",
    "urgency.Contains ID": "Contains ID",
    "urgency.Medical": "Medical / Critical",
}
