"""
Vocabulary mappings for Indic Languages 1:
hi, mr, gu, bn, ta, te, kn, ml, pa, or, as
"""

# Common phrases and terms for the new 425 keys
VOCAB_INDIC_1 = {
    "hi": {
        "voice.stop": "रिकॉर्डिंग रोकें",
        "voice.error": "आवाज़ पहचानने में त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "voice.hint": "वस्तु का ब्रांड, रंग, स्थान और तारीख जैसे विवरण बोलें।",
        "report.title": "वस्तु की रिपोर्ट करें",
        "report.subtitle": "स्मार्ट स्थानिक सहसंबंध के साथ खोई या मिली वस्तु दर्ज करें।",
        "report.type": "रिपोर्ट प्रकार",
        "report.typeLost": "मेरी वस्तु खो गई है",
        "report.typeFound": "मुझे कोई वस्तु मिली है",
        "report.stepBasics": "1. बुनियादी विवरण",
        "report.stepLocation": "2. स्थान और तारीख",
        "report.stepPhotos": "3. तस्वीरें और सुराग",
        "report.stepSecurity": "4. सुरक्षा और संपर्क",
        "report.itemTitle": "वस्तु का नाम",
        "report.itemTitlePlaceholder": "उदा. काली लेदर टाइटन घड़ी, नीला वाइल्डक्राफ्ट बैग",
        "report.category": "श्रेणी",
        "report.selectCategory": "वस्तु श्रेणी चुनें",
        "report.description": "विस्तृत विवरण",
        "report.descriptionPlaceholder": "रंग, मॉडल, खरोंच, पहचान चिह्न, अंदर की वस्तुएं आदि बताएं...",
        "report.location": "स्थान (जहाँ मिली / खोई)",
        "report.locationPlaceholder": "उदा. अंधेरी मेट्रो स्टेशन गेट 2, मुंबई",
        "report.date": "तारीख और अनुमानित समय",
        "report.urgency": "प्राथमिकता स्तर",
        "report.urgencyNormal": "सामान्य",
        "report.urgencyUrgent": "आवश्यक",
        "report.urgencyMedical": "चिकित्सा / अत्यंत महत्वपूर्ण",
        "report.photos": "तस्वीरें अपलोड करें",
        "report.photosHint": "स्पष्ट तस्वीरें एआई मिलान सटीकता में काफी सुधार करती हैं।",
        "report.reward": "इनाम राशि (वैकल्पिक)",
        "report.rewardPlaceholder": "₹ राशि रुपये में",
        "report.contact": "व्हाट्सएप / फोन संपर्क",
        "report.contactPlaceholder": "10 अंकों का मोबाइल नंबर",
        "report.pin": "4 अंकों का सुरक्षा पिन",
        "report.pinPlaceholder": "••••",
        "report.pinHint": "बाद में रिपोर्ट संपादित करने या हल चिह्नित करने के लिए आवश्यक।",
        "report.submit": "कम्युनिटी में रिपोर्ट प्रकाशित करें",
        "report.submitting": "सुरक्षित रजिस्ट्री में प्रकाशित किया जा रहा है...",
        "report.success": "आपकी वस्तु रिपोर्ट सफलतापूर्वक प्रकाशित हो गई है!",
        "report.viewListing": "फ़ीड में लिस्टिंग देखें",
        "report.brand": "ब्रांड / निर्माता",
        "report.brandPlaceholder": "उदा. एप्पल, सैमसंग, टाइटन, वाइल्डक्राफ्ट",
        "report.primaryColor": "मुख्य रंग",
        "report.secondaryColor": "सहायक रंग",
        "report.landmark": "निकटतम लैंडमार्क",
        "report.landmarkPlaceholder": "उदा. प्लेटफॉर्म 3 एस्केलेटर के पास, कैफ़े के सामने",
        "report.secretClue": "गुप्त पहचान सुराग (सत्यापन के लिए)",
        "report.secretCluePlaceholder": "उदा. अंदर की जेब में लाल कीचेन, खुदा हुआ नाम 'RS'",
        "feed.searchPlaceholder": "वस्तुएं, टैग, रंग, ब्रांड, शहर खोजें...",
        "feed.filters": "फ़िल्टर",
        "feed.applyFilters": "फ़िल्टर लागू करें",
        "feed.recentSearches": "हाल की खोजें",
        "feed.savedSearches": "सहेजी गई खोजें",
        "feed.listingRegistry": "लिस्टिंग रजिस्ट्री",
        "feed.category": "श्रेणी",
        "feed.allCategories": "सभी श्रेणियां",
        "feed.city": "शहर",
        "feed.allCities": "सभी शहर",
        "feed.dateRange": "तारीख सीमा",
        "feed.proximity": "दूरी का दायरा",
        "feed.allProximities": "सभी दूरियां (कोई भी दायरा)",
        "feed.within5km": "5 किमी के भीतर",
        "feed.within15km": "15 किमी के भीतर",
        "feed.within30km": "30 किमी के भीतर",
        "feed.within50km": "50 किमी के भीतर",
        "feed.sortCatalog": "कैटलॉग क्रमबद्ध करें",
        "feed.colorSwatch": "रंग पैलेट",
        "feed.allColors": "सभी रंग",
        "feed.hardwareBrand": "ब्रांड निर्माता",
        "feed.allBrands": "सभी ब्रांड",
        "feed.resetFilters": "फ़िल्टर रीसेट करें",
        "feed.viewList": "सूची",
        "feed.viewMap": "मानचित्र",
        "feed.noMatchesFound": "इंडेक्स में कोई मिलान नहीं मिला",
        "feed.noMatchesDesc": "हमारे सुरक्षित डेटाबेस में इन फ़िल्टर के साथ कोई वस्तु नहीं मिली। कृपया खोज शब्द बदलें या फ़िल्टर रीसेट करें।",
        "feed.reportItem": "खोई/मिली वस्तु रिपोर्ट करें",
        "feed.saveParameters": "सर्च पैरामीटर सहेजें",
        "feed.deleteSavedSearch": "सहेजी गई खोज हटाएं",
        "feed.universalSearchBar": "सार्वभौमिक खोज पट्टी",
        "feed.clearSearch": "खोज इनपुट साफ़ करें",
        "feed.toggleFilters": "उन्नत फ़िल्टर चालू/बंद",
        "feed.newestFirst": "नवीनतम पहले",
        "feed.oldestFirst": "पुरातन पहले",
        "feed.highestReward": "अधिकतम इनाम",
        "feed.closestDistance": "निकटतम दूरी",
        "postcard.unlockConnection": "कनेक्शन अनलॉक करें",
        "postcard.iHaveThisItem": "यह वस्तु मेरे पास है",
        "postcard.reclaimed": "वापस प्राप्त और सौंपी गई",
        "postcard.claims": "दावे",
        "postcard.image": "तस्वीर",
        "postcard.qr": "क्यूआर",
        "postcard.aiMatch": "एआई मिलान",
        "postcard.geminiMatches": "जेमिनी ने स्मार्ट मिलान पाया!",
        "postcard.contactOwner": "मालिक से संपर्क करें",
        "postcard.creatorNotice": "केवल इस लिस्टिंग के सत्यापित निर्माता ही मिलान विवरण देख सकते हैं।",
        "postcard.markResolved": "सुलझा हुआ चिह्नित करें",
        "postcard.deleteListing": "लिस्टिंग हटाएं",
        "postcard.unlockWithPin": "सुरक्षा पिन से कनेक्शन अनलॉक करें",
        "postcard.manageClaims": "दावे प्रबंधित और स्वीकृत/अस्वीकृत करें",
        "postcard.shareTemplate": "शेयर/टेम्पलेट टेक्स्ट कॉपी करें",
        "postcard.downloadCard": "कार्ड छवि के रूप में डाउनलोड करें",
        "postcard.qrSettings": "इंटरएक्टिव क्यूआर और प्रिंट सेटिंग्स",
        "postcard.postedOn": "पोस्ट किया गया",
        "postcard.reward": "इनाम",
        "postcard.secureHandover": "सुरक्षित सुपुर्दगी",
        "matches.title": "एआई स्मार्ट मिलान और आपसी सत्यापन",
        "matches.subtitle": "जेमिनी खोई और मिली लिस्टिंग की तुलना करता है। सुरक्षित हैंडओवर चैट से पहले सख्त आपसी सत्यापन आवश्यक है।",
        "matches.myMatches": "मेरे मिलान",
        "matches.publicMatches": "सार्वजनिक मिलान",
        "matches.threshold": "न्यूनतम सीमा:",
        "matches.security": "सुरक्षा:",
        "matches.mutualApprovalRequired": "आपसी स्वीकृति आवश्यक",
        "matches.noMatchesFound": "कोई संभावित मिलान नहीं मिला",
        "matches.improveReport": "अपनी रिपोर्ट में सुधार करें",
        "matches.noPhoto": "कोई तस्वीर नहीं",
        "matches.chatLive": "लाइव चैट",
        "matches.chatLocked": "चैट लॉक है",
        "matches.inspectReview": "निरीक्षण और समीक्षा",
        "matches.openChatLive": "लाइव चैट खोलें",
        "matches.verifyApprove": "सत्यापित और स्वीकृत करें",
        "matches.approvalNotice": "चैट अनलॉक होने से पहले मालिक और पाने वाले दोनों को सत्यापन स्वीकृत करना होगा।",
        "matches.tabComparison": "तुलना",
        "matches.tabVerification": "सत्यापन",
        "matches.tabTrust": "विश्वास और व्हाट्सएप",
        "matches.tabHandover": "सुपुर्दगी",
        "matches.noImageProvided": "कोई छवि प्रदान नहीं की गई",
        "matches.itemName": "वस्तु का नाम",
        "matches.category": "श्रेणी",
        "matches.reward": "इनाम",
        "matches.locationAddress": "स्थान और पता",
        "matches.detailsDescription": "विस्तृत विवरण",
        "matches.finderContact": "पाने वाले का संपर्क",
        "matches.matchStatus": "मिलान स्थिति:",
        "matches.mutualConfirmed": "आपसी स्वीकृति की पुष्टि हुई। दोनों पक्षों ने सत्यापन कर लिया है।",
        "matches.mutualProtocol": "आपसी सत्यापन प्रोटोकॉल",
        "matches.protocolNotice": "धोखाधड़ी रोकने के लिए दोनों पक्ष सत्यापन विवरण जमा करते हैं। जब तक दोनों पक्ष स्वीकृत नहीं करते, चैट लॉक रहती है।",
        "matches.ownerStatus": "मालिक की स्थिति",
        "matches.submittedBy": "द्वारा प्रस्तुत:",
        "matches.aiScore": "एआई सत्यापन स्कोर:",
        "matches.ownerNotSubmitted": "वस्तु के मालिक ने अभी तक सत्यापन उत्तर जमा नहीं किए हैं।",
        "matches.finderStatus": "पाने वाले की स्थिति",
        "matches.finderNotSubmitted": "पाने वाले ने अभी तक सत्यापन उत्तर जमा नहीं किए हैं।",
        "matches.actionControls": "प्रतिभागी कार्रवाई नियंत्रण",
        "matches.selectRole": "विवरण जमा करने या समीक्षा करने के लिए अपनी भूमिका चुनें।",
        "matches.iAmOwner": "मैं मालिक हूँ",
        "matches.iAmFinder": "मुझे यह वस्तु मिली है",
        "matches.yourName": "आपका नाम",
        "matches.contactWhatsApp": "व्हाट्सएप / संपर्क",
        "matches.forensicQuestions": "फोरेंसिक सत्यापन प्रश्न",
        "matches.trustTitle": "आपसी विश्वास और सुरक्षित व्हाट्सएप संपर्क",
        "matches.trustNotice": "समुदाय की सुरक्षा के लिए, सीधे फोन नंबर तभी दिखाई देते हैं जब दोनों पक्ष \"मैं इस व्यक्ति पर भरोसा करता हूँ\" पर क्लिक करते हैं।",
        "matches.ownerTrust": "मालिक का भरोसा",
        "matches.finderTrust": "पाने वाले का भरोसा",
        "matches.unlocked": "अनलॉक किया गया",
        "matches.masked": "सुरक्षित और छिपा हुआ",
        "matches.contactAlias": "संपर्क नाम / उपनाम",
        "matches.phoneWhatsApp": "फोन / व्हाट्सएप",
        "matches.openWhatsApp": "व्हाट्सएप चैट खोलें",
        "matches.directCall": "सीधा कॉल",
        "matches.trustInstructions": "व्हाट्सएप लिंक और फोन नंबर प्रकट करने के लिए दोनों उपयोगकर्ताओं को नीचे दिए गए बटन पर क्लिक करना होगा।",
        "matches.trustConsent": "भरोसा पर क्लिक करके, आप सुरक्षित हैंडओवर के लिए संपर्क विवरण साझा करने की अनुमति देते हैं।",
        "matches.reunitedResolved": "वस्तु सफलतापूर्वक पुनः प्राप्त और मामला हल हुआ!",
        "matches.reunitedNotice": "मालिक और पाने वाले दोनों ने सुरक्षित सुपुर्दगी की पुष्टि की है। मामला सुलझ गया!",
        "matches.handoverProtocol": "सुरक्षित सुपुर्दगी प्रोटोकॉल",
        "matches.handoverNotice": "किसी सार्वजनिक स्थान पर मिलने का समय तय करें (जैसे मेट्रो स्टेशन या पुलिस बूथ)। सौंपने के बाद दोनों पुष्टि करें।",
        "matches.handoverSchedule": "सुपुर्दगी स्थान और समय",
        "matches.publicMeetingSpot": "सार्वजनिक मिलन स्थल",
        "matches.scheduledDateTime": "निर्धारित तारीख / समय",
        "matches.confirmHandover": "सुपुर्दगी की पुष्टि करें और मामला हल करें",
        "matches.confirmHandoverDesc": "मिलन स्थल पर वस्तु मिलने के बाद, वापसी को अंतिम रूप देने के लिए पुष्टि करें।",
        "matches.iHandedOver": "मैंने यह वस्तु सौंप दी",
        "matches.iReceived": "मुझे मेरी वस्तु मिल गई",
        "matches.chatUnlocksAfter": "सत्यापन के बाद सुरक्षित चैट अनलॉक होगी",
        "matches.chatUnlocksDesc": "दावे के सत्यापन के बाद दोनों पक्षों के बीच एंड-टू-एंड सुरक्षित चैट स्वतः खुल जाएगी।",
        "matches.goToVerification": "सत्यापन टैब पर जाएं",
        "matches.secureHandoverChat": "सुरक्षित हैंडओवर चैट",
        "matches.connectionVerified": "कनेक्शन सत्यापित! सुरक्षित हैंडओवर के लिए संदेश भेजें।",
        "matches.dismissMatch": "मिलान खारिज करें",
        "matches.shareMatch": "शेयर करें",
        "matches.directClaim": "सीधा दावा",
        "claim.ownershipIndex": "स्वामित्व निष्ठा सूचकांक",
        "claim.safeVerification": "सुरक्षित स्वामित्व सत्यापन",
        "claim.stepsNotice": "हम सुपुर्दगी को सुरक्षित और प्रामाणिक बनाने के लिए निजी चरणों का उपयोग करते हैं।",
        "claim.protectedContact": "आपका संपर्क विवरण पूरी तरह सुरक्षित है। केवल सत्यापित व्यक्ति ही इसे देख सकता है।",
        "claim.unlockedMutual": "आपसी सत्यापन के बाद ही संपर्क विकल्प अनलॉक होते हैं। आपका फोन कभी सार्वजनिक नहीं किया जाता।",
        "claim.aiEvaluationNotice": "हमारा एआई दावों का मूल्यांकन करता है ताकि धोखाधड़ी को रोका जा सके।",
        "claim.trackingNotice": "अद्वितीय ट्रैकिंग कोड दोनों पक्षों की सुरक्षा करते हैं।",
        "claim.modalDescription": "वस्तु उसके असली मालिक को मिले, इसके लिए हम संपर्क साझा करने से पहले मिलान सत्यापित करते हैं। कृपया नीचे दिए गए प्रश्नों के उत्तर दें।",
        "claim.aiPreparingQuestions": "एआई आपके सत्यापन प्रश्न तैयार कर रहा है...",
        "claim.claimantName": "दावेदार का नाम",
        "claim.officialNamePlaceholder": "आपका आधिकारिक नाम",
        "claim.whatsappMobile": "व्हाट्सएप मोबाइल",
        "claim.mobilePlaceholder": "9876543210",
        "claim.verifyItemDetails": "वस्तु विवरण सत्यापित करें",
        "claim.detailsPlaceholder": "कृपया विस्तार से बताएं (निशान, अंदर की सामग्री, बिल का विवरण आदि)...",
        "claim.verificationRegistered": "सत्यापन पंजीकृत",
        "claim.detailsSavedSecurely": "आपका विवरण सुरक्षित रूप से सहेज लिया गया है। हमारे एआई ने विवरण का मिलान किया है।",
        "claim.verificationId": "सत्यापन आईडी (दावा आईडी)",
        "claim.aiMatchDetails": "एआई मिलान विवरण",
        "claim.bookmarkLink": "सीधा लिंक (बाद में देखने के लिए बुकमार्क करें)",
        "claim.doneAwaitSignoff": "पूर्ण और मालिक की स्वीकृति की प्रतीक्षा करें",
        "auth.recoverBelongings": "विश्वसनीय नागरिकों और बुद्धिमान सत्यापन के माध्यम से खोई हुई वस्तुओं को सुरक्षित रूप से पुनः प्राप्त करें।",
        "auth.startEmail": "ईमेल से शुरुआत करें",
        "auth.continuePhone": "फोन से आगे बढ़ें",
        "auth.signIn": "साइन इन करें",
        "auth.welcomeBack": "वापसी पर स्वागत है",
        "auth.resumeTracking": "ट्रैकिंग जारी रखने के लिए अपने लिंको खाते में साइन इन करें।",
        "auth.emailOrUsername": "ईमेल या यूज़रनेम",
        "auth.password": "पासवर्ड",
        "auth.forgotPassword": "पासवर्ड भूल गए?",
        "auth.createAccount": "खाता बनाएं",
        "auth.joinNetwork": "स्मार्ट स्थानीय अभिभावक नेटवर्क में शामिल हों।",
        "auth.fullName": "पूरा नाम",
        "auth.username": "यूज़रनेम",
        "auth.emailAddress": "ईमेल पता",
        "auth.confirmPassword": "पासवर्ड की पुष्टि करें",
        "auth.acceptPolicy": "मैं गोपनीयता नीति स्वीकार करता हूँ और एन्क्रिप्टेड डेटा साझाकरण की सहमति देता हूँ।",
        "auth.resetPassword": "पासवर्ड रीसेट करें",
        "auth.resetNotice": "हम आपके खाते तक पहुँच बहाल करने के लिए एक सुरक्षित लिंक भेजेंगे।",
        "auth.sendResetLink": "रीसेट लिंक भेजें",
        "auth.returnSignIn": "साइन इन पर वापस जाएं",
        "auth.setupProfile": "अपनी प्रोफ़ाइल सेट करें",
        "auth.setupNotice": "अपनी प्रोफ़ाइल पूरी करें ताकि नागरिक आपके साथ समन्वय कर सकें।",
        "auth.takeSnapshot": "फोटो खींचें",
        "auth.choosePhoto": "फोटो चुनें",
        "auth.cityNeighborhood": "शहर / क्षेत्र (आवश्यक)",
        "auth.shortBio": "संक्षिप्त परिचय (वैकल्पिक)",
        "auth.completeSetup": "प्रोफ़ाइल सेटअप पूरा करें",
        "dashboard.welcomeTitle": "अपनी प्रोफ़ाइल सेट करें",
        "dashboard.welcomeDesc": "लिंको में आपका स्वागत है। अपने बारे में थोड़ा बताएं ताकि नागरिक आपके साथ हैंडओवर का समन्वय कर सकें।",
        "dashboard.chooseAvatar": "प्रोफ़ाइल तस्वीर चुनें",
        "dashboard.fullName": "पूरा नाम",
        "dashboard.username": "यूज़रनेम",
        "dashboard.bio": "परिचय (वैकल्पिक)",
        "dashboard.city": "शहर",
        "dashboard.createProfile": "प्रोफ़ाइल बनाएं",
        "dashboard.skipForNow": "अभी छोड़ें",
        "dashboard.changeCover": "कवर बदलें",
        "dashboard.editProfile": "प्रोफ़ाइल संपादित करें",
        "dashboard.shareProfile": "प्रोफ़ाइल साझा करें",
        "dashboard.settings": "सेटिंग्स",
        "dashboard.editDetails": "प्रोफ़ाइल विवरण संपादित करें",
        "dashboard.accountSection": "खाता",
        "dashboard.email": "ईमेल",
        "dashboard.password": "पासवर्ड",
        "dashboard.privacySection": "गोपनीयता",
        "dashboard.blockedUsers": "अवरुद्ध उपयोगकर्ता",
        "dashboard.downloadData": "मेरा डेटा डाउनलोड करें",
        "dashboard.deleteAccount": "खाता हटाएं",
        "dashboard.notifSection": "सूचनाएं",
        "dashboard.pushNotifs": "पुश सूचनाएं",
        "dashboard.pushDesc": "तत्काल मिलान और चैट के लिए अपडेट",
        "dashboard.emailReports": "ईमेल रिपोर्ट",
        "dashboard.emailDesc": "लावारिस वस्तुओं का साप्ताहिक सारांश",
        "dashboard.appearanceSection": "दिखावट",
        "dashboard.theme": "थीम",
        "dashboard.language": "भाषा",
        "dashboard.supportSection": "सहायता",
        "dashboard.help": "मदद",
        "dashboard.contact": "संपर्क",
        "dashboard.about": "के बारे में",
        "dashboard.logout": "लिंको से लॉग आउट करें",
        "dashboard.updateEmail": "ईमेल पता अपडेट करें",
        "dashboard.saveEmail": "ईमेल सहेजें",
        "dashboard.changePassword": "पासवर्ड बदलें",
        "dashboard.unblock": "अवरोध हटाएं",
        "dashboard.noBlocked": "कोई अवरुद्ध उपयोगकर्ता नहीं।",
        "dashboard.contactSupport": "लिंको सहायता से संपर्क करें",
        "dashboard.supportDesc": "सामान्य सहायता या पड़ोस समन्वय प्रश्नों के लिए, हमारे डेवलपर्स से संपर्क करें:",
        "dashboard.aboutLinco": "लिंको के बारे में",
        "dashboard.aboutDesc": "लिंको एक निजी लॉस्ट एंड फाउंड ऐप है जो जेमिनी एआई का उपयोग करके खोई हुई वस्तुओं को खोजने में मदद करता है।",
        "dashboard.appVersion": "एप्लिकेशन संस्करण: v1.3.0 स्टेबल",
        "dashboard.capturePhoto": "फोटो खींचें",
        "dashboard.useCamera": "कैमरा स्ट्रीम उपयोग करें",
        "dashboard.chooseGallery": "गैलरी से चुनें (क्लाउडिनरी)",
        "dashboard.confirmDeletion": "हटाने की पुष्टि करें",
        "dashboard.deletionWarning": "यह कार्रवाई अंतिम है और इसे पूर्ववत नहीं किया जा सकता है। आपकी सभी लिस्टिंग और डेटा हटा दिया जाएगा।",
        "dashboard.typePasswordConfirm": "पुष्टि के लिए अपना पासवर्ड टाइप करें",
        "dashboard.typeDeletePrompt": "अपने खाते को स्थायी रूप से हटाने के लिए नीचे DELETE लिखें।",
        "ownerClaims.controlBoard": "दावा नियंत्रण बोर्ड",
        "ownerClaims.enterPin": "सुरक्षा पिन दर्ज करें",
        "ownerClaims.pinDesc": "कनेक्शन अनलॉक करने के लिए रिपोर्ट बनाते समय दिया गया 4 अंकों का सुरक्षा पिन दर्ज करें।",
        "ownerClaims.clear": "साफ़ करें",
        "ownerClaims.authenticating": "प्रमाणीकरण हो रहा है...",
        "ownerClaims.integrityScore": "जेमिनी अखंडता स्कोर",
        "ownerClaims.reviewNotice": "उत्तरों की समीक्षा करें। स्वीकृत करने से सुरक्षित रिकवरी रूम सक्रिय हो जाएगा।",
        "ownerClaims.completeHandover": "सुपुर्दगी पूरी करें",
        "ownerClaims.postClosed": "यह पोस्ट बंद कर दी गई है। पिछले दावों का इतिहास नीचे दिखाई दे रहा है।",
        "ownerClaims.closeWindow": "विंडो बंद करें",
        "ownerClaims.approved": "स्वीकृत",
        "ownerClaims.resolved": "सुलझ गया",
        "ownerClaims.youReturned": "आपने लौटाया:",
        "ownerClaims.meetingCoords": "सुरक्षित बैठक निर्देशांक लिखें...",
        "pin.title": "सुरक्षा पिन प्रविष्टि",
        "pin.passcode": "4 अंकों का पासकोड",
        "pin.verifying": "सत्यापन हो रहा है...",
        "pin.clear": "साफ़ करें",
        "pin.unlock": "संवेदनशील संपर्क अनलॉक करें",
        "pin.promise": "आपका पिन आपके व्यक्तिगत संपर्क को सार्वजनिक पहुंच से सुरक्षित रखता है।",
        "communityFound.title": "यह वस्तु मेरे पास है",
        "communityFound.protocol": "शून्य-विश्वास प्रोटोकॉल",
        "communityFound.verifyFinding": "प्राप्ति सत्यापित करें",
        "communityFound.withoutLeaking": "निजी डेटा लीक किए बिना",
        "communityFound.lostReported": "खोई हुई वस्तु की रिपोर्ट",
        "communityFound.whereFound": "आपको यह कहाँ मिली?",
        "communityFound.insideContents": "अंदर की सामग्री / विशिष्ट वस्तुएं (वैकल्पिक)",
        "communityFound.secretDetails": "अद्वितीय विशेषताएं / गुप्त विवरण",
        "communityFound.createPin": "अपना सुरक्षा पिन बनाएं",
        "communityFound.reward": "इनाम",
        "communityFound.registeredNotice": "दर्ज कर लिया गया है। मालिक को आपके उत्तरों की समीक्षा के लिए सूचित कर दिया गया है।",
        "claimTracker.title": "रिकवरी स्थिति समयरेखा",
        "claimTracker.protocols": "सुरक्षित रिकवरी प्रोटोकॉल",
        "claimTracker.publicSpaces": "मेट्रो स्टेशन या कैफे जैसी सार्वजनिक, अच्छी रोशनी वाली जगहों पर मिलें।",
        "claimTracker.verifyCarefully": "इनाम देने या पूरा करने से पहले वस्तु की सावधानीपूर्वक जांच करें।",
        "claimTracker.documentDetails": "बैठक के विवरण को रिकॉर्ड करने के लिए हमारे सुरक्षित चैट का उपयोग करें।",
        "claimTracker.lookupAnother": "दूसरा खोजें",
        "claimTracker.unsuccessful": "दावा मूल्यांकन असफल",
        "claimTracker.trustCheck": "आपसी विश्वास जांच",
        "claimTracker.awaitingApproval": "पाने वाले की स्वीकृति की प्रतीक्षा है",
        "claimTracker.recoveryRoom": "सुरक्षित रिकवरी रूम",
        "claimTracker.enterRoom": "रिकवरी रूम में प्रवेश करें",
        "claimTracker.discussion": "एंड-टू-एंड समन्वित सुपुर्दगी चर्चा",
        "recovery.transmissionSecured": "ट्रांसमिशन सुरक्षित",
        "recovery.reportIndexed": "रिपोर्ट सफलतापूर्वक अनुक्रमित की गई",
        "recovery.dossierActive": "आपकी सत्यापन फ़ाइल अब सक्रिय है। जेमिनी सक्रिय सूचकांकों का विश्लेषण कर रहा है।",
        "recovery.engineTitle": "एआई रिकवरी संभावना इंजन",
        "recovery.retrievalLikelihood": "पुनः प्राप्ति की संभावना:",
        "recovery.analyzedFactors": "विश्लेषण किए गए रिकवरी कारक",
        "recovery.semanticNotice": "हमारा जनरेटर अनुकूलित मिलान मॉडल बनाने के लिए ब्रांड, रंग और पहचानकर्ताओं को निकालता है।",
        "recovery.uniqueIdentifier": "एक अनूठा पहचानकर्ता पूर्ण सत्यापित मिलान सक्षम बनाता है।",
        "recovery.setReward": "इनाम निर्धारित करें",
        "reward.fairRange": "अनुमानित उचित दायरा",
        "reward.suggestReward": "इनाम का सुझाव दें",
        "reward.customReward": "कस्टम इनाम राशि",
        "privacy.complianceProtocols": "अनुपालन, गोपनीयता और विश्वास प्रोटोकॉल",
        "privacy.title": "विश्वास और अनुपालन केंद्र",
        "privacy.subtitle": "हम उपयोगकर्ता सुरक्षा, अत्यधिक गोपनीयता और पारदर्शिता के उच्चतम मानकों का पालन करते हैं।",
        "privacy.exitSection": "अनुभाग से बाहर निकलें",
        "privacy.privacyPolicy": "गोपनीयता नीति",
        "privacy.lastUpdated": "अंतिम अपडेट: 7 जुलाई, 2026। डेटा न्यूनतमकरण हमारी बुनियाद है।",
        "privacy.dataAcquisition": "हम केवल खोई हुई वस्तुओं को खोजने और मिलाने के लिए आवश्यक डेटा एकत्र करते हैं:",
        "privacy.spatiotemporalTags": "स्थानिक-कालिक टैग:",
        "privacy.coldStorage": "स्वचालित कोल्ड स्टोरेज संग्रह से पहले अधिकतम सीमा।",
        "privacy.cookiePreferences": "कुकी प्राथमिकताएं और सहमति नीतियां प्रबंधित करें।",
        "privacy.purgeBrowser": "इस ब्राउज़र से सक्रिय कुकीज़ और कैश किए गए डेटा को तुरंत हटा दें।",
        "privacy.hereToHelp": "हम मदद के लिए यहाँ हैं।",
        "privacy.connectFounder": "फीडबैक या सहायता के लिए हमारे नेटवर्क प्रोफाइल पर संपर्क करें।",
        "cookie.title": "गोपनीयता संप्रभुता",
        "cookie.message": "हम केवल खोई हुई वस्तुओं को पुनः प्राप्त करने के लिए आवश्यक जानकारी एकत्र करते हैं।",
        "cookie.trackingNotice": "स्वामित्व सत्यापित होने तक आपकी पहचान निजी रहती है। कोई ट्रैकिंग नहीं, कोई प्रोफ़ाइलिंग नहीं।",
        "cookie.acceptAll": "सभी स्वीकार करें",
        "cookie.learnMore": "और जानें",
        "about.tagline": "समुदायों को जोड़ना, वस्तुओं को वापस दिलाना",
        "about.mission": "लिंको नैतिक एआई और सामुदायिक विश्वास का लाभ उठाकर खोई हुई वस्तुओं को उनके असली मालिकों तक पहुँचाने के लिए समर्पित है।",
        "notifications.title": "सूचनाएं",
        "notifications.empty": "कोई नई सूचना नहीं",
        "notifications.markAllRead": "सभी को पढ़ा हुआ चिह्नित करें",
        "notifications.clearAll": "सभी साफ़ करें",
        "notifications.matchFoundTitle": "संभावित मिलान मिला",
        "notifications.matchFoundMsg": "हमारे एआई मैचिंग इंजन द्वारा एक संभावित मिलान खोजा गया है।",
        "notifications.claimReceivedTitle": "नया दावा प्रस्तुत किया गया",
        "notifications.claimReceivedMsg": "एक नागरिक ने आपकी लिस्टिंग के लिए सत्यापन उत्तर प्रस्तुत किए हैं।",
        "notifications.claimApprovedTitle": "दावा स्वीकृत",
        "notifications.claimApprovedMsg": "आपके दावे को वस्तु के मालिक द्वारा सत्यापित और स्वीकृत कर दिया गया है।",
        "notifications.chatMessageTitle": "रिकवरी रूम में नया संदेश",
        "notifications.chatMessageMsg": "आपको अपने रिकवरी समन्वय के संबंध में एक नया संदेश प्राप्त हुआ है।",
        "notifications.handoverDoneTitle": "सुपुर्दगी की पुष्टि हुई",
        "notifications.handoverDoneMsg": "वस्तु की वापसी की पुष्टि हो गई है और मामला अब हल हो गया है।",
        "enhance.button": "एआई विवरण सुधारें",
        "enhance.loading": "जेमिनी एआई आपका विवरण व्यवस्थित कर रहा है...",
        "enhance.apply": "सुधारे गए विवरण का उपयोग करें",
        "enhance.discard": "मूल विवरण रखें",
        "enhance.rewardTitle": "एआई उचित इनाम सुझाव",
        "enhance.rewardCalculated": "सुझाया गया इनाम: ₹",
        "enhance.rewardReason": "वस्तु श्रेणी, ब्रांड मूल्य और समुदाय मानकों पर आधारित।",
        "timeline.reconstruct": "टाइमलाइन पुनर्निर्माण करें",
        "timeline.loading": "यात्रा पथ और चेकपॉइंट का विश्लेषण हो रहा है...",
        "timeline.spotLikelihood": "संभावित खोने का स्थान:",
        "timeline.window": "संभावित समय विंडो:",
        "timeline.analysis": "पूर्ण यात्रा विश्लेषण:",
        "timeline.confidence": "पथ विश्वसनीयता:",
        "timeline.addPoint": "पथ चेकपॉइंट जोड़ें",
        "timeline.pointName": "चेकपॉइंट नाम / स्टेशन",
        "chat.assistant": "एआई सहायक",
        "chat.subtitle": "आपका संवाद साथी",
        "chat.description": "खोई या मिली वस्तु की रिपोर्ट 60 सेकंड में करें। बोलें या अपनी भाषा में टाइप करें। हमारा एआई स्वचालित रूप से विवरण निकालता है।",
        "chat.startAssistant": "एआई रिपोर्ट सहायक शुरू करें",
        "chat.location": "स्थान:",
        "chat.securityPin": "सुरक्षा पिन:",
        "chat.skipPhoto": "फोटो छोड़ें",
        "chat.item": "वस्तु:",
        "chat.errorLoading": "चैटबॉट सहायक लोड करते समय त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "chat.welcomeMessage": "लिंकोसाथी में आपका स्वागत है! मैं आपका साथी हूँ। मुझे बताएं क्या खोया या मिला है।",
        "chat.networkError": "सॉरी, नेटवर्क समस्या हुई। कृपया पुनः प्रयास करें!",
        "chat.understoodError": "मैं ठीक से समझ नहीं पाया। क्या आप अधिक विवरण दे सकते हैं?",
        "feed.lostOnly": "खोई वस्तुएं",
        "feed.foundOnly": "मिली वस्तुएं",
        "feed.filterByCategory": "श्रेणी",
        "feed.filterByCity": "शहर",
        "feed.filterByUrgency": "प्राथमिकता",
        "feed.empty": "सक्रिय खोज मानदंडों से कोई वस्तु मेल नहीं खाती।",
        "feed.emptyAction": "नई वस्तु की रिपोर्ट करें",
        "matches.contactFinder": "पाने वाले से संपर्क करें",
        "matches.contactOwner": "मालिक से संपर्क करें",
        "matches.verifyOwnership": "स्वामित्व सत्यापित करें",
        "claim.title": "स्वामित्व दावा प्रस्तुत करें",
        "claim.subtitle": "बिना सार्वजनिक संपर्क लीक के एआई सुरक्षा के साथ स्वामित्व सत्यापित करें।",
        "claim.questionsTitle": "सत्यापन प्रश्न",
        "claim.questionsSubtitle": "असली स्वामित्व प्रदर्शित करने के लिए प्रश्नों के उत्तर दें:",
        "claim.answerPlaceholder": "इस प्रश्न का आपका उत्तर...",
        "claim.submit": "समीक्षा के लिए दावा प्रस्तुत करें",
        "claim.submitting": "सत्यापन विवरण प्रस्तुत किया जा रहा है...",
        "claim.success": "दावा प्रस्तुत! मालिक आपके उत्तरों की समीक्षा करेगा।",
        "dashboard.myReports": "मेरी रिपोर्टें",
        "dashboard.myClaims": "मेरे दावे",
        "dashboard.savedPosts": "सहेजी गई पोस्ट",
        "help.title": "अक्सर पूछे जाने वाले प्रश्न",
        "help.q1": "लिंको मेरी गोपनीयता की रक्षा कैसे करता है?",
        "help.a1": "लिंको आपका संपर्क कभी सार्वजनिक नहीं करता। केवल आपसी सत्यापन के बाद संपर्क खुलता है।",
        "help.q2": "जब मैं खोई वस्तु रिपोर्ट करता हूँ तो क्या होता है?",
        "help.a2": "हमारा एआई आपकी रिपोर्ट की तुलना सभी शहरों और चेकपॉइंट की मिली वस्तुओं से करता है।",
        "help.q3": "स्वामित्व सत्यापन कैसे काम करता है?",
        "help.a3": "दावेदारों को एआई द्वारा तैयार गुप्त प्रश्नों के उत्तर देने होते हैं जो केवल असली मालिक जानता है।",
        "help.q4": "क्या लिंको उपयोग के लिए मुफ़्त है?",
        "help.a4": "हाँ, लिंको पूरी तरह मुफ़्त और समुदाय-संचालित है।",
        "home.heroTitle": "एआई और सत्यापित विश्वास से खोया सामान पुनः पाएं",
        "home.heroSubtitle": "भारत का समुदाय-संचालित लॉस्ट एंड फाउंड मंच। सुरक्षित, निजी और जेमिनी एआई द्वारा संचालित।",
        "home.statsRecovered": "पुनः मिला सामान",
        "home.statsActive": "सक्रिय नागरिक निगरानी",
        "home.statsCities": "कवर किए गए शहर",
        "home.howItWorks": "लिंको कैसे काम करता है",
        "home.step1Title": "1. सेकंडों में रिपोर्ट करें",
        "home.step1Desc": "39 भाषाओं में आवाज़, टेक्स्ट या फोटो से वस्तु दर्ज करें।",
        "home.step2Title": "2. स्मार्ट एआई मिलान",
        "home.step2Desc": "जेमिनी विज़ुअल विशेषताओं और विवरणों की तुलना करता है।",
        "home.step3Title": "3. सत्यापित सुपुर्दगी",
        "home.step3Desc": "गुप्त प्रश्नों से दावे सत्यापित करें और सुरक्षित वापसी करें।",
    }
}

print("VOCAB_INDIC_1 initialized.")
